### ISSUE TITLE
Unable to open Ride.py

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1005]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=967) by automati... on 25 Apr 2012*

In the commandline it says 
-----------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\Scripts\ride.py", line 20, in &lt;module&gt;
    from robotide import main
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 35, in &lt;module
&gt;
    import robotpatch
  File "C:\Python27\lib\site-packages\robotide\robotpatch.py", line 21, in &lt;modu
le&gt;
    from robot.parsing.settings import Timeout, _Setting, Fixture, Template
ImportError: cannot import name _Setting
-----------------------------------------------------------------
I am using Windows7 64 bit
I ran these installers in order:
1. python-2.7.3.amd64.msi (Python)
2. jre-6u31-windows-i586-iftw.exe (Java Runtime Environment)
3. robotframework-2.7.1.win-amd64.exe (Robot Framework)
4. wxPython2.8-win64-unicode-2.8.12.1-py27.exe (wxPython)
5. robotide-0.29.2.win-amd64.exe (Robot IDE)
6. In my System Path I added C:\Python27\Scripts

My command line has the following versions:
-----------------------------------------------------------------
C:&gt;pybot --version
Robot Framework 2.7.1 (Python 2.7.3 on win32)

C:&gt;jybot --version
Robot Framework 2.7.1 (Jython 2.5.3b1 on java1.6.0_31)

C:&gt;java -version
java version "1.6.0_31"
Java(TM) SE Runtime Environment (build 1.6.0_31-b05)
Java HotSpot(TM) Client VM (build 20.6-b01, mixed mode, sharing)
---------------------------------------------------------------

I cannot open Robot IDE.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=967#c1) by automati... on 26 Apr 2012*


Nevermind, I had fixed this by installing previous versions of Python, Robot Framework and Robotide that worked.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=967#c2) by @mkorpela on 6 May 2012*


Closing as invalid.

robotpatch seems to be some custom python script that is not part of normal RIDE.
