### ISSUE TITLE
The color of keyword doesn't change to blue if sikuli is imported

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1024]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985) by kyooky123ac on 11 Jun 2012*

If my library(MyTestLib) imports Sikuli library, its keyword in RIDE doesn't change to blue.

Please see the screenshot I attached.

Please help investigate. Thanks.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c2) by kyooky123ac on 11 Jun 2012*


P.S. Those keyword works well no matter their color changes or not, but I really need the change on color and hint which are helpful.

After modifying the code in MyTestLib, you need to restart RIDE to keep update.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c3) by @mkorpela on 11 Jun 2012*


How have you imported the library in your test suite?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c4) by kyooky123ac on 11 Jun 2012*


By the way, 

#from __future__ import with_statement
#from sikuli.Sikuli import *

When the comments are added to Sikuli Library, the keyword will get hint and color.
Then remove the comment.
If just click Reload Directory button in RIDE, the color and hints still work well, but if you restart RIDE, the color and hints lost.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c5) by @mkorpela on 11 Jun 2012*


What does the RIDE log show? Tools / View RIDE Log

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c6) by kyooky123ac on 11 Jun 2012*


How have you imported the library in your test suite?

I just click Add Library button in RIDE, then type the name 'MyTestLib'.

MyTestlib only has one file __init__.py. The two functions(keywords) in __init__.py work well, but with sikuli imported, the color and hint lost.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c7) by kyooky123ac on 11 Jun 2012*


What does the RIDE log show? Tools / View RIDE Log


20120612 14:19:57.712 [WARN]: Importing test library "MyTestLib" failed

Traceback (most recent call last):
Importing test library 'MyTestLib' failed: ImportError: No module named java.io.File
Traceback (most recent call last):
  File "D:\Python27\Lib\site-packages\MyTestLib\__init__.py", line 2, in &lt;module&gt;
    from sikuli.Sikuli import *
  File "D:\Python27\Lib\site-packages\Sikuli\Lib\sikuli\__init__.py", line 3, in &lt;module&gt;
    from Sikuli import *
  File "D:\Python27\Lib\site-packages\Sikuli\Lib\sikuli\Sikuli.py", line 8, in &lt;module&gt;
    import java.io.File
PYTHONPATH:
  D:\Python27\Lib\site-packages\robotide\lib\robot\libraries
  D:\Python27\Lib\site-packages\robotide\lib
  D:\Python27\Lib\site-packages\wx-2.8-msw-unicode
  D:\Python27\Lib\site-packages\wx-2.8-msw-unicode
  D:\Python27\Scripts
  D:\Python27\Lib\site-packages
  D:\Python27\Lib\site-packages\robotide\contrib\testrunner
  C:\Windows\system32\python27.zip
  D:\Python27\DLLs
  D:\Python27\lib
  D:\Python27\lib\plat-win
  D:\Python27\lib\lib-tk
  D:\Python27
  D:\Python27\lib\site-packages\PIL
  D:\Python27\lib\site-packages\win32
  D:\Python27\lib\site-packages\win32\lib
  D:\Python27\lib\site-packages\Pythonwin
  .
  D:\Python27\Lib\site-packages\robotide\spec
  D:\Python27\Lib\site-packages\Sikuli
  D:\Python27\Lib\site-packages\Sikuli\Lib
  D:\Python27\Lib\site-packages\Sikuli\sikuli-script.jar
  D:\Python27\Lib\site-packages\Sikuli
  D:\Python27\Lib\site-packages\Sikuli\Lib
  D:\Python27\Lib\site-packages\Sikuli\sikuli-script.jar
  File "D:\Python27\Lib\site-packages\robotide\spec\xmlreaders.py", line 62, in __init__
    self.keywords, self.doc = self._init_from_library(self.name, args)
  File "D:\Python27\Lib\site-packages\robotide\spec\xmlreaders.py", line 72, in _init_from_library
    lib = RobotTestLibrary(path, args)
  File "D:\Python27\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 37, in TestLibrary
    libcode = importer.import_class_or_module(name)
  File "D:\Python27\Lib\site-packages\robotide\lib\robot\utils\importer.py", line 64, in import_class_or_module
    self._raise_import_failed(name, err)
  File "D:\Python27\Lib\site-packages\robotide\lib\robot\utils\importer.py", line 102, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c8) by @mkorpela on 11 Jun 2012*


The Sikuli library is a java library and doesn't work with native python.

Please see <a href="https://github.com/robotframework/RIDE/wiki/Keyword-Completion#wiki-libraries-not-available-locally-or-written-in-java" rel="nofollow">https://github.com/robotframework/RIDE/wiki/Keyword-Completion#wiki-libraries-not-available-locally-or-written-in-java</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c9) by kyooky123ac on 11 Jun 2012*


I created a directory named 'Sikuli' in 'D:\Python27\Lib\site-packages' and copied Lib(get from 'jar -xf sikuli-script.jar') and sikuli-script.jar to that directory.

I also created JYTHONPATH in system environment variable
JYTHONPATH
D:\Python27\Lib\site-packages\Sikuli\Lib;D:\Python27\Lib\site-packages;D:\Program Files (x86)\Sikuli X\sikuli-script.jar

I don't know why it couldn't find module named java.io.File.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c10) by kyooky123ac on 11 Jun 2012*


The Sikuli library is a java library and doesn't work with native python.

OK, thanks for your investigation. I'll try to find a better solution.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c11) by kyooky123ac on 12 Jun 2012*


Finally, I got the solution :)

Use libdoc.py to generate MyTestLib.xml.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c12) by @pekkaklarck on 12 Jun 2012*


Good that the problem was solved.

I noticed that RIDE's documentation had examples with old libdoc and updated them to contain also RF 2.7 compatible examples:
<a href="https://github.com/robotframework/RIDE/wiki/Keyword-Completion#wiki-creating-library-specs" rel="nofollow">https://github.com/robotframework/RIDE/wiki/Keyword-Completion#wiki-creating-library-specs</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=985#c13) by sieudang... on 2 Jan 2013*


Hi @&#8288;kyooky12,

Could you give me more detail about importing sikuli like your issue that you met?
Thanks.
