### ISSUE TITLE
Run configuration list editor can't delete empty items

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1029]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=990) by @tommi on 26 Jun 2012*

Steps to reproduce:
1. Open Run -&gt; Manage run configurations
2. Click new
3. Click remove

Expected:
1. Line to be removed

Actual:
Traceback (most recent call last):
  File "/Users/asiala/code/RIDE/src/robotide/run/configmanagerui.py", line 100, in OnRemove
    self.OnDelete(event)
  File "/Users/asiala/code/RIDE/src/robotide/run/configmanagerui.py", line 110, in OnDelete
    ListEditorBase.OnDelete(self, event)
  File "/Users/asiala/code/RIDE/src/robotide/editor/listeditor.py", line 105, in OnDelete
    self._with_column_width_preservation(self._delete_selected)
  File "/Users/asiala/code/RIDE/src/robotide/editor/listeditor.py", line 111, in _with_column_width_preservation
    func()
  File "/Users/asiala/code/RIDE/src/robotide/editor/listeditor.py", line 116, in _delete_selected
    self._controller.execute(DeleteItem(self._selection))
  File "/Users/asiala/code/RIDE/src/robotide/controller/basecontroller.py", line 25, in execute
    return command.execute(self)
  File "/Users/asiala/code/RIDE/src/robotide/controller/commands.py", line 403, in execute
    context.delete(self._item)
  File "/Users/asiala/code/RIDE/src/robotide/run/runanything.py", line 102, in delete
    self._configs.pop(index)
IndexError: pop index out of range

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=990#c1) by @tommi on 26 Jun 2012*


Stacktrace of commit <a href="https://code.google.com/p/robotframework-ride/source/detail?r=ad95a08c9db084716dc16c1dd379c7a3026b4a8d">ad95a08c9db084716dc16c1dd379c7a3026b4a8d</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=990#c5) by @mkorpela on 9 Aug 2012*


Fixed in:

<a href="https://github.com/robotframework/RIDE/commit/1048f0e5dea88c00c22e1848f800c0b48b3162b7" rel="nofollow">https://github.com/robotframework/RIDE/commit/1048f0e5dea88c00c22e1848f800c0b48b3162b7</a>
