### ISSUE TITLE
Initialization parameters are not passed to libraries

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#104]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=69) by c.martin.taylor on 18 Dec 2008*

I know that Remote.py and RobotRemoteServer.py are still prototypes in
robotframework, but I'm beginning to use them to wrap one of my own custom
Robot Framework libraries.  When I do so, and run the tests, the remoting
works fine.  When I try Ctrl-Space to get keyword help in Robot IDE I get
the following traceback from Robot IDE:

Traceback (most recent call last):
  File "C:\Python25\lib\site-packages\robotide\ui\mainframe.py", line 231,
in OnKeywordCompletion
    kwe.show_content_assist()
  File "C:\Python25\lib\site-packages\robotide\ui\editors\kweditor.py",
line 251, in show_content_assist
    self.GetCellEditor(self._active_row,
self._active_col).show_content_assist()
  File "C:\Python25\lib\site-packages\robotide\ui\editors\kweditor.py",
line 391, in show_content_assist
    self._tc.show_content_assist()
  File "C:\Python25\lib\site-packages\robotide\ui\editors\contenassist.py",
line 104, in show_content_assist
    if self._populate_content_assist():
  File "C:\Python25\lib\site-packages\robotide\ui\editors\contenassist.py",
line 114, in _populate_content_assist
    self._choices = choices = [ kw for kw in
self._cache.get_suite_or_resource_keywords(self._item)
  File "C:\Python25\lib\site-packages\robotide\model\cache.py", line 94, in
get_suite_or_resource_keywords
    keywords.extend(self._add_keywords_from_imports(handled_imports,
item.imports))
  File "C:\Python25\lib\site-packages\robotide\model\cache.py", line 105,
in _add_keywords_from_imports
    keywords.extend(self.get_library_keywords(name))
  File "C:\Python25\lib\site-packages\robotide\model\cache.py", line 53, in
get_library_keywords
    self.add_library(name)
  File "C:\Python25\lib\site-packages\robotide\model\cache.py", line 31, in
add_library
    self.libraries[name] = LibraryKeywordSpec(name)
  File "C:\Python25\lib\site-packages\robotide\model\keywordspec.py", line
29, in __init__
    self._init_data()
  File "C:\Python25\lib\site-packages\robotide\model\keywordspec.py", line
52, in _init_data
    self._init_from_library()
  File "C:\Python25\lib\site-packages\robotide\model\keywordspec.py", line
57, in _init_from_library
    lib = RobotTestLibrary(self.name)
  File "C:\Python25\Lib\site-packages\robot\running\testlibraries.py", line
32, in TestLibrary
    return libclass(libcode, source, name, utils.to_list(args), syslog)
  File "C:\Python25\Lib\site-packages\robot\running\testlibraries.py", line
244, in __init__
    _BaseTestLibrary.__init__(self, libcode, source, name, args, syslog)
  File "C:\Python25\Lib\site-packages\robot\running\testlibraries.py", line
74, in __init__
    self.handlers = self._create_handlers(self._libinst, syslog)
  File "C:\Python25\Lib\site-packages\robot\running\testlibraries.py", line
159, in _create_handlers
    for name in self._get_handler_names(libinst):
  File "C:\Python25\Lib\site-packages\robot\running\testlibraries.py", line
248, in _get_handler_names
    return instance.get_keyword_names()
  File "c:\python25\lib\site-packages\robot\libraries\Remote.py", line 29,
in get_keyword_names
    raise RuntimeError('Connecting remote server failed: &#37;s' &#37; err)
RuntimeError: Connecting remote server failed: Connection refused

This probably has to do with Robot IDE not reading and passing the Args to
the library initialization, in this case passing the correct host and port
to Remote.py.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=69#c1) by @pekkaklarck on 26 Jan 2009*


This should be pretty easy to fix. To make this more useful, we also need to support
variables in library (and other) imports. We have <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=46" title="Resource, library and variable imports should support variables"> issue 46 </a> about that.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=69#c4) by @yanne on 27 Jan 2009*


Initial implementation is in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=243">r243</a>, related tests in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=242">r242</a>.
Still need to think how this can be broken?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=69#c5) by @pekkaklarck on 27 Jan 2009*


How would you like to break this?? =)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=69#c6) by @yanne on 11 Feb 2009*


Seems to working.
