### ISSUE TITLE
Test Case Rename does not work

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1042]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1003) by c.martin.taylor on 3 Jul 2012*

Right click on a test case name in the suite/test tree and select "Rename".  Observe this exception in the CMD window where RIDE was started:
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 725, in OnLeftDown
    self._tree.OnCancelEdit(self._tree.GetSelection())
AttributeError: 'Tree' object has no attribute 'OnCancelEdit'
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 725, in OnLeftDown
    self._tree.OnCancelEdit(self._tree.GetSelection())
AttributeError: 'Tree' object has no attribute 'OnCancelEdit'

This may also be related to <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=994" title="Test Case Rename does not work correctly in OSX"> Issue #994 </a>, but this bug happens on Windows as well as Mac.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1003#c1) by c.martin.taylor on 3 Jul 2012*


RF 2.7.1, RIDE 0.46.1, ActivePython 2.6.4.10

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1003#c2) by c.martin.taylor on 3 Jul 2012*


OOPS, that should have read RF 2.7.3.  Just updated both RF and RIDE today!

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1003#c3) by @jussimalinen on 11 Jul 2012*


I am unable to reproduce this one still. What is your wxversion? If it less than the latest (2.8.12.1.), can you try updating and see if that changes anything?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1003#c4) by @mkorpela on 8 Aug 2012*


Seems that the old wx.lib.customtreectrl does not have OnCancelEdit attribute.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1003#c5) by @mkorpela on 8 Aug 2012*


No enough information about the wx version in question

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1003#c9) by @Tattoo on 6 Nov 2012*


Duplicate of <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=998" title="Rename error when renaming KW"> issue 998 </a>
