### ISSUE TITLE
Robotframework use unit test feature will get "I/O operation on closed file"

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1059]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1020) by nkc24nk... on 6 Aug 2012*

OS: Win7 , python27, jython2.5.3b1,sikuli1.0rc3

I use java to run selenium-server.jar

I use selemium-ide to recorder script and save as python language for RC

If use sikuli or python-ide to execute is work fine.

Use Robotframework will get ValueError: I/O operation on closed file.

ttt.py
###################################
from selenium import selenium
import unittest, time, re

class ttt(unittest.TestCase):
    def setUp(self):
        self.verificationErrors = []
        self.selenium = selenium("localhost", 4444, "*chrome", "<a href='http://www.google.com.tw/"' rel="nofollow">http://www.google.com.tw/"</a>)
        self.selenium.start()

    def test_ttt(self):
        sel = self.selenium
        sel.open("/")
        sel.type("id=lst-ib", "1234")
        sel.click("name=btnK")
        try: self.failUnless(sel.is_text_present(u"123(1234)"))
        except AssertionError, e: self.verificationErrors.append(str(e))

        print("Pass")

    def tearDown(self):
        self.selenium.stop()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
###################################

main.py
###################################
import ttt
import unittest
class main:
  def test(self):
      suite = unittest.TestLoader().loadTestsFromTestCase(ttt.ttt)
      unittest.TextTestRunner(verbosity=2).run(suite)

###################################

Traceback (most recent call last):
  File "F:\Robot\Belkin\lib\main.py", line 6, in test
    unittest.TextTestRunner(verbosity=2).run(suite)
  File "C:\Program Files\Sikuli X\sikuli-script.jar\Lib\unittest.py", line 705, in run
    test(result)
  File "C:\Program Files\Sikuli X\sikuli-script.jar\Lib\unittest.py", line 437, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Sikuli X\sikuli-script.jar\Lib\unittest.py", line 433, in run
    test(result)
  File "C:\Program Files\Sikuli X\sikuli-script.jar\Lib\unittest.py", line 281, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\Sikuli X\sikuli-script.jar\Lib\unittest.py", line 247, in run
    result.startTest(self)
  File "C:\Program Files\Sikuli X\sikuli-script.jar\Lib\unittest.py", line 649, in startTest
    self.stream.write(self.getDescription(test))
  File "C:\Program Files\Sikuli X\sikuli-script.jar\Lib\StringIO.py", line 213, in write
    _complain_ifclosed(self.closed)
  File "C:\Program Files\Sikuli X\sikuli-script.jar\Lib\StringIO.py", line 40, in _complain_ifclosed
    raise ValueError, "I/O operation on closed file"

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1020#c1) by @mkorpela on 6 Aug 2012*


What is the command that you use to start your test run?

Where is the Robot Framework test?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1020#c2) by @mkorpela on 6 Aug 2012*


Closing as Invalid.

These problems do not seem to be directly Robot Framework or RIDE related. Please consider using Selenium2Library or SeleniumLibrary if you are testing web based application with Robot Framework.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1020#c3) by nkc24nk... on 6 Aug 2012*


text.txt
###################################
*** Settings ***
Library    lib/main.py

*** Test Cases ***
test
    test
###################################


Use RIDE or command line will get error.
