### ISSUE TITLE
ride.py gives an error

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1062]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1023) by fandi.ya... on 7 Aug 2012*

Hi

When i try to run ride.py (on my mac) i get the following error. I dont know if this a bug or not and could not find other place to post. Sorry if this is not the right place

new-host-2:/ helloupthere$ ride.py 
Traceback (most recent call last):
  File "/usr/local/bin/ride.py", line 5, in &lt;module&gt;
    pkg_resources.run_script('robotframework-ride==0.46.1', 'ride.py')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 489, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1207, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/EGG-INFO/scripts/ride.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/robotide/__init__.py", line 65, in main
    _run(inpath, not noupdatecheck)
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/robotide/__init__.py", line 77, in _run
    from robotide.application import RIDE
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/robotide/application/__init__.py", line 15, in &lt;module&gt;
    from application import RIDE, ChiefController
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/robotide/application/application.py", line 21, in &lt;module&gt;
    from robotide.namespace import Namespace
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/robotide/namespace/__init__.py", line 15, in &lt;module&gt;
    from namespace import Namespace
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/robotide/namespace/namespace.py", line 27, in &lt;module&gt;
    from robotide.namespace.cache import LibraryCache, ExpiringCache
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/robotide/namespace/cache.py", line 18, in &lt;module&gt;
    from robotide.spec import LibrarySpec
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/robotide/spec/__init__.py", line 15, in &lt;module&gt;
    from xmlreaders import LibrarySpec
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/robotide/spec/xmlreaders.py", line 21, in &lt;module&gt;
    from robotide.publish import RideLogException
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/robotide/publish/__init__.py", line 120, in &lt;module&gt;
    from messages import *
  File "/Library/Python/2.7/site-packages/robotframework_ride-0.46.1-py2.7.egg/robotide/publish/messages.py", line 15, in &lt;module&gt;
    from wx.lib.pubsub import Publisher as WxPublisher
ImportError: cannot import name Publisher

Thanks
Yacine

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1023#c1) by @mkorpela on 8 Aug 2012*


Might be that you have a too old wxpython version. My version is 2.8.12.1

You can check your version in python:
import wx
print wx.__version__

Could you try updating wxpython?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1023#c2) by fandi.ya... on 8 Aug 2012*


Moi Mikko,

I am running: 2.9.4.0

new-host-2:Desktop yacinefandi$ python test.py 
2.9.4.0

Terveisin
Yacine

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1023#c4) by @mkorpela on 8 Aug 2012*


Unfortunately RIDE does not support wx 2.9.

Use wx 2.8.12

Terveisin,
Mikko

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1023#c5) by fandi.ya... on 8 Aug 2012*


This is just for reference. After installing the 2.8 i had another problem of 32 / 64 bits as i am running on a mac
Running this script fixed it
#!/bin/bash
export VERSIONER_PYTHON_PREFER_32_BIT=yes
ride.py

For more info  please check this out :<a href="http://www.orangeandbronze.com/orange-orchard/blog/2012/05/resolving-the-64-bit-problem-when-running-robot-framework-ide-ride-on-mac-os-x/" rel="nofollow">http://www.orangeandbronze.com/orange-orchard/blog/2012/05/resolving-the-64-bit-problem-when-running-robot-framework-ide-ride-on-mac-os-x/</a>
