### ISSUE TITLE
TestCaseFileEditor has no delete_rows

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1104]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1066) by @mkorpela on 10 Sep 2012*

Traceback (most recent call last):
  File "src\robotide\ui\actiontriggers.py", line 354, in __call__
    action.act(event)
  File "src\robotide\action\action.py", line 86, in act
    self.action(event)
  File "src\robotide\editor\__init__.py", line 190, in OnDeleteRows
    self.editor.delete_rows()
AttributeError: 'TestCaseFileEditor' object has no attribute 'delete_rows'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1066#c1) by @mkorpela on 11 Sep 2012*


- Open Test case file
- Click focus to editor tab (settings)
- Press Ctrl+D

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1066#c2) by @mkorpela on 13 Sep 2012*


<a href="https://github.com/robotframework/RIDE/commit/2fb3ba14d193e4efd52906ff64e277488d6319c1" rel="nofollow">https://github.com/robotframework/RIDE/commit/2fb3ba14d193e4efd52906ff64e277488d6319c1</a>
