### ISSUE TITLE
Caret moves to the top of text edit when change between edit- and text edit-tabs

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1116]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1078) by cloudwingking84 on 20 Sep 2012*

there are 60 user keywords , 600 lines in my resource file.
click a keyword in edit,and click text edit ,
the mouse position is in the beginning of file, not in the line of the keyword.

there is the same problem when change from text edit to edit.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1078#c2) by @Tattoo on 6 Nov 2012*


When user switches between text edit- and edit-tabs, caret moves always on the first line. This is irritating, when you have big files and you move between the tabs, as you need to every time scroll to the point where you were.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1078#c4) by ilmari.k... on 13 Nov 2012*


Implemented this so, that the text editor now saves the caret position and restores it per file. We will investigate the possibility to implement other usability enhancements regarding editors and the tree component. But this will be descoped from 1.0.
Commits that affect this implementation:
- <a href="https://github.com/robotframework/RIDE/commit/65a2d8d128ee22ac41fe730436dc58bca5b09507" rel="nofollow">https://github.com/robotframework/RIDE/commit/65a2d8d128ee22ac41fe730436dc58bca5b09507</a>
- <a href="https://github.com/robotframework/RIDE/commit/01c4216803602e54171c5b7d6fe51e39aef79340" rel="nofollow">https://github.com/robotframework/RIDE/commit/01c4216803602e54171c5b7d6fe51e39aef79340</a>
- <a href="https://github.com/robotframework/RIDE/commit/36d7c48951be33a568d4c7a78059dee1bf597c1e" rel="nofollow">https://github.com/robotframework/RIDE/commit/36d7c48951be33a568d4c7a78059dee1bf597c1e</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1078#c5) by @mkorpela on 13 Nov 2012*


20121113 12:46:36.126 [ERROR]: Error in listener: 'NoneType' object has no attribute '_data'
While handling &lt;robotide.publish.messages.RideTreeSelection object at 0x2992510&gt;

Traceback (most recent call last):
'NoneType' object has no attribute '_data'
  File "src/robotide/publish/publisher.py", line 84, in __call__
    self.listener(event.data)
  File "src/robotide/editor/texteditor.py", line 116, in OnTreeSelection
    self._editor.store_position()
  File "src/robotide/editor/texteditor.py", line 292, in store_position
    self._positions[self.datafile_controller] = self._editor.GetCurrentPos()
  File "src/robotide/editor/texteditor.py", line 307, in datafile_controller
    return self._data._data


20121113 12:46:36.127 [INFO]: Started RIDE trunk using python version 2.7.3 with wx version 2.8.12.1 in linux2.

20121113 12:46:36.340 [ERROR]: Error in listener: 'NoneType' object has no attribute '_data'
While handling &lt;robotide.publish.messages.RideTreeSelection object at 0x2a14e10&gt;

Traceback (most recent call last):
'NoneType' object has no attribute '_data'
  File "src/robotide/publish/publisher.py", line 84, in __call__
    self.listener(event.data)
  File "src/robotide/editor/texteditor.py", line 116, in OnTreeSelection
    self._editor.store_position()
  File "src/robotide/editor/texteditor.py", line 292, in store_position
    self._positions[self.datafile_controller] = self._editor.GetCurrentPos()
  File "src/robotide/editor/texteditor.py", line 307, in datafile_controller
    return self._data._data


20121113 12:46:42.695 [ERROR]: Error in listener: &lt;robotide.controller.filecontrollers.TestCaseFileController object at 0x2424490&gt;
While handling &lt;robotide.publish.messages.RideNotebookTabChanging object at 0x7ff2b80df5d0&gt;

Traceback (most recent call last):
&lt;robotide.controller.filecontrollers.TestCaseFileController object at 0x2424490&gt;
  File "src/robotide/publish/publisher.py", line 84, in __call__
    self.listener(event.data)
  File "src/robotide/editor/texteditor.py", line 141, in OnTabChange
    self._editor.set_editor_caret_position()
  File "src/robotide/editor/texteditor.py", line 295, in set_editor_caret_position
    position = self._positions[self.datafile_controller]


20121113 12:46:46.354 [ERROR]: Error in listener: 'RobotDataEditor' object has no attribute '_editor'
While handling &lt;robotide.publish.messages.RideNotebookTabChanging object at 0x7ff2b80df650&gt;

Traceback (most recent call last):
'RobotDataEditor' object has no attribute '_editor'
  File "src/robotide/publish/publisher.py", line 84, in __call__
    self.listener(event.data)
  File "src/robotide/editor/texteditor.py", line 143, in OnTabChange
    self._editor.remove_and_store_state()
  File "src/robotide/editor/texteditor.py", line 391, in remove_and_store_state
    self._editor.datafile_controller.position = self._editor._editor.GetCurrentPos()


20121113 12:46:50.091 [ERROR]: Error in listener: 'RobotDataEditor' object has no attribute '_editor'
While handling &lt;robotide.publish.messages.RideNotebookTabChanging object at 0x7ff2b81014d0&gt;

Traceback (most recent call last):
'RobotDataEditor' object has no attribute '_editor'
  File "src/robotide/publish/publisher.py", line 84, in __call__
    self.listener(event.data)
  File "src/robotide/editor/texteditor.py", line 143, in OnTabChange
    self._editor.remove_and_store_state()
  File "src/robotide/editor/texteditor.py", line 391, in remove_and_store_state
    self._editor.datafile_controller.position = self._editor._editor.GetCurrentPos()


20121113 12:46:54.973 [ERROR]: Error in listener: &lt;robotide.controller.filecontrollers.TestDataDirectoryController object at 0x2424810&gt;
While handling &lt;robotide.publish.messages.RideTreeSelection object at 0x7ff2d40b4210&gt;

Traceback (most recent call last):
&lt;robotide.controller.filecontrollers.TestDataDirectoryController object at 0x2424810&gt;
  File "src/robotide/publish/publisher.py", line 84, in __call__
    self.listener(event.data)
  File "src/robotide/editor/texteditor.py", line 126, in OnTreeSelection
    self._editor.set_editor_caret_position()
  File "src/robotide/editor/texteditor.py", line 295, in set_editor_caret_position
    position = self._positions[self.datafile_controller]


20121113 12:46:55.806 [ERROR]: Error in listener: &lt;robotide.controller.filecontrollers.TestDataDirectoryController object at 0x2965150&gt;
While handling &lt;robotide.publish.messages.RideTreeSelection object at 0x296cbd0&gt;

Traceback (most recent call last):
&lt;robotide.controller.filecontrollers.TestDataDirectoryController object at 0x2965150&gt;
  File "src/robotide/publish/publisher.py", line 84, in __call__
    self.listener(event.data)
  File "src/robotide/editor/texteditor.py", line 126, in OnTreeSelection
    self._editor.set_editor_caret_position()
  File "src/robotide/editor/texteditor.py", line 295, in set_editor_caret_position
    position = self._positions[self.datafile_controller]


20121113 12:46:59.322 [ERROR]: Error in listener: &lt;robotide.controller.filecontrollers.TestCaseFileController object at 0x2965a10&gt;
While handling &lt;robotide.publish.messages.RideTreeSelection object at 0x7ff2b80d9ed0&gt;

Traceback (most recent call last):
&lt;robotide.controller.filecontrollers.TestCaseFileController object at 0x2965a10&gt;
  File "src/robotide/publish/publisher.py", line 84, in __call__
    self.listener(event.data)
  File "src/robotide/editor/texteditor.py", line 126, in OnTreeSelection
    self._editor.set_editor_caret_position()
  File "src/robotide/editor/texteditor.py", line 295, in set_editor_caret_position
    position = self._positions[self.datafile_controller]


20121113 12:47:14.476 [ERROR]: Error in listener: &lt;robotide.controller.filecontrollers.TestCaseFileController object at 0x2965b10&gt;
While handling &lt;robotide.publish.messages.RideTreeSelection object at 0x7ff2b81014d0&gt;

Traceback (most recent call last):
&lt;robotide.controller.filecontrollers.TestCaseFileController object at 0x2965b10&gt;
  File "src/robotide/publish/publisher.py", line 84, in __call__
    self.listener(event.data)
  File "src/robotide/editor/texteditor.py", line 126, in OnTreeSelection
    self._editor.set_editor_caret_position()
  File "src/robotide/editor/texteditor.py", line 295, in set_editor_caret_position
    position = self._positions[self.datafile_controller]

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1078#c6) by ilmari.k... on 13 Nov 2012*


fixed stack trace printing in <a href="https://github.com/robotframework/RIDE/commit/8d03dbe73622f52440cd84715070b4aa22306a5e" rel="nofollow">https://github.com/robotframework/RIDE/commit/8d03dbe73622f52440cd84715070b4aa22306a5e</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1078#c7) by cloudwingking84 on 30 Nov 2012*


it still doesn't work for me .
windows xp
RIDE 0.53 running on Python 2.7.2. 
Robot Framework 2.7.5 (Python 2.7.2 on win32)
