### ISSUE TITLE
Using 'Rename Keyword' on variable name in Step cell hangs RIDE

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1119]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1081) by rojwi... on 24 Sep 2012*

If I try to use the 'Rename Keyword' command on a variable name in a Step cell, RIDE will pop up a little 'Executing' progress bar and hang.  The console shows the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/utils/eventhandler.py", line 23, in wrapped
    method(self, event)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/editor/kweditor.py", line 580, in OnRenameKeyword
    RenameProgressObserver(self.GetParent())))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/editor/kweditor.py", line 126, in _execute
    return self._controller.execute(command)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/controller/basecontroller.py", line 25, in execute
    return command.execute(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/controller/commands.py", line 171, in execute
    result = self._execute_without_redo_clear(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/controller/commands.py", line 176, in _execute_without_redo_clear
    result = self._execute(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/controller/commands.py", line 280, in _execute
    self._replace_keywords_in(self._occurrences)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/controller/commands.py", line 295, in _replace_keywords_in
    oc.replace_keyword(self._new_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/controller/commands.py", line 94, in replace_keyword
    self._item.replace_keyword(*self._get_replace_values(new_name))
AttributeError: 'DocumentationController' object has no attribute 'replace_keyword'

I am using RIDE 0.50, Robot Framework 2.7.1 (Python 2.7.2 on darwin), Mac OSX 10.7.4 (Lion)

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1081#c1) by @mkorpela on 8 Oct 2012*


Thanks for the report!

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1081#c2) by @mkorpela on 9 Oct 2012*


Currently variable rename with Rename Keyword functionality is not supported.

--&gt; Ignore rename keyword call when old value is a variable

Fixed in:
<a href="https://github.com/robotframework/RIDE/commit/3cb588a4f78bcdad32b5f239962850326dbde76b" rel="nofollow">https://github.com/robotframework/RIDE/commit/3cb588a4f78bcdad32b5f239962850326dbde76b</a>
