### ISSUE TITLE
Source distribution is broken

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#113]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=77) by jrvilda on 23 Jan 2009*

windows 2003 ESP SP 1
python 2.5.
robotframework 2.0.4

E:\Documents and Settings\Administrador&gt;e:\Python25\python.exe -m robotide
&gt;&gt; error.txt
Traceback (most recent call last):
  File "e:\Python25\lib\runpy.py", line 95, in run_module
    filename, loader, alter_sys)
  File "e:\Python25\lib\runpy.py", line 52, in _run_module_code
    mod_name, mod_fname, mod_loader)
  File "e:\Python25\lib\runpy.py", line 32, in _run_code
    exec code in run_globals
  File "e:\Python25\lib\site-packages\robotide\__init__.py", line 79, in
&lt;module&gt;
    main(sys.argv[1:])
  File "e:\Python25\lib\site-packages\robotide\__init__.py", line 47, in main
    _run(*args)
  File "e:\Python25\lib\site-packages\robotide\__init__.py", line 58, in _run
    ride = RobotIde(inpath)
  File "E:\python25\Lib\site-packages\robotide\layout\application.py", line
15, in __init__
    wx.App.__init__(self, redirect=False)
  File "e:\python25\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line
7935, in __init__
    self._BootstrapApp()
  File "e:\python25\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line
7509, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "E:\python25\Lib\site-packages\robotide\layout\application.py", line
19, in OnInit
    self._frame = RideFrame(self)
  File "E:\python25\Lib\site-packages\robotide\layout\mainframe.py", line
32, in __init__
    self._create_containers(application.model)
  File "E:\python25\Lib\site-packages\robotide\layout\mainframe.py", line
46, in _create_containers
    self.tree = SuiteTree(splitter, self._editor_panel, model)
  File "E:\python25\Lib\site-packages\robotide\layout\suitetree.py", line
30, in __init__
    self._images = TreeImageList()
  File "E:\python25\Lib\site-packages\robotide\layout\images.py", line 29,
in __init__
    self.test = self.Add(wx.Image(path, wx.BITMAP_TYPE_PNG).ConvertToBitmap())
  File "e:\python25\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line
3362, in ConvertToBitmap
    return _core_.Image_ConvertToBitmap(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "image.Ok()" failed at
..\..\src\msw\bitmap.cpp(802) in wxBitmap::CreateFromImage(): invalid image

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=77#c2) by jrvilda on 23 Jan 2009*


robotide 0.12.0

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=77#c3) by jrvilda on 23 Jan 2009*


include robotide 0.12.1

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=77#c4) by @pekkaklarck on 23 Jan 2009*


Interesting. Have you tried earlier 0.11 release? I'd like to know is this a
regression in 0.12 or does it have something to do with Windows 2003 (we test
normally with XP and Linux). Could you also tell the wxPython version you are using?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=77#c5) by jrvilda on 23 Jan 2009*


yes, With the version 0.11 works well.
The error also occurs in Windows 2000 SP4 clean in spanish and XP sp3.

I am using the robotide-0.12.1.tar.gz file and wxPython2.8-win32-unicode-2.8.9.1-py25.exe

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=77#c6) by @pekkaklarck on 23 Jan 2009*


I tested 0.12.1 on WinXP first with the Windows installer package
(robotide-0.12.1.win32.exe) and both installing and starting RIDE succeeded. I then
tested using the source distribution (robotide-0.12.1.tar.gz) like you had done (good
that you mentioned it!!) and starting RIDE failed just like you had told.

A closer investigation shows that the process.png image used by RIDE is not included
in the source distribution. This bug is due to us changing the core organization and
not updating MANIFEST.in accordingly. We had updated setup.py and that's why Windows
installer and installing from a checkout from a version control works....

A simple workaround for installation problems on Windows is thus using the Windows
installer and not the source distribution. We anyway need to fix the source
distribution ASAP. Thanks for reporting this!

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=77#c7) by jrvilda on 23 Jan 2009*


the problem is in (C:\python25\lib\site-packages\robotide\layout\images.py)

class TreeImageList(wx.ImageList):

    def __init__(self):
        size = (16, 16)
        wx.ImageList.__init__(self, *size)
        self.suite = self.Add(self._get_image(wx.ART_FOLDER, size))
        self.suite_open = self.Add(self._get_image(wx.ART_FOLDER_OPEN, size))
        self.suite_file = self.Add(self._get_image(wx.ART_NORMAL_FILE, size))
        self.tests = self.keywords = self.variables = self.suite_file
        path = os.path.join(os.path.dirname(__file__),  'process.png')
        self.test = self.Add(wx.Image(path, wx.BITMAP_TYPE_PNG).ConvertToBitmap())
        self.keyword = self.test

with 
        #self.test = self.Add(wx.Image(path, wx.BITMAP_TYPE_PNG).ConvertToBitmap())
        #self.keyword = self.test

ok

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=77#c8) by @yanne on 23 Jan 2009*


New source distribution including the process.png is here:
<a href="http://robotframework-ride.googlecode.com/files/robotide-0.12.2.tar.gz" rel="nofollow">http://robotframework-ride.googlecode.com/files/robotide-0.12.2.tar.gz</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=77#c9) by jrvilda on 23 Jan 2009*


I'm sorry
but ....

python -m robotide o:\script\robot

return:

  File "C:\python25\lib\runpy.py", line 95, in run_module
    filename, loader, alter_sys)
  File "C:\python25\lib\runpy.py", line 52, in _run_module_code
    mod_name, mod_fname, mod_loader)
  File "C:\python25\lib\runpy.py", line 32, in _run_code
    exec code in run_globals
  File "C:\python25\lib\site-packages\robotide\__init__.py", line 79, in &lt;module&gt;
    main(sys.argv[1:])
  File "C:\python25\lib\site-packages\robotide\__init__.py", line 47, in main
    _run(*args)
  File "C:\python25\lib\site-packages\robotide\__init__.py", line 58, in _run
    ride = RobotIde(inpath)
  File "C:\python25\Lib\site-packages\robotide\layout\application.py", line 15, in
__init__
    wx.App.__init__(self, redirect=False)
  File "C:\python25\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7935, in
__init__
    self._BootstrapApp()
  File "C:\python25\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7509, in
_BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "C:\python25\Lib\site-packages\robotide\layout\application.py", line 19, in OnInit
    self._frame = RideFrame(self)
  File "C:\python25\Lib\site-packages\robotide\layout\mainframe.py", line 32, in __init__
    self._create_containers(application.model)
  File "C:\python25\Lib\site-packages\robotide\layout\mainframe.py", line 46, in
_create_containers
    self.tree = SuiteTree(splitter, self._editor_panel, model)
  File "C:\python25\Lib\site-packages\robotide\layout\suitetree.py", line 36, in __init__
    self.create_tree(model)
  File "C:\python25\Lib\site-packages\robotide\layout\suitetree.py", line 44, in
create_tree
    model.render(self)
  File "C:\python25\Lib\site-packages\robotide\model\datamodel.py", line 106, in render
    self.suite.render(renderer)
  File "C:\python25\Lib\site-packages\robotide\model\model.py", line 201, in render
    self.keywords.render(renderer)
  File "C:\python25\Lib\site-packages\robotide\model\model.py", line 408, in render
    kw.render(renderer)
  File "C:\python25\Lib\site-packages\robotide\model\model.py", line 346, in render
    renderer.start_keyword(self)
  File "C:\python25\Lib\site-packages\robotide\layout\suitetree.py", line 100, in
start_keyword
    self._images.keyword)
AttributeError: 'TreeImageList' object has no attribute 'keyword'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=77#c10) by @pekkaklarck on 23 Jan 2009*


jrvilda, fixing the problem like you did might be enough to get RIDE open but it'll
definitely break later. The correct fix is adding that 'process.png' file to the
source distribution so that it is copied to right place in installation. Janne has
already done that, but you can also download the missing image from
<a href="http://robotframework-ride.googlecode.com/svn/trunk/src/robotide/layout/process.png" rel="nofollow">http://robotframework-ride.googlecode.com/svn/trunk/src/robotide/layout/process.png</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=77#c11) by @pekkaklarck on 23 Jan 2009*


jrvilda, the reason you get "AttributeError: 'TreeImageList' object has no attribute
'keyword'" is that you commented 'keyword' attribute out! Please install RIDE from
the new 0.12.2 source distribution or use the Windows installer.
