### ISSUE TITLE
"File Changed On Disk" keeps poping up repeatedly even after a deleted suite has been removed from the project

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1130]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1092) by t.vlaev on 30 Oct 2012*

RIDE 0.51 running on Python 2.7.2.

1. Open a test suite with RIDE
2. Delete the suite from the file system
3. RIDE displays an error prompt:

"The file has been removed from the file system.
Do you want to remove it from the project?
Answering &lt;No&gt; will rewrite the file on disk.

Changed file is:
&lt;filename&gt;"

4. Answer &lt;Yes&gt;

Expected result: The file is removed from the project and it's possible to open a new suite
Actual result: The file is removed from the hierarchy on the left, however upon moving the mouse around, the dialog keeps poping up effectively making RIDE unusable.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1092#c1) by t.vlaev on 30 Oct 2012*


This is Minor.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1092#c3) by @mkorpela on 30 Oct 2012*


I mean: Thanks for the report.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1092#c5) by @mkorpela on 1 Nov 2012*


Use the same mechanism as with the file changed on disk to prevent multiple dialogs.

<a href="https://github.com/robotframework/RIDE/commit/0e28aec91a88675de1205ec0f7adc468859fb54a" rel="nofollow">https://github.com/robotframework/RIDE/commit/0e28aec91a88675de1205ec0f7adc468859fb54a</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1092#c6) by @mkorpela on 2 Nov 2012*


Not ready yet.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1092#c8) by @mkorpela on 6 Nov 2012*


Needs discussion with Todor.

Currently there at most will be one dialog at a time.
CANCEL-option is removed.
NO-option will currently update also file changed info.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1092#c10) by @mkorpela on 7 Nov 2012*


AttributeError: 'NoneType' object has no attribute 'remove_child'
Traceback (most recent call last):
   File "src/robotide/utils/eventhandler.py", line 21, in wrapped
     if self._can_be_edited(event):
   File "src/robotide/utils/eventhandler.py", line 41, in _can_be_edited
     return self._show_removed_from_disk_warning(ctrl, event)
   File "src/robotide/utils/eventhandler.py", line 50, in _show_removed_from_disk_warning
   self._execute_if_not_in_the_set(RideEventHandler._SHOWING_REMOVED_ON_DISK_CONTROLLERS_, ctrl, msg, ctrl.remove)
   File "src/robotide/utils/eventhandler.py", line 67, in _execute_if_not_in_the_set
     self._show_warning(msg, ctrl, yes_handler)
   File "src/robotide/utils/eventhandler.py", line 82, in _show_warning
     yes_handler()
   File "src/robotide/controller/filecontrollers.py", line 628, in remove
     self._chief_controller.remove_datafile(self)
   File "src/robotide/controller/chiefcontroller.py", line 259, in remove_datafile
     self._controller.remove_child(controller)
 AttributeError: 'NoneType' object has no attribute 'remove_child

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1092#c21) by @Tattoo on 5 Dec 2012*


Fixed after <a href="https://github.com/robotframework/RIDE/commit/5ffce3aaa312be197b647a97176ab12de8c71d61" rel="nofollow">https://github.com/robotframework/RIDE/commit/5ffce3aaa312be197b647a97176ab12de8c71d61</a>
