### ISSUE TITLE
Searching results in sqllite3.ProgrammingError

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1133]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1095) by @mikahanninen on 5 Nov 2012*

20121105 14:16:22.905 [INFO]: Started RIDE 0.51 using python version 2.7.3 with wx version 2.8.12.1 in win32.

Example case for reproducing

Step 1    : Search for unused keywords
Expected: List of unused keywords
Step 2    : Edit file which contains keywords, resource file for example, and add new keyword, or edit existing
Expected: File changed
Step 3    : Save changes
Expected: Changes saved
Step 4    :  Rerun 'search for unused keywords'
Expected: List of unused keywords
Actual    : Nothing is returned, seemingly in loop, console has following error

Problem occurs when using 'search unused keywords' or 'search keywords' (probably also on other search functionality related actions).
---------------------------------------------------------------
E:\RIDE&gt;paver run smallerdir
---&gt; pavement.run
Exception in thread Thread-7:
Traceback (most recent call last):
  File "c:\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "c:\Python27\lib\threading.py", line 483, in run
    self.__target(*self.__args, **self.__kwargs)
  File "src\robotide\ui\review.py", line 366, in _run
    if self._is_unused(keyword):
  File "src\robotide\ui\review.py", line 374, in _is_unused
    self._controller.execute(FindUsages(keyword.name, keyword_info=keyword.info)).next()
  File "src\robotide\usages\commands.py", line 24, in execute
    for occ in FindOccurrences.execute(self, context):
  File "src\robotide\controller\commands.py", line 585, in &lt;genexpr&gt;
    return (Occurrence(item, self._keyword_name) for item in items
  File "src\robotide\controller\commands.py", line 554, in _items_from
    if self._items_from_datafile_should_be_checked(df):
  File "src\robotide\controller\commands.py", line 562, in _items_from_datafile_should_be_checked
    return self._find_keyword_source(datafile) == self._keyword_source
  File "src\robotide\controller\commands.py", line 581, in _find_keyword_source
    item_info = datafile_controller.keyword_info(self._keyword_name)
  File "src\robotide\controller\filecontrollers.py", line 198, in keyword_info
    return WithNamespace.keyword_info(self, self.data, keyword_name)
  File "src\robotide\controller\basecontroller.py", line 109, in keyword_info
    return self._namespace.find_keyword(datafile, keyword_name)
  File "src\robotide\namespace\namespace.py", line 172, in find_keyword
    self._context_factory)
  File "src\robotide\namespace\namespace.py", line 421, in get_keywords_cached
    words = self.get_keywords_from(datafile, context_factory.ctx_for_datafile(datafile))
  File "src\robotide\namespace\namespace.py", line 334, in get_keywords_from
    self._get_imported_library_keywords(datafile, ctx)))
  File "src\robotide\namespace\namespace.py", line 351, in _get_imported_library_keywords
    self._lib_kw_getter, ctx)
  File "src\robotide\namespace\namespace.py", line 356, in _collect_kws_from_imports
    kws.extend(getter(imp, ctx))
  File "src\robotide\namespace\namespace.py", line 364, in _lib_kw_getter
    return self._lib_cache.get_library_keywords(name, args, alias)
  File "src\robotide\namespace\cache.py", line 81, in get_library_keywords
    self._library_keywords[key] = [k.with_alias(alias) for k in self._get_library(name, args)]
  File "src\robotide\namespace\cache.py", line 67, in _get_library
    last_updated = self._library_database.get_library_last_updated(name, args)
  File "src\robotide\spec\librarydatabase.py", line 104, in get_library_last_updated
    lib = self._fetch_lib(library_name, library_arguments, self._cursor())
  File "src\robotide\spec\librarydatabase.py", line 73, in _cursor
    return self._connection.cursor()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 3668 and this is thread id 3848

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1095#c3) by @mikahanninen on 7 Nov 2012*


<a href="https://github.com/robotframework/RIDE/commit/c77ea785288513738abbb12fffcbfe28eb6cdc64" rel="nofollow">https://github.com/robotframework/RIDE/commit/c77ea785288513738abbb12fffcbfe28eb6cdc64</a>
