### ISSUE TITLE
New users can't start RIDE

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1143]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1105) by tapio.ko... on 9 Nov 2012*

Installation instructions say:
"If RIDE is used only to edit test cases, Robot Framework does not need to installed at all. However, the Test runner plugin requires Robot Framework to be separately installed."

When I try to run RIDE for the first time, I get the following error traceback:

C:\Users\t&gt;ride.py
Traceback (most recent call last):
  File "C:\Python27\Scripts\ride.py", line 27, in &lt;module&gt;
    main(sys.argv[1:])
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 72, in main
    _run(inpath, not noupdatecheck)
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 84, in _run
    from robotide.application import RIDE
  File "C:\Python27\lib\site-packages\robotide\application\__init__.py", line 15, in &lt;module&gt;
    from application import RIDE, ChiefController
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line 22, in &lt;module&gt;
    from robotide.controller import ChiefController
  File "C:\Python27\lib\site-packages\robotide\controller\__init__.py", line 15, in &lt;module&gt;
    from chiefcontroller import ChiefController
  File "C:\Python27\lib\site-packages\robotide\controller\chiefcontroller.py", line 29, in &lt;module&gt;
    from robotide.spec.librarydatabase import DATABASE_FILE
  File "C:\Python27\lib\site-packages\robotide\spec\librarydatabase.py", line 17, in &lt;module&gt;
    from robotide.preferences.settings import SETTINGS_DIRECTORY
  File "C:\Python27\lib\site-packages\robotide\preferences\__init__.py", line 15, in &lt;module&gt;
    from .settings import Settings, initialize_settings, RideSettings
  File "C:\Python27\lib\site-packages\robotide\preferences\settings.py", line 27, in &lt;module&gt;
    os.mkdir(SETTINGS_DIRECTORY)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\t\\AppData\\Roaming\\RobotFramework\\ride'

Versions:
 Windows 7
 Python 2.73
 RIDE 0.52.1

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1105#c2) by @mkorpela on 9 Nov 2012*


Fixed in <a href="https://github.com/robotframework/RIDE/commit/f2d3771be3b6979a56834e5a5bdc1cdbfef38802" rel="nofollow">https://github.com/robotframework/RIDE/commit/f2d3771be3b6979a56834e5a5bdc1cdbfef38802</a>
