### ISSUE TITLE
Tools > Manage Plugins generates wxPython error on OSX

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1154]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1115) by ahn.sa... on 15 Nov 2012*

Framework version: Robot Framework 2.7.5 (Python 2.7.1 on darwin)
Operating System: Mac OS X 10.7.5

Steps:
1. In RIDE menu bar, click Tools &gt; Manage Plugins.

Expected Results: 
A change in the RIDE GUI that allows user to manage plug ins.

Actual Results:
Nothing happens.

Error reported on console:
--------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/robotide/ui/actiontriggers.py", line 354, in __call__
    action.act(event)
  File "/Library/Python/2.7/site-packages/robotide/action/action.py", line 86, in act
    self.action(event)
  File "/Library/Python/2.7/site-packages/robotide/utils/eventhandler.py", line 22, in wrapped
    method(self, event)
  File "/Library/Python/2.7/site-packages/robotide/ui/mainframe.py", line 237, in OnManagePlugins
    self._plugin_manager.show(self._application.get_plugins())
  File "/Library/Python/2.7/site-packages/robotide/ui/pluginmanager.py", line 31, in show
    self._tab = _PluginPanel(self._notebook, plugins, self._show_tab)
  File "/Library/Python/2.7/site-packages/robotide/ui/pluginmanager.py", line 46, in __init__
    sizer.Add(self._create_body(plugins, activation_callback),
  File "/Library/Python/2.7/site-packages/robotide/ui/pluginmanager.py", line 69, in _create_body
    flag=wx.ALIGN_CENTER_HORIZONTAL)
  File "/usr/local/lib/wxPython-2.9.4.0/lib/python2.7/site-packages/wx-2.9.4-osx_cocoa/wx/_core.py", line 14469, in Add
    return _core_.Sizer_Add(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at /BUILD/wxPython-src-2.9.4.0/src/common/sizer.cpp(1377) in DoInsert(): too many items (3 &gt; 2*1) in grid sizer (maybe you should omit the number of either rows or columns?)

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1115#c1) by @jussimalinen on 19 Nov 2012*


There seem to be a lot of problems with wx 2.9 on osx. Unfortunately osx is not very high priority for us, so unless someone can provide a patch, fixing this might take some time.
