### ISSUE TITLE
Deleting resource file and imports throws an exception

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1158]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1119) by @mkorpela on 20 Nov 2012*

Traceback (most recent call last):
  File "src/robotide/ui/treenodehandlers.py", line 333, in OnDelete
    ResourceDeleteDialog(self.controller).execute()
  File "src/robotide/ui/resourcedialogs.py", line 94, in execute
    self._controller.execute(DeleteResourceAndImports())
  File "src/robotide/controller/basecontroller.py", line 25, in execute
    return command.execute(self)
  File "src/robotide/controller/commands.py", line 496, in execute
    context.remove_static_imports_to_this()
  File "src/robotide/controller/filecontrollers.py", line 745, in remove_static_imports_to_this
    for resource_import in self.get_where_used():
  File "src/robotide/controller/filecontrollers.py", line 790, in get_where_used
    for usage in source:
RuntimeError: Set changed size during iteration

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1119#c3) by @Tattoo on 22 Nov 2012*


Fixed in <a href="https://github.com/robotframework/RIDE/commit/b8c793d463a3f8d0781cfde90e7516ba0c366008" rel="nofollow">https://github.com/robotframework/RIDE/commit/b8c793d463a3f8d0781cfde90e7516ba0c366008</a>
