### ISSUE TITLE
New Preferences dialog doesn't work with old wxPython versions

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1164]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1125) by c.martin.taylor on 20 Nov 2012*

On a WinXP Professional Version 2002, Service Pack 3 system running on an Intel Core2 Duo CPU T7500 @&#8288; 2.20 GHz with2 GB RAM, with RIDE 0.53, if you select Tools--&gt;Preferences, the CMD window where RIDE was launched shows the following error messages:

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\ui\actiontriggers.py", line 354,
in __call__
    action.act(event)
  File "C:\Python26\lib\site-packages\robotide\action\action.py", line 86, in act
    self.action(event)
  File "C:\Python26\lib\site-packages\robotide\utils\eventhandler.py", line 22, in wrapped
    method(self, event)
  File "C:\Python26\lib\site-packages\robotide\ui\mainframe.py", line 247, in OnPreferences
    self._application.preferences, style='tree')
  File "C:\Python26\lib\site-packages\robotide\preferences\editor.py", line 62,
in __init__
    self._populate_tree(panels)
  File "C:\Python26\lib\site-packages\robotide\preferences\editor.py", line 134,
 in _populate_tree
    item = self._get_item(location)
  File "C:\Python26\lib\site-packages\robotide\preferences\editor.py", line 141,
 in _get_item
    item = self._get_child_item(item, text)
  File "C:\Python26\lib\site-packages\robotide\preferences\editor.py", line 149,
 in _get_child_item
    if self._tree.ItemHasChildren(parent):
  File "C:\Python26\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line
5377, in ItemHasChildren
    return _controls_.TreeCtrl_ItemHasChildren(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "tvItem-&gt;hItem != ((HTREEITEM)(ULONG_PT
R)-0x10000)" failed at ..\..\src\msw\treectrl.cpp(854) in wxTreeCtrl::DoGetItem(
): can't retrieve virtual root item

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1125#c1) by @mkorpela on 20 Nov 2012*


Seems like you have an old version of wxpython.

What version of wxpython are you using?

Could you try to update it.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1125#c2) by @pekkaklarck on 27 Nov 2012*


This seems to be caused by the following wxWidgets bug:
<a href="http://trac.wxwidgets.org/ticket/11169" rel="nofollow">http://trac.wxwidgets.org/ticket/11169</a>

The bug has been fixed already three years ago so latest releases definitely contain the fix. Based on the description the bug is in ItemHasChildren but GetChildrenCount ought to work fine.

I'm not sure does it make sense to fix this, though, or should we explicitly require new enough wxPython version. On a quick look at least <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1126" title="Select All Tests doesn't work in WinXP"> issue 1126 </a> and <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1129" title="Error when escaping from rename test case"> issue 1129 </a> seem to be caused by bugs or missing features in in old wxPython versions too.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1125#c3) by @mkorpela on 28 Nov 2012*


Seems to work with wxpython 2.8.11 but not 2.8.10.

We need to decide what is the minimum wxpython version before 1.0.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1125#c4) by c.martin.taylor on 28 Nov 2012*


Updated to wxPython 2.8.12.1 and the problem goes away, PC and Mac.
