### ISSUE TITLE
Search Keywords get error and never stops refreshing the screen

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1193]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1154) by c.martin.taylor on 10 Dec 2012*

The "Find Usages" button on the "Search Keywords" dialog causes a "nn - matches found" window to appear.  This window continually "blinks" as it is repeatedly refreshed.  The CMD window where RIDE was started displays this error:

ride.py .
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Python26\lib\threading.py", line 527, in __bootstrap_inner
    self.run()
  File "C:\Python26\lib\threading.py", line 479, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python26\lib\site-packages\robotide\usage\UsageRunner.py", line 45, in _run
    for usage in self._find_usages():
  File "C:\Python26\lib\site-packages\robotide\usages\commands.py", line 24, in execute
    for occ in FindOccurrences.execute(self, context):
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 590, in &lt;genexpr&gt;
    return (Occurrence(item, self._keyword_name) for item in items
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 559, in _items_from
    if self._items_from_datafile_should_be_checked(df):
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 567, in _items_from_dat
afile_should_be_checked
    return self._find_keyword_source(datafile) == self._keyword_source
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 586, in _find_keyword_source
    item_info = datafile_controller.keyword_info(self._keyword_name)
AttributeError: 'ExcludedDirectoryController' object has no attribute 'keyword_info'

Found today in new RIDE 0.54 release, although the "flash forever" behaviour was seen in earlier releases the error message was not seen.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1154#c1) by @mikahanninen on 10 Dec 2012*


Seems ExcludedDirectoryController is missing some data needed for FindOccurrences.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1154#c3) by @mikahanninen on 11 Dec 2012*


<a href="https://github.com/robotframework/RIDE/commit/e84a896a5a8d9a75a697f96fc52b10cfb92ad5ad" rel="nofollow">https://github.com/robotframework/RIDE/commit/e84a896a5a8d9a75a697f96fc52b10cfb92ad5ad</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1154#c4) by @pekkaklarck on 14 Dec 2012*


Included into 0.55 preview available at <a href="http://bit.ly/RobotPreview" rel="nofollow">http://bit.ly/RobotPreview</a>
