### ISSUE TITLE
HTML format change does not work

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1196]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1157) by @mikahanninen on 12 Dec 2012*

Underlying exception when changing format to HTML

E:\RIDE&gt;paver run
---&gt; pavement.run
Traceback (most recent call last):
  File "src\robotide\ui\treenodehandlers.py", line 236, in OnChangeFormat
    ChangeFormatDialog(self.controller).execute()
  File "src\robotide\widgets\dialog.py", line 39, in execute
    retval = self._execute()
  File "src\robotide\ui\filedialogs.py", line 227, in _execute
    self._controller.execute(cmd(self._get_format()))
  File "src\robotide\controller\basecontroller.py", line 25, in execute
    return command.execute(self)
  File "src\robotide\controller\commands.py", line 771, in execute
    context.save_with_new_format(self._format)
  File "src\robotide\controller\filecontrollers.py", line 277, in save_with_new_format
    self._chief_controller.change_format(self, format)
  File "src\robotide\controller\chiefcontroller.py", line 240, in change_format
    controller.set_format(format)
  File "src\robotide\controller\filecontrollers.py", line 732, in set_format
    lambda imp: imp.change_format(format))
  File "src\robotide\controller\filecontrollers.py", line 752, in _modify_file_name
    for resource_import in self.get_where_used():
  File "src\robotide\controller\filecontrollers.py", line 790, in get_where_used
    for usage in source:
RuntimeError: Set changed size during iteration

Extra information
---------------------------------------------
RIDE git:(master) ack-grep get_where_used src 

src/robotide/controller/filecontrollers.py
484:        for resource_import in self.get_where_used():
487:    def get_where_used(self):
750:        imports = [import_ for import_ in self.get_where_used()]
758:        for resource_import in self.get_where_used():
791:    def get_where_used(self):

src/robotide/controller/commands.py
684:                files += [imp.datafile_controller for imp in f.get_where_used()]

src/robotide/usages/commands.py
55:        for imp in context.get_where_used():
62:        for imp in context.get_where_used():

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1157#c2) by @mikahanninen on 12 Dec 2012*


Fixed in <a href="https://github.com/robotframework/RIDE/commit/fa4b10888500da5e038eb476560a66c080b536ab" rel="nofollow">https://github.com/robotframework/RIDE/commit/fa4b10888500da5e038eb476560a66c080b536ab</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1157#c3) by @pekkaklarck on 14 Dec 2012*


Included into 0.55 preview available at <a href="http://bit.ly/RobotPreview" rel="nofollow">http://bit.ly/RobotPreview</a>
