### ISSUE TITLE
RIDE freezes w/ 'DocumentationController' object has no attribute 'replace_keyword'

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1200]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161) by rdesgroppes on 13 Dec 2012*

RIDE 0.54 running on Python 2.7.3, under Mint 13, Ubuntu 12.04 and Ubuntu 12.10.

When renaming a keyword like '${the_result} must ${satisfy_constraints}', the renaming dialog freezes after a couple of seconds.

On the console, I see the following traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/robotide/ui/tree.py", line 757, in OnLabelEdited
    self._tree._controller.get_handler(event.GetItem()).end_label_edit(event)
  File "/usr/local/lib/python2.7/dist-packages/robotide/ui/treenodehandlers.py", line 165, in end_label_edit
    self.rename(event.GetLabel())
  File "/usr/local/lib/python2.7/dist-packages/robotide/ui/treenodehandlers.py", line 416, in rename
    self.controller.execute(self._create_rename_command(new_name))
  File "/usr/local/lib/python2.7/dist-packages/robotide/controller/basecontroller.py", line 25, in execute
    return command.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/robotide/controller/commands.py", line 171, in execute
    result = self._execute_without_redo_clear(context)
  File "/usr/local/lib/python2.7/dist-packages/robotide/controller/commands.py", line 176, in _execute_without_redo_clear
    result = self._execute(context)
  File "/usr/local/lib/python2.7/dist-packages/robotide/controller/commands.py", line 280, in _execute
    self._replace_keywords_in(self._occurrences)
  File "/usr/local/lib/python2.7/dist-packages/robotide/controller/commands.py", line 295, in _replace_keywords_in
    oc.replace_keyword(self._new_name)
  File "/usr/local/lib/python2.7/dist-packages/robotide/controller/commands.py", line 94, in replace_keyword
    self._item.replace_keyword(*self._get_replace_values(new_name))
AttributeError: 'DocumentationController' object has no attribute 'replace_keyword'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161#c1) by @pekkaklarck on 13 Dec 2012*


I tried to reproduce this but failed. Could you provide a simple example with instructions which keyword to rename and how?

Also, what wxPython version do you use? Based on that you tested on pretty recent distro's I doubt that matters. I tested this with Mint 14 that has wxPython 2.8.12.1.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161#c2) by rdesgroppes on 14 Dec 2012*


Yes, we're all using wxPython 2.8.12.1.
The keyword in question was freshly added to a resource file, not yet used from within the test suite. Just renaming it led to the exception.
Looking at RIDE source code, the replace_keyword method is defined for classes FixtureController, ItemNameController, StepController, TemplateController but not for DocumentationController...

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161#c3) by @mkorpela on 14 Dec 2012*


Is the keywords name in the documentation?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161#c4) by rdesgroppes on 14 Dec 2012*


Yes, Mikko, there's something in the documentation accidentally matching the pattern '${the_result} must ${satisfy_constraints}'.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161#c5) by @pekkaklarck on 14 Dec 2012*


Interesting. I hope this information is enough for us to get this fixed for 0.55. If you have a simple example demonstrating this issue you may want to attach it here or copy it to a comment.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161#c7) by @mkorpela on 17 Dec 2012*


I can reproduce the problem with this small suite (when renaming the keyword ${jotain} ja ${taas}):

*** Settings ***
Documentation  hui ja hai

*** Test Case ***
testii
  Just ja Ei

*** Keywords ***
${jotain} ja ${taas}
  Log  ${jotain} ja ${taas}

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161#c8) by @mkorpela on 17 Dec 2012*


can also be reproduced without embedded arguments syntax

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161#c9) by @mkorpela on 17 Dec 2012*


More easy to detect when there are embedded arguments as the keyword name must match the whole documentation.

IMHO rename should not touch documentation. So this should be easy to fix.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161#c10) by @mkorpela on 17 Dec 2012*


This is a regression that has fist occurred in: <a href="https://code.google.com/p/robotframework-ride/source/detail?r=9ccaf8f5d22008193cf2d6bceb1baf7c75d370e4">9ccaf8f5d22008193cf2d6bceb1baf7c75d370e4</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161#c11) by @mkorpela on 17 Dec 2012*


Fixed in:
<a href="https://github.com/robotframework/RIDE/commit/9996744ee89209d858e3372bca25ae8f856d5fec" rel="nofollow">https://github.com/robotframework/RIDE/commit/9996744ee89209d858e3372bca25ae8f856d5fec</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1161#c12) by rdesgroppes on 17 Dec 2012*


Thanks, guys.
