### ISSUE TITLE
For loop header row move throws an exception

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1205]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1166) by @mkorpela on 17 Dec 2012*

While moving two for loop headers:
:FOR	${i}	IN RANGE	1	2	3
:FOR	${i}	IN	1	2	# comment

AttributeError: 'PartialForLoop' object has no attribute 'args'
Traceback (most recent call last):
  File "src/robotide/utils/eventhandler.py", line 22, in wrapped
    method(self, event)
  File "src/robotide/editor/kweditor.py", line 386, in OnKeyDown
    self._move_rows(keycode)
  File "src/robotide/editor/kweditor.py", line 437, in _move_rows
    self.OnMoveRowsUp()
  File "src/robotide/utils/eventhandler.py", line 22, in wrapped
    method(self, event)
  File "src/robotide/editor/kweditor.py", line 224, in OnMoveRowsUp
    self._row_move(MoveRowsUp, -1)
  File "src/robotide/editor/kweditor.py", line 231, in _row_move
    if self._execute(command(rows)):
  File "src/robotide/editor/kweditor.py", line 144, in _execute
    return self._controller.execute(command)
  File "src/robotide/controller/basecontroller.py", line 25, in execute
    return command.execute(self)
  File "src/robotide/controller/commands.py", line 171, in execute
    result = self._execute_without_redo_clear(context)
  File "src/robotide/controller/commands.py", line 176, in _execute_without_redo_clear
    result = self._execute(context)
  File "src/robotide/controller/commands.py", line 239, in _execute
    if self.change_steps(context):
  File "src/robotide/controller/commands.py", line 1043, in change_steps
    if len(self._rows) == 0 or self._last_row &gt; len(context.steps)-1 or self._first_row == 0:
  File "src/robotide/controller/macrocontrollers.py", line 99, in steps
    self._recreate_steps()
  File "src/robotide/controller/macrocontrollers.py", line 112, in _recreate_steps
    flattened_steps.extend(for_loop.steps)
  File "src/robotide/controller/stepcontrollers.py", line 453, in steps
    return [IntendedStepController(self, sub_step) for sub_step in self._get_raw_steps()]
  File "src/robotide/controller/stepcontrollers.py", line 32, in __init__
    self._step.args = self._change_last_empty_to_empty_var(self._step.args, self._step.comment)

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1166#c2) by @mkorpela on 18 Dec 2012*


Fixed after: <a href="https://github.com/robotframework/RIDE/commit/47e811729fca91778f863aa9c400f02413473294" rel="nofollow">https://github.com/robotframework/RIDE/commit/47e811729fca91778f863aa9c400f02413473294</a>
