### ISSUE TITLE
Keyword cell information threw an exception when External Resources selected from tree

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1209]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1170) by @mkorpela on 18 Dec 2012*

Traceback (most recent call last):
  File "src/robotide/utils/eventhandler.py", line 22, in wrapped
    method(self, event)
  File "src/robotide/editor/kweditor.py", line 382, in OnKeyDown
    self._show_cell_information()
  File "src/robotide/editor/kweditor.py", line 411, in _show_cell_information
    self._show_user_keyword_link(cell, value)
  File "src/robotide/editor/kweditor.py", line 420, in _show_user_keyword_link
    if cell != self._marked_cell and self._plugin.get_user_keyword(value):
  File "src/robotide/pluginapi/plugin.py", line 319, in get_user_keyword
    keyword_info = self.__namespace.find_user_keyword(self.datafile, name)
  File "src/robotide/namespace/namespace.py", line 152, in find_user_keyword
    kw = self.find_keyword(datafile, kw_name)
  File "src/robotide/namespace/namespace.py", line 172, in find_keyword
    self._context_factory)
  File "src/robotide/namespace/namespace.py", line 419, in get_keywords_cached
    values = self.keyword_cache.get(datafile.source)
AttributeError: 'NoneType' object has no attribute 'source'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1170#c1) by @mkorpela on 19 Dec 2012*


This happens when trying to get context help in the opened test case grid editor while External Resources is selected from tree.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1170#c2) by @mkorpela on 19 Dec 2012*


Fixed in:
<a href="https://github.com/robotframework/RIDE/commit/54fd82850e9388574ca21ee224d51d7cabc74133" rel="nofollow">https://github.com/robotframework/RIDE/commit/54fd82850e9388574ca21ee224d51d7cabc74133</a>
