### ISSUE TITLE
Unable to start RIDE, wxPython requires upgrade msg

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1215]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1176) by jerry57 on 20 Dec 2012*

OS is Mac OS X 10.6.8 (clean install)
Python is 2.6.1
wxPython is installed from wxPython2.8-osx-unicode-2.8.12.1-universal-py2.6.dmg
RobotFramework v2.7.5
RobotFramework_RIDE v1.0, 0.55 &amp; 0.54

When I try to start 0.55 or 0.54 it get the following:
Jerry-Ss-MacBook-Pro:robotframework-quickstart-20090113 jerry$ ride.py &amp;
[1] 217
Jerry-Ss-MacBook-Pro:robotframework-quickstart-20090113 jerry$ Traceback (most recent call last):
  File "/usr/local/bin/ride.py", line 27, in &lt;module&gt;
    main(*sys.argv[1:])
  File "/Library/Python/2.6/site-packages/robotide/__init__.py", line 76, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/Library/Python/2.6/site-packages/robotide/__init__.py", line 89, in _run
    from robotide.application import RIDE
  File "/Library/Python/2.6/site-packages/robotide/application/__init__.py", line 15, in &lt;module&gt;
    from application import RIDE, ChiefController
  File "/Library/Python/2.6/site-packages/robotide/application/application.py", line 25, in &lt;module&gt;
    from robotide.ui.mainframe import RideFrame
  File "/Library/Python/2.6/site-packages/robotide/ui/mainframe.py", line 32, in &lt;module&gt;
    from .tree import Tree
  File "/Library/Python/2.6/site-packages/robotide/ui/tree.py", line 16, in &lt;module&gt;
    import wx.lib.agw.customtreectrl as customtreectrl
ImportError: No module named agw.customtreectrl

[1]+  Exit 1                  ride.py

Starting 1.0 results in the popup window (attached screenshot)

python
Python 2.6.1 (<a href="https://code.google.com/p/robotframework-ride/source/detail?r=261">r261</a>:67515, Jun 24 2010, 21:47:49) 
[GCC 4.2.1 (Apple Inc. build 5646)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
&gt;&gt;&gt; import wxversion
&gt;&gt;&gt; print wxversion.getInstalled()
['2.8-mac-unicode', '2.8-mac-unicode']
&gt;&gt;&gt; wxversion.select('2.8')
&gt;&gt;&gt; import wx
&gt;&gt;&gt; print wx.__version__
2.8.8.1

Running the wxPython uninstall shows only one wx installed 2.8.12.1

./uninstall_wxPython.py 

This script will search for installed versions of wxPython on OSX and
allow the user to choose one to uninstall.  It then will use the
metadata stored about the installed package to remove all the files
associated with that install.

Only the files installed by the main Installer Package will be
removed.  This includes the Python modules and the wxWidgets shared
libraries. If you also installed the demo or docs by dragging them out
of the disk image, then you will need to drag them to the Trash
yourself.

  1.  wxPython2.8-osx-unicode-universal-py2.6     2.8.12.1

Enter the number of the install to examine or 'Q' to quit: q

Attached is the screenshot of the error message received when starting RIDE.  If I uninstall all of RIDE and then install v0.53, I am able to run RIDE normally.  0.54, 0.55 and 1.0 all fail with the error message or a stacktrace on startup.

I was able to install 0.55 on another laptop running Mac OS X 10.7 Lion without issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1176#c1) by @mkorpela on 27 Dec 2012*


To mee this seems like a problem in wxpython. After deciding that 2.8.12.1 is the minimum version I don't think that we have time to find a solution to this issue.

Patches are of course accepted.

jerry: Could you try to ask help from wxpython group?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1176#c2) by @spooning on 7 Jan 2013*


Do I get it right that for some reason RIDE ends up using 2.8.8.1 even if you have 2.8.12.1 installed? I don't know why that would happen.

As Mikko wrote, we have decided to support only wxPython 2.8.12.1 to ease development and testing (see <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1141" title="Document and notify at start-up that wxPython 2.8.12.1 is the minimum supported version"> issue 1141 </a> and <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1139" title="Document and test minimum wxPython and Python versions"> issue 1139 </a> for details). We have removed some support code that made it possible to use older wxPython versions because these older versions didn't really work anyway. At least 2.8.11 and most likely also 2.8.10 still open these days, but all features don't work even with them due to changes to wxPython APIs.

The reason that with 0.54 and 0.55 you got a stacktrace and with 1.0 the dialog is that we changed this dialog to appear earlier. Good to see that at least that feature works as intended.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1176#c3) by jerry57 on 18 Feb 2013*


I have not had any luck getting help in resolving this.  I was able to find that on Mac OS X 10.6 it appears that wxPython 2.8.8.1 is installed by default.  It appears to be located in the following locations:
/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wx-2.8-mac-unicode/wx
/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wx-2.8-mac-unicode/wxPython
/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wx-2.8-mac-unicode/wxPython-2.8.8.1-py2.6.egg-info
/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wxPython_common-2.8.8.1-py2.6.egg-info
/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wxaddons
/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wxaddons-2.8.8.1-py2.6.egg.info

When I went in as root and renamed ALL of these to *-old, I was then able to launch RIDE v1.0.1 without error.  And it now senses my 2.8.12.1 install of wxPython.  All of this was done on a machine with a Fresh/Clean install of OS X 10.6.  I don't know if this breaks anything else at this point though. And I have not found anyway to "uninstall" 2.8.8.1 from the system.  Plus I am sure there should be an easier way to get the system to pickup and use the newer install, but I have not found it yet.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1176#c4) by @mkorpela on 3 Sep 2013*


We are closing this as invalid as this is system specific configuration issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1176#c5) by jerry57 on 3 Sep 2013*


Yes this is a "system specific" issue in that it is Mac OS X specific.  Maybe adding some instructions on how to fix this permanently for ALL Max OS X systems would be a better solution.  What I did above works, but hardly sounds like a proper solution.
