### ISSUE TITLE
Test execution fails when starting from scratch

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1218]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1179) by @mkorpela on 26 Dec 2012*

Started ride.py without any content
Created one test suite file with New Project
Created one test case with trivial content (Log  Hello World!)
Tried to execute tests:

AttributeError: No attribute or settings with name '_test_names_to_run' found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 257, in OnRun
    command = self._create_command()
  File "/usr/local/lib/python2.7/dist-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 275, in _create_command
    self._test_names_to_run)
  File "/usr/local/lib/python2.7/dist-packages/robotide/pluginapi/plugin.py", line 134, in __getattr__
    raise AttributeError("No attribute or settings with name '&#37;s' found" &#37; name)
AttributeError: No attribute or settings with name '_test_names_to_run' found

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1179#c3) by @mkorpela on 27 Dec 2012*


Fixed in <a href="https://github.com/robotframework/RIDE/commit/507a0eab233b7eedde8b34fac0d76ba45825e7d8" rel="nofollow">https://github.com/robotframework/RIDE/commit/507a0eab233b7eedde8b34fac0d76ba45825e7d8</a>
