### ISSUE TITLE
user keyword clicking leads to segmentation fault

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1222]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1183) by granuleg on 7 Jan 2013*

Hi,
i have a segfault  when clicking on a user keyword of a resource file.

i used debian 6.0
RIDE 1.0 running on Python 2.6.6. 

thanks

see log above

ride.py --debugconsole
RIDE - access to the running application
print_stacks() - print current stack traces

&gt;&gt;&gt; /usr/local/lib/python2.6/dist-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp &gt;= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp &gt;= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)

Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_misc.py", line 1342, in Notify
    self.notify()
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14716, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/gridcolorizer.py", line 49, in _coloring_task
    wx.CallAfter(self._coloring_task, task_index, selection_content, row, col+1)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14609, in CallAfter
    assert app is not None, 'No wx.App created yet'
AssertionError: No wx.App created yet
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_misc.py", line 1342, in Notify
    self.notify()
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14720, in Notify
    wx.CallAfter(self.Stop)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14609, in CallAfter
    assert app is not None, 'No wx.App created yet'
AssertionError: No wx.App created yet
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 4763, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4715, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Segmentation fault

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1183#c2) by @mkorpela on 17 Jan 2013*


What wxpython version are you using?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1183#c4) by granuleg on 29 Jan 2013*


Hi,
wxversion version is 2.8.10.1. This bug was found with incomptable
RIDE and pybot version (ride 1.0 and pybot 2.7.6).

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1183#c5) by @mkorpela on 7 Mar 2013*


We are officially supporting only wxpython 2.8.12.1 now. So I'm closing this as wontfix. If you encounter problems with wxpython 2.8.12.1, we can reopen this issue.
