### ISSUE TITLE
wx crash on ride

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1234]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1195) by granuleg on 6 Feb 2013*

hi,

i have a crash with latest version when i try to click on test

thanks

VERSION
=======
ride 1.0.2preview
robotframework &gt; 2.6.7 + parent: 7843:93ead481bc02 tip
python-wxgtk2.8_2.8.12.1-0_i386.deb
python_2.6.6-3+squeeze7_all.deb

LOG
===
$ride.py 
/usr/local/lib/python2.6/dist-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp &gt;= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp &gt;= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)

Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/flatnotebook.py", line 4938, in OnPaint
    dc = wx.BufferedPaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4901, in __init__
    _gdi_.BufferedPaintDC_swiginit(self,_gdi_.new_BufferedPaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/tooltips.py", line 42, in OnShowToolTip
    content = self._grid.get_tooltip_content()
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/kweditor.py", line 124, in get_tooltip_content
    cell = self.cell_under_cursor
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/grid.py", line 78, in cell_under_cursor
    x, y = self.ScreenToClient(wx.GetMousePosition())
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_misc.py", line 564, in GetMousePosition
    return _misc_.GetMousePosition(*args)
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/flatnotebook.py", line 4938, in OnPaint
    dc = wx.BufferedPaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4901, in __init__
    _gdi_.BufferedPaintDC_swiginit(self,_gdi_.new_BufferedPaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/flatnotebook.py", line 4938, in OnPaint
    dc = wx.BufferedPaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4901, in __init__
    _gdi_.BufferedPaintDC_swiginit(self,_gdi_.new_BufferedPaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/flatnotebook.py", line 4938, in OnPaint
    dc = wx.BufferedPaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4901, in __init__
    _gdi_.BufferedPaintDC_swiginit(self,_gdi_.new_BufferedPaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/flatnotebook.py", line 4938, in OnPaint
    dc = wx.BufferedPaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4901, in __init__
    _gdi_.BufferedPaintDC_swiginit(self,_gdi_.new_BufferedPaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/tooltips.py", line 42, in OnShowToolTip
    content = self._grid.get_tooltip_content()
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/kweditor.py", line 124, in get_tooltip_content
    cell = self.cell_under_cursor
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/grid.py", line 78, in cell_under_cursor
    x, y = self.ScreenToClient(wx.GetMousePosition())
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_misc.py", line 564, in GetMousePosition
    return _misc_.GetMousePosition(*args)
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/flatnotebook.py", line 4938, in OnPaint
    dc = wx.BufferedPaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4901, in __init__
    _gdi_.BufferedPaintDC_swiginit(self,_gdi_.new_BufferedPaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/tooltips.py", line 42, in OnShowToolTip
    content = self._grid.get_tooltip_content()
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/kweditor.py", line 124, in get_tooltip_content
    cell = self.cell_under_cursor
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/grid.py", line 78, in cell_under_cursor
    x, y = self.ScreenToClient(wx.GetMousePosition())
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_misc.py", line 564, in GetMousePosition
    return _misc_.GetMousePosition(*args)
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/flatnotebook.py", line 4938, in OnPaint
    dc = wx.BufferedPaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4901, in __init__
    _gdi_.BufferedPaintDC_swiginit(self,_gdi_.new_BufferedPaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/flatnotebook.py", line 4938, in OnPaint
    dc = wx.BufferedPaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4901, in __init__
    _gdi_.BufferedPaintDC_swiginit(self,_gdi_.new_BufferedPaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/agw/customtreectrl.py", line 6127, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 4734, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1195#c1) by @mikahanninen on 6 Feb 2013*


How did you install this version and if you had previous RIDE version, you need to uninstall that first.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1195#c2) by granuleg on 6 Feb 2013*


i uninstalled all ride with pip, and install ride from git with paver=&gt; not working
i then remove my ~/.robotframework and i works, do not know where the problem was, but it works knows
thanks for answerring and give me clue

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1195#c3) by @mikahanninen on 6 Feb 2013*


Good it works now. 

Btw you can install the source distro with 'pip install &lt;tar.gz file&gt;'
