### ISSUE TITLE
RIDE starts but it is not able to open project files and closes again

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1239]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1200) by fabiol... on 14 Feb 2013*

RIDE starts but it is not able to open project files and closes again.

It is a big project and it has always taken time for RIDE to load the files. Now after installing RIDE 1.0, i am able to launch it, it starts the loading process but it stops and it closes by itself.

Here the error report:

Traceback (most recent call last):
  File "C:\Python27\Scripts\ride.py", line 27, in &lt;module&gt;
    main(*sys.argv[1:])
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 76, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 96, in _run
    ride = RIDE(inpath, updatecheck)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line
 40, in __init__
    wx.App.__init__(self, redirect=False)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7978
, in __init__
    self._BootstrapApp()
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7552
, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line
 56, in OnInit
    self.frame.tree.populate(self.model)
  File "C:\Python27\lib\site-packages\robotide\ui\tree.py", line 187, in populat
e
    self._populate_model(model)
  File "C:\Python27\lib\site-packages\robotide\ui\tree.py", line 206, in _popula
te_model
    self._render_datafile(self._root, model.data, 0)
  File "C:\Python27\lib\site-packages\robotide\ui\tree.py", line 253, in _render
_datafile
    self._render_datafile(node, child)
  File "C:\Python27\lib\site-packages\robotide\ui\tree.py", line 246, in _render
_datafile
    node = self._create_node_with_handler(parent_node, controller, index)
  File "C:\Python27\lib\site-packages\robotide\ui\tree.py", line 261, in _create
_node_with_handler
    if not controller.is_used():
  File "C:\Python27\lib\site-packages\robotide\controller\filecontrollers.py", l
ine 801, in is_used
    return any(self._resolve_known_imports())
  File "C:\Python27\lib\site-packages\robotide\controller\filecontrollers.py", l
ine 815, in _resolve_known_imports
    if imp.get_imported_controller() is self:
  File "C:\Python27\lib\site-packages\robotide\controller\settingcontrollers.py"
, line 529, in get_imported_controller
    self.parent.resource_file_controller_factory.find_with_import(self._import)
  File "C:\Python27\lib\site-packages\robotide\controller\filecontrollers.py", l
ine 680, in find_with_import
    assert(res is not None)
AssertionError

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1200#c1) by fabiol... on 14 Feb 2013*


I have python 2.7.2 and the problem occurs in both ride latest releases 1.0. and 1.0.1

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1200#c2) by @mkorpela on 14 Feb 2013*


Thanks for the report!

This is somehow related to a resource import in your data.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1200#c4) by fabiol... on 15 Feb 2013*


Well I've found a workaround. I open ride with an empty dummy project, then, I load only the the directory containing the tests, not one above that also contains libraries and resources folders. 
This way, ride loads everything correctly albeit slowly (it takes 1 and half minutes around)

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1200#c5) by @mkorpela on 18 Feb 2013*


Hi,
Could you install this debug version? <a href="https://dl.dropbox.com/u/40102182/robotframework-ride-1.0.1preview1.0.2.win32.exe" rel="nofollow">https://dl.dropbox.com/u/40102182/robotframework-ride-1.0.1preview1.0.2.win32.exe</a>

It will display information about the import that fails. This might help you to make a small example where the problem can be seen - so we can fix the problem.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1200#c6) by fabiol... on 19 Feb 2013*


Not sure If I can make you quickly an example, but i will try to explain what is going on.

We have a file structure as follows

CommonResources
CommonLib
Project1
  LocalResources
  LocalLib
  Tests
Project2
  LocalResources
  LocalLib
  Tests

In each project we have a set of test cases which can run in simulation and real devices environments without code modification (test case reusability). To do that we rely on resource files that contain keywords which have the same name but do a different thing depending on the environment. 

Our local resource folder contain several configuration resource files (environment dependent) which tell which files to import. 

Each test suite in each project always imports the same  resource file, e.g. "config_File.txt" which it is created before launching ride (by renaming the right configuration file into config_file.txt). We do this on a batch file

If we open only the "tests" folder ride manages to import everything nicely. 

If we open a "Project1" directory ride cannot figure it out the imports, and it gets into a loop which never resolves when trying to import a resource file from CommonResources folder which is imported from a local resource file, eventually ride shutdown.

I tried to delete a local configuration file, but then ride got stuck in the next configuration file. 

I'll attach the report soon

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1200#c7) by fabiol... on 19 Feb 2013*


Error report attached

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1200#c8) by @mkorpela on 19 Feb 2013*


Thanks! I can reproduce the problem.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1200#c10) by @mkorpela on 19 Feb 2013*


I think that I have a fix for this issue. Could you test if it works on your environment?
<a href="https://dl.dropbox.com/u/40102182/robotframework-ride-1.0.1preview2.win32.exe" rel="nofollow">https://dl.dropbox.com/u/40102182/robotframework-ride-1.0.1preview2.win32.exe</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1200#c11) by fabiol... on 19 Feb 2013*


yes it works! Thanks..

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1200#c12) by @mkorpela on 20 Feb 2013*


Fixed after: <a href="https://github.com/robotframework/RIDE/commit/e9d99dee271d28634e46f8e7041cefed4e373d88" rel="nofollow">https://github.com/robotframework/RIDE/commit/e9d99dee271d28634e46f8e7041cefed4e373d88</a>
