### ISSUE TITLE
Text box stuck on UI when renaming a test suite

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1249]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1210) by guy.kisel on 28 Feb 2013*

[INFO]: Started RIDE 1.1 using python version 2.7.3 with wx version 2.8.12.1 in win32.

I selected a test suite and pressed F2 to rename it, changed the name, and tried to click away, but got an error message that a file with that name already exists. After this, the text box would not go away until I closed and reopened RIDE. I only saw this issue once - I can not reproduce it.

In the console, I got this stack trace:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_misc.py", line 1358
, in Notify
    self.notify()
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 1477
1, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\robotide\utils\eventhandler.py", line 71,
in _try_show_warning
    self._show_warning(msg, ctrl, yes_handler)
  File "C:\Python27\lib\site-packages\robotide\utils\eventhandler.py", line 86,
in _show_warning
    yes_handler()
  File "C:\Python27\lib\site-packages\robotide\utils\eventhandler.py", line 57,
in reload_datafile
    self.refresh_datafile(ctrl, event)
  File "C:\Python27\lib\site-packages\robotide\editor\kweditor.py", line 367, in
 refresh_datafile
    self._tree.refresh_datafile(item, event)
  File "C:\Python27\lib\site-packages\robotide\ui\tree.py", line 527, in refresh
_datafile
    to_be_selected = self._get_pending_selection(event)
  File "C:\Python27\lib\site-packages\robotide\ui\tree.py", line 546, in _get_pe
nding_selection
    if not (item.IsOk() and self._click_on_item(flags)):
AttributeError: 'NoneType' object has no attribute 'IsOk'

**Comment by yanne** [comment]
Fixed in 6a18b1ab8a4402d5b2587dff90d218174581b99c
