### ISSUE TITLE
cant open RIDE: "no such table: libraries"

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1254]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1215) by qit... on 6 Mar 2013*

My friend installed RIDE1.0 first time. He cant start ride. 
There is the message show in cmd:

C:\Python27\Scripts&gt;ride.py
error during database validation "no such table: libraries"
removing database "D:\Users\gongxinge615\AppData\Roaming\RobotFramework\ride\lib
rarykeywords.db"
Traceback (most recent call last):
  File "C:\Python27\Scripts\ride.py", line 27, in &lt;module&gt;
    main(*sys.argv[1:])
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 76, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 96, in _run
    ride = RIDE(inpath, updatecheck)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line
 40, in __init__
    wx.App.__init__(self, redirect=False)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7981
, in __init__
    self._BootstrapApp()
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7555
, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line
 44, in OnInit
    librarydatabase.initialize_database()
  File "C:\Python27\lib\site-packages\robotide\spec\librarydatabase.py", line 59
, in initialize_database
    os.remove(DATABASE_FILE)
WindowsError: [Error 32] : 'D:\\Users\\gongxinge615\\AppData\\Roaming\\RobotFram
ework\\ride\\librarykeywords.db'

C:\Python27\Scripts&gt;

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1215#c1) by qit... on 6 Mar 2013*


well. I find the way. I delete this file "D:\Users\gongxinge615\AppData\Roaming\RobotFramework\ride\lib
rarykeywords.db". reinstall RIDE1.1
Then I can start RIDE.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1215#c2) by @mkorpela on 6 Mar 2013*


Seems that for some reason your library database was corrupted and locked.

Have to see if there is a way to handle this situation in a nicer way.
