### ISSUE TITLE
Nonascii resource path problem

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1255]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1216) by docon... on 6 Mar 2013*

ride is opened and then closed when I opened directry, it happend in one of my computers:

D:\&gt;ride.py
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\robotide\ui\actiontriggers.py", line 379, in __call__
    action.act(event)
  File "D:\Python27\lib\site-packages\robotide\action\action.py", line 86, in act
    self.action(event)
  File "D:\Python27\lib\site-packages\robotide\utils\eventhandler.py", line 22, in wrapped
    method(self, event)
  File "D:\Python27\lib\site-packages\robotide\ui\mainframe.py", line 207, in OnOpenDirectory
    self.open_suite(path)
  File "D:\Python27\lib\site-packages\robotide\ui\mainframe.py", line 196, in open_suite
    self._controller.load_datafile(path, LoadProgressObserver(self))
  File "D:\Python27\lib\site-packages\robotide\controller\chiefcontroller.py", line 139, in load_datafile
    datafile = self._load_datafile(path, load_observer)
  File "D:\Python27\lib\site-packages\robotide\controller\chiefcontroller.py", line 148, in _load_datafile
    self._populate_from_datafile(path, datafile, load_observer)
  File "D:\Python27\lib\site-packages\robotide\controller\chiefcontroller.py", line 154, in _populate_from_datafile
    self._create_controllers(datafile, resources)
  File "D:\Python27\lib\site-packages\robotide\controller\chiefcontroller.py", line 162, in _create_controllers
    for r in resources:
TypeError: 'NoneType' object is not iterable

Always include the framework version, Python or Jython version, and
operating system. You can, for example, copy the output of 'pybot/jybot
--version'.
C:\Users\xxxx&gt;pybot --version
Robot Framework 2.7.7 (Python 2.7.3 on win32)

C:\Users\xxxx&gt;jybot --version
Robot Framework 2.7.7 (Jython 2.5.4rc1 on java1.7.0_10)

windows7-32bits/windowsXP

1、java7upadate10
2、Python 2.7.3
3、wxPython2.8-win32-unicode-2.8.12.1-py27
4、Jython 2.5.4rc
5、RF 2.7.7
6、RIDE 1.1

For new features and other enhancements, please use the Enhancement request
template.

All this text can be deleted.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1216#c1) by docon... on 6 Mar 2013*


windows7-32bits doesn't work
windowsXP can work

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1216#c2) by @mkorpela on 7 Mar 2013*


Thanks for the report!

Can you open ride in the following way and see what is written in to View RIDE log:
1) ride.py somefile.txt
==&gt; Will not find that file but should open anyway
2) select the project with the data that you normally use - the directory
3) Open Tools / View RIDE Log

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1216#c3) by docon... on 7 Mar 2013*


I think I have found why it happened. 
It's not about win7 or XP,just because my autoTest project path includes Chinese Characters. So, maybe it's not a bug. 

Does RIDE need to support unascii string path?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1216#c4) by @mkorpela on 12 Mar 2013*


It should support nonascii paths also.

It would be very helpful if you could give a small example that shows the problem.

**Comment by yanne** [comment]
Closing this due to inactivity
