### ISSUE TITLE
Can not open RIDE by error: sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1286]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1248) by qit... on 22 Apr 2013*

Python:2.7.3
RIDE:1.1
Robotframework:2.7.7
OS:WinXP

My friend cant open ride anyway. In cmd window, it shows the error message following. 

C:\Python27\Scripts&gt;ride.py
Creating librarykeywords database to "D:\用户\ex_xxkjb_LF\AppData\Roaming\RobotF
ramework\ride\librarykeywords.db"
Traceback (most recent call last):
  File "C:\Python27\Scripts\ride.py", line 27, in &lt;module&gt;
    main(*sys.argv[1:])
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 76, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 96, in _run
    ride = RIDE(inpath, updatecheck)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line
 40, in __init__
    wx.App.__init__(self, redirect=False)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7981
, in __init__
    self._BootstrapApp()
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7555
, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line
 44, in OnInit
    librarydatabase.initialize_database()
  File "C:\Python27\lib\site-packages\robotide\spec\librarydatabase.py", line 52
, in initialize_database
    _create_database()
  File "C:\Python27\lib\site-packages\robotide\spec\librarydatabase.py", line 37
, in _create_database
    connection = sqlite3.connect(DATABASE_FILE)
sqlite3.OperationalError: unable to open database file

C:\Python27\Scripts&gt;

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1248#c1) by @mkorpela on 23 Apr 2013*


Does your friend have read and write rights to D:\用户\ex_xxkjb_LF\AppData\Roaming\RobotF
ramework\ride\"?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1248#c2) by qit... on 24 Apr 2013*


Yes. I think the problem is the path has none-ascii characters. I try to get the os.environ['appdata'], the path is like D:\\xeb\xb2\ex_xxkjb_LF\AppData\Roaming\.
well, in most machines, D:\用户 is same as D:\Users. but in this machine, it is just chinese path, not D:\users. 
At last I change the source code in settings.py, I replace the chinese to english when setting SETTINGS_DIRECTORY value as following:
SETTINGS_DIRECTORY = os.path.join(os.environ['APPDATA'].replace('用户','Users'), 'RobotFramework', 'ride')
I just deal with it by temporary solution. I dont know how to fix it.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1248#c3) by @mkorpela on 24 Apr 2013*


Thanks for the report!

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1248#c6) by @mikahanninen on 13 Jun 2013*


Fixed by <a href="https://github.com/robotframework/RIDE/commit/0a35a59988d64f535cce01ef9452d0ff0d04a16b" rel="nofollow">https://github.com/robotframework/RIDE/commit/0a35a59988d64f535cce01ef9452d0ff0d04a16b</a>
