### ISSUE TITLE
Cannot install source distribution to a machine that does not have paver installed

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1315]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1277) by trefor.2... on 2 Sep 2013*

I've downloaded the latest sources and paver and done a

paver set_version 1.1.1
paver sdist

This has made a new robotframework-ride-1.1.1.zip and a

python setup.py install works OK. No Problem.

BUT I would like to make a new copy of the windows installable

robotframework-ride-1.1.win32.exe

How can I do this?

Thanks

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1277#c1) by @Tattoo on 3 Sep 2013*


May I ask why do you use paver to run RIDE? For Windows, we have installers for 32- and 64-bit Windows [1]. For Linux, you can install from the sources with `python setup.py install`, as specified in the installation instructions [2].

[1] <a href="https://code.google.com/p/robotframework-ride/downloads/list" rel="nofollow">https://code.google.com/p/robotframework-ride/downloads/list</a>
[2] <a href="https://github.com/robotframework/RIDE/wiki/Installation-Instructions" rel="nofollow">https://github.com/robotframework/RIDE/wiki/Installation-Instructions</a>

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1277#c2) by trefor.2... on 3 Sep 2013*


I don't use paver to run ride, I'll try and explain....

We have used the downloaded version 1.1 and installed it using robotframework-ride-1.1.win32.exe which works without a problem.

However, I was trying to use the latest development version which has some useful bug fixes.

The build procedure uses paver which I've install the development PC and built it using paver sdist. This does not build a new version of robotframework-ride-1.1.win32.exe

I need to install this development version it on a different Window Server, and when I use 
python setup.py install  
on the Window Server - which does not have paver installed, I get an error
 
Traceback (most recent call last):
  File "setup.py", line 8, in &lt;module&gt;
    import paver.tasks
  File "paver-minilib.zip\paver\tasks.py", line 16, in &lt;module&gt;
ImportError: No module named version

Hence my question is it possible for me to generate a new version of the robotframework-ride-1.1.win32.exe on my development Pc sho that I can install the development version on the Windows Server?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1277#c3) by @Tattoo on 4 Sep 2013*


The new zip file created with `paver sdist` should be installable with `python setup.py install` even on machines that do not have paver installed regardless of OS.

Unfortunately this is broken in paver version 1.2.1 [1] and seems that it's going to be fixed in a future release of paver. Therefore, we won't be doing anything about this since it's not an issue with RIDE.

As a workaround, if you installed paver using pip, downgrade to paver 1.2 with command `pip install paver==1.2` and then re-create the zip with `paver sdist`.

You are also able to create Windows installer with `paver wininst`. Unfortunately, you can only create it on a Windows, which therefore doesen't seem to fit your needs -- so I recommend you creating (working) source distribution instead. 

[1] <a href="https://github.com/paver/paver/issues/112" rel="nofollow">https://github.com/paver/paver/issues/112</a>

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1277#c4) by trefor.2... on 17 Sep 2013*


Excellent - That fixed my problem exactly. Thanks very much.  Thank you.
