### ISSUE TITLE
Edit directory init file in Text Edit can not be applied

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1323]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1285) by yanfei428 on 28 Sep 2013*

RIDE 1.1 or 1.2, Python 2.7.5, Win7
Edit directory init file in Text Edit GUI, but cannot be saved.
This means all what modified will be lost on this way to edit directory init file.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1285#c1) by @mkorpela on 30 Sep 2013*


I can not reproduce the problem.

Do you have a specific example case where this problem occurs?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1285#c4) by yanfei428 on 30 Sep 2013*


All my directory init files have the same phenomenon. Here I just pick up one of them as the attachment. By the way, this problem really influences a lot on me, please fixate as soon as possible, my great appreciations!

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1285#c5) by @mkorpela on 30 Sep 2013*


Could you see if there is anything in RIde Log?
Tools / View Ride Log

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1285#c6) by @mkorpela on 1 Oct 2013*


Ok. I can reproduce the problem. Thanks for the information.

Traceback (most recent call last):
  File "src\robotide\editor\texteditor.py", line 287, in &lt;lambda&gt;
    ButtonWithHandler(self, 'Apply Changes', handler=lambda e: self.save()))
  File "src\robotide\editor\texteditor.py", line 419, in save
    self._editor.utf8_text):
  File "src\robotide\editor\texteditor.py", line 175, in validate_and_update
    if not self._sanity_check(data, text):
  File "src\robotide\editor\texteditor.py", line 184, in _sanity_check
    formatted_text = data.format_text(text).encode('UTF-8')
  File "src\robotide\editor\texteditor.py", line 235, in format_text
    return self._txt_data(self._create_target_from(text))
  File "src\robotide\editor\texteditor.py", line 230, in _create_target_from
    target = self._create_target()
  File "src\robotide\editor\texteditor.py", line 246, in _create_target
    return target_class(source=self._data.source)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1285#c7) by @mkorpela on 1 Oct 2013*


This has been around from at least RIDE 1.0

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1285#c9) by @mkorpela on 1 Oct 2013*


Fixed in:
<a href="https://github.com/robotframework/RIDE/commit/48b2488750da17f9ebeab02aca47995ab33227d1" rel="nofollow">https://github.com/robotframework/RIDE/commit/48b2488750da17f9ebeab02aca47995ab33227d1</a>

Still needs testing.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1285#c10) by @mkorpela on 1 Oct 2013*


Testing done.

Marking as Done.
