### ISSUE TITLE
Executing unexecuted testcases on system errors such as Memory error

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1345]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1305) by otlasanju on 14 Nov 2013*

Hi All,

We have a huge number of testcase and most of the times the testcase execution stops in the middle due to Memoryerror by Python . Is there a way we can continue to the test execution for all the unexecuted testcases from the testcase that failed automatically? 
The output.xml provides me the last executed testcase and the argumentfile has the list of all the testcases in the suite ,Is there a way we can automate the execution of remaining testcases as and when the testexecution stops abruptly ?

regards
Sanjay

P.S the error we usually encounter is as below
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\robot\run.py", line 452, in &lt;module&gt;
    run_cli(sys.argv[1:])
  File "C:\Python27\lib\site-packages\robot\run.py", line 415, in run_cli
    RobotFramework().execute_cli(arguments)
  File "C:\Python27\lib\site-packages\robot\utils\application.py", line 44, in execute_cli
    rc = self._execute(arguments, options)
  File "C:\Python27\lib\site-packages\robot\utils\application.py", line 84, in _execute
    error, details = get_error_details()
  File "C:\Python27\lib\site-packages\robot\utils\error.py", line 45, in get_error_details
    details = ErrorDetails()
  File "C:\Python27\lib\site-packages\robot\utils\error.py", line 58, in ErrorDetails
    raise exc_value
MemoryError
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
MIC1 Bandwidth Test                                                                               unexpected error: Traceback (most recent call last):
test finished 11/12/13 09:45:53

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1305#c1) by @mkorpela on 22 Nov 2013*


This is RIDE tool issue tracker.
To find out a solution to your problem, please contact robotframework-users google group.

Closing as invalid.
