### ISSUE TITLE
Error with RIDE installation

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1360]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1320) by tr.yami... on 15 Jan 2014*

I have tried to install RIDE in two different ways.

1. I installed Python 2-7, WXPython 2.7 and RIDE for 64 bit then I got error 
close failed: [Errno 9] Bad file descriptor" returns;
Can RF support install on windows 7

2. I read in articles that 32 bit would be better, so i have all the three softwares in 32 bit then I got error:
Traceback (most recent call last):
  File "&lt;string&gt;", line 3, in &lt;module&gt;
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 38, in &lt;module&gt;
    import FixTk
  File "C:\Python27\lib\lib-tk\FixTk.py", line 65, in &lt;module&gt;
    import _tkinter
ImportError: DLL load failed: &#37;1 is not a valid Win32 application.

So, Please help me ASAP as I am blocked.

Thanks,
Yamini

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1320#c1) by @mkorpela on 15 Jan 2014*


Looks like wxpython problem with the 64 bit version. You could try to install 32 bit unicode version of wxpython2.8.

<a href="http://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1/" rel="nofollow">http://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1/</a>

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1320#c2) by tr.yami... on 16 Jan 2014*


I have tried and I still get the same issue. 

Thing is clicking on RIDE icon does not launch RIDE because of the error.

I have attached for reference.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1320#c3) by tr.yami... on 17 Jan 2014*


I figured the problem and the issue is fixed. But now the issue I am not able to configure selenium2library.

I have tried regular windows installer did not work.
I have tried pip install did not work
I have tried easy install did not work
If I say import Selenium2Library I keep getting the error Selenium2Library is not an internal or external command

Please help me to figure out the problem ASAP

steps:
C:\Python&gt;easy_install selenium
Searching for selenium
Reading <a href="https://pypi.python.org/simple/selenium/" rel="nofollow">https://pypi.python.org/simple/selenium/</a>
Best match: selenium 2.39.0
Downloading <a href="https://pypi.python.org/packages/source/s/selenium/selenium-2.39.0.t" rel="nofollow">https://pypi.python.org/packages/source/s/selenium/selenium-2.39.0.t</a>
ar.gz#md5=3f7aaad3eb52a218854bf0196c9daeda
Processing selenium-2.39.0.tar.gz
Writing c:\users\u6017929\appdata\local\temp\easy_install-dwlemx\selenium-2.39.0
\setup.cfg
Running selenium-2.39.0\setup.py -q bdist_egg --dist-dir c:\users\u6017929\appda
ta\local\temp\easy_install-dwlemx\selenium-2.39.0\egg-dist-tmp-2aehw3
Adding selenium 2.39.0 to easy-install.pth file

Installed c:\python\lib\site-packages\selenium-2.39.0-py2.7.egg
Processing dependencies for selenium
Finished processing dependencies for selenium

C:\Python&gt;easy_install decorator
Searching for decorator
Best match: decorator 3.4.0
Processing decorator-3.4.0-py2.7.egg
decorator 3.4.0 is already the active version in easy-install.pth

Using c:\python\lib\site-packages\decorator-3.4.0-py2.7.egg
Processing dependencies for decorator
Finished processing dependencies for decorator

C:\Python&gt;easy_install docutils
Searching for docutils
Best match: docutils 0.11
Processing docutils-0.11-py2.7.egg
docutils 0.11 is already the active version in easy-install.pth
Installing rst2html.py script to C:\Python\Scripts
Installing rst2latex.py script to C:\Python\Scripts
Installing rst2man.py script to C:\Python\Scripts
Installing rst2odt.py script to C:\Python\Scripts
Installing rst2odt_prepstyles.py script to C:\Python\Scripts
Installing rst2pseudoxml.py script to C:\Python\Scripts
Installing rst2s5.py script to C:\Python\Scripts
Installing rst2xetex.py script to C:\Python\Scripts
Installing rst2xml.py script to C:\Python\Scripts
Installing rstpep2html.py script to C:\Python\Scripts

Using c:\python\lib\site-packages\docutils-0.11-py2.7.egg
Processing dependencies for docutils
Finished processing dependencies for docutils

C:\Python&gt;pip install robotframework-selenium2library
Requirement already satisfied (use --upgrade to upgrade): robotframework-seleniu
m2library in c:\python\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): decorator&gt;=3.3.2 in c:
\python\lib\site-packages\decorator-3.4.0-py2.7.egg (from robotframework-seleniu
m2library)
Requirement already satisfied (use --upgrade to upgrade): selenium&gt;=2.32.0 in c:
\python\lib\site-packages\selenium-2.39.0-py2.7.egg (from robotframework-seleniu
m2library)
Requirement already satisfied (use --upgrade to upgrade): robotframework&gt;=2.6.0
in c:\python\lib\site-packages (from robotframework-selenium2library)
Requirement already satisfied (use --upgrade to upgrade): docutils&gt;=0.8.1 in c:\
python\lib\site-packages\docutils-0.11-py2.7.egg (from robotframework-selenium2l
ibrary)
Cleaning up...

C:\Python&gt;&gt; import Selenium2Library
'Selenium2Library' is not recognized as an internal or external command,
operable program or batch file.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1320#c4) by @mkorpela on 20 Jan 2014*


From what I can see everything was installed correctly.

"import Selenium2Library" is  a python command and you are running it in a normal shell.
type python to get in to python REPL and type the same command there.

Anyway this is not a valid RIDE issue. Please post questions to the robot framework users list in google groups. Closing as invalid.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1320#c5) by maora... on 24 Feb 2014*


I figured the problem and the issue is fixed. ...

how did you fix it? I have the same problem installing RIDE
