### ISSUE TITLE
'View All Tags (F7)' does not work if there are multiple identical tags with different case(upper/lower)

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1370]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1330) by ate.fokk... on 19 Feb 2014*

Using RIDE 1.3.0 and python 2.7.3.

I'm loading an extensive test directory, some tags are uppercased, some are lowercased. Sometimes the same tag is used uppercase and lowercase(due to different committers, not saying this is a good idea, but it happens).

View all tags doesn't work in this case.

This is in the log:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\ui\actiontriggers.py", line 379, in __call__
    action.act(event)
  File "C:\Python27\lib\site-packages\robotide\action\action.py", line 86, in act
    self.action(event)
  File "C:\Python27\lib\site-packages\robotide\utils\eventhandler.py", line 22, in wrapped
    method(self, event)
  File "C:\Python27\lib\site-packages\robotide\ui\mainframe.py", line 248, in OnViewAllTags
    self._view_all_tags_dialog.show_dialog()
  File "C:\Python27\lib\site-packages\robotide\ui\tagdialogs.py", line 114, in show_dialog
    self._execute()
  File "C:\Python27\lib\site-packages\robotide\ui\tagdialogs.py", line 92, in _execute
    self._search_for_tags()
  File "C:\Python27\lib\site-packages\robotide\ui\tagdialogs.py", line 139, in _search_for_tags
    self._tagit[tag_name].append(tag)
KeyError: u'Under_construction'

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1330#c2) by @yanne on 2 Jun 2015*


Fixed in <a href="https://github.com/robotframework/RIDE/commit/d7eb247e840aea357aad3d56ffa15cb76293f9e4" rel="nofollow">https://github.com/robotframework/RIDE/commit/d7eb247e840aea357aad3d56ffa15cb76293f9e4</a>
