### ISSUE TITLE
RIDE IndexError during test execution

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1395]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1355) by guy.kisel on 5 May 2014*

I added the line "self._output(str(traceback.format_exc()))" in the except block of OnRun in testrunnerplugin.py because I've been experiencing random crashes that are difficult to debug without a stack trace. I just experienced a crash, with this stack trace:

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 44438)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 638, in __init__
    self.handle()
  File "/home/sdet/.virtualenvs/robot/local/lib/python2.7/site-packages/robotide/contrib/testrunner/testrunner.py", line 411, in handle
    self.server.callback(name, *args)
  File "/home/sdet/.virtualenvs/robot/local/lib/python2.7/site-packages/robotide/contrib/testrunner/testrunner.py", line 95, in handle
    result_handler(*args)
  File "/home/sdet/.virtualenvs/robot/local/lib/python2.7/site-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 688, in _post_result
    self._handle_end_keyword()
  File "/home/sdet/.virtualenvs/robot/local/lib/python2.7/site-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 726, in _handle_end_keyword
    self._progress_bar.empty_current_keyword()
  File "/home/sdet/.virtualenvs/robot/local/lib/python2.7/site-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 798, in empty_current_keyword
    self._current_keywords.pop()
IndexError: pop from empty list
----------------------------------------
Killed

Version info:
20140505 13:32:02.511 [INFO]: Started RIDE 1.3 using python version 2.7.3 with wx version 2.8.12.1 in linux2.
This is in Ubuntu 12.04.

**Comment by yanne** [comment]
I am not entirely sure what causes the corrupted state in testrunnernplugin, but I at least fixed this problem by just preventing the pop from empty list.
