### ISSUE TITLE
Ride crashes constantly.

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1406]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1366) by derek.robati on 17 Jun 2014*

<a href="http://paste.ubuntu.com/7659748/" rel="nofollow">http://paste.ubuntu.com/7659748/</a>

Xlib:  extension "RANDR" missing on display ":1".
/automation/global/tcli-dev/libraries/f7/F7Library/__init__.py:342: UserWarning: F7Library: NED Interface unavailable: No module named selenium
  warn("F7Library: NED Interface unavailable: &#37;s" &#37; e)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 872, in emit
    stream.write(fs &#37; msg)
  File "/usr/lib/python2.7/StringIO.py", line 213, in write
    _complain_ifclosed(self.closed)
  File "/usr/lib/python2.7/StringIO.py", line 40, in _complain_ifclosed
    raise ValueError, "I/O operation on closed file"
ValueError: I/O operation on closed file
Logged from file ontclient.py, line 77

Tcl_AsyncDelete: async handler deleted by the wrong thread
/usr/local/bin/ride: line 2: 57437 Aborted                 (core dumped) python `which ride.py` $@&#8288;

This is reproduced for me simply by renaming a Test Case or User Keyword, or saving a resource or suite.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1366#c1) by derek.robati on 18 Jun 2014*


I found out today that this wasn't RIDE, or in my case a patched version of RIDE. This was some imported python library wrapping a tcl binary.

Please close.
