### ISSUE TITLE
Memory issue in ride

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1408]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1368) by shikhaml... on 2 Jul 2014*

Hi
In ride in file menu we have open directory option i am trying to open a directory of 13 gb .
if i am open it 2 times it is allow me two open but in 3rd time it gives me error that

""cant create window of class wxWindowClassNR(error 1158: the current process has used all of its system allowances for Window manger objects.)""and its crashing ride.
screen shot of this error is present in attached file.

if i am trying the same operation with small file it is not giving the above error.

i am doing the above procedure because if some changes has been done in resource or library file(eg. if some new keyword has been added into that library) those changes will not reflect in ride so we need open that directory or open the ride again.so is their any way to refresh those data 
without opening ride again.      

so is their any way to resolve this issue.

Thanks
Shikha kabra

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1368#c1) by tomasz.m... on 23 Jul 2014*


I have the same issue but I have a 1,3GB directory and still have the same error.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1368#c2) by Amirhad... on 14 Aug 2014*


One of my coworkers had the same issue with a 70MB directory containing 1300 files.
It seems that RIDE is consuming &gt; 1000 USER objects on a constant basis, and when I looked at his station it was consuming &gt; 9000 USER objects.
Looking at process explorer, I see many handles of type 'Event'.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1368#c3) by @yanne on 19 May 2015*


Do I understand correctly that even though you close RIDE, the memory does not get freed and you are unable to start RIDE again?

**Comment by yanne** [comment]
closing due to lack of information

**Comment by joris255** [comment]
Hello,

I would like to reopen this issue.
config:
python 2.7.5
wx python 2.8.12.1 (msw-unicode)
RIDE 1.5

when loading a directory with a huge number of files, ride has systematic troubles with "windows manager objects handles". here is the console output:

```
C:\Python27\Scripts>python ride.py
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 118, in OnTreeSelection
    panel = self._container.AddPanel(instance_or_class, self._settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 197, in AddPanel
    panel = panel_class(parent=self.panels_container, settings=settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\saving.py", line 29, in __init__
    self._add_editor(editor)
  File "c:\Python27\lib\site-packages\robotide\preferences\saving.py", line 58, in _add_editor
    self.Sizer.AddMany([editor.label(self), (editor.chooser(self),)])
  File "c:\Python27\lib\site-packages\robotide\preferences\widgets.py", line 112, in label
    return wx.StaticText(parent, wx.ID_ANY, self._label)
  File "c:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line 1136, in __init__
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at ..\..\src\msw\control.cpp(159) in wxControl::MSWCreateControl(): CreateWindowEx("STATIC", flags=52000100, ex=00000000) failed
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 118, in OnTreeSelection
    panel = self._container.AddPanel(instance_or_class, self._settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 197, in AddPanel
    panel = panel_class(parent=self.panels_container, settings=settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\saving.py", line 29, in __init__
    self._add_editor(editor)
  File "c:\Python27\lib\site-packages\robotide\preferences\saving.py", line 58, in _add_editor
    self.Sizer.AddMany([editor.label(self), (editor.chooser(self),)])
  File "c:\Python27\lib\site-packages\robotide\preferences\widgets.py", line 112, in label
    return wx.StaticText(parent, wx.ID_ANY, self._label)
  File "c:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line 1136, in __init__
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at ..\..\src\msw\control.cpp(159) in wxControl::MSWCreateControl(): CreateWindowEx("STATIC", flags=52000100, ex=00000000) failed
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 118, in OnTreeSelection
    panel = self._container.AddPanel(instance_or_class, self._settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 197, in AddPanel
    panel = panel_class(parent=self.panels_container, settings=settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\imports.py", line 28, in __init__
    self._add_settings(settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\imports.py", line 40, in _add_settings
    self._create_list_setting_editor(settings, name, help)
  File "c:\Python27\lib\site-packages\robotide\preferences\imports.py", line 44, in _create_list_setting_editor
    self, settings, name, name.capitalize(), help)
  File "c:\Python27\lib\site-packages\robotide\preferences\widgets.py", line 144, in comma_separated_value_editor
    editor = TextField(parent, initial_value)
  File "c:\Python27\lib\site-packages\robotide\widgets\text.py", line 22, in __init__
    wx.TextCtrl.__init__(self, parent, style=flags)
  File "c:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line 1736, in __init__
    _controls_.TextCtrl_swiginit(self,_controls_.new_TextCtrl(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at ..\..\src\msw\control.cpp(159) in wxControl::MSWCreateControl(): CreateWindowEx("EDIT", flags=52010080, ex=00000200) failed
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 118, in OnTreeSelection
    panel = self._container.AddPanel(instance_or_class, self._settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 197, in AddPanel
    panel = panel_class(parent=self.panels_container, settings=settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\editors.py", line 130, in __init__
    settings['Grid'], *args, **kwargs)
  File "c:\Python27\lib\site-packages\robotide\preferences\editors.py", line 36, in __init__
    font_editor = self._create_font_editor()
  File "c:\Python27\lib\site-packages\robotide\preferences\editors.py", line 48, in _create_font_editor
    sizer.AddMany([f.label(self), f.chooser(self)])
  File "c:\Python27\lib\site-packages\robotide\preferences\widgets.py", line 112, in label
    return wx.StaticText(parent, wx.ID_ANY, self._label)
  File "c:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line 1136, in __init__
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at ..\..\src\msw\control.cpp(159) in wxControl::MSWCreateControl(): CreateWindowEx("STATIC", flags=52000100, ex=00000000) failed
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 118, in OnTreeSelection
    panel = self._container.AddPanel(instance_or_class, self._settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 197, in AddPanel
    panel = panel_class(parent=self.panels_container, settings=settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\editors.py", line 65, in __init__
    settings['Text Edit'], *args, **kwargs)
  File "c:\Python27\lib\site-packages\robotide\preferences\editors.py", line 36, in __init__
    font_editor = self._create_font_editor()
  File "c:\Python27\lib\site-packages\robotide\preferences\editors.py", line 48, in _create_font_editor
    sizer.AddMany([f.label(self), f.chooser(self)])
  File "c:\Python27\lib\site-packages\robotide\preferences\widgets.py", line 112, in label
    return wx.StaticText(parent, wx.ID_ANY, self._label)
  File "c:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line 1136, in __init__
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at ..\..\src\msw\control.cpp(159) in wxControl::MSWCreateControl(): CreateWindowEx("STATIC", flags=52000100, ex=00000000) failed
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 118, in OnTreeSelection
    panel = self._container.AddPanel(instance_or_class, self._settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\editor.py", line 197, in AddPanel
    panel = panel_class(parent=self.panels_container, settings=settings)
  File "c:\Python27\lib\site-packages\robotide\preferences\excludes.py", line 100, in __init__
    self._create_sizer()
  File "c:\Python27\lib\site-packages\robotide\preferences\excludes.py", line 105, in _create_sizer
    self._add_text_box(sizer)
  File "c:\Python27\lib\site-packages\robotide\preferences\excludes.py", line 117, in _add_text_box
    value=self._settings.excludes.get_excludes())
  File "c:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line 1736, in __init__
    _controls_.TextCtrl_swiginit(self,_controls_.new_TextCtrl(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at ..\..\src\msw\control.cpp(159) in wxControl::MSWCreateControl(): CreateWindowEx("EDIT", flags=52211044, ex=00000200) failed
```

When loading the big directory first, there is just a popup with `python error` or `pythonw error`. The "edit" tab is not loaded, and the UI is gonna freeze soon. You will have to kill the UI.
When loading a smaller folder first, no error appears. Then switching to the big folder (File/open directory) : `Python Error: Can't crete window of class wxWindozClassNR (error 1158: the current process has used all of its system allowance of handles for Windows Manager objects.)`. The UI is going to freeze soon too.

Feel free to ask more questions.

**Comment by joris255** [comment]
Additionally, to answer the last question, closing and restarting RIDE cleans the memory (the process is killed). It is possible to restart RIDE.
