### ISSUE TITLE
Use Imported library in Plugins

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1423]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1383) by otlasanju on 16 Oct 2014*

Hello,

I am trying to use an imported library in my Plugin with BuiltIn().get_library_instance(NAME_OF_THE_LIBRARY) , but I get AttributeError: 'NoneType' object has no attribute 'namespace'. If I use the same get_library_instance from with in one of the testcase , I am able to access the loaded library . Any thing I am missing here ?

#########################################################################
STACK TRACE
#########################################################################
str: Traceback (most recent call last):
  File "C:\bellagio_eclipse\eclipse-standard-kepler-SR2-RC2-win32\eclipse\plugins\org.python.pydev_3.3.3.201401272249\pysrc\pydevd_resolver.py", line 183, in _getPyDictionary
    attr = getattr(var, n)
  File "C:\Users\skvenkatesh\Documents\robot-workspace\Ride\lib\robot\libraries\BuiltIn.py", line 2435, in _namespace
    return self._context.namespace
AttributeError: 'NoneType' object has no attribute 'namespace'

Regards
Sanjay

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1383#c1) by otlasanju on 16 Oct 2014*


it looks like , when calling the BuiltIn().get_library_instance from a testcase , it is referring to the builtin module from "C:\Python27\Lib\site-packages\robot\libraries\BuiltIn.py" but from with in the plugin file (placed under 'C:\Python27\Lib\site-packages\robotide\ui' folder) , the call to BuiltIn().get_library_instance is being redirected to "C:\Python27\Lib\site-packages\robotide\lib\robot\libraries\BuiltIn.py" with in the robotide folder .
I am importing the Builtin module as from robot.libraries.BuiltIn import BuiltIn

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1383#c2) by @yanne on 19 May 2015*


Hi,

the BuiltIn library instance needs a Robot Framework execution context for instantiation. So it's only possible to use BuiltIn when running the tests. RIDE itself tries to import the libraries without the execution context, thus it fails. 

You see the different imports because RIDE bundles it's own version of RF to ensure compatibility.

The library instantiation issue cannot be resolved in RIDE. If this is still relevant you can ask for help in the Robot Framework users mailing list: <a href="https://groups.google.com/forum/#!forum/robotframework-users" rel="nofollow">https://groups.google.com/forum/#!forum/robotframework-users</a>

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1383#c3) by san... on 19 May 2015*


Thanks for the update
