### ISSUE TITLE
View All Tags Bug

### ISSUE THREAD

**Issue by robotride** [robotframework/RIDE#1492]
If I have tag:
TableCleanUp 

on one test, and:
Table CleanUp

on another test, when I select Tools -> View All Tags, nothing happens. I hooked RIDE into an IDE, and got the following:

Connected to pydev debugger (build 135.1057)
Traceback (most recent call last):
  File "C:\DeploymentUnit\Anaconda\Lib\site-packages\robotframework_ride-1.3-py2.7-win32.egg\robotide\ui\actiontriggers.py", line 379, in __call__
    action.act(event)
  File "C:\DeploymentUnit\Anaconda\Lib\site-packages\robotframework_ride-1.3-py2.7-win32.egg\robotide\action\action.py", line 86, in act
    self.action(event)
  File "C:\DeploymentUnit\Anaconda\Lib\site-packages\robotframework_ride-1.3-py2.7-win32.egg\robotide\utils\eventhandler.py", line 22, in wrapped
    method(self, event)
  File "C:\DeploymentUnit\Anaconda\Lib\site-packages\robotframework_ride-1.3-py2.7-win32.egg\robotide\ui\mainframe.py", line 248, in OnViewAllTags
    self._view_all_tags_dialog.show_dialog()
  File "C:\DeploymentUnit\Anaconda\Lib\site-packages\robotframework_ride-1.3-py2.7-win32.egg\robotide\ui\tagdialogs.py", line 114, in show_dialog
    self._execute()
  File "C:\DeploymentUnit\Anaconda\Lib\site-packages\robotframework_ride-1.3-py2.7-win32.egg\robotide\ui\tagdialogs.py", line 92, in _execute
    self._search_for_tags()
  File "C:\DeploymentUnit\Anaconda\Lib\site-packages\robotframework_ride-1.3-py2.7-win32.egg\robotide\ui\tagdialogs.py", line 139, in _search_for_tags
    self._tagit[tag_name].append(tag)
KeyError: u'Table CleanUp'

**Comment by yanne** [comment]
This should already be fixed in RIDE 1.4, please try to upgrade.

**Comment by robotride** [comment]
In 1.4, the issue no longer hampers the 'View all tags' UI from coming up. Good stuff!

Unfortunately, both tags show up under the same tag in the 'View all tags' UI. Thus, if I have two tests, with the tag names I noted in this ticket, when 'View all tags' UI appears, it shows "TableCleanUp" with 2 Occurrences, and doesn't break out "Table CleanUp" as a different tag. Should I write a new ticket for this? Or keep it contained here? Thx.

**Comment by yanne** [comment]
Tag name normalisation is done because that's how Robot Framework groups tags in report. However, it might be useful for RIDE to show the tags as they are, or at least offer an option to do so. Since the original bug was fixed already, I'll edit this issue.
