### ISSUE TITLE
Should not crash when removing old log files fails

### ISSUE THREAD

**Issue by godchaser** [robotframework/RIDE#1539]
I just upgraded on our ubuntu 14.04 test machine  robotframework-ride-1.5a2 -> robotframework-ride-1.5 and now I get attached exception. ride 1.5a2 versions worked fine. 
Robot Framework 2.9.2 (Python 2.7.6 on linux2)
```
$ ride.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/robotide/__init__.py", line 73, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/usr/local/lib/python2.7/dist-packages/robotide/__init__.py", line 99, in _run
    ride = RIDE(inpath, updatecheck)
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/application.py", line 42, in __init__
    wx.App.__init__(self, redirect=False)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/application.py", line 55, in OnInit
    coreplugins.get_core_plugins())
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/pluginloader.py", line 30, in __init__
    standard_classes + self._find_classes(load_dirs) ]
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/pluginconnector.py", line 23, in PluginFactory
    return BrokenPlugin(utils.get_error_details(), plugin_class)
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/pluginconnector.py", line 69, in __init__
    + 'Error: ' + error
TypeError: cannot concatenate 'str' and 'tuple' objects
```

**Comment by yanne** [comment]
Hi, 

can you try to debug this a bit further, because others (including me) have not encountered the same problem.

Can you try to change L23 of `pluginconnector.py` with simple `raise`. That will re-raise the original exception, and all give (hopefully) relevant information about the root cause of this.

**Comment by godchaser** [comment]
When i changed the lines:
except Exception:
        raise
        return BrokenPlugin(utils.get_error_details(), plugin_class)

Then I got error:
$ ride.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/robotide/__init__.py", line 73, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/usr/local/lib/python2.7/dist-packages/robotide/__init__.py", line 99, in _run
    ride = RIDE(inpath, updatecheck)
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/application.py", line 42, in __init__
    wx.App.__init__(self, redirect=False)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/application.py", line 55, in OnInit
    coreplugins.get_core_plugins())
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/pluginloader.py", line 30, in __init__
    standard_classes + self._find_classes(load_dirs) ]
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/pluginconnector.py", line 21, in PluginFactory
    plugin = plugin_class(application)
  File "/usr/local/lib/python2.7/dist-packages/robotide/log/log.py", line 44, in __init__
    self._remove_old_log_files()
  File "/usr/local/lib/python2.7/dist-packages/robotide/log/log.py", line 56, in _remove_old_log_files
    os.remove(fname)
OSError: [Errno 1] Operation not permitted: '/tmp/ride.log'

And then I deleted the /tmp/ride.log file and it works now. So it seems it has to do something with writing log file. We are running ride on same machine with multiple users. Maybe it should have been better if there was no global /tmp/ride.log file, but log per user.

**Comment by HelioGuilherme66** [comment]
Hi,

That /tmp/ride.log file must be an old file (or from other origin than
RIDE). Current RIDE creates temporary log files, using an <uuid>-ride.log
filename format to allow different RIDE sessions.

**Comment by godchaser** [comment]
You are right, now I see that somebody used explicit log path in some runner script. Sorry for all the trouble :)

**Comment by mekerhult** [comment]
I am running RIDE on Windows and got the same problem when stepping from 1.5a2 -> 1.5.
I have removed all files in my temp directory, but still RIDE complains that it cannot access the log file when I open a second instance of RIDE. It seems like the second instance always wants to access the logfile the first instance created.

This is the output I get (modded L23 in pluginconnector.py)

C:\Users\maek>ride.py
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 73, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 99, in _run
    ride = RIDE(inpath, updatecheck)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line
 42, in __init__
    wx.App.__init__(self, redirect=False)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7981
, in __init__
    self._BootstrapApp()
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7555
, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line
 55, in OnInit
    coreplugins.get_core_plugins())
  File "C:\Python27\lib\site-packages\robotide\application\pluginloader.py", lin
e 30, in __init__
    standard_classes + self._find_classes(load_dirs) ]
  File "C:\Python27\lib\site-packages\robotide\application\pluginconnector.py",
line 21, in PluginFactory
    plugin = plugin_class(application)
  File "C:\Python27\lib\site-packages\robotide\log\log.py", line 44, in __init__
    self._remove_old_log_files()
  File "C:\Python27\lib\site-packages\robotide\log\log.py", line 56, in _remove_
old_log_files
    os.remove(fname)
WindowsError: [Error 32] Det gÕr inte att komma Õt filen eftersom den
anvõnds av en annan process: 'c:\\users\\rtlmaek\\appdata\\local\\temp\\2c0f1e89
-05c8-449e-8587-df7adc41436d-ride.log'

I have stepped back to 1.5a2 and then it works.

**Comment by HelioGuilherme66** [comment]
On Mon, Nov 16, 2015 at 12:22 PM, mekerhult <notifications@github.com>
wrote:

> I am running RIDE on Windows and got the same problem when stepping from
> 1.5a2 -> 1.5.
> I have removed all files in my temp directory, but still RIDE complains
> that it cannot access the log file when I open a second instance of RIDE.
> It seems like the second instance always wants to access the logfile the
> first instance created.
>
Yes the second instance wants to delete all the temporary *-ride.log files.
But Windows is too picky about this a causes the error.

If you want to fix this, you may edit the log.py file at:
C:\\Python27\\Lib\\site-packages\\robotide\\log.py

at line near 58, edit to:
```
            except OSError or IOError as e:
                print >> sys.stderr, e
                pass
```
You may omit the print line, if not you must import sys, like, for example
at line 21:
```
import sys
```

If you feel brave, you may test my fork and branch, which allows to run
RIDE with wxPython 2.8, 2.9 and 3.0. I tested it in Windows 7 and allows to
have several RIDE sessions running.

https://github.com/HelioGuilherme66/RIDE/tree/wxPython3-compatibility

**Comment by yanne** [comment]
@HelioGuilherme66: can you make a separate PR about fixing this log issue. I'd like to merge it and release 1.5.1 as soon as convenient.
