### ISSUE TITLE
Error in RIDE startup

### ISSUE THREAD

**Issue by KowKiller** [robotframework/RIDE#1549]
After a fresh install with pip, I tried to run RIDE.
The main window flashed for a moment and then closed with this error:

```
C:\Python27\Scripts>python ride.py
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 73, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 99, in _run
    ride = RIDE(inpath, updatecheck)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line 42, in __init__
    wx.App.__init__(self, redirect=False)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line 61, in OnInit
    self._find_robot_installation()
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line 108, in _find_robot_installation
    publish.get_html_message('no_robot'), notify_user=True
  File "C:\Python27\lib\site-packages\robotide\publish\__init__.py", line 128, in get_html_message
    os.path.dirname(__file__), 'html', '{}.html'.format(name))).read()
IOError: [Errno 2] No such file or directory: 'C:\\Python27\\lib\\site-packages\\robotide\\publish\\html\\no_robot.html'
```
I manually added an empty no_robot.html file to that path and I was able to run the editor correctly.

**Comment by yanne** [comment]
Thanks @HelioGuilherme66 for the patch

**Comment by whatswhat** [comment]
谢谢 @HelioGuilherme66 重新安装了下robotframework就可以用了
pip install robotframework
