### ISSUE TITLE
IOError During Ride startup when robotframework is not installed

### ISSUE THREAD

**Issue by sknauth** [robotframework/RIDE#1558]
Detected in Ride1.5 installed in a plain virtualenv on Ubuntu 12.04. Robotframework ist NOT installed. Executing ride.py results in a IOError. Workaround just install Robotframework.

Traceback (most recent call last):
  File "/home/neu/ride/local/lib/python2.7/site-packages/robotide/__init__.py", line 73, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/home/neu/ride/local/lib/python2.7/site-packages/robotide/__init__.py", line 99, in _run
    ride = RIDE(inpath, updatecheck)
  File "/home/neu/ride/local/lib/python2.7/site-packages/robotide/application/application.py", line 42, in __init__
    wx.App.__init__(self, redirect=False)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/home/neu/ride/local/lib/python2.7/site-packages/robotide/application/application.py", line 61, in OnInit
    self._find_robot_installation()
  File "/home/neu/ride/local/lib/python2.7/site-packages/robotide/application/application.py", line 108, in _find_robot_installation
    publish.get_html_message('no_robot'), notify_user=True
  File "/home/neu/ride/local/lib/python2.7/site-packages/robotide/publish/__init__.py", line 128, in get_html_message
    os.path.dirname(__file__), 'html', '{}.html'.format(name))).read()
IOError: [Errno 2] No such file or directory: '/home/neu/ride/local/lib/python2.7/site-packages/robotide/publish/html/no_robot.html'

**Comment by yanne** [comment]
This is fixed by #1551, I'll try to have to create a release during the weekend.
