### ISSUE TITLE
Manage Plugins not working 1.5.1 (wxPython3)

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#1576]
When we select "Manage Plugins" the following errors are printed:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/robotide/ui/actiontriggers.py", line 377, in __call__
    action.act(event)
  File "/usr/lib/python2.7/site-packages/robotide/action/action.py", line 86, in act
    self.action(event)
  File "/usr/lib/python2.7/site-packages/robotide/utils/eventhandler.py", line 24, in wrapped
    method(self, event)
  File "/usr/lib/python2.7/site-packages/robotide/ui/mainframe.py", line 253, in OnManagePlugins
    self._plugin_manager.show(self._application.get_plugins())
  File "/usr/lib/python2.7/site-packages/robotide/ui/pluginmanager.py", line 31, in show
    self._tab = _PluginPanel(self._notebook, plugins, self._show_tab)
  File "/usr/lib/python2.7/site-packages/robotide/ui/pluginmanager.py", line 47, in __init__
    sizer.Add(self._create_body(plugins, activation_callback), 1, flag=wx.EXPAND|wx.ALL, border=16)
  File "/usr/lib/python2.7/site-packages/robotide/ui/pluginmanager.py", line 69, in _create_body
    flag=wx.ALIGN_CENTER_HORIZONTAL)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py", line 14453, in Add
    return _core_.Sizer_Add(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ./src/common/sizer.cpp(1401) in DoInsert(): too many items (3 > 2*1) in grid sizer (maybe you should omit the number of either rows or columns?)
```

**Comment by yanne** [comment]
Fixed by #1578.
