### ISSUE TITLE
Importing test library "RemoteSwingLibrary" fails

### ISSUE THREAD

**Issue by mikaheikkinen** [robotframework/RIDE#1583]
Trace:

Initializing test library 'RemoteSwingLibrary' with no arguments failed: RobotNotRunningError: Cannot access execution context
Traceback (most recent call last):
  File "C:\apps\python\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 184, in _get_instance
    return libcode(*self.positional_args, **self.named_args)
  File "D:\dev_ac16\robot\tex\nadc\suite\testcases\nadc_lite\remoteswinglibrary-2.0.3.jar\RemoteSwingLibrary.py", line 216, in __init__
    self._create_env(bool(debug), port != 'TEST')
  File "D:\dev_ac16\robot\tex\nadc\suite\testcases\nadc_lite\remoteswinglibrary-2.0.3.jar\RemoteSwingLibrary.py", line 242, in _create_env
    BuiltIn().set_global_variable('\${REMOTESWINGLIBRARYPATH}', self._escape_path(RemoteSwingLibrary.AGENT_PATH))
  File "C:\apps\python\Lib\site-packages\robot\libraries\BuiltIn.py", line 1307, in set_global_variable
    name = self._get_var_name(name)
  File "C:\apps\python\Lib\site-packages\robot\libraries\BuiltIn.py", line 1315, in _get_var_name
    name = self._resolve_possible_variable(orig)
  File "C:\apps\python\Lib\site-packages\robot\libraries\BuiltIn.py", line 1323, in _resolve_possible_variable
    resolved = self._variables.replace_string(name)
  File "C:\apps\python\Lib\site-packages\robot\libraries\BuiltIn.py", line 74, in _variables
    return self._namespace.variables
  File "C:\apps\python\Lib\site-packages\robot\libraries\BuiltIn.py", line 70, in _namespace
    return self._get_context().namespace
  File "C:\apps\python\Lib\site-packages\robot\libraries\BuiltIn.py", line 65, in _get_context
    raise RobotNotRunningError('Cannot access execution context')
  File "C:\apps\python\Lib\site-packages\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\apps\python\Lib\site-packages\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\apps\python\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 50, in TestLibrary
    lib.create_handlers()
  File "C:\apps\python\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 109, in create_handlers
    self._create_handlers(self.get_instance())
  File "C:\apps\python\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 176, in get_instance
    self._libinst = self._get_instance(self._libcode)
  File "C:\apps\python\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 186, in _get_instance
    self._raise_creating_instance_failed()
  File "C:\apps\python\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 263, in _raise_creating_instance_failed
    % (self.name, args_text, msg, details))

**Comment by pekkaklarck** [comment]
I think this is a bug in the library. It shouldn't call `BuiltIn().set_global_variable()` in its `__init__`. RIDE tries to create an instance of the library similarly as Robot does, but because Robot isn't actually running `set_global_variable` fails.

RIDE could possibly stub `BuiltIn` so that calls like this wouldn't fail. A much better solution is that the library itself avoids such calls. This is already reported in RetemoSwingLibrary tracker: https://github.com/robotframework/remoteswinglibrary/issues/29

@yanne and others, what do you think about this? I would be in favor of closing this as wontfix.

**Comment by pekkaklarck** [comment]
Oooops, didn't meant to actually close this yet. Annoying for GitHub to have Close and Comment buttons so close to each others.

**Comment by yanne** [comment]
I really think this should be fixed in the library itself, or even in RF. Adding a workaround to RIDE is a far worse option.

**Comment by pekkaklarck** [comment]
Agreed.
