### ISSUE TITLE
Inefective Delete tag button in View All Tags dialog

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#1594]
After selecting a tag and confirming the action, the tag is not deleted from tests (and remains in dialog).

This was detected when fixing #1588.

**Comment by HelioGuilherme66** [comment]
This is the console output:
`Traceback (most recent call last):
  File "/home/helio/github/RIDE/src/robotide/ui/tagdialogs.py", line 247, in OnDelete
    tag.execute(DeleteTag())
  File "/home/helio/github/RIDE/src/robotide/controller/basecontroller.py", line 25, in execute
    return command.execute(self)
  File "/home/helio/github/RIDE/src/robotide/controller/commands.py", line 178, in execute
    tag.delete()
  File "/home/helio/github/RIDE/src/robotide/controller/tags.py", line 45, in delete
    self.controller._tags.remove(unicode(self.name))
AttributeError: 'Tags' object has no attribute 'remove'
`
I am a bit stuck here, went to compare with ChangeTag (Rename tag) which is working, but can't reach a conclusion. Anyone would give a try in finding the bug?

**Comment by yanne** [comment]
I can take a look at this.
