### ISSUE TITLE
[DEV] When running tests in Windows with RIDE started from command line Unicode Errors are shown

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#1607]
I am running RIDE from a command window in Windows 7.
I have installed a text colorizer ANSICON. The testrunner plugin is receiving colors from this and the errors are shown in console (only here, all works fine in GUI).

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 367, in OnTimer
    self.OnProcessEnded(None)
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 334, in OnProcessEnded
    self.get_current_profile())
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 251, in get_output_and_errors
    self._process.get_errors(), self._process.get_returncode()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 308, in get_errors
    return self._error_stream.pop()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 400, in pop
    return result.decode('UTF-8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc1 in position 58: invalid start byte 
```

I know how to fix the errors outputting (in this particular setup), by changing code in line 400, to:

```
return result.decode('UTF-8', 'ignore')
```

With this change there will be no errors in console but now in GUI there will be an error (localized, but translates to: ...\ansicon not recognized as an internal or external, system program or batch file.)
The text is shown in red color (here in **bold**), and due to my code change some unicode chars are absent and I put them in _italic_:

> command: pybot.bat --argumentfile c:\users\helio\appdata\local\temp\RIDEv4ze3k.d\argfile.txt --listener C:\GitHub\RIDE\src\robotide\contrib\testrunner\TestRunnerAgent.py:51663:False E:\wondows\import_test.robot
> **'"C:\Windows\system32\ansicon"' n**_ã_**o** _é_ **reconhecido como um comando interno ou externo, programa operacional ou ficheiro batch.**
> # 
> 
> Import Test             
> # 
> 
> Use case                                                                                             | PASS |
> ---
> 
> (...)

@pekkaklarck and @yanne What do you think is best? Leave as it is, or change like I did (or other options)?
Thanks.

**Comment by yanne** [comment]
The most important thing in these cases is not to break functionality for users that are not using the text coloriser. If the coloriser can be supported without any special cases, it's ok to change the existing code, but otherwise I wouldn't do anything.

**Comment by friesan** [comment]
Hello!
have the same problem while running tests

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplug
in.py", line 367, in OnTimer
    self.OnProcessEnded(None)
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplug
in.py", line 334, in OnProcessEnded
    self.get_current_profile())
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py"
, line 251, in get_output_and_errors
    self._process.get_errors(), self._process.get_returncode()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py"
, line 308, in get_errors
    return self._error_stream.pop()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunner.py"
, line 400, in pop
    return result.decode('UTF-8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xad in position 9: invalid s
tart byte


The given solution above didn't help. Please give me some other tips to fix the problem.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
