### ISSUE TITLE
Calling method 'report_file' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 

### ISSUE THREAD

**Issue by 359274651** [robotframework/RIDE#1634]
Hello , i have a question ,i wang to solution the problem, i will run the robotframework-ride ,the browser is firefox ,but the browser is too long of the response time,so throw the execption ,follow this:

[ ERROR ] Calling method 'log_message' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'log_message' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'end_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'log_message' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'log_message' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'end_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'log_message' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'end_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'start_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'end_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'end_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'start_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
[ ERROR ] Calling method 'start_keyword' of listener 'D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] 
Traceback (most recent call last):
File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
self.filehandler.flush()
File "D:\Python27\lib\socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
self.filehandler.flush()
File "D:\Python27\lib\socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
self.filehandler.flush()
File "D:\Python27\lib\socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
self.filehandler.flush()
File "D:\Python27\lib\socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
self.filehandler.flush()
File "D:\Python27\lib\socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
self.filehandler.flush()
File "D:\Python27\lib\socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
self.filehandler.flush()
File "D:\Python27\lib\socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] 
Traceback (most recent call last):
File "D:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
self.filehandler.flush()
File "D:\Python27\lib\socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053]

**Comment by HelioGuilherme66** [comment]
@359274651 Do you still see these errors? If not, please close this issue. Thanks.
Are you using RIDE 1.5.2.1?
