### ISSUE TITLE
RIDE crashes if parsed user keywords contain invalid data

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#168]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=133) by c.martin.taylor on 4 May 2009*

See the attached RF project in ZIPped format.  I created this trivial test
suite, test and resource file all with RIDE, based on the
testcase_template.tsv that comes with Robot Framework.  RIDE lets you
create and save the Resource file using File--&gt;New Resource but when you
try to import the resource file from the test file, or even just open the
resource file in RIDE, you get the following:

Traceback (most recent call last):
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line
30, in wrapped
    method(self, event)
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line
492, in OnNewResource
    self._show_import_editor_dialog('Resource', ResourceImportDialogEditor)
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line
502, in _show_import_editor_dialog
    item = self._data.new_import(type_,  name, dlg.get_value())
  File "C:\Python25\Lib\site-packages\robotide\model\lists.py", line 70, in
new_import
    context.APP.open_resource(res_path)
  File "C:\Python25\Lib\site-packages\robotide\layout\application.py", line
39, in open_resource
    resources = self.model.open_resource(path)
  File "C:\Python25\Lib\site-packages\robotide\model\datamodel.py", line
47, in open_resource
    resource = ResourceFile(path)
  File "C:\Python25\Lib\site-packages\robotide\model\model.py", line 60, in
ResourceFile
    return _ResourceFile(data)
  File "C:\Python25\Lib\site-packages\robotide\model\model.py", line 371,
in __init__
    _AbstractDataFile.__init__(self, data)
  File "C:\Python25\Lib\site-packages\robotide\model\model.py", line 76, in
__init__
    self.keywords = _UserKeywordList(self, data.user_keywords)
  File "C:\Python25\Lib\site-packages\robotide\model\lists.py", line 33, in
__init__
    self._parse_data(data)
  File "C:\Python25\Lib\site-packages\robotide\model\model.py", line 536,
in _parse_data
    self.append(UserKeyword(self.parent, kw))
  File "C:\Python25\Lib\site-packages\robotide\model\model.py", line 465,
in __init__
    _ComplexData.__init__(self, suite, ukdata, name)
  File "C:\Python25\Lib\site-packages\robotide\model\model.py", line 400,
in __init__
    self._parse_data(data)
  File "C:\Python25\Lib\site-packages\robotide\model\model.py", line 480,
in _parse_data
    self._parse_settings(data)
  File "C:\Python25\Lib\site-packages\robotide\model\model.py", line 485,
in _parse_settings
    self.settings['Arguments'] = Arguments(self, data.args, data.defaults,
data.varargs)
AttributeError: UserErrorHandler instance has no attribute 'args'

If you remove the 
    Resource ~Resources/My_Keywords.tsv
line from RIDE_Bug_Test.tsv then you can open the project OK in RIDE.  As
soon as this line is added back, you get the errors listed above.

This bug also happens if you generate a .html resource file instead of a
.tsv resource file.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=133#c1) by c.martin.taylor on 6 May 2009*


I found that the real source of this bug is the way I expressed the arguments to the
keyword in the resource file.  I did it like:

My User Keyword | [Arguments] | Arg1 | Arg2 |				

where the correct notation is:

My User Keyword | [Arguments] | ${Arg1} | ${Arg2} |

With this fix to the resource file it opens OK with RIDE.

BUT I still think this is a bug in the way it is (NOT) handled.  The failure looks
much more drastic than the simple error that caused it.  A suitable error message to
tell the user about the mistake would be much more useful.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=133#c2) by @yanne on 14 May 2009*


It is probably true that we should try to give more informative error messages in
these kinds of situations. This particular error message comes actually from RF code
and therein lies the problem: We use RF modules for every kind of parsing and invalid
data can break it in really many places. Wrapping them all in try-excepts is quite
much work, and will probably not be prioritized very highly.

Anyway, I'll keep this issue open, since it needs to addressed at some point.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=133#c4) by @yanne on 22 Sep 2009*


We'll going to investigate this a bit for 0.19.
As an aside, user keyword arguments should be validated by RIDE to avoid serializing
invalid user keywords, see <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=249" title="Validate arguments set to user keywords"> issue 249 </a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=133#c5) by @pekkaklarck on 23 Sep 2009*


I tested that RIDE really blows up badly when user keyword arguments are invalid. Now
that arguments are validated (<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=249" title="Validate arguments set to user keywords"> issue 249 </a>) it's not possible to create this kind of
invalid tests from RIDE anymore. Existing test data may obviously have invalid
arguments and that situation should be handled more gracefully than now.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=133#c6) by @pekkaklarck on 24 Sep 2009*


I investigated this a bit. Good new is that I found the reason for this behavior but
the bad news is that I don't think there's any good way to fix it without changing
the core framework.

When parsing keyword arguments fails, RF creates UserErrorHandler instead of normal
UserKeywordHandler, and this object is what RIDE gets in this case. These objects
only have the error message and no original data. They don't even have all the same
attributes as normal UserKeywordHandlers which causes the error in the description:
"AttributeError: UserErrorHandler instance has no attribute 'args'".

As there's not original data left in UserErrorHanlers other than the keyword name,
fixing this on RIDE side alone is problematic. The patch below allows loading data
containing invalid arguments, but the loaded user keyword will be totally empty. If
such test data is saved, all original data is obviously overwritten. 

We are thus left with two nasty choices: selecting between RIDE blowing up totally
onto users face and possible data loss. A real fix is changing the parsing logic on
RF side and I already submitted an issue about it:
<a href="https://code.google.com/p/robotframework/issues/detail?id=403" rel="nofollow">https://code.google.com/p/robotframework/issues/detail?id=403</a>


Index: src/robotide/model/tcuk.py
===================================================================
--- src/robotide/model/tcuk.py	(<a href="https://code.google.com/p/robotframework-ride/source/detail?r=918">revision 918</a>)
+++ src/robotide/model/tcuk.py	(working copy)
@&#8288;@&#8288; -69,6 +69,9 @&#8288;@&#8288;
 class UserKeyword(_TcUkBase):
 
     def __init__(self, datafile, data=None, name=None):
+        if data and data.type == 'error':
+            name = data.name
+            data = None
         _TcUkBase.__init__(self, datafile, data, name)
         self.settings = UserKeywordSettings(data)
         self.source = datafile.name

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=133#c7) by @pekkaklarck on 24 Sep 2009*


My feeling is that RIDE crashing is better than data loss especially because 1) this
is very rare, and 2) it's not possible anymore to create this kind of data from RIDE
(<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=249" title="Validate arguments set to user keywords"> issue 249 </a>). I'll thus descope this from 0.19 to 1.0, which will happen only after RF
2.2. I'll also raise the severity slightly as we definitely don't want crashers in 1.0.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=133#c8) by @pekkaklarck on 11 Aug 2010*


RF's parsing modules were rewritten in RF 2.5 and nowadays user keyword arguments (or other user keyword content) is not validated at parsing time. That fixes this problem. I even verified that the original example file can be opened fine. I assume this has been fixed since RIDE 0.25.
