### ISSUE TITLE
BUG?-----Ride Setting Page Truncated

### ISSUE THREAD

**Issue by luopeijie** [robotframework/RIDE#1712]
Help----I met a strange thing that when I open the Ride Setting Page, the Page is Truncted. I can not see the "Arguments" Field and other Field below it.

Environment:
1. PC system: Win10 x64  Lenovo-E470
2. wxPython  version: 4.0.0b1
3. robotframework-ride version: 2.0a1

**Comment by luopeijie** [comment]
Ride log info as follows:

20170816 12:01:59.304 [INFO]: Found Robot Framework version 3.0.2 from 'D:\Program Files (x86)\Python27\lib\site-packages\robotframework-3.0.2-py2.7.egg\robot'.

20170816 12:01:59.304 [INFO]: Started RIDE 2.0a1 using python version 2.7.13 with wx version 3.0.2.0 in win32.

20170816 12:03:35.670 [WARN]: Importing test library "E:\api-portal-qa（from Amy）\api-portal-qa\testsuites\scripts/Conductor.py" failed

Traceback (most recent call last):
'ascii' codec can't decode byte 0xa3 in position 260: ordinal not in range(128)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\running\testlibraries.py", line 46, in TestLibrary
    return_source=True)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\utils\importer.py", line 67, in import_class_or_module
    self._raise_import_failed(name, err)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\utils\importer.py", line 103, in _raise_import_failed
    raise DataError('\n'.join(msg))


20170816 12:05:18.974 [WARN]: Importing test library "E:\api-portal-qa（from Amy）\api-portal-qa\testsuites\scripts/Conductor.py" failed

Traceback (most recent call last):
'ascii' codec can't decode byte 0xa3 in position 260: ordinal not in range(128)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\running\testlibraries.py", line 46, in TestLibrary
    return_source=True)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\utils\importer.py", line 67, in import_class_or_module
    self._raise_import_failed(name, err)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\utils\importer.py", line 103, in _raise_import_failed
    raise DataError('\n'.join(msg))


20170816 12:05:23.256 [WARN]: Importing test library "E:\api-portal-qa（from Amy）\api-portal-qa\testsuites\scripts/TestLogin.py" failed

Traceback (most recent call last):
'ascii' codec can't decode byte 0xa3 in position 260: ordinal not in range(128)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\running\testlibraries.py", line 46, in TestLibrary
    return_source=True)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\utils\importer.py", line 67, in import_class_or_module
    self._raise_import_failed(name, err)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\utils\importer.py", line 103, in _raise_import_failed
    raise DataError('\n'.join(msg))


20170816 12:05:23.396 [WARN]: Importing test library "E:\api-portal-qa（from Amy）\api-portal-qa\testsuites\scripts/TestCases/UserAccountTest.py" failed

Traceback (most recent call last):
'ascii' codec can't decode byte 0xa3 in position 260: ordinal not in range(128)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\running\testlibraries.py", line 46, in TestLibrary
    return_source=True)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\utils\importer.py", line 67, in import_class_or_module
    self._raise_import_failed(name, err)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\lib\robot\utils\importer.py", line 103, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by luopeijie** [comment]
Open a test case, Ride Info as follows:

20170816 12:33:28.653 [INFO]: Found Robot Framework version 3.0.2 from 'D:\Program Files (x86)\Python27\lib\site-packages\robotframework-3.0.2-py2.7.egg\robot'.

20170816 12:33:28.653 [INFO]: Started RIDE 2.0a1 using python version 2.7.13 with wx version 3.0.2.0 in win32.

**Comment by luopeijie** [comment]
If It Informed me that I have the wrong version? I used the win64 system, Log informed me that I Started RIDE in win32, so how to deal with it? and which one I got the wrong verion, wx, python or ride? thanks a log

**Comment by HelioGuilherme66** [comment]
First, I wonder where did you get the package to install RIDE? It was not from the official version 1.5.2.1, for example with `pip install robotframework-ride`.
Second, the errors you are seeing are from robotframework inside RIDE installation, and not from a the independent installation.
Third, `win32` is the normal report for a Windows system (for historical reasons is win32, regardless of 32 or 64 bit processing).

You could try to install from my [fork](https://github.com/HelioGuilherme66/RIDE/releases/tag/v1.7) and see if the problem still exists. Please see the wiki about possible problems.

**Comment by luopeijie** [comment]
Hi HelioGuiherme66,
very appreciate for your response, I remembered that I used "pip install robotframework-ride" commend to have the RIED installed, but not sure. Today I will try to install version 1.5.2.1 from your fork, see if my problem can be solved.

**Comment by luopeijie** [comment]
Hi HelioGuiherme66,
Thanks a lot, my problem has been solved after install RIDE version1.5.2.1
