### ISSUE TITLE
Cannot run ride.py

### ISSUE THREAD

**Issue by ividito** [robotframework/RIDE#1722]
I am unable to run ride.py, either from the desktop shortcut, from the command line, or from a python shell. This is the error I get from running `python ride.py`:

> Traceback (most recent call last):
  File ".\ride.py", line 20, in <module>
    from robotide import main
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 64, in <module>
    from robot.errors import DataError
  File "C:\Python27\lib\site-packages\robotide\lib\robot\__init__.py", line 22, in <module>
    from robot.rebot import rebot, rebot_cli
  File "C:\Python27\lib\site-packages\robotide\lib\robot\rebot.py", line 273, in <module>
    from robot.run import RobotFramework
  File "C:\Python27\lib\site-packages\robotide\lib\robot\run.py", line 339, in <module>
    from robot.output import LOGGER, Output, pyloggingconf
  File "C:\Python27\lib\site-packages\robotide\lib\robot\output\pyloggingconf.py", line 17, in <module>
    from robot.api import logger
  File "C:\Python27\lib\site-packages\robotide\lib\robot\api\__init__.py", line 50, in <module>
    from robot.running import TestSuite
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\__init__.py", line 24, in <module>
    from .model import TestSuite
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\model.py", line 24, in <module>
    from .namespace import Namespace
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\namespace.py", line 26, in <module>
    from .userkeyword import UserLibrary
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\userkeyword.py", line 27, in <module>
    from .arguments import UserKeywordArguments
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\arguments\__init__.py", line 17, in <module>
    from .argumentmapper import ArgumentMapper
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\arguments\argumentmapper.py", line 15, in <module>
    from robotide.lib.robot.errors import DataError
  File "C:\Python27\lib\site-packages\robotide\lib\robot\__init__.py", line 22, in <module>
    from robot.rebot import rebot, rebot_cli
ImportError: cannot import name rebot

**Comment by ividito** [comment]
Not 100% sure how this was fixed, and I suspect it may be something unrelated to RIDE that was causing the problem. Uninstalling and reinstalling an older version caused everything to work as intended. I had tried the same thing with the same and with a newer version with no success, so I'm not sure how the older version fixed things.

**Comment by HelioGuilherme66** [comment]
@ividito I could be important to know the versions you tried and how they were installed. Also the Robot Framework version. Thanks.

**Comment by JafarBadour** [comment]
Please can you elaborate how did you fix this problem?
I have the same problem and I have no Idea how to fix it. I literally tried everything.

**Comment by ividito** [comment]
@JafarBadour Double check version compatibility for RIDE, robotframework, and wxPython. The version I eventually got working was RIDE 1.3. I did not have PyPI access on my machine, so I had to use manual installation. I probably had some sort of version mismatch somewhere along the way.

My other related package versions are robotframework 3.0.2 and wxPython 2.8.12.1.
