### ISSUE TITLE
error while opening ride from cmd propmt

### ISSUE THREAD

**Issue by ChandraMouliMerugu** [robotframework/RIDE#1762]
Hi,
I'm facing issue while opening ride from cmd prompt,
Below is the required info, please help me to resolve the issue.

C:\Users\chandramouli.merugu>pip freeze
numpy==1.14.5
pyodbc==4.0.23
Pypubsub==4.0.0
robotframework==3.0.4
robotframework-ride==1.7.1
six==1.11.0
wxPython==4.0.3
xlrd==1.1.0

C:\Users\chandramouli.merugu>ride.py
Thank you for helping developing and testing RIDE on Python 3 and wxPython 4
Traceback (most recent call last):
  File "c:\users\chandramouli.merugu\appdata\local\programs\python\python36-32\lib\site-packages\robotide\application\application.py", line 56, in OnInit
    coreplugins.get_core_plugins())
  File "c:\users\chandramouli.merugu\appdata\local\programs\python\python36-32\lib\site-packages\robotide\context\coreplugins.py", line 22, in get_core_plugins
    from robotide.editor.texteditor import TextEditorPlugin
  File "c:\users\chandramouli.merugu\appdata\local\programs\python\python36-32\lib\site-packages\robotide\editor\texteditor.py", line 41, in <module>
    from . import robotframeworklexer
  File "c:\users\chandramouli.merugu\appdata\local\programs\python\python36-32\lib\site-packages\robotide\editor\robotframeworklexer.py", line 17, in <module>
    from pygments.lexer import Lexer
ModuleNotFoundError: No module named 'pygments'
OnInit returned false, exiting...

**Comment by HelioGuilherme66** [comment]
That version is from my fork. You should not create Issues here.
There is a newer version [v1.7.2](https://github.com/HelioGuilherme66/RIDE/releases/tag/v1.7.2)
The instructions include installing `Pygments` (from the requirements).

Please close this issue afterwards.

**Comment by HelioGuilherme66** [comment]
This Issue is now fixed, so closing:
Users may want to see: [latest releases](https://github.com/robotframework/RIDE/releases)
The best installation process is:
```
pip install -U -r https://raw.githubusercontent.com/robotframework/RIDE/master/requirements.txt
pip install -U robotframework-ride
```
