### ISSUE TITLE
RIDE on High Sierra

### ISSUE THREAD

**Issue by NiveditaMirjikar** [robotframework/RIDE#1781]
I tried installing ride on mac high sierra. Even after installing wxPython I'm not able to run and launch ride on mac. Can someone provide me clear steps of installation for installing ride on mac. I'm facing the following issues

sogs-mbp:~ sogdev$ ride.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/__init__.py", line 81, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/__init__.py", line 100, in _run
    from robotide.application import RIDE
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/application/__init__.py", line 15, in <module>
    from .application import RIDE, Project
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/application/application.py", line 20, in <module>
    from robotide.namespace import Namespace
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/namespace/__init__.py", line 15, in <module>
    from .namespace import Namespace
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/namespace/namespace.py", line 30, in <module>
    from robotide.publish import PUBLISHER, RideSettingsChanged, RideLogMessage
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/publish/__init__.py", line 122, in <module>
    from .messages import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/publish/messages.py", line 20, in <module>
    from .messages2 import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/publish/messages2.py", line 24, in <module>
    from robotide.publish import publisher
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/publish/publisher.py", line 18, in <module>
    from wx.lib.pubsub import Publisher
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx/lib/pubsub/__init__.py", line 38, in <module>
    from pubsub import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pubsub/pub.py", line 146
    def getDefaultPublisher() -> Publisher:
                              ^
SyntaxError: invalid syntax

Use --help to get usage information.

**Comment by NiveditaMirjikar** [comment]
sudo -H pip install -U Pypubsub==3.3.0

The above solution worked for me thank you @HelioGuilherme66 so closing the issue
