### ISSUE TITLE
Unable to launch ride--warnings.warn("wxPython/wxWidgets release number mismatch")

### ISSUE THREAD

**Issue by NiveditaMirjikar** [robotframework/RIDE#1787]
Hello,
Please help me with a solution since I'm not able to launch ride. I'm badly looking for a solution please help.
When tried to launch ride I'm facing the following issue:

sogdev$ ride.py
/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py:16633: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/robotide/__init__.py", line 81, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/usr/local/lib/python2.7/site-packages/robotide/__init__.py", line 100, in _run
    from robotide.application import RIDE
  File "/usr/local/lib/python2.7/site-packages/robotide/application/__init__.py", line 15, in <module>
    from .application import RIDE, Project
  File "/usr/local/lib/python2.7/site-packages/robotide/application/application.py", line 20, in <module>
    from robotide.namespace import Namespace
  File "/usr/local/lib/python2.7/site-packages/robotide/namespace/__init__.py", line 15, in <module>
    from .namespace import Namespace
  File "/usr/local/lib/python2.7/site-packages/robotide/namespace/namespace.py", line 29, in <module>
    from robotide import robotapi, utils
  File "/usr/local/lib/python2.7/site-packages/robotide/robotapi.py", line 34, in <module>
    from robotide.lib.robot.running import TestLibrary, EXECUTION_CONTEXTS
  File "/usr/local/lib/python2.7/site-packages/robotide/lib/robot/running/__init__.py", line 103, in <module>
    from .builder import TestSuiteBuilder, ResourceFileBuilder
  File "/usr/local/lib/python2.7/site-packages/robotide/lib/robot/running/builder.py", line 17, in <module>
    from robot.parsing import TestData, ResourceFile as ResourceData, VALID_EXTENSIONS
ImportError: cannot import name VALID_EXTENSIONS

**Comment by ravihuang** [comment]
please use wxPython 2.8.12.1, you can download from: http://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1
