### ISSUE TITLE
ImportError: No module named plugins

### ISSUE THREAD

**Issue by shivanand199** [robotframework/RIDE#1792]
PS C:\DemoProject\WFMIS-master> python manage.py syncdb
Traceback (most recent call last):
File "manage.py", line 15, in
execute_from_command_line(sys.argv)
File "C:\Python27\lib\site-packages\django\core\management_init_.py", line 364, in execute_from_command_line
utility.execute()
File "C:\Python27\lib\site-packages\django\core\management_init_.py", line 338, in execute
django.setup()
File "C:\Python27\lib\site-packages\django_init_.py", line 27, in setup
apps.populate(settings.INSTALLED_APPS)
File "C:\Python27\lib\site-packages\django\apps\registry.py", line 85, in populate
app_config = AppConfig.create(entry)
File "C:\Python27\lib\site-packages\django\apps\config.py", line 120, in create
mod = import_module(mod_path)
File "C:\Python27\lib\importlib_init_.py", line 37, in import_module
import(name)
ImportError: No module named plugins

I am getting this error when we run python manage.py runserver. I am using python 2.7 and Django framework

**Comment by HelioGuilherme66** [comment]
@shivanand199 This is wrong project, closing...
