### ISSUE TITLE
The new ride v1.7.3.1 can not execute by pythonw.exe

### ISSUE THREAD

**Issue by zhujunling-nj** [robotframework/RIDE#1804]
The new ride v1.7.3.1 can not execute by pythonw.exe (Python 3.6.8 or 3.7.2). The error message is:
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\robotide\preferences\settings.py", line 60, in _copy_or_migrate_user_settings
    SettingsMigrator(source_path, settings_path).migrate()
  File "C:\Python36\lib\site-packages\robotide\preferences\settings.py", line 81, in __init__
    self._default_settings = ConfigObj(default_path, unrepr=True)
  File "C:\Python36\lib\site-packages\robotide\preferences\configobj.py", line 1260, in __init__
    self._load(infile, configspec)
  File "C:\Python36\lib\site-packages\robotide\preferences\configobj.py", line 1343, in _load
    infile = converttypes(infile)
  File "C:\Python36\lib\site-packages\robotide\utils\__init__.py", line 139, in converttypes
    enc = sys.stdout.encoding or "utf-8"
AttributeError: 'NoneType' object has no attribute 'encoding'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\robotide\application\application.py", line 50, in OnInit
    self.settings = RideSettings()
  File "C:\Python36\lib\site-packages\robotide\preferences\settings.py", line 431, in __init__
    user_path = initialize_settings(self._default_path)
  File "C:\Python36\lib\site-packages\robotide\preferences\settings.py", line 38, in initialize_settings
    SETTINGS_DIRECTORY, path, dest_file_name)
  File "C:\Python36\lib\site-packages\robotide\preferences\settings.py", line 72, in _copy_or_migrate_user_settings
    SettingsMigrator(source_path, settings_path).merge()
  File "C:\Python36\lib\site-packages\robotide\preferences\settings.py", line 81, in __init__
    self._default_settings = ConfigObj(default_path, unrepr=True)
  File "C:\Python36\lib\site-packages\robotide\preferences\configobj.py", line 1260, in __init__
    self._load(infile, configspec)
  File "C:\Python36\lib\site-packages\robotide\preferences\configobj.py", line 1343, in _load
    infile = converttypes(infile)
  File "C:\Python36\lib\site-packages\robotide\utils\__init__.py", line 139, in converttypes
    enc = sys.stdout.encoding or "utf-8"
AttributeError: 'NoneType' object has no attribute 'encoding'
OnInit returned false, exiting...

I fix it by modify the robotide\utils\__init__.py:
change
    enc = sys.stdout.encoding or "utf-8"
to
  enc = sys.stdout and sys.stdout.encoding or "utf-8"

**Comment by HelioGuilherme66** [comment]
@zhujunling-nj Thanks, it will go on next release.
(You know you can create a Pull Request, even if it is just a line of code?)
