### ISSUE TITLE
Installation error on Mac - desktop shortcut

### ISSUE THREAD

**Issue by technigirl** [robotframework/RIDE#1815]
Hi, I received an error during installation on Mac OSX (Mojave).  Since pip install no longer works, I installed by cloning this repo and then using python3 setup.py build and setup.py install, per the comments on a previous issue.  The following error occurred, apparently when it was trying to create a desktop shortcut:

4.0.4 osx-cocoa (phoenix) wxWidgets 3.0.5Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/robotide/postinstall/__main__.py", line 262, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/robotide/postinstall/__main__.py", line 253, in main
    create_desktop_shortcut(platform)
  File "/usr/local/lib/python3.7/site-packages/robotide/postinstall/__main__.py", line 214, in create_desktop_shortcut
    return _create_desktop_shortcut_mac(frame)
  File "/usr/local/lib/python3.7/site-packages/robotide/postinstall/__main__.py", line 160, in _create_desktop_shortcut_mac
    link = os.path.join("/Users", user, "Desktop", "RIDE")
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components

That said, I was still able to run RIDE so I think this is really just an issue with creating the shortcut.

**Comment by HelioGuilherme66** [comment]
Maybe your username has some UTF-8 characters (considered bytes)?
os.path.join("/Users", user, "Desktop", "RIDE")

**Comment by technigirl** [comment]
Hmm, I don't think so?  My username is simply, "melissa". But I do have a dash in the computer name, I don't know if that would mess things up...
