### ISSUE TITLE
Ride not working after upgrade from 1.5.2.1 to 1.7.3.1

### ISSUE THREAD

**Issue by manoska** [robotframework/RIDE#1816]
Hello

I've been using
RIDE 1.5.2.1 running on Python 2.7.11

RIDE was starting as a shortcut with Target:
C:\Python27\pythonw.exe -c "from robotide import main; main()"

After upgrading RIDE to 1.7.3.1 the shortcut isn't working.

Trying to start the command from cmd prompt as admin also failed without output
C:\Windows\system32>C:\Python27\pythonw.exe -c "from robotide import main; main()"
C:\Windows\system32>

Trying to run it via python showed the error below
C:\>C:\Python27\python.exe
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from robotide import main; main()
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 83, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 102, in _run
    from robotide.application import RIDE
  File "C:\Python27\lib\site-packages\robotide\application\__init__.py", line 16, in <module>
    from .application import RIDE, Project
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line 22, in <module>
    from robotide.namespace import Namespace
  File "C:\Python27\lib\site-packages\robotide\namespace\__init__.py", line 16, in <module>
    from .namespace import Namespace
  File "C:\Python27\lib\site-packages\robotide\namespace\namespace.py", line 31, in <module>
    from robotide.publish import PUBLISHER, RideSettingsChanged, RideLogMessage
  File "C:\Python27\lib\site-packages\robotide\publish\__init__.py", line 123, in <module>
    from .messages import *
  File "C:\Python27\lib\site-packages\robotide\publish\messages.py", line 21, in <module>
    from .messages2 import *
  File "C:\Python27\lib\site-packages\robotide\publish\messages2.py", line 24, in <module>
    from robotide.publish import publisher
  File "C:\Python27\lib\site-packages\robotide\publish\publisher.py", line 24, in <module>
    from pubsub import pub
  File "C:\Python27\lib\site-packages\pubsub\pub.py", line 146
    def getDefaultPublisher() -> Publisher:
                              ^
SyntaxError: invalid syntax

Use --help to get usage information.
>>>

thanks
Manolis

**Comment by manoska** [comment]
Looks like that new version assumes/requires Python3?

**Comment by HelioGuilherme66** [comment]
You fix that by installing correct version of PyPubSub.
If wanting to  upgrade wxPython:
```
pip install -U -r https://raw.githubusercontent.com/robotframework/RIDE/v1.7.3.1/requirements.txt
```
If just want to fix PyPubSub:
```
pip install -U Pypubsub==3.3.0
```

**Comment by HelioGuilherme66** [comment]
How to fix documented
