### ISSUE TITLE
not starting: PubSub cannot import name policies

### ISSUE THREAD

**Issue by Stips123** [robotframework/RIDE#1820]
Gentleman,

unfortunately, I'm unable to start RIDE on my Windows 10. I have installed Python Anaconda 2.7, wxPython2.8 with Unicode (with the windows installer) and the RIDE installation.
When I start the ride.py in PyCharm, I get the following error message:

```
C:\Python27\Anaconda\python.exe C:/Python27/Anaconda/Scripts/ride.py
Traceback (most recent call last):
File "C:\Python27\Anaconda\lib\site-packages\robotide\__init__.py", line 83, in main
    _run(inpath, not noupdatecheck, debug_console)
File "C:\Python27\Anaconda\lib\site-packages\robotide\__init__.py", line 102, in _run
    from robotide.application import RIDE
File "C:\Python27\Anaconda\lib\site-packages\robotide\application\__init__.py", line 16, in <module>
    from .application import RIDE, Project
File "C:\Python27\Anaconda\lib\site-packages\robotide\application\application.py", line 22, in <module>
    from robotide.namespace import Namespace
File "C:\Python27\Anaconda\lib\site-packages\robotide\namespace\__init__.py", line 16, in <module>
    from .namespace import Namespace
File "C:\Python27\Anaconda\lib\site-packages\robotide\namespace\namespace.py", line 31, in <module>
    from robotide.publish import PUBLISHER, RideSettingsChanged, RideLogMessage
File "C:\Python27\Anaconda\lib\site-packages\robotide\publish\__init__.py", line 123, in <module>
    from .messages import *
File "C:\Python27\Anaconda\lib\site-packages\robotide\publish\messages.py", line 21, in <module>
    from .messages2 import *
File "C:\Python27\Anaconda\lib\site-packages\robotide\publish\messages2.py", line 24, in <module>
    from robotide.publish import publisher
File "C:\Python27\Anaconda\lib\site-packages\robotide\publish\publisher.py", line 24, in <module>
    from pubsub import pub
File "C:\Python27\Anaconda\lib\site-packages\pypubsub-3.3.0-py2.7.egg\pubsub\pub.py", line 35, in <module>
    from .core import (
File "C:\Python27\Anaconda\lib\site-packages\pypubsub-3.3.0-py2.7.egg\pubsub\core\__init__.py", line 42, in <module>
    from .. import policies
ImportError: cannot import name policies
```

this problem might not be an actual RIDE issue, but maybe you have an idea what I can do?`
Any help appreciated, thanks!

Please note: I do not have internet access on the PC where RIDE is supposed to work, so any "pip"-Tipps might not work :-/

**Comment by HelioGuilherme66** [comment]
@Stips123 Maybe my Internet search skills are better than yours ;). I have found the `pypubsub` issue that mentions the missing files, and has a solution. See https://github.com/schollii/pypubsub/issues/16
where they recommend to download the package from PyPi and install it.

**Comment by Stips123** [comment]
thanks, now with the 3.4 version of pypubsub it works: https://github.com/schollii/pypubsub/tree/v3.4.0
thanks
