### ISSUE TITLE
Python3.7.1 cannot open ride(1.7.3.1)

### ISSUE THREAD

**Issue by Leowyys** [robotframework/RIDE#1828]
"Traceback (most recent call last):
  File "f:\program files (x86)\python3\lib\site-packages\robotide\application\application.py", line 59, in OnInit
    self._plugin_loader.enable_plugins()
  File "f:\program files (x86)\python3\lib\site-packages\robotide\application\pluginloader.py", line 43, in enable_plugins
    p.enable_on_startup()
  File "f:\program files (x86)\python3\lib\site-packages\robotide\application\pluginconnector.py", line 52, in enable_on_startup
    self.enable()
  File "f:\program files (x86)\python3\lib\site-packages\robotide\application\pluginconnector.py", line 57, in enable
    self._plugin.enable()
  File "f:\program files (x86)\python3\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 162, in enable
    self._build_ui()
  File "f:\program files (x86)\python3\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 558, in _build_ui
    self._build_notebook_tab()
  File "f:\program files (x86)\python3\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 734, in _build_notebook_tab
    self.out = self._create_output_textctrl()
  File "f:\program files (x86)\python3\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 769, in _create_output_textctrl
    font = self._create_font()
  File "f:\program files (x86)\python3\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 789, in _create_font
    font=wx.SystemSettings.GetFont(wx.SYS_ANSI_FIXED_FONT)
wx._core.wxAssertionError: C++ assertion "wxFontEnumerator::IsValidFacename(font.GetFaceName())" failed at ..\..\src\msw\settings.cpp(301) in wxSystemSettingsNative::GetFont():
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed"
Can you tell me how to resolve it?

**Comment by mrmaramreddy** [comment]
I had similar issue when Python2.7 was loading default in RIDE 1.7.3.1. I did uninstall 2.7 and installed Python 3.7.2 which resolved the issue for me.

**Comment by Leowyys** [comment]
@mrmaramreddy  I only installed 3.7.2 , but this issue still exist for me

**Comment by Leowyys** [comment]
@HelioGuilherme66 , do you have some advice? this problem  has puzzled me for many days

**Comment by HelioGuilherme66** [comment]
Don't know if it is a problem of permissions since your python is installed in drive F:, indicating it is not the system drive, so it may not have been installed globally. Other thing you can try is to reinstall wxPython.
I have python 3.7.2 on windows 10 without problems.

**Comment by Leowyys** [comment]
I reset the OS, then it's OK

**Comment by xg0719** [comment]
This problem needs to change the font parameters of _create_font function in testrunnerplugin.py. After the change, the UI of RIDE can be started normally. For details, please see my blog： https://blog.csdn.net/u011127242/article/details/88864476

**Comment by Duanxh2018** [comment]
solution：
find file testrunnerplugin.py
in   XXXX\python\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py
find 789 row：
change  font=wx.SystemSettings.GetFont(wx.SYS_ANSI_VAR_FONT)  to 
 font=wx.SystemSettings.GetFont(wx.SYS_ANSI_FIXED_FONT)
if still not use, u can change to
font=wx.SystemSettings.GetFont(wx.SYS_SYSTEM_FONT)
