### ISSUE TITLE
problem with robotide class?

### ISSUE THREAD

**Issue by pavolskulavik** [robotframework/RIDE#1831]
Dear experts. I was using a Robotframework with RIDe a lot on WIN7 but now I have WIN10 and have a problem to run RIDE properly. It doesnt show any libraries and in Tools->View RIDE log I can see still the same and I dont know how to fix it :(

`Traceback (most recent call last):
unsupported operand type(s) for -: 'float' and 'unicode'
  File "c:\Python27\Lib\site-packages\robotide\publish\publisher.py", line 88, in __call__
    self.listener(data)
  File "c:\Python27\Lib\site-packages\robotide\editor\__init__.py", line 125, in OnTreeItemSelected
    self._show_editor()
  File "c:\Python27\Lib\site-packages\robotide\editor\__init__.py", line 118, in _show_editor
    self._editor = self._create_editor()
  File "c:\Python27\Lib\site-packages\robotide\editor\__init__.py", line 122, in _create_editor
    return self._creator.editor_for(self, self._tab, self.tree)
  File "c:\Python27\Lib\site-packages\robotide\editor\editorcreator.py", line 52, in editor_for
    self._editor = self._create_editor(editor_panel, plugin, tree)
  File "c:\Python27\Lib\site-packages\robotide\editor\editorcreator.py", line 69, in _create_editor
    return self._create_new_editor(controller, editor_panel, plugin, tree)
  File "c:\Python27\Lib\site-packages\robotide\editor\editorcreator.py", line 86, in _create_new_editor
    return editor_class(plugin, editor_panel, controller, tree)
  File "c:\Python27\Lib\site-packages\robotide\editor\editors.py", line 253, in __init__
    _RobotTableEditor.__init__(self, *args)
  File "c:\Python27\Lib\site-packages\robotide\editor\editors.py", line 79, in __init__
    self._populate()
  File "c:\Python27\Lib\site-packages\robotide\editor\editors.py", line 346, in _populate
    _FileEditor._populate(self)
  File "c:\Python27\Lib\site-packages\robotide\editor\editors.py", line 276, in _populate
    self._add_settings()
  File "c:\Python27\Lib\site-packages\robotide\editor\editors.py", line 134, in _add_settings
    self._settings = self._create_settings()
  File "c:\Python27\Lib\site-packages\robotide\editor\editors.py", line 143, in _create_settings
    settings.build(self.controller.settings, self.plugin, self._tree)
  File "c:\Python27\Lib\site-packages\robotide\editor\editors.py", line 222, in build
    editor = self.create_editor_for(setting, plugin, tree)
  File "c:\Python27\Lib\site-packages\robotide\editor\editors.py", line 211, in create_editor_for
    return editor_cls(self.GetPane(), controller, plugin, tree)
  File "c:\Python27\Lib\site-packages\robotide\editor\settingeditors.py", line 47, in __init__
    self._create_controls()
  File "c:\Python27\Lib\site-packages\robotide\editor\settingeditors.py", line 59, in _create_controls
    self.update_value()
  File "c:\Python27\Lib\site-packages\robotide\editor\settingeditors.py", line 183, in update_value
    self._value_display.set_value(self._controller, self.plugin)
  File "c:\Python27\Lib\site-packages\robotide\editor\settingeditors.py", line 222, in set_value
    self._is_user_keyword = plugin.is_user_keyword(self._keyword_name)
  File "c:\Python27\Lib\site-packages\robotide\pluginapi\plugin.py", line 342, in is_user_keyword
    return self.__namespace.is_user_keyword(self.datafile, name)
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 177, in is_user_keyword
    return bool(self.find_user_keyword(datafile, kw_name))
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 173, in find_user_keyword
    kw = self.find_keyword(datafile, kw_name)
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 195, in find_keyword
    self._context_factory)
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 473, in get_keywords_cached
    datafile, context_factory.ctx_for_datafile(datafile))
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 382, in get_keywords_from
    self._get_imported_resource_keywords(datafile, ctx) +
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 428, in _get_imported_resource_keywords
    ctx)
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 405, in _collect_kws_from_imports
    kws.extend(getter(imp, ctx))
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 438, in _res_kw_recursive_getter
    kws.extend(self._res_kw_recursive_getter(child, ctx))
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 439, in _res_kw_recursive_getter
    kws.extend(self._get_imported_library_keywords(res, ctx))
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 400, in _get_imported_library_keywords
    self._lib_kw_getter, ctx)
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 405, in _collect_kws_from_imports
    kws.extend(getter(imp, ctx))
  File "c:\Python27\Lib\site-packages\robotide\namespace\namespace.py", line 413, in _lib_kw_getter
    return self._lib_cache.get_library_keywords(name, args, alias)
  File "c:\Python27\Lib\site-packages\robotide\namespace\cache.py", line 77, in get_library_keywords
    [k.with_alias(alias) for k in self._get_library(name, args)]
  File "c:\Python27\Lib\site-packages\robotide\namespace\cache.py", line 61, in _get_library
    if time.time() - last_updated > 10.0:`

in RIDE, TAB "Edit" **is empty** even though I load the test suite with such definition

`*** Settings ***
Suite Setup       Run Keywords    Test Suite Setup    CRM Admin Suite Setup
Test Setup        Test Case Setup
Test Teardown     Test Case Teardown
Test Timeout      20 minutes
Resource          ../../../../testbeds/integration/${testbed}.txt
Resource          ../../../../keywords/http/HTTP_keywords.txt
Resource          ../../../../keywords/yaml/yaml_keywords.txt
Resource          ../../../../keywords/testlink/testlink_keywords.txt
Resource          ../../../../keywords/sql/OTL_DB_keywords.txt
Resource          ../../../../keywords/idbt/idbt_keywords.txt
Resource          ../../../../keywords/otl/otl_objects.txt
Resource          ../../../../keywords/otl/otl_csi_requests.txt
Library           SSHLibrary    10 s
....
.... many other lines continue
....`

very appreciate any hint.

my PATH contains rather more
c:\Python27
c:\Python27\Scripts
c:\Python27\Lib\site-packages

same is in PYTHONPATH

C:\Python27\Scripts>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> wx.version()
'2.8.12.1 (msw-unicode)'

**Comment by xinxjxjxj** [comment]
I've the same problem after I downgraded ride version from 1.7.3.1 to 1.5.2.1.
 :(

**Comment by xinxjxjxj** [comment]
I solved this problem by referring to this link.
https://github.com/robotframework/RIDE/issues/1827#issuecomment-462829588

**Comment by pavolskulavik** [comment]
xinxjxjxj amazing help

works, thank you very much.
