### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ColorRGB'

### ISSUE THREAD

**Issue by linuxha** [robotframework/RIDE#1849]
ride.py is crashing with
AttributeError: 'module' object has no attribute 'ColorRGB'

Details
Linux mozart 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux
Python 2.7.9
ride - 1.7.3.1

$ ride.py
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/robotide/__init__.py", line 73, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/usr/local/lib/python2.7/dist-packages/robotide/__init__.py", line 99, in _run
    ride = RIDE(inpath, updatecheck)
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/application.py", line 42, in __init__
    wx.App.__init__(self, redirect=False)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/application.py", line 59, in OnInit
    self.frame.tree.populate(self.model)
  File "/usr/local/lib/python2.7/dist-packages/robotide/ui/tree.py", line 211, in populate
    self._populate_model(model)
  File "/usr/local/lib/python2.7/dist-packages/robotide/ui/tree.py", line 230, in _populate_model
    self._render_datafile(self._root, model.data, 0)
  File "/usr/local/lib/python2.7/dist-packages/robotide/ui/tree.py", line 277, in _render_datafile
    self._render_datafile(node, child)
  File "/usr/local/lib/python2.7/dist-packages/robotide/ui/tree.py", line 277, in _render_datafile
    self._render_datafile(node, child)
  File "/usr/local/lib/python2.7/dist-packages/robotide/ui/tree.py", line 270, in _render_datafile
    node = self._create_node_with_handler(parent_node, controller, index)
  File "/usr/local/lib/python2.7/dist-packages/robotide/ui/tree.py", line 286, in _create_node_with_handler
    self.SetItemTextColour(node, wx.ColorRGB(0xA9A9A9))
AttributeError: 'module' object has no attribute 'ColorRGB'

Use --help to get usage information.

**Comment by HelioGuilherme66** [comment]
There was changes in the Color macros from wxPython 2.8.12.1 to 3.0.2. I have that condition in some parts of the code, but I wonder why it was not reached in your case.
What version of wxPython are you using and how it was installed? What Linux distribution are you using?
Thanks-

**Comment by linuxha** [comment]
It's Debian 8 Jessie
# pip freeze |grep wx
wxPython==3.0.1.1
wxPython-common==3.0.1.1
#

**Comment by HelioGuilherme66** [comment]
The problem is that the condition is considering wxPython >2.8.12.1, and seems that your old wxPython still uses 2.8.12.1 code. What you can do is to modify the code to use your 3.0.1.1 version.
Or you can upgrade wxPython to at least 3.0.2 (it was the last of 3.x series).
You can have multiple wxPython installations. See [Build.rst](https://github.com/robotframework/RIDE/blob/master/BUILD.rest)

**Comment by linuxha** [comment]
I attempted to upgrade but that went badly (tied to the dirtibution). But in the process ride.py started working. I'm confused but this seems to be a natural state lately.

Help now returns:
RIDE 1.5.2.1 running on Python 2.7.9. 

I wish I knew what I just did. Most likely I broke something else.
