### ISSUE TITLE
Permission Issue after creating new test suite

### ISSUE THREAD

**Issue by alepo239** [robotframework/RIDE#1869]
Running RIDE 1.7.4.dev0, Robotframework 3.1.1, wxPython 4.0.4, Windows 10.

Steps to reproduce:
1. Create new test suite in RIDE.
2. Add empty test cases
3. In the Text edit panel I then try to add my libraries and after saving iget a permission error. 

I am running RIDE with the debug console open however no stack trace is given when I hit this error.
![image](https://user-images.githubusercontent.com/41382631/55427597-50f00880-5555-11e9-9d83-54921228088a.png)

Closing RIDE after creating and saving the test suite fixes the issue. After reopening RIDE the tester can then use the text edit panel to add their libraries.

**Comment by queenmooo** [comment]
I'm facing the same issue, please help.

**Comment by queenmooo** [comment]
> Running RIDE 1.7.4.dev0, Robotframework 3.1.1, wxPython 4.0.4, Windows 10.
> 
> Steps to reproduce:
> 
> 1. Create new test suite in RIDE.
> 2. Add empty test cases
> 3. In the Text edit panel I then try to add my libraries and after saving iget a permission error.
> 
> I am running RIDE with the debug console open however no stack trace is given when I hit this error.
> ![image](https://user-images.githubusercontent.com/41382631/55427597-50f00880-5555-11e9-9d83-54921228088a.png)
> 
> Closing RIDE after creating and saving the test suite fixes the issue. After reopening RIDE the tester can then use the text edit panel to add their libraries.

Try this, it works for me
python -m pip install --user google-assistant-sdk       # this step is to allow ride to save file

**Comment by alepo239** [comment]
No such luck on my end. Still getting the error after trying that. This does give me some new places to look though.

**Comment by queenmooo** [comment]
> No such luck on my end. Still getting the error after trying that. This does give me some new places to look though.

Did you run as administrator, and restart cmd?

**Comment by alepo239** [comment]
Yes, I am running as admin and restarted cmd. I also tried to rebuild the RIDE packages after running your pip command but am still getting the permission issues. I think I may need to reach out to IT to see how the user is setup on my VM.

**Comment by HelioGuilherme66** [comment]
Need to investigate more, but seems to happen only when the test suite has the same name as the directory where created.

**Comment by rekcodocker** [comment]
I second this bug.

It is not because the suite is the same as the directory. It happens every time I make a new suite.

This is what happens:
-I create a new suite.  
- I specify the extension. Whether I use .robot or .txt does not matter.
- Whenever I click 'save' or 'save all', Ride gives erorr13 and it specifies that it tries to save the suite WITH a period but WITHOUT the extension.   So 'file1.robot' gives an error "Permission denied file1."
- The file is created WITH the extension and size 0.   Ride does not write to it.

- workaround: Exit Ride. Create a file in the directory manually. Start Ride.  Now ride will read all files in the directory. 

So the error occurs when Ride creates new suite-files. (have not tested with project or resourcefiles yet).

**Comment by PaulLiu9527** [comment]
I have the same problem, hope for help. 
When I try to SAVE or SAVE ALL my project, this occurs.

**Comment by rekcodocker** [comment]
Here are reproduction-steps and a trace.
Used the latest version of RIDE (downloaded yesterday)  1.7.3.1.

Reproduce:
In a new project:

**action**: Right-click on project -> New Suite
**action:** Create a new file. Type in the name, click OK.
My default extension is .robot.   Behaviour is the same if I choose other extensions. 
**Observed**: The new file is displayed in the project with a * in front of the name to indicate it is unsaved.  The file is not yet created.

**Action**: Add a testcase so there is content to save. I use the text-editor, type *** test cases , and a testcase "blabla".

**Action**: Save, or Save All.


Here is the output from the commandline. 
Interestingly, "**PermissionError: [Errno 13] Permission denied: 'C:\\wrk\\smoketest\\hetProject.**'"  is actually my project file, not the new file I tried to create.

Hope this helps.


`C:\wrk\smoketest>pipenv run ride
Traceback (most recent call last):
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\ui\actiontriggers.py", line 338, in __call__
    action.act(event)
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\action\action.py", line 89, in act
    self.action(event)
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\ui\mainframe.py", line 452, in OnSaveAll
    self.save_all()
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\ui\mainframe.py", line 456, in save_all
    self._controller.execute(SaveAll())
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\controller\basecontroller.py", line 27, in execute
    return command.execute(self)
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\controller\ctrlcommands.py", line 1003, in execute
    datafile_controller.execute(SaveFile())
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\controller\basecontroller.py", line 27, in execute
    return command.execute(self)
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\controller\ctrlcommands.py", line 993, in execute
    datafile_controller.save()
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\controller\filecontrollers.py", line 366, in save
    self._project.save(self)
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\controller\project.py", line 280, in save
    self._serializer.serialize_file(controller)
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\controller\project.py", line 305, in serialize_file
    self._serialize_file(controller)
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\controller\project.py", line 312, in _serialize_file
    controller.datafile.save(**self._get_options())
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\lib\robot\parsing\model.py", line 158, in save
    return DataFileWriter(**options).write(self)
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\lib\robot\writer\datafilewriter.py", line 41, in write
    with WritingContext(datafile, **self._options) as ctx:
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\lib\robot\writer\datafilewriter.py", line 100, in __enter__
    self.output = file_writer(path, newline=self.line_separator)
  File "c:\users\axz09d0\.virtualenvs\smoketest-rymetuq_\lib\site-packages\robotide\lib\robot\utils\robotio.py", line 23, in file_writer
    f = io.open(path, 'w', encoding=encoding, newline=newline)
PermissionError: [Errno 13] Permission denied: 'C:\\wrk\\smoketest\\hetProject.'
`

**Comment by rbradhika530** [comment]
Please help me @HelioGuilherme66 in the above permision denied issue
