### ISSUE TITLE
Not able to install RIDE in cygwin (64-bit)

### ISSUE THREAD

**Issue by amittendulkar** [robotframework/RIDE#1875]
Getting following error,
```
$ pip install robotframework-ride                                               DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting robotframework-ride
  Using cached https://files.pythonhosted.org/packages/4e/a6/1835a17fa566b19c166735a9a75d55101e53b68566771ddb0b690dd4be83/robotframework_ride-1.7.3.1-py2.py3-none-any.whl
Requirement already satisfied: robotframework in /usr/lib/python2.7/site-packages (from robotframework-ride) (3.1.1)
Collecting Pywin32 (from robotframework-ride)
  Could not find a version that satisfies the requirement Pywin32 (from robotframework-ride) (from versions: )
No matching distribution found for Pywin32 (from robotframework-ride)

```

I am using Windows 7 (64-bit),
```
$ uname -a
CYGWIN_NT-6.1 CDTWVDI1520 3.0.6(0.338/5/3) 2019-04-06 16:18 x86_64 Cygwin
```

I installed `python-wx2.8` through cygwin. I didn't find `python-wxgtk2.8` package.

[This](https://sourceforge.net/p/pywin32/mailman/pywin32-bugs/thread/From_noreply@sourceforge.net_Fri_May_10_22:50:41_2013/) thread mentions that win32 extensions are not supported in cygwin.

The command `pip install wxPython` didn't succeed for me either. Any pointers?

**Comment by HelioGuilherme66** [comment]
Please see [this solution](https://github.com/robotframework/RIDE/issues/1874#issuecomment-482899629).

Why don't you use the native Windows python + wx + RIDE?

**Comment by amittendulkar** [comment]
The RIDE with Windows python + wx was working fine for me until recently. Then it started crashing during startup (probably after I switched to directory tree with cygwin subversion?). I will log a separate issue for it if required after investigation.

Meanwhile, trying the solution is giving me SSL handshake error,
```
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'inappropriate fallback')],)",),)': /robotframework/RIDE/archive/master.zip
Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /robotframework/RIDE/archive/master.zip (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'inappropriate fallback')],)",),))
```
I see openssl and Python openssl binding related packages are installed in cygwin.

**Comment by HelioGuilherme66** [comment]
> Does pip command allows installing manually downloaded file RIDE-master.zip?
Did you tried?
(the answer is yes)

Looks like you are still using cygwin, and it is giving too much trouble.

To start RIDE with no file or directory selected, pass an non-existing path:
```
ride.py garbage.robot
```

**Comment by amittendulkar** [comment]
With `ride.py garbage.robot` on Windows (without cygwin) is also failing to start the UI. The window appears for a split second and then closes. I have opened #1876 for RIDE starting trouble on windows issue.

For cygwin I tried copying the manually downloaded file at /tmp/pip/RIDE-master.zip and tried installing it with `pip install --cache-dir /tmp/pip RIDE-master.zip`. but it seems I am missing to enter the correct syntax.

**Comment by HelioGuilherme66** [comment]
It is just the `pip install path_to_archive_file`

**Comment by amittendulkar** [comment]
Thanks. I was able to install RIDE with the above syntax. Running ride.py threw error `pubsub module not found`. I installed it using `pip install pubsub`. Now I have stumbled upon another error: `ImportError: cannot import name pub`. Do I need to pubsub from master as well?

Here is the complete log,
```
$ pip install RIDE-master.zip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Processing ./RIDE-master.zip
Requirement already satisfied: wxPython in /usr/lib/python2.7/site-packages/wx-3.0-gtk3 (from robotframework-ride==1.7.4.dev0) (3.0.2.0)
Building wheels for collected packages: robotframework-ride
  Building wheel for robotframework-ride (setup.py) ... done
  Stored in directory: /cygdrive/c/Sandbox/Amit/.cache/pip/wheels/23/5c/63/743e213ecf55e12d37855bc5d377d766751ee218883024679d
Successfully built robotframework-ride
Installing collected packages: robotframework-ride
Successfully installed robotframework-ride-1.7.4.dev0

$ ride.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/robotide/__init__.py", line 83, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/usr/lib/python2.7/site-packages/robotide/__init__.py", line 102, in _run
    from robotide.application import RIDE
  File "/usr/lib/python2.7/site-packages/robotide/application/__init__.py", line 16, in <module>
    from .application import RIDE, Project
  File "/usr/lib/python2.7/site-packages/robotide/application/application.py", line 22, in <module>
    from robotide.namespace import Namespace
  File "/usr/lib/python2.7/site-packages/robotide/namespace/__init__.py", line 16, in <module>
    from .namespace import Namespace
  File "/usr/lib/python2.7/site-packages/robotide/namespace/namespace.py", line 31, in <module>
    from robotide.publish import PUBLISHER, RideSettingsChanged, RideLogMessage
  File "/usr/lib/python2.7/site-packages/robotide/publish/__init__.py", line 123, in <module>
    from .messages import *
  File "/usr/lib/python2.7/site-packages/robotide/publish/messages.py", line 21, in <module>
    from .messages2 import *
  File "/usr/lib/python2.7/site-packages/robotide/publish/messages2.py", line 24, in <module>
    from robotide.publish import publisher
  File "/usr/lib/python2.7/site-packages/robotide/publish/publisher.py", line 24, in <module>
    from pubsub import pub
ImportError: No module named pubsub


Use --help to get usage information.

$ pip install pubsub
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pubsub
  Downloading https://files.pythonhosted.org/packages/1b/6a/587dd0d9ab5e1a9ff0d71be6e251640644e3b692cbf65a8772b787300b58/pubsub-0.1.2.tar.gz
Requirement already satisfied: six<2,>=1 in /usr/lib/python2.7/site-packages (from pubsub) (1.12.0)
Building wheels for collected packages: pubsub
  Building wheel for pubsub (setup.py) ... done
  Stored in directory: /cygdrive/c/Sandbox/Amit/.cache/pip/wheels/23/c0/96/2983b027e439349b429c4d02ced8f8c4a3f594a5c4fc05b437
Successfully built pubsub
Installing collected packages: pubsub
Successfully installed pubsub-0.1.2

$ ride.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/robotide/__init__.py", line 83, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/usr/lib/python2.7/site-packages/robotide/__init__.py", line 102, in _run
    from robotide.application import RIDE
  File "/usr/lib/python2.7/site-packages/robotide/application/__init__.py", line 16, in <module>
    from .application import RIDE, Project
  File "/usr/lib/python2.7/site-packages/robotide/application/application.py", line 22, in <module>
    from robotide.namespace import Namespace
  File "/usr/lib/python2.7/site-packages/robotide/namespace/__init__.py", line 16, in <module>
    from .namespace import Namespace
  File "/usr/lib/python2.7/site-packages/robotide/namespace/namespace.py", line 31, in <module>
    from robotide.publish import PUBLISHER, RideSettingsChanged, RideLogMessage
  File "/usr/lib/python2.7/site-packages/robotide/publish/__init__.py", line 123, in <module>
    from .messages import *
  File "/usr/lib/python2.7/site-packages/robotide/publish/messages.py", line 21, in <module>
    from .messages2 import *
  File "/usr/lib/python2.7/site-packages/robotide/publish/messages2.py", line 24, in <module>
    from robotide.publish import publisher
  File "/usr/lib/python2.7/site-packages/robotide/publish/publisher.py", line 24, in <module>
    from pubsub import pub
ImportError: cannot import name pub


Use --help to get usage information.

$
```

**Comment by HelioGuilherme66** [comment]
That is not the correct library.
This is the one:
```
pip install PyPubSub==3.3.0
```

**Comment by amittendulkar** [comment]
Thanks. After installing RIDE through cygwin I started getting DISPLAY related issues. I also tried using Xming display server on my desktop.

```
$ which ride.py
/usr/bin/ride.py

$ ride.py
Unable to access the X Display, is $DISPLAY set properly?

$ export DISPLAY=:0.0

$ ride.py
process 1930: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
  D-Bus not compiled with backtrace support so unable to print a backtrace
Aborted (core dumped)

```

I am not sure why DISPLAY needs to be set here. I can start Emacs with GUI without any issues from Cygwin.

**Comment by amittendulkar** [comment]
I referred to OpenGL section in http://x.cygwin.com/docs/ug/cygwin-x-ug.pdf

Using the `+lgx -nowgl` options while starting Cygwin/X eliminates the first error (`libGL error: Windows-DRI extension disabled for GDI Generic renderer`). However all the latter errors remain and ride.py won't launch.

```
$ startxwin -- +iglx -nowgl -nolock &
...
$ export LIBGL_ALWAYS_INDIRECT=1
$ ride.py
<same errors as above except the first libGL error>
```

**Comment by HelioGuilherme66** [comment]
Try to start RIDE in the background:
```
$ ride.py &
```

**Comment by amittendulkar** [comment]
I agree. :) Next will be my last attempt to see whether it works... I will close this issue in my next reply.

Running ride.py in background gave me below error,

```
$ ride.py &
[3] 1217

$
** (ride.py:1217): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
14:49:06: Debug: ScreenToClient cannot work when toplevel window is not shown
14:49:07: Debug: ScreenToClient cannot work when toplevel window is not shown
14:49:07: Debug: ScreenToClient cannot work when toplevel window is not shown
14:49:07: Debug: ScreenToClient cannot work when toplevel window is not shown
14:49:07: Debug: ScreenToClient cannot work when toplevel window is not shown
14:49:07: Debug: ScreenToClient cannot work when toplevel window is not shown
14:49:07: Debug: ScreenToClient cannot work when toplevel window is not shown
14:49:07: Debug: ScreenToClient cannot work when toplevel window is not shown
14:49:07: Debug: ScreenToClient cannot work when toplevel window is not shown
14:49:07: Debug: Failed to connect to session manager: SESSION_MANAGER environment variable not defined
14:49:07: Debug: ScreenToClient cannot work when toplevel window is not shown
14:49:07: Debug: ScreenToClient cannot work when toplevel window is not shown
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/robotide/__init__.py", line 83, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/usr/lib/python2.7/site-packages/robotide/__init__.py", line 112, in _run
    ride = RIDE(inpath, updatecheck)
  File "/usr/lib/python2.7/site-packages/robotide/application/application.py", line 45, in __init__
    wx.App.__init__(self, redirect=False)
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/robotide/application/application.py", line 55, in OnInit
    self.frame = RideFrame(self, self._controller)
  File "/usr/lib/python2.7/site-packages/robotide/ui/mainframe.py", line 174, in __init__
    self.Bind(wx.EVT_DIRCTRL_FILEACTIVATED, self.OnOpenFile)
AttributeError: 'module' object has no attribute 'EVT_DIRCTRL_FILEACTIVATED'


Use --help to get usage information.

[3]+  Done                    ride.py
```

**Comment by Nyral** [comment]
@HelioGuilherme66 I don't think there's any point in keeping this open.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
