### ISSUE TITLE
Unable to see edit page

### ISSUE THREAD

**Issue by pradeepbantu** [robotframework/RIDE#1914]
Hi Team,

i am unable to view edit tab in framewor, what could be the possible reason.

![image](https://user-images.githubusercontent.com/37433888/57859322-623a5f00-77fb-11e9-9ab4-5f72b19e1117.png)

Thanks

**Comment by pradeepbantu** [comment]
Python 2.7.15 

![image](https://user-images.githubusercontent.com/37433888/57859606-f1e00d80-77fb-11e9-82b9-4e2af1bcbd34.png)

**Comment by HelioGuilherme66** [comment]
There should be errors/messages in RIDE>Tools>RIDE Log

**Comment by pradeepbantu** [comment]
I am able to see edit option now, but there is no option to start the Test case.
In ride log , i am getting this.

20190517 08:21:19.880 [INFO]: Found Robot Framework version 3.1.1 from C:\Python27\lib\site-packages\robot.

20190517 08:21:19.880 [INFO]: Started RIDE 1.7.3.1 using python version 2.7.16 with wx version 4.0.4 in win32.

Please help

**Comment by pradeepbantu** [comment]
Previous issue fixed after using 32 bit MSI installer of Python.

**Comment by pradeepbantu** [comment]
this issue is not still not resolved, getting below error message on command line

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\ui\keywordsearch.py", line 211, in OnActivate
    if self._plugin.have_keywords_changed():
  File "C:\Python27\lib\site-packages\robotide\ui\keywordsearch.py", line 64, in have_keywords_changed
    self._update()
  File "C:\Python27\lib\site-packages\robotide\ui\keywordsearch.py", line 69, in _update
    self.all_keywords = self.model.get_all_keywords()
  File "C:\Python27\lib\site-packages\robotide\controller\project.py", line 210, in get_all_keywords
    return self.get_all_keywords_from(ctrl.datafile for ctrl in self.datafiles if ctrl.datafile)
  File "C:\Python27\lib\site-packages\robotide\controller\basecontroller.py", line 103, in get_all_keywords_from
    return self._namespace.get_all_keywords(*datafiles)
  File "C:\Python27\lib\site-packages\robotide\namespace\namespace.py", line 101, in get_all_keywords
    kws.update(self._get_default_keywords())
  File "C:\Python27\lib\site-packages\robotide\namespace\namespace.py", line 106, in _get_default_keywords
    return self._lib_cache.get_default_keywords()
  File "C:\Python27\lib\site-packages\robotide\namespace\cache.py", line 89, in get_default_keywords
    return self._default_kws[:]
  File "C:\Python27\lib\site-packages\robotide\namespace\cache.py", line 49, in _default_kws
    self.__default_kws = self._build_default_kws()
  File "C:\Python27\lib\site-packages\robotide\namespace\cache.py", line 93, in _build_default_kws
    for keywords_in_library in self._default_libraries.values():
  File "C:\Python27\lib\site-packages\robotide\namespace\cache.py", line 43, in _default_libraries
    self.__default_libraries = self._get_default_libraries()
  File "C:\Python27\lib\site-packages\robotide\namespace\cache.py", line 101, in _get_default_libraries
    default_libs[name] = self._get_library(name, args)
  File "C:\Python27\lib\site-packages\robotide\namespace\cache.py", line 61, in _get_library
    if time.time() - last_updated > 10.0:
TypeError: unsupported operand type(s) for -: 'float' and 'unicode'

**Comment by HelioGuilherme66** [comment]
@pradeepbantu That is not the same problem as initially reported.

The problem you now report is because you used a newer version of RIDE and the timestamp on the settings.cfg was updated. To solve that, if you want to still use version 1.5.2.1 of RIDE, you have to delete the settings.cfg file (or just the value you have in `last_updated`).
