### ISSUE TITLE
GRID editor not available in version 1.7.4.a1

### ISSUE THREAD

**Issue by rerazin** [robotframework/RIDE#1915]
Hi,

Upgraded to 1.7.4.a1 and noticed that grid editor is not available. I click on the grid editor but on the right pane I still see the Text Editor. RIDE is installed on Win 10.

Thanks!
![Grid_edit](https://user-images.githubusercontent.com/50689959/57868595-20d49000-77b8-11e9-87b2-1850b70b22d1.png)

**Comment by HelioGuilherme66** [comment]
There should be errors/messages in RIDE>Tools>RIDE Log

See Tools >Manaeg Plugins.

**Comment by Nyral** [comment]
It works for me...

**Comment by rerazin** [comment]
RIDE log doesn't seem to reflect this(see below). See attached screen record

### 20190515 21:59:39.364 [INFO]: Found Robot Framework version 3.1.1 from C:\Python\lib\site-packages\robot.
![grid_problem](https://user-images.githubusercontent.com/50689959/57871443-2c2aba00-77be-11e9-9a43-c06d5583abd2.gif)

20190515 21:59:39.365 [INFO]: Started RIDE 1.7.4a1 using python version 3.7.2 with wx version 4.0.4 in win32.

20190515 22:06:30.996 [WARN]: Importing test library "SeleniumLibrary" failed

Traceback (most recent call last):
'NoneType' object has no attribute 'write'
  File "C:\Python\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python\lib\site-packages\robotide\spec\libraryfetcher.py", line 24, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 50, in TestLibrary
    return_source=True)
  File "C:\Python\lib\site-packages\robotide\lib\robot\running\outputcapture.py", line 38, in __exit__
    self._release_and_log()
  File "C:\Python\lib\site-packages\robotide\lib\robot\running\outputcapture.py", line 49, in _release_and_log
    sys.__stderr__.write(console_encode(stderr, stream=sys.__stderr__))

**Comment by Nyral** [comment]
Can you open ride.py with python.exe from command line?
(ride.py is located in Python37\Scripts)

Check if any errors appear there after you open preferences and grid editor.

**Comment by rerazin** [comment]
Here you go, getting this when clicking on the grid in preferences:

ValueError: value 2000 exceeds the integer width of the control (3)
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\robotide\preferences\editor.py", line 123, in OnTreeSelection
    panel = self._container.AddPanel(instance_or_class, self._settings)
  File "C:\Python\lib\site-packages\robotide\preferences\editor.py", line 211, in AddPanel
    panel = panel_class(parent=self.panels_container, settings=settings)
  File "C:\Python\lib\site-packages\robotide\preferences\editors.py", line 132, in __init__
    self.Sizer.Add(self._create_grid_config_editor())
  File "C:\Python\lib\site-packages\robotide\preferences\editors.py", line 142, in _create_grid_config_editor
    sizer.Add(self._number_editor(settings, 'max col size'))
  File "C:\Python\lib\site-packages\robotide\preferences\editors.py", line 153, in _number_editor
    editor = NumCtrl(self, value=initial_value, integerWidth=3, allowNone=True)
  File "C:\Python\lib\site-packages\wx\lib\masked\numctrl.py", line 643, in __init__
    self.SetValue(value)
  File "C:\Python\lib\site-packages\wx\lib\masked\numctrl.py", line 1304, in SetValue
    BaseMaskedTextCtrl.SetValue( self, self._toGUI(value) )
  File "C:\Python\lib\site-packages\wx\lib\masked\numctrl.py", line 1700, in _toGUI
    raise ValueError ('value %s exceeds the integer width of the control (%d)' % (s, self._integerWidth))
ValueError: value 2000 exceeds the integer width of the control (3)

**Comment by Nyral** [comment]
Ok, now we are getting somewhere. I think I know what's causing the issue.

To confirm my theory,  can you also show me the contents from settings.cfg file?
Ir show be in (`C:\Users\<username>\AppData\Roaming\RobotFramework\ride`)

**Comment by rerazin** [comment]
Please see attached
[settings.txt](https://github.com/robotframework/RIDE/files/3189090/settings.txt)

**Comment by Nyral** [comment]
Ok, so in that file you have the following line `max col size = 2000`.
This value should never exceed 3 digits (max 999). That's why the issue occurs.

It shouldn't even be possible to change this from RIDE preferences, so I dunno how you managed to do it. Edit the file and change it to something reasonable and the issue should go away.

**Comment by rerazin** [comment]
You could do this in older version that I had, most probably was carried to this version after the upgrade

**Comment by Nyral** [comment]
Yeah, grid editor has suffered some major changes in the recent versions. Some settings are not backwards compatible anymore.

Why do you need such a big column size? Are you using a 4k monitor?

**Comment by rerazin** [comment]
Grids were flaky in that version so I just played around to make them a bit more friendly

Thanks for the help!

**Comment by HelioGuilherme66** [comment]
@Nyral Thank you for helping troubleshooting this!
