### ISSUE TITLE
Unable to execute test cases in RIDE

### ISSUE THREAD

**Issue by koolestkrystal** [robotframework/RIDE#2002]
Hi,

I had python 2.7 and I have now installed python 3.7.4 as the former will be deprecated. I have also changed my PATH variables to point to the new 3.7 folder. I am able to load my test cases in RIDE, however, when I select and try to execute any of them, it doesn't execute and gives the below in the cmd.

C:\Users\XXXXXXXX>ride.py
Traceback (most recent call last):
  File "C:\Python3.7.4\lib\site-packages\robotide\ui\actiontriggers.py", line 33
8, in __call__
    action.act(event)
  File "C:\Python3.7.4\lib\site-packages\robotide\action\action.py", line 89, in
 act
    self.action(event)
  File "C:\Python3.7.4\lib\site-packages\robotide\contrib\testrunner\testrunnerp
lugin.py", line 300, in OnRun
    command = self._create_command()
  File "C:\Python3.7.4\lib\site-packages\robotide\contrib\testrunner\testrunnerp
lugin.py", line 325, in _create_command
    self.get_current_profile(),
  File "C:\Python3.7.4\lib\site-packages\robotide\contrib\testrunner\testrunnerp
lugin.py", line 699, in get_current_profile
    return self._test_runner.get_profile(self.choice.GetStringSelection())
  File "C:\Python3.7.4\lib\site-packages\robotide\contrib\testrunner\testrunner.
py", line 106, in get_profile
    return self.profiles[name]
KeyError: ''

Thanks

**Comment by Nyral** [comment]
Which execution profile did you select in the Run tab?

**Comment by koolestkrystal** [comment]
Hi @Nyral ,

Apologies, my execution profile was incorrect. Its working now when I selected 'robot'.
Thanks
