### ISSUE TITLE
Validate Search for unused keywords

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2012]
With v1.7.4b2 did a Tools>Search Unused Keywords, and it never stops, keeps showing Searching...

RIDE 1.7.4b2 using python version 3.7.4 with wx version 4.0.6 in win32 (Windows 10 64bit)

**Comment by Nyral** [comment]
Python 3 error, needs replaced with `__next__()`
```
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python37\lib\site-packages\robotide\ui\review.py", line 373, in _run
    if self._is_unused(keyword):
  File "C:\Python37\lib\site-packages\robotide\ui\review.py", line 381, in _is_unused
    self._controller.execute(FindUsages(keyword.name, keyword_info=keyword.info)).next()
AttributeError: 'generator' object has no attribute 'next'
```
