### ISSUE TITLE
new keywords can't work

### ISSUE THREAD

**Issue by whitePythonLearn** [robotframework/RIDE#2024]
20191010 17:38:56.600 [ERROR]: Error in listener: wrapped C/C++ object of type KeywordEditor has been deleted
While handling <robotide.publish.messages3.RideSaved object at 0x05AE6DB0>

Traceback (most recent call last):
wrapped C/C++ object of type KeywordEditor has been deleted
  File "D:\python37\lib\site-packages\robotide\publish\publisher.py", line 103, in __call__
    self.listener(data)
  File "D:\python37\lib\site-packages\robotide\editor\kweditor.py", line 143, in _resize_grid
    self.AutoSizeColumns(False)

20191010 17:38:56.601 [ERROR]: Error in listener: wrapped C/C++ object of type KeywordEditor has been deleted
While handling <robotide.publish.messages3.RideSaved object at 0x05AE6DB0>

Traceback (most recent call last):
wrapped C/C++ object of type KeywordEditor has been deleted
  File "D:\python37\lib\site-packages\robotide\publish\publisher.py", line 103, in __call__
    self.listener(data)
  File "D:\python37\lib\site-packages\robotide\editor\kweditor.py", line 143, in _resize_grid
    self.AutoSizeColumns(False)

#soft verson
robotframework-3.1.2
wxpython-4.0.6
robotframework-ride-1.7.4b2
Requirement already satisfied: pywin32 in d:\python37\lib\site-packages (225)
Requirement already satisfied: pygments in d:\python37\lib\site-packages (2.4.2)
#OS
Win10 x64

**Comment by whitePythonLearn** [comment]
orz, i need help!

**Comment by whitePythonLearn** [comment]
python verson :
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32

**Comment by HelioGuilherme66** [comment]
Closing (just because)
