### ISSUE TITLE
On python 2.7 error in listener Test Runner

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2090]
We see the following on RIDE log:
```
20191225 00:47:21.020 [INFO]: Found Robot Framework version 3.1.2 from /usr/lib/python2.7/site-packages/robot.

20191225 00:47:21.021 [ERROR]: Error in listener: write() argument 1 must be unicode, not str
While handling <robotide.publish.messages2.RideLogMessage object at 0x7fe2659f27d0>

Traceback (most recent call last):
write() argument 1 must be unicode, not str
  File "/usr/lib/python2.7/site-packages/robotide/publish/publisher.py", line 103, in __call__
    self.listener(data)
  File "/usr/lib/python2.7/site-packages/robotide/log/log.py", line 91, in _log_message
    self._logfile.write(_message_to_string(log_event))
```
Python 2.7.17 on Linux Fedora Core 30

**Comment by Nyral** [comment]
Check if that errors appears for parserlog too.
