### ISSUE TITLE
Unable to see edit page

### ISSUE THREAD

**Issue by kuks2580** [robotframework/RIDE#2115]
Hi,

Im having problems with edit page.
Ride log is below.

20200116 09:16:27.900 [INFO]: Started RIDE 1.7.4rc1.dev using python version 2.7.15 with wx version 2.8.12.1 in linux2.

20200116 09:16:42.554 [ERROR]: Error in listener: No constructor defined
While handling <robotide.publish.messages2.RideTreeSelection object at 0x7f77732f45d0>

Traceback (most recent call last):
No constructor defined
  File "/usr/local/lib/python2.7/dist-packages/robotide/publish/publisher.py", line 103, in __call__
    self.listener(data)
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/__init__.py", line 124, in OnTreeItemSelected
    self._show_editor()
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/__init__.py", line 117, in _show_editor
    self._editor = self._create_editor()
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/__init__.py", line 121, in _create_editor
    return self._creator.editor_for(self, self._tab, self.tree)
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/editorcreator.py", line 53, in editor_for
    self._editor = self._create_editor(editor_panel, plugin, tree)
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/editorcreator.py", line 70, in _create_editor
    return self._create_new_editor(controller, editor_panel, plugin, tree)
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/editorcreator.py", line 87, in _create_new_editor
    return editor_class(plugin, editor_panel, controller, tree)
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/editors.py", line 80, in __init__
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/macroeditors.py", line 33, in _populate
    self._create_kweditor()
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/macroeditors.py", line 37, in _create_kweditor
    self.kweditor = KeywordEditor(self, self.controller, self._tree)
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/kweditor.py", line 109, in __init__
    self._configure_grid()
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/kweditor.py", line 174, in _configure_grid
    self._set_cells()
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/kweditor.py", line 154, in _set_cells
    CellRenderer(col_size, max_col_size, auto_col_size, word_wrap))
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/cellrenderer.py", line 27, in __init__
    wx.grid.GridCellRenderer.__init__(self)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/grid.py", line 113, in __init__
    def __init__(self): raise AttributeError, "No constructor defined"

**Comment by HelioGuilherme66** [comment]
@kuks2580 Please install newer wxPython, (better get from wxPython.org). If RIDE works OK with new version, currently wxPython is 4.0.7.post2, then, please close this issue.
