### ISSUE TITLE
Latest RIDE couldn't start with latest python ver win32 and latest wxpython win32

### ISSUE THREAD

**Issue by satymaju** [robotframework/RIDE#2172]
C:\Users\satymaju>ride.py
Traceback (most recent call last):
  File "C:\Users\satymaju\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotide\application\application.py", line 55, in OnInit
    self.frame = RideFrame(self, self._controller)
  File "C:\Users\satymaju\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotide\ui\mainframe.py", line 170, in __init__
    self._init_ui()
  File "C:\Users\satymaju\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotide\ui\mainframe.py", line 274, in _init_ui
    self.tree = Tree(self, self.actions,
  File "C:\Users\satymaju\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotide\ui\tree.py", line 86, in __init__
    self._images = TreeImageList()
  File "C:\Users\satymaju\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotide\ui\images.py", line 42, in __init__
    TestCaseController: _TreeImage(self, 'robot.png'),
  File "C:\Users\satymaju\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotide\ui\images.py", line 80, in __init__
    self.normal = self._get_image(image_list, normal)
  File "C:\Users\satymaju\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotide\ui\images.py", line 91, in _get_image
    img = wx.Image(path, wx.BITMAP_TYPE_PNG).ConvertToBitmap()
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

**Comment by satymaju** [comment]
pip version latest
ride ver tried ride==1.7.4 and ride==1.7.4b(something)

**Comment by HelioGuilherme66** [comment]
@satymaju Read [README](https://github.com/robotframework/RIDE/blob/master/README.adoc).
