### ISSUE TITLE
Unable to Create new project on 2.0b1.dev1

### ISSUE THREAD

**Issue by the-kool-sk** [robotframework/RIDE#2186]
Getting below crash while creating new project in Windows10 64bit machine : 

Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\robotide\ui\actiontriggers.py", line 334, in __call__
    action.act(event)
  File "C:\Python36-32\lib\site-packages\robotide\action\action.py", line 89, in act
    self.action(event)
  File "C:\Python36-32\lib\site-packages\robotide\utils\eventhandler.py", line 25, in wrapped
    method(self, event)
  File "C:\Python36-32\lib\site-packages\robotide\ui\mainframe.py", line 389, in OnNewProject
    NewProjectDialog(self._controller).execute()
  File "C:\Python36-32\lib\site-packages\robotide\ui\filedialogs.py", line 164, in __init__
    _CreationDialog.__init__(self, project.default_dir, "New Project")
  File "C:\Python36-32\lib\site-packages\robotide\ui\filedialogs.py", line 40, in __init__
    self._name_editor = self._create_name_editor(label_sizer)
  File "C:\Python36-32\lib\site-packages\robotide\ui\filedialogs.py", line 73, in _create_name_editor
    disp_sizer.Add(name_editor, 1, wx.ALIGN_CENTRE | wx.ALL | wx.EXPAND, 3)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at ..\..\src\common\sizer.cpp(2114) in wxBoxSizer::DoInsert(): Vertical alignment flags are ignored with wxEXPAND

System  configuration :
numpy==1.18.3
Pillow==7.1.2
Pygments==2.6.1
Pypubsub==4.0.3
pywin32==227
robotframework==3.1.2
robotframework-ride==2.0b1.dev1
six==1.14.0
wxPython==4.1.0

**Comment by HelioGuilherme66** [comment]
@the-kool-sk Thank you for reporting this. You can install now, with the fix from current development.
