### ISSUE TITLE
After installating Robotframework ride, Ride.py is not opening and gives an exception

### ISSUE THREAD

**Issue by apoom15** [robotframework/RIDE#2188]
Python version: Python 2.7.18
After robot framework - ride installation, ride does not open and gives the following exception:
C:\Users\apoom>ride.py
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line 62, in OnInit
    self._plugin_loader.enable_plugins()
  File "C:\Python27\lib\site-packages\robotide\application\pluginloader.py", line 43, in enable_plugins
    p.enable_on_startup()
  File "C:\Python27\lib\site-packages\robotide\application\pluginconnector.py", line 52, in enable_on_startup
    self.enable()
  File "C:\Python27\lib\site-packages\robotide\application\pluginconnector.py", line 57, in enable
    self._plugin.enable()
  File "C:\Python27\lib\site-packages\robotide\recentfiles\recentfiles.py", line 44, in enable
    self._add_recent_files_to_menu()
  File "C:\Python27\lib\site-packages\robotide\recentfiles\recentfiles.py", line 117, in _add_recent_files_to_menu
    self._add_file_to_menu(path, n)
  File "C:\Python27\lib\site-packages\robotide\recentfiles\recentfiles.py", line 124, in _add_file_to_menu
    self.register_action(entry.get_action_info())
  File "C:\Python27\lib\site-packages\robotide\pluginapi\plugin.py", line 204, in register_action
    action = self.__frame.actions.register_action(action_info)
  File "C:\Python27\lib\site-packages\robotide\ui\mainframe.py", line 751, in register_action
    self._menubar.register(action)
  File "C:\Python27\lib\site-packages\robotide\ui\actiontriggers.py", line 60, in register
    menu.add_menu_item(action)
  File "C:\Python27\lib\site-packages\robotide\ui\actiontriggers.py", line 98, in add_menu_item
    menu_item = self._construct_menu_item(action)
  File "C:\Python27\lib\site-packages\robotide\ui\actiontriggers.py", line 107, in _construct_menu_item
    menu_item = self._create_menu_item(action)
  File "C:\Python27\lib\site-packages\robotide\ui\actiontriggers.py", line 139, in _create_menu_item
    pos = action.get_insertion_index(self.wx_menu)
  File "C:\Python27\lib\site-packages\robotide\action\action.py", line 40, in get_insertion_index
    return self._insertion_point.get_index(menu)
  File "C:\Python27\lib\site-packages\robotide\action\actioninfo.py", line 286, in get_index
    index = self._find_position_in_menu(menu)
  File "C:\Python27\lib\site-packages\robotide\action\actioninfo.py", line 296, in _find_position_in_menu
    if self._get_menu_item_name(item).lower() == self._item.lower():
  File "C:\Python27\lib\site-packages\robotide\action\actioninfo.py", line 301, in _get_menu_item_name
    return self._shortcut_remover.split(item.GetLabel())[0]
AttributeError: 'MenuItem' object has no attribute 'GetLabel'
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(475) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(475) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

installed packages:
bcrypt==3.1.7
cffi==1.14.0
cryptography==2.9.2
enum34==1.1.10
ipaddress==1.0.23
numpy==1.16.6
paramiko==2.7.1
Pillow==6.2.2
pycparser==2.20
Pygments==2.5.2
PyNaCl==1.3.0
PyPubSub==3.3.0
pywin32==227
robotframework==3.2
robotframework-ride==1.7.4.1
six==1.14.0
wxPython==4.1.0

Please help me resolve this

**Comment by HelioGuilherme66** [comment]
@apoom15 You solve that by downgrading wxPython:
`pip install -U --force wxPython==4.0.7.post2`

**Comment by apoom15** [comment]
Robot framework ride installation is successful. 
Thank you for the support.

**Comment by mbharath12** [comment]
Thanks, It's worked for me successfully.

**Comment by HelioGuilherme66** [comment]
@aaresuresh Please don't ask for support on closed issues, and in this bug tracker. Use the other communication ways as mentioned on the README file. Loog in the Wiki for similar problems related with the installation of wxPython (you are trying to build it, when you should have gotten the package from wxpython.org).

**Comment by rbradhika530** [comment]
After installating Robotframework ride, Ride.py is not opening and gives an exception and ride is not getting opened

**Comment by rbradhika530** [comment]
After installating Robotframework ride, Ride.py is not opening and gives an exception and pip install -U --force wxPython==4.0.7.post2 this is not working
