### ISSUE TITLE
ImportError: No module named plugins

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#221]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=186) by jrvilda on 6 Jul 2009*

Traceback (most recent call last):
  File "C:\python25\lib\runpy.py", line 95, in run_module
    filename, loader, alter_sys)
  File "C:\python25\lib\runpy.py", line 52, in _run_module_code
    mod_name, mod_fname, mod_loader)
  File "C:\python25\lib\runpy.py", line 32, in _run_code
    exec code in run_globals
  File "C:\python25\lib\site-packages\robotide\__init__.py", line 83, in
&lt;module
&gt;
    main(sys.argv[1:])
  File "C:\python25\lib\site-packages\robotide\__init__.py", line 50, in main
    _run(*args)
  File "C:\python25\lib\site-packages\robotide\__init__.py", line 60, in _run
    from robotide.application import RobotIde
  File "C:\Python25\Lib\site-packages\robotide\application\__init__.py",
line 15
, in &lt;module&gt;
    from application import RobotIde
  File "C:\Python25\Lib\site-packages\robotide\application\application.py",
line
 23, in &lt;module&gt;
    from pluginmanager import PluginLoader, PluginManager
  File
"C:\Python25\Lib\site-packages\robotide\application\pluginmanager.py", li
ne 28, in &lt;module&gt;
    from recentfiles import RecentFilesPlugin
  File "C:\python25\lib\site-packages\robotide\application\recentfiles.py",
line
 19, in &lt;module&gt;
    from robotide.plugins import Plugin
ImportError: No module named plugins

	
with the previous version worked correctly.
	
	
There is no plugins folder

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=186#c2) by @yanne on 7 Jul 2009*


The plugin directory has been removed on purpose.
This works for me, both in Windows and Linux.
Could you try to uninstall (e.g. remove C:\python25\lib\site-packages\robotide) and
install again.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=186#c3) by jrvilda on 7 Jul 2009*


And where are now?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=186#c4) by @yanne on 7 Jul 2009*


plugins are currently under the `application` package

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=186#c7) by @yanne on 9 Jul 2009*


This is unfortunate, but the plugin API is not yet stable.
Some breakages are due to happen in next release also.

**Comment by shivanand199** [comment]
PS C:\DemoProject\WFMIS-master>  python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 338, in execute
    django.setup()
  File "C:\Python27\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Python27\lib\site-packages\django\apps\config.py", line 120, in create
    mod = import_module(mod_path)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named plugins



i am getting this error
