### ISSUE TITLE
RIDE GUI not launching

### ISSUE THREAD

**Issue by vkosuri** [robotframework/RIDE#2211]
Hi

``` Bash
Windows 10
Python 2.7.17 64Bit
```

When I tried to open using ride.py i am getting invalid syntax error.

``` Bash
C:\Python27\Scripts>python ride.py
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 82, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 101, in _run
    from robotide.application import RIDE
  File "C:\Python27\lib\site-packages\robotide\application\__init__.py", line 16, in <module>
    from .application import RIDE, Project
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line 22, in <module>
    from robotide.namespace import Namespace
  File "C:\Python27\lib\site-packages\robotide\namespace\__init__.py", line 16, in <module>
    from .namespace import Namespace
  File "C:\Python27\lib\site-packages\robotide\namespace\namespace.py", line 31, in <module>
    from robotide.publish import PUBLISHER, RideSettingsChanged, RideLogMessage
  File "C:\Python27\lib\site-packages\robotide\publish\__init__.py", line 123, in <module>
    from .messages import *
  File "C:\Python27\lib\site-packages\robotide\publish\messages.py", line 21, in <module>
    from .messages2 import *
  File "C:\Python27\lib\site-packages\robotide\publish\messages2.py", line 24, in <module>
    from robotide.publish import publisher
  File "C:\Python27\lib\site-packages\robotide\publish\publisher.py", line 24, in <module>
    from pubsub import pub
  File "C:\Python27\lib\site-packages\pubsub\pub.py", line 146
    def getDefaultPublisher() -> Publisher:
                              ^
SyntaxError: invalid syntax


Use --help to get usage information.
```

Here is the pip list

``` Bash
C:\Python27\Scripts>pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package             Version
------------------- -----------
numpy               1.16.1
Pillow              6.2.2
pip                 19.2.3
Pygments            2.5.2
Pypubsub            4.0.0
pywin32             228
robotframework      3.2.1
robotframework-ride 1.7.4.2
setuptools          41.2.0
six                 1.15.0
typing              3.7.4.1
wxPython            4.0.7.post2
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Python27\Scripts>
```

**Comment by HelioGuilherme66** [comment]
@vkosuri That is a known problem because of the version of `Pypubsub            4.0.0`. We have a requirement.txt with the correct version for python 2.7. I wonder why that version is installed. Did you upgraded it? How did you installed RIDE? Can't you upgrade to python3?

**Comment by vkosuri** [comment]
I installed through ``pip install robotframework-ride``

The system which i am using had very limited access. Is there any alternatives to resolve this with Python 2.7?

**Comment by HelioGuilherme66** [comment]
You need to downgrade PyPubsub to 3.3.0:
`pip install -U --force PyPubSub==3.3.0`

**Comment by vkosuri** [comment]
@HelioGuilherme66 Thank you very much, the above fix worked for me.
