### ISSUE TITLE
Importing RequestsChecker library does not work

### ISSUE THREAD

**Issue by emilezwiggelaar** [robotframework/RIDE#2265]
After succesful install of RequestsChecker library (https://pypi.org/project/robotframework-requestschecker/) the import in RIDE is red, and there is an error shown in the RIDE log.

**Error shown in RIDE log in v1.7.4.2**
```
[WARN]: Importing test library "RequestsChecker" failed
Traceback (most recent call last):
list index out of range
  File "c:\users\emile\appdata\local\programs\python\python37\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "c:\users\emile\appdata\local\programs\python\python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 32, in get_import_result
    ) for kw in lib.handlers]
  File "c:\users\emile\appdata\local\programs\python\python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 32, in <listcomp>
    ) for kw in lib.handlers]
  File "c:\users\emile\appdata\local\programs\python\python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 43, in _parse_args
    parsed[index] = parsed[index] + '=' + unicode(value)
```

**Error shown in RIDE log in v2.0b2.dev0 (last line is different)**
```
 [WARN]: Importing test library "C:\Users\Emile\RF_Tst_Proj\../AppData/Local/Programs/Python/Python37/Lib/site-packages/RequestsChecker.py" failed
Traceback (most recent call last):
list index out of range
  File "c:\users\emile\appdata\local\programs\python\python37\lib\site-packages\robotide\spec\librarymanager.py", line 82, in _fetch_keywords
    return get_import_result(path, library_args)
  File "c:\users\emile\appdata\local\programs\python\python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 29, in get_import_result
    ) for kw in lib.handlers]
  File "c:\users\emile\appdata\local\programs\python\python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 29, in <listcomp>
    ) for kw in lib.handlers]
  File "c:\users\emile\appdata\local\programs\python\python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 40, in _parse_args
    parsed[index] = parsed[index] + '=' + str(args.defaults[value])  # DEBUG str(value)
```

A workaround is to use libdoc to create an XML and use the Import Library Spec XML option to fix the error. (Thanks @HelioGuilherme66 for this solution)

**Comment by JFoederer** [comment]
The error being reported here looks very similar to issue #2342

**Comment by JFoederer** [comment]
I gave it a try to import the RequestChecker library on my machine that had Pull request #2343 installed, that succeeded. I did not check if it failed without that change.

**Comment by HelioGuilherme66** [comment]
Thanks. The problem with this library, is that it only have one keyword or no documentation.
