### ISSUE TITLE
RIDE crash when renaming keyword in resource tree node

### ISSUE THREAD

**Issue by jnhyperion** [robotframework/RIDE#2316]
- rename keyword name, open in name edit text ctrl
- modify name, and then quick double click in the border of the entry box
- repeat sometimes. RIDE will crash

Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\robotide\application\application.py", line 62, in OnInit
    self._plugin_loader.enable_plugins()
  File "D:\Python37\lib\site-packages\robotide\application\pluginloader.py", line 43, in enable_plugins
    p.enable_on_startup()
  File "D:\Python37\lib\site-packages\robotide\application\pluginconnector.py", line 52, in enable_on_startup
    self.enable()
  File "D:\Python37\lib\site-packages\robotide\application\pluginconnector.py", line 57, in enable
    self._plugin.enable()
  File "D:\Python37\lib\site-packages\robotide\recentfiles\recentfiles.py", line 44, in enable
    self._add_recent_files_to_menu()
  File "D:\Python37\lib\site-packages\robotide\recentfiles\recentfiles.py", line 117, in _add_recent_files_to_menu
    self._add_file_to_menu(path, n)
  File "D:\Python37\lib\site-packages\robotide\recentfiles\recentfiles.py", line 124, in _add_file_to_menu
    self.register_action(entry.get_action_info())
  File "D:\Python37\lib\site-packages\robotide\pluginapi\plugin.py", line 204, in register_action
    action = self.__frame.actions.register_action(action_info)
  File "D:\Python37\lib\site-packages\robotide\ui\mainframe.py", line 751, in register_action
    self._menubar.register(action)
  File "D:\Python37\lib\site-packages\robotide\ui\actiontriggers.py", line 60, in register
    menu.add_menu_item(action)
  File "D:\Python37\lib\site-packages\robotide\ui\actiontriggers.py", line 98, in add_menu_item
    menu_item = self._construct_menu_item(action)
  File "D:\Python37\lib\site-packages\robotide\ui\actiontriggers.py", line 107, in _construct_menu_item
    menu_item = self._create_menu_item(action)
  File "D:\Python37\lib\site-packages\robotide\ui\actiontriggers.py", line 139, in _create_menu_item
    pos = action.get_insertion_index(self.wx_menu)
  File "D:\Python37\lib\site-packages\robotide\action\action.py", line 40, in get_insertion_index
    return self._insertion_point.get_index(menu)
  File "D:\Python37\lib\site-packages\robotide\action\actioninfo.py", line 286, in get_index
    index = self._find_position_in_menu(menu)
  File "D:\Python37\lib\site-packages\robotide\action\actioninfo.py", line 296, in _find_position_in_menu
    if self._get_menu_item_name(item).lower() == self._item.lower():
  File "D:\Python37\lib\site-packages\robotide\action\actioninfo.py", line 301, in _get_menu_item_name
    return self._shortcut_remover.split(item.GetLabel())[0]
AttributeError: 'MenuItem' object has no attribute 'GetLabel'
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(475) in wxWindowBase::~wxWindowBase(): any pushed event handlers m
e been removed

**Comment by JioHooney** [comment]
I had the same problem
Is it resolved?

**Comment by HelioGuilherme66** [comment]
@JioHooney Can you try the current development version?

**Comment by HelioGuilherme66** [comment]
Closing Issue as fixed.
Currently on RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors).
