### ISSUE TITLE
Comment PAUSE does not work in Suite Setup

### ISSUE THREAD

**Issue by zssomi** [robotframework/RIDE#2347]
Hi,

I am using RIDE 1.7.4.2 running on Python 3.7.3. I tied to use the "Comment    PAUSE" statement.
It works fine, if I use it in a Test, but the process hangs over, if I write this command in to the Suite Setup.
The RIDE editor stopp the process, but does not write <<  PAUSED  >> to the screen, and the "continue"
button is also inactive. I can only stop the process.

The command line window has:

Exception happened during processing of request from ('127.0.0.1', 49695)
Traceback (most recent call last):
  File "D:\Pama_Test_Share\Ride-Editor\Lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "D:\Pama_Test_Share\Ride-Editor\Lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "D:\Pama_Test_Share\Ride-Editor\Lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Pama_Test_Share\Ride-Editor\Lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\Pama_Test_Share\Ride-Editor\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 512, in handle
    self.server.callback(name, *args)
  File "D:\Pama_Test_Share\Ride-Editor\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 136, in handle
    self._result_handler(*args)
  File "D:\Pama_Test_Share\Ride-Editor\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 167, in _result_handler
    self._pause_longname, self._pause_testname))
  File "D:\Pama_Test_Share\Ride-Editor\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 179, in _get_test_controller
    ret = self._project.find_controller_by_longname(longname, testname)
  File "D:\Pama_Test_Share\Ride-Editor\lib\site-packages\robotide\controller\project.py", line 104, in find_controller_by_longname
    return self._controller.find_controller_by_longname(longname, testname)
  File "D:\Pama_Test_Share\Ride-Editor\lib\site-packages\robotide\controller\filecontrollers.py", line 411, in find_controller_by_longname
    return self.find_controller_by_names(longname.split("."), testname)
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------

My suspition is, that the variable testname is not initialized. I am not in a test, I am in that moment in Suite Setup.

Sincerely Yours

Zsolt

**Comment by HelioGuilherme66** [comment]
@zssomi Hello! I know that 3 years have passed, but now I tried to reproduce your problem. And I did not.
These are the files I experimented (current development version v2.0.8dev26 ,Python 3.11.6, wxPython 4.2.1, Fedora 38):

```
*** Settings ***
Suite Setup       Prepare    test
Resource          prepare.resource

*** Test Cases ***
example test
    Log    Ending test

```

prepare.resource:
```
*** Keywords ***
Prepare
    [Arguments]    ${arg1}
    Log    Argument is: ${arg1}
    FOR    ${idx}    IN RANGE    3
        Log    Counter: ${idx}
        Comment    Pause    Sleep    ${idx}
        Sleep    1
    END
```
