### ISSUE TITLE
Option "Only run tests with the tags" not working.

### ISSUE THREAD

**Issue by SanSiets73** [robotframework/RIDE#2365]
I'm noticing that the filter option (tags) is not working in RIDE.
If I run: `robot --include XXX -d C:\Log C:\Script\01.robot via a DOS prompt,only the testcases with tag XXX are executed.
but when I use the option Only run tetst with the tags in RIDE all my testcases are executed.

Example file 01.robot:
```
*** Test Cases ***
1
    [Tags]    XXX
    Log to Console    \n----- 01.01
2
    [Tags]    BulkExecute
    Log to Console    \n----- 01.02
3
    [Tags]    BulkExecute
    Log to Console    \n----- 01.03
```

Hélio Guilherme asked me to add the following to this ticket:
```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\robotide\contrib\testrunner\runprofiles.py", line 130, in __getattr__
    return getattr(self.plugin, self._get_setting_name(name))
  File "C:\Python38\lib\site-packages\robotide\pluginapi\plugin.py", line 137, in __getattr__
    raise AttributeError("No attribute or settings with name '%s' found" % name)
AttributeError: No attribute or settings with name 'robot__include_tags' found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\robotide\contrib\testrunner\runprofiles.py", line 530, in OnIncludeTagsChanged
    self.set_setting("include_tags", self._include_tags.GetValue())
  File "C:\Python38\lib\site-packages\robotide\contrib\testrunner\runprofiles.py", line 133, in __getattr__
    return getattr(self.plugin, name)
  File "C:\Python38\lib\site-packages\robotide\pluginapi\plugin.py", line 137, in __getattr__
    raise AttributeError("No attribute or settings with name '%s' found" % name)
AttributeError: No attribute or settings with name '_include_tags' found
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\robotide\contrib\testrunner\runprofiles.py", line 130, in __getattr__
    return getattr(self.plugin, self._get_setting_name(name))
  File "C:\Python38\lib\site-packages\robotide\pluginapi\plugin.py", line 137, in __getattr__
    raise AttributeError("No attribute or settings with name '%s' found" % name)
AttributeError: No attribute or settings with name 'robot__include_tags' found
```

**Comment by HelioGuilherme66** [comment]
@SanderMSB I have just tested with current `master` version and this does not happen.

My RIDE Log:
```
20210514 00:39:10.033 [INFO]: Found Robot Framework version 4.0.2 from /usr/local/lib/python3.8/site-packages/robot.

20210514 00:39:10.033 [INFO]: Started RIDE v2.0b2.dev3 using python version 3.8.9 with wx version 4.1.1 in linux.
```
