### ISSUE TITLE
Robotframework-ride 1.7.4: Can't see grid with python 2.7.12

### ISSUE THREAD

**Issue by xiaojike1213** [robotframework/RIDE#2369]
I have installed Robotframework-ride 1.7.4 for python2 and python3
But can't see grid with python 2.7.12

**The error in RIDE log:**
20210305 13:43:05.072 [ERROR]: Error in listener: 'utf8' codec can't decode byte 0x8b in position 4: invalid start byte
While handling <robotide.publish.messages2.RideTreeSelection object at 0x000000000AC16940>

Traceback (most recent call last):
'utf8' codec can't decode byte 0x8b in position 4: invalid start byte
  File "C:\Python27\lib\site-packages\robotide\publish\publisher.py", line 103, in __call__
    self.listener(data)
  File "C:\Python27\lib\site-packages\robotide\editor\__init__.py", line 124, in OnTreeItemSelected
    self._show_editor()
  File "C:\Python27\lib\site-packages\robotide\editor\__init__.py", line 117, in _show_editor
    self._editor = self._create_editor()
  File "C:\Python27\lib\site-packages\robotide\editor\__init__.py", line 121, in _create_editor
    return self._creator.editor_for(self, self._tab, self.tree)
  File "C:\Python27\lib\site-packages\robotide\editor\editorcreator.py", line 53, in editor_for
    self._editor = self._create_editor(editor_panel, plugin, tree)
  File "C:\Python27\lib\site-packages\robotide\editor\editorcreator.py", line 70, in _create_editor
    return self._create_new_editor(controller, editor_panel, plugin, tree)
  File "C:\Python27\lib\site-packages\robotide\editor\editorcreator.py", line 87, in _create_new_editor
    return editor_class(plugin, editor_panel, controller, tree)
  File "C:\Python27\lib\site-packages\robotide\editor\editors.py", line 80, in __init__
    self._populate()
  File "C:\Python27\lib\site-packages\robotide\editor\macroeditors.py", line 33, in _populate
    self._create_kweditor()
  File "C:\Python27\lib\site-packages\robotide\editor\macroeditors.py", line 37, in _create_kweditor
    self.kweditor = KeywordEditor(self, self.controller, self._tree)
  File "C:\Python27\lib\site-packages\robotide\editor\kweditor.py", line 111, in __init__
    self._configure_grid()
  File "C:\Python27\lib\site-packages\robotide\editor\kweditor.py", line 180, in _configure_grid
    self._set_fonts()
  File "C:\Python27\lib\site-packages\robotide\editor\kweditor.py", line 191, in _set_fonts
    font = wx.Font(font_size, font_family, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, False, font_face)

**Comment by HelioGuilherme66** [comment]
@xiaojike1213 Please retest on new version 2.0b2.

**Comment by HelioGuilherme66** [comment]
Closing because of no response from author.
