### ISSUE TITLE
Import RPA.Tables fails with list index out of range

### ISSUE THREAD

**Issue by Harm10** [robotframework/RIDE#2370]
When importing RPA.Tables I get these messages (on 2.0b1 and 1.7.4.2 on Python 3.7.9):
20210305 18:53:14.834 [WARN]: Importing test library "RPA.Tables" failed

Traceback (most recent call last):
list index out of range
  File "D:\Program Files\Python\lib\site-packages\robotide\spec\librarymanager.py", line 82, in _fetch_keywords
    return get_import_result(path, library_args)
  File "D:\Program Files\Python\lib\site-packages\robotide\spec\libraryfetcher.py", line 29, in get_import_result
    ) for kw in lib.handlers]
  File "D:\Program Files\Python\lib\site-packages\robotide\spec\libraryfetcher.py", line 29, in <listcomp>
    ) for kw in lib.handlers]
  File "D:\Program Files\Python\lib\site-packages\robotide\spec\libraryfetcher.py", line 40, in _parse_args
    parsed[index] = parsed[index] + '=' + str(args.defaults[value])  # DEBUG str(value)

According the RPA developers there is nothing wrong in their package and it should import normally in RIDE. When importing within Python itself I get no errors.
What is happening?

**Comment by osrjv** [comment]
Possibly related to https://github.com/robotframework/RIDE/issues/2342.

I think this is a minimal repro of what RIDE doesn't accept:
```
class TestLibrary:
    def keyword_with_varags(self, *args, kwarg=False):
        pass
```

**Comment by Harm10** [comment]
Any idea what I should do now? RIDE seems not to notice and I can still not use RPA.Tables.

**Comment by Harm10** [comment]
I installed a new release of RPA.Dialogs and now this package throws the same error:
`Traceback (most recent call last):
list index out of range
  File "D:\Program Files\Python\lib\site-packages\robotide\spec\librarymanager.py", line 82, in _fetch_keywords
    return get_import_result(path, library_args)
  File "D:\Program Files\Python\lib\site-packages\robotide\spec\libraryfetcher.py", line 29, in get_import_result
    ) for kw in lib.handlers]
  File "D:\Program Files\Python\lib\site-packages\robotide\spec\libraryfetcher.py", line 29, in <listcomp>
    ) for kw in lib.handlers]
  File "D:\Program Files\Python\lib\site-packages\robotide\spec\libraryfetcher.py", line 40, in _parse_args
    parsed[index] = parsed[index] + '=' + str(args.defaults[value])  # DEBUG str(value)`

Any idea when this problem in RIDE can be resolved? Version 2.0b1

**Comment by HelioGuilherme66** [comment]
@Harm10 This is fixed in current `master, version v2.0b2.dev3.

**Comment by Harm10** [comment]
Is that available for pip install?

**Comment by Harm10** [comment]
I have installed this version and index out of range message is gone.

If I experience issues with this dev version can I just report them here on Github?

**Comment by HelioGuilherme66** [comment]
>I have installed this version and index out of range message is gone.
Good :)

>If I experience issues with this dev version can I just report them here on Github?
I would prefer to have confirmation before creation of Issues. There are already many issues here :)

Can you use the #ride channel on our Slack?

**Comment by Harm10** [comment]
I joined the Robotframework Slack and joined the #ride and #ride-dev channel.
