### ISSUE TITLE
Failure to start current beta2.dev3 on Windows Python 3.8, wxPython 4.1.1

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2379]
The following error appears:
```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\robotide\application\application.py", line 80, in OnInit
    self.frame._mgr.LoadPerspective(perspective, True)
  File "C:\Python38\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 5555, in LoadPerspective
    self.Update()
  File "C:\Python38\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 6388, in Update
    self.DoUpdate()
  File "C:\Python38\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 6498, in DoUpdate
    frame.SetPaneWindow(p)
  File "C:\Python38\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 3011, in SetPaneWindow
    indx = self._owner_mgr._panes.index(pane)
ValueError: <wx.lib.agw.aui.framemanager.AuiPaneInfo object at 0x000001B9DB077640> is not in list
OnInit returned false, exiting...
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\robotide\ui\treeplugin.py", line 150, in OnShowTree
    self._tree = Tree(self, self._parent.actions, self._parent._application.settings)
  File "C:\Python38\lib\site-packages\robotide\ui\treeplugin.py", line 216, in __init__
    treemixin.DragAndDrop.__init__(self, parent, **_TREE_ARGS)
  File "C:\Python38\lib\site-packages\wx\lib\mixins\treemixin.py", line 510, in __init__
    super(DragAndDrop, self).__init__(*args, **kwargs)
  File "C:\Python38\lib\site-packages\wx\lib\agw\customtreectrl.py", line 2880, in __init__
    wx.ScrolledWindow.__init__(self, parent, id, pos, size, style|wx.HSCROLL|wx.VSCROLL, name)
TypeError: ScrolledWindow(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'TreePlugin'
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(470) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed
```

Probably due to detached Project Tree explorer.

**Comment by HelioGuilherme66** [comment]
Workaround, is to edit `settings.cfg` and change:
Delete "AUI Perspective" and "AUI NB Perspective".
```
[[File Explorer]]
docked = True

[[Tree]]
docked = True

```
