### ISSUE TITLE
[DEV] Crash on Windows when panes are detached.

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2387]
Current 2.0b2.dev3.
wxPython 4.1.1
Investigate why crash happens on Windows when panes are detached:
```
D:\Testes>c:\Python39\python.exe -m robotide.__init__
Traceback (most recent call last):
  File "c:\Python39\lib\site-packages\robotide\application\application.py", line 80, in OnInit
    self.frame._mgr.LoadPerspective(perspective, True)
  File "c:\Python39\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 5555, in LoadPerspective
    self.Update()
  File "c:\Python39\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 6388, in Update
    self.DoUpdate()
  File "c:\Python39\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 6498, in DoUpdate
    frame.SetPaneWindow(p)
  File "c:\Python39\lib\site-packages\wx\lib\agw\aui\framemanager.py", line 3011, in SetPaneWindow
    indx = self._owner_mgr._panes.index(pane)
ValueError: <wx.lib.agw.aui.framemanager.AuiPaneInfo object at 0x0000021D506988E0> is not in list
OnInit returned false, exiting...
Traceback (most recent call last):
  File "c:\Python39\lib\site-packages\robotide\ui\treeplugin.py", line 150, in OnShowTree
    self._tree = Tree(self, self._parent.actions, self._parent._application.settings)
  File "c:\Python39\lib\site-packages\robotide\ui\treeplugin.py", line 216, in __init__
    treemixin.DragAndDrop.__init__(self, parent, **_TREE_ARGS)
  File "c:\Python39\lib\site-packages\wx\lib\mixins\treemixin.py", line 510, in __init__
    super(DragAndDrop, self).__init__(*args, **kwargs)
  File "c:\Python39\lib\site-packages\wx\lib\agw\customtreectrl.py", line 2880, in __init__
    wx.ScrolledWindow.__init__(self, parent, id, pos, size, style|wx.HSCROLL|wx.VSCROLL, name)
TypeError: ScrolledWindow(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'TreePlugin'
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(470) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

```

**Comment by HelioGuilherme66** [comment]
No crash but the errors are present (panes are docked) v2.0b2.dev3:
```
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\robotide\ui\treeplugin.py", line 150, in OnShowTree
    self._tree = Tree(self, self._parent.actions, self._parent._application.settings)
  File "C:\Python39\lib\site-packages\robotide\ui\treeplugin.py", line 216, in __init__
    treemixin.DragAndDrop.__init__(self, parent, **_TREE_ARGS)
  File "C:\Python39\lib\site-packages\wx\lib\mixins\treemixin.py", line 510, in __init__
    super(DragAndDrop, self).__init__(*args, **kwargs)
  File "C:\Python39\lib\site-packages\wx\lib\agw\customtreectrl.py", line 2880, in __init__
    wx.ScrolledWindow.__init__(self, parent, id, pos, size, style|wx.HSCROLL|wx.VSCROLL, name)
TypeError: ScrolledWindow(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'TreePlugin'

```

**Comment by HelioGuilherme66** [comment]
Well, five years have passed and with several code changes and versions upgrades, the issue cured by itself.

Current 2.2.5dev10
wxPython 4.2.5
Python 3.13/3.14
