### ISSUE TITLE
Linux install failed

### ISSUE THREAD

**Issue by wang-qa** [robotframework/RIDE#2437]
![image](https://user-images.githubusercontent.com/58168764/156505330-22f2ef0b-cbe6-4b8d-af2c-873136fc7b34.png)

```bash
# lenovo @ lenovo-laptop in ~ [13:55:34]
$ pip install -U https://github.com/robotframework/RIDE/archive/master.zip
Defaulting to user installation because normal site-packages is not writeable
Collecting https://github.com/robotframework/RIDE/archive/master.zip
  Downloading https://github.com/robotframework/RIDE/archive/master.zip
     | 2.1 MB 139.7 kB/s 0:00:15
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/lenovo/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 20, in <module>
          from setuptools.dist import Distribution, Feature
        File "/home/lenovo/.local/lib/python3.9/site-packages/setuptools/dist.py", line 34, in <module>
          from setuptools.depends import Require
        File "/home/lenovo/.local/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
          from .py33compat import Bytecode
        File "/home/lenovo/.local/lib/python3.9/site-packages/setuptools/py33compat.py", line 55, in <module>
          unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
      AttributeError: 'HTMLParser' object has no attribute 'unescape'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by HelioGuilherme66** [comment]
Nothing that we can reproduce, so closing.
