### ISSUE TITLE
BuiltIn.Skip make ride to fail

### ISSUE THREAD

**Issue by rbuchmann77** [robotframework/RIDE#2451]
I created a test case with 1 line/step:
```BuiltIn.Skip    TODO```

When I run robot from bash, it works. The report generates no warning/errors. I have the right number of tests count, passed, failed, and skipped.

When I use Ride, I get exceptions:
```1 test, 0 passed, 0 failed, 1 skipped
=============================================================================================================================================================
Output:  /tmp/RIDEy6lvd2vi.d/output.xml
[ ERROR ] Calling method 'log_message' of listener '/usr/local/lib/python3.6/dist-packages/robotide/contrib/testrunner/TestRunnerAgent.py' failed: BrokenPipeError: [Errno 32] Broken pipe
[ ERROR ] Calling method 'end_keyword' of listener '/usr/local/lib/python3.6/dist-packages/robotide/contrib/testrunner/TestRunnerAgent.py' failed: BrokenPipeError: [Errno 32] Broken pipe
[ ERROR ] Calling method 'end_suite' of listener '/usr/local/lib/python3.6/dist-packages/robotide/contrib/testrunner/TestRunnerAgent.py' failed: BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/robotide/contrib/testrunner/TestRunnerAgent.py", line 260, in _send_socket
    self.filehandler.flush()
  File "/usr/lib/python3.6/socket.py", line 604, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
Log:     /tmp/RIDEy6lvd2vi.d/log.html
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/robotide/contrib/testrunner/TestRunnerAgent.py", line 260, in _send_socket
    self.filehandler.flush()
  File "/usr/lib/python3.6/socket.py", line 604, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
Report:  /tmp/RIDEy6lvd2vi.d/report.html
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/robotide/contrib/testrunner/TestRunnerAgent.py", line 260, in _send_socket
    self.filehandler.flush()
  File "/usr/lib/python3.6/socket.py", line 604, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
[ ERROR ] Calling method 'log_file' of listener '/usr/local/lib/python3.6/dist-packages/robotide/contrib/testrunner/TestRunnerAgent.py' failed: BrokenPipeError: [Errno 32] Broken pipe
[ ERROR ] Calling method 'report_file' of listener '/usr/local/lib/python3.6/dist-packages/robotide/contrib/testrunner/TestRunnerAgent.py' failed: BrokenPipeError: [Errno 32] Broken pipe
[ ERROR ] Calling method 'close' of listener '/usr/local/lib/python3.6/dist-packages/robotide/contrib/testrunner/TestRunnerAgent.py' failed: BrokenPipeError: [Errno 32] Broken pipe```

I tried with ride 1.7.4.2 and 2.0b1.

**Comment by HelioGuilherme66** [comment]
This is fixed in current development version.
From the [CHANGELOG](https://github.com/robotframework/RIDE/blob/master/CHANGELOG.adoc): `Fixed TestRunner crash when test use SKIP keyword`
