### ISSUE TITLE
Traceback if inpath CLI argument not given

### ISSUE THREAD

**Issue by psam44** [robotframework/RIDE#2463]
Win 10
robotframework-ride-2.0b1

Every time I leave the RIDE window:
```
Traceback (most recent call last):
  File "C:\venvs\py310wx\lib\site-packages\robotide\application\application.py", line 195, in OnAppActivate
    RideFSWatcherHandler.start_listening(self.workspace_path)
  File "C:\venvs\py310wx\lib\site-packages\robotide\utils\eventhandler.py", line 36, in start_listening
    if not os.path.exists(path):
  File "C:\Program Files\Python310\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
No surprise, inpath is None (and no file ever open), and so is self.workspace_path, given to RideFSWatcherHandler.

And every time I return to the window (I suppose it is related):
![image](https://user-images.githubusercontent.com/537094/178822022-85503d54-fe3b-4e45-a14d-28d39954d1d1.png)

**Comment by HelioGuilherme66** [comment]
@psam44 Thanks for the report, but 2.0b1 code is already too much changed to be considered as fixable. Users should always try the most recent version from development (install from `master` branch), and confirm if the issue still exists.
The relevant part of the code with the problem you report is now:
```python
    def OnAppActivate(self, event):
        if self.workspace_path is not None and RideFSWatcherHandler.is_watcher_created():
            if event.GetActive():
                # print(f"DEBUG: OnAppActivate event.GetActive  is_project_changed_from_disk = {self._controller.is_project_changed_from_disk()}")
                #print(f"DEBUG: OnAppActivate event.GetActive  is_workspace_dirty = {RideFSWatcherHandler.is_workspace_dirty()}")
                #DEBUG if self._controller.is_project_changed_from_disk() or \
                if RideFSWatcherHandler.is_workspace_dirty():
                    self.frame.show_confirm_reload_dlg(event)
                RideFSWatcherHandler.stop_listening()
            else:
                RideFSWatcherHandler.start_listening(self.workspace_path)
        event.Skip()
```
