### ISSUE TITLE
Add List & Add Dict are not working

### ISSUE THREAD

**Issue by Futhark1988** [robotframework/RIDE#2477]
**Steps to reproduce:**

- Open RIDE
- Creata a Project
- Click on Add List & Add Dict

**Expected result**
A window appears in which you can set the values of lists and dictionaries respectivly.

**Actual result**
Nothing happens.

**Version**
RIDE v2.0b2.dev20 running on Python 3.10.6. 

**OS**
Windows 11 Home 21H2

**wxPython**
4.2.0

**Comment by HelioGuilherme66** [comment]
@Futhark1988 Thanks for the report. (you could have added more info, like operative system and version of wxPython)

Here is the error output on Windows 10, wxPython 4.2.0, Python 3.10.6 (venv):
```
(venv310) C:\GitHub\RIDE>invoke devel
Traceback (most recent call last):
  File "C:\GitHub\RIDE\src\robotide\editor\settingeditors.py", line 480, in OnAddList
    ListVariableDialog(self._controller, plugin=self.Parent.plugin))
  File "C:\GitHub\RIDE\src\robotide\editor\editordialogs.py", line 46, in __init__
    self._editors = self._get_editors(item)
  File "C:\GitHub\RIDE\src\robotide\editor\editordialogs.py", line 118, in _get_editors
    ListValueEditor(self, value, 'Value',
  File "C:\GitHub\RIDE\src\robotide\editor\fieldeditors.py", line 47, in __init__
    self._create_editor(value, label, settings)
  File "C:\GitHub\RIDE\src\robotide\editor\fieldeditors.py", line 171, in _create_editor
    self._editor = _EditorGrid(self, value, cols)
  File "C:\GitHub\RIDE\src\robotide\editor\fieldeditors.py", line 229, in __init__
    GridEditor.__init__(self, parent, num_rows, num_cols)
  File "C:\GitHub\RIDE\src\robotide\editor\gridbase.py", line 60, in __init__
    self.CreateGrid(num_rows, num_cols)
TypeError: Grid.CreateGrid(): argument 1 has unexpected type 'float'
```

This looks like an easy fix.

**Comment by Futhark1988** [comment]
I added the details. A template for the issues would help a lot. ;)

**Comment by HelioGuilherme66** [comment]
@Futhark1988 Current fix allows to create variables but not Edit (causing RIDE lock!!) Still debugging this.
Code at: https://github.com/HelioGuilherme66/RIDE/archive/refs/heads/miscellaneous.zip
