### ISSUE TITLE
ride can not see run page

### ISSUE THREAD

**Issue by zhangys1989** [robotframework/RIDE#2483]
python version 3.10.0
wxpython version 4.2.0
ride version is master code

robotframework                  5.0.1
robotframework-appiumlibrary    1.6.3
robotframework-databaselibrary  1.2.4
robotframework-pythonlibcore    3.0.0
robotframework-ride             2.0b2.dev23
robotframework-selenium2library 3.0.0

![13](https://user-images.githubusercontent.com/41988543/187354263-37732df3-eeee-458f-9a07-fa650f94a205.jpg)

**Comment by zhangys1989** [comment]
log_message
    return pluginapi.RideLogMessage(
AttributeError: module 'robotide.pluginapi' has no attribute 'RideLogMessage'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 570, in OnTimer
    self.OnProcessEnded(None)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 521, in OnProcessEnded
    output, errors, log_message = self._test_runner.get_output_and_errors(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/robotide/contrib/testrunner/testrunner.py", line 177, in get_output_and_errors
    error, log_message = profile.format_error(stderr, returncode)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/robotide/contrib/testrunner/runprofiles.py", line 118, in format_error
    return error, self._create_error_log_message(error, returncode)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/robotide/contrib/testrunner/runprofiles.py", line 423, in _create_error_log_message
    return pluginapi.RideLogMessage(
AttributeError: module 'robotide.pluginapi' has no attribute 'RideLogMessage'

**Comment by zhangys1989** [comment]
@HelioGuilherme66 can you help me?

**Comment by zhangys1989** [comment]
@tommi @pekkaklarck @edbrannin @bjornfor can you help me?

**Comment by JFoederer** [comment]
Not a fix, but a workaround to get it back:
From the _Tools_ menu open _Manage Plugins_, and then disable and re-enable the _Test Runner_ plugin.

**Comment by zhangys1989** [comment]
@JFoederer thank you

**Comment by zhangys1989** [comment]
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 521, in OnProcessEnded
    output, errors, log_message = self._test_runner.get_output_and_errors(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/robotide/contrib/testrunner/testrunner.py", line 177, in get_output_and_errors
    error, log_message = profile.format_error(stderr, returncode)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/robotide/contrib/testrunner/runprofiles.py", line 118, in format_error
    return error, self._create_error_log_message(error, returncode)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/robotide/contrib/testrunner/runprofiles.py", line 423, in _create_error_log_message
    return pluginapi.RideLogMessage(
AttributeError: module 'robotide.pluginapi' has no attribute 'RideLogMessage'
^C


@JFoederer run case,An error occurred
can you help me？

**Comment by zhangys1989** [comment]
![image](https://user-images.githubusercontent.com/41988543/187421510-9a7801e5-90e3-441d-a5ed-01b60722057a.png)

**Comment by HelioGuilherme66** [comment]
@zhangys1989 Like I mentioned in #2482, you are using `pybot` run profile, which exists in RIDE just for a matter of backwards compatibility. and probably will be removed in a near future.

The solution is to use the `robot` run profile.

If you want to keep several Python/RIDE or Robot Framework versions, you should adjust the scripts to launch each tool (like PATH, PYTHONPATH, etc).
