### ISSUE TITLE
error when trying to run ride.py - ImportError: cannot import name 'Mapping' from 'collections' 

### ISSUE THREAD

**Issue by doniks** [robotframework/RIDE#2490]
```
$ uname -a
Linux peter-ThinkPad 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

$ cd ~/.local/lib
$ rm -rf python3.10/
$ pip3 install robotframework
Defaulting to user installation because normal site-packages is not writeable
Collecting robotframework
  Using cached robotframework-5.0.1-py3-none-any.whl (639 kB)
Installing collected packages: robotframework
Successfully installed robotframework-5.0.1
$ robot --version
Robot Framework 5.0.1 (Python 3.10.4 on linux)

$ pip3 install robotframework-ride
Defaulting to user installation because normal site-packages is not writeable
Collecting robotframework-ride
  Using cached robotframework_ride-1.7.4.2-py3-none-any.whl
Requirement already satisfied: wxPython<=4.0.7.post2 in /usr/lib/python3/dist-packages (from robotframework-ride) (4.0.7)
Requirement already satisfied: PyPubSub in /usr/lib/python3/dist-packages (from robotframework-ride) (4.0.3)
Requirement already satisfied: Pygments in /usr/lib/python3/dist-packages (from robotframework-ride) (2.11.2)
Installing collected packages: robotframework-ride
Successfully installed robotframework-ride-1.7.4.2
peter@peter-ThinkPad:~/.local/lib
$ ride.py
Traceback (most recent call last):
  File "/home/peter/.local/bin/ride.py", line 21, in <module>
    from robotide import main
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/__init__.py", line 59, in <module>
    from robotide.utils import PY2, PY3
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/utils/__init__.py", line 21, in <module>
    import robotide.lib.robot.utils
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/__init__.py", line 44, in <module>
    from robotide.lib.robot.rebot import rebot, rebot_cli
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/rebot.py", line 40, in <module>
    from robotide.lib.robot.conf import RebotSettings
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/conf/__init__.py", line 27, in <module>
    from .settings import RobotSettings, RebotSettings
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/conf/settings.py", line 22, in <module>
    from robotide.lib.robot.output import LOGGER, loggerhelper
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/output/__init__.py", line 22, in <module>
    from .output import Output
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/output/output.py", line 16, in <module>
    from . import pyloggingconf
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/output/pyloggingconf.py", line 19, in <module>
    from robotide.lib.robot.utils import get_error_details, unic
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/utils/__init__.py", line 36, in <module>
    from .argumentparser import ArgumentParser, cmdline2list
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/utils/argumentparser.py", line 28, in <module>
    from .misc import plural_or_not
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/utils/misc.py", line 21, in <module>
    from .robottypes import is_integer
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/utils/robottypes.py", line 25, in <module>
    from .robottypes3 import (is_bytes, is_dict_like, is_integer, is_list_like,
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/lib/robot/utils/robottypes3.py", line 16, in <module>
    from collections import Mapping, UserString
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by HelioGuilherme66** [comment]
That version of RIDE is not compatible with Python 3.10 (not even python 3.8)
```
$ pip3 install robotframework-ride
Defaulting to user installation because normal site-packages is not writeable
Collecting robotframework-ride
  Using cached robotframework_ride-1.7.4.2-py3-none-any.whl
```

Correct command is:
```
pip3 install --pre robotframework-ride
```

**Comment by doniks** [comment]
thanks for the quick response @HelioGuilherme66 , I tried however, now I see a different error 

```


$ pip3 install robotframework
Defaulting to user installation because normal site-packages is not writeable
Collecting robotframework
  Using cached robotframework-5.0.1-py3-none-any.whl (639 kB)
Installing collected packages: robotframework
Successfully installed robotframework-5.0.1


$ pip3 install --pre robotframework-ride
Defaulting to user installation because normal site-packages is not writeable
Collecting robotframework-ride
  Using cached robotframework_ride-2.0b2-py3-none-any.whl (1.4 MB)
Requirement already satisfied: Pygments in /usr/lib/python3/dist-packages (from robotframework-ride) (2.11.2)
Requirement already satisfied: PyPubSub in /usr/lib/python3/dist-packages (from robotframework-ride) (4.0.3)
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from robotframework-ride) (5.9.0)
Requirement already satisfied: wxPython in /usr/lib/python3/dist-packages (from robotframework-ride) (4.0.7)
Installing collected packages: robotframework-ride
Successfully installed robotframework-ride-2.0b2


$ ride.py 
Traceback (most recent call last):
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/application/application.py", line 72, in OnInit
    self.frame = RideFrame(self, self._controller)
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/ui/mainframe.py", line 175, in __init__
    self._init_ui()
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/ui/mainframe.py", line 279, in _init_ui
    self.tree = Tree(self, self.actions, self._application.settings)
  File "/home/peter/.local/lib/python3.10/site-packages/robotide/ui/treeplugin.py", line 233, in __init__
    treemixin.DragAndDrop.__init__(self, parent, **_TREE_ARGS)
  File "/usr/lib/python3/dist-packages/wx/lib/mixins/treemixin.py", line 510, in __init__
    super(DragAndDrop, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/customtreectrl.py", line 2919, in __init__
    self.SetFocus()
TypeError: could not convert 'Tree' to 'Panel'
OnInit returned false, exiting...
Exception ignored in atexit callback: <built-in function _wxPyCleanup>
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ../src/common/wincmn.cpp(477) in ~wxWindowBase(): any pushed event handlers must have been removed


```

**Comment by doniks** [comment]
I've now reread some of the docs wrt compatibility... It's still not completely clear to me which version or combination thereof is the most stable / suggested one. Maybe python 3.7?! However from the normal Ubuntu repos directly I can only get 3.8 and 3.10... So, maybe I'm just out of luck

**Comment by HelioGuilherme66** [comment]
@doniks 
Try to install this:
`sudo apt install wxpython-tools -y` 

If still not working, try to install latest wxPython, version 4.2.0.
