### ISSUE TITLE
Fail execution with runas command

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#251]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=216) by jrvilda on 1 Sep 2009*

La ejecucion del RIDE falla en windows XP cuando se ejecuta con runas.
Ride guarda en la ruta &#37;appdata&#37; el fichero de configuración.
Cuando se ejecuta cmd desde el usuario y se muestra la salida del comando 
set, existe la ruta &#37;appdata&#37; pero cuando se ejecuta cmd desde usuario con 
el comando runas, y se muestra la salida del comando set,esta ruta no 
existe.
-------------
RIDE Execution fails when running Windows XP with runas. 
Ride stored in the &#37;appdata&#37; the configuration file. 
When you run cmd from the user and shows the output of the set command, 
there is the &#37;appdata&#37; but when you run cmd from user with the runas 
command, and displays the output of the command set, this route does not 
exist.
 
python 2.5.4
Robotframework 2.1.1
Ride 0.17.1

Windows XP

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=216#c1) by @yanne on 3 Sep 2009*


Can you provide the exact error message that you get?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=216#c2) by jrvilda on 4 Sep 2009*


Traceback (most recent call last):
  File "E:\python25\lib\runpy.py", line 95, in run_module
    filename, loader, alter_sys)
  File "E:\python25\lib\runpy.py", line 52, in _run_module_code
    mod_name, mod_fname, mod_loader)
  File "E:\python25\lib\runpy.py", line 32, in _run_code
    exec code in run_globals
  File "E:\python25\lib\site-packages\robotide\__init__.py", line 83, in &lt;module
&gt;
    main(sys.argv[1:])
  File "E:\python25\lib\site-packages\robotide\__init__.py", line 50, in main
    _run(*args)
  File "E:\python25\lib\site-packages\robotide\__init__.py", line 60, in _run
    from robotide.application import RobotIde
  File "E:\python25\Lib\site-packages\robotide\application\__init__.py", line 15
, in &lt;module&gt;
    from application import RobotIde
  File "E:\python25\Lib\site-packages\robotide\application\application.py", line
 19, in &lt;module&gt;
    from robotide import context
  File "E:\python25\Lib\site-packages\robotide\context\__init__.py", line 21, in
 &lt;module&gt;
    from settings import Settings, initialize_settings
  File "E:\python25\lib\site-packages\robotide\context\settings.py", line 10, in
 &lt;module&gt;
    SETTINGS_DIRECTORY = os.path.join(os.environ['APPDATA'], 'RobotFramework')
  File "E:\Python25\lib\os.py", line 433, in __getitem__
    return self.data[key.upper()]
KeyError: 'APPDATA'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=216#c3) by @pekkaklarck on 29 Sep 2009*


The problem seems to be that if you run RIDE as another user, the user's environment
is not initialized fully and thus APPDATA environment variable is not set. At least
from the command line you can use /env switch to use the current environment instead
of the user's. Could you try that?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=216#c4) by @pekkaklarck on 30 Sep 2009*


The easiest fix I can think for this issue is using default settings and disabling
writing settings to disk. That's covered by <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=166" title="Show error if user settings are invalid"> issue 166 </a> so perhaps this issue should be
closed as a duplicate for <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=166" title="Show error if user settings are invalid"> issue 166 </a>.
