### ISSUE TITLE
Ride UI is opening and closed before loading completely

### ISSUE THREAD

**Issue by rithanyasiva** [robotframework/RIDE#2569]
C:\Users\as>ride.py
Traceback (most recent call last):
  File "c:\users\as\appdata\local\programs\python\python37\lib\site-packages\robotide\application\application.py", line 68, in OnInit
    self._find_robot_installation()
  File "c:\users\as\appdata\local\programs\python\python37\lib\site-packages\robotide\application\application.py", line 106, in _find_robot_installation
    ['import robot; print(robot.__file__ + \", \" + robot.__version__)'])
  File "c:\users\as\appdata\local\programs\python\python37\lib\site-packages\robotide\utils\__init__.py", line 126, in run_python_command
    stderr=subprocess.PIPE)  # DEBUG STDOUT PIPE
  File "c:\users\as\appdata\local\programs\python\python37\lib\subprocess.py", line 728, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "c:\users\as\appdata\local\programs\python\python37\lib\subprocess.py", line 1049, in _get_handles
    c2pread, c2pwrite = _winapi.CreatePipe(None, 0)
PermissionError: [WinError 5] Access is denied
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

**Comment by HelioGuilherme66** [comment]
@rithanyasiva Can you, please upgrade RIDE to version 2.0?
```
pip install -U robotframework-ride
```

**Comment by HelioGuilherme66** [comment]
Closing because no answer from author, or the issue is fixed in newer versions.
