### ISSUE TITLE
ride installation issue

### ISSUE THREAD

**Issue by bansal1988** [robotframework/RIDE#2649]
hi,
when i am trying to install ride having following error:
Traceback (most recent call last):
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\__init__.py", line 71, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\__init__.py", line 91, in _run
    from robotide.application import RIDE
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\application\__init__.py", line 16, in <module>
    from .application import RIDE
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\application\application.py", line 20, in <module>
    from ..namespace import Namespace
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\namespace\__init__.py", line 16, in <module>
    from .namespace import Namespace
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\namespace\namespace.py", line 27, in <module>
    from ..spec.iteminfo import (TestCaseUserKeywordInfo, ResourceUserKeywordInfo, VariableInfo, UserKeywordInfo,
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\spec\__init__.py", line 16, in <module>
    from .librarydatabase import DATABASE_FILE
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\spec\librarydatabase.py", line 20, in <module>
    from ..preferences.settings import SETTINGS_DIRECTORY
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\preferences\__init__.py", line 17, in <module>
    from .editors import GridEditorPreferences, TextEditorPreferences, TestRunnerPreferences
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\preferences\editors.py", line 22, in <module>
    from ..ui.preferences_dialogs import (PreferencesPanel, SpinChoiceEditor, IntegerChoiceEditor, boolean_editor,
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\ui\__init__.py", line 18, in <module>
    from .treeplugin import Tree
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\ui\treeplugin.py", line 34, in <module>
    from ..ui.images import (RUNNING_IMAGE_INDEX, PASSED_IMAGE_INDEX, FAILED_IMAGE_INDEX, PAUSED_IMAGE_INDEX,
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\ui\images.py", line 20, in <module>
    from ..controller import filecontrollers
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\controller\__init__.py", line 18, in <module>
    from .project import Project
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\controller\project.py", line 27, in <module>
    from ..spec.xmlreaders import SpecInitializer
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\spec\xmlreaders.py", line 20, in <module>
    from ..utils.versioncomparator import cmp_versions
  File "C:\Users\shivban\AppData\Local\Programs\Python\Python312\Lib\site-packages\robotide\utils\versioncomparator.py", line 16, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'

Use --help to get usage information.

the following is my pip list:
C:\>pip list
Package             Version
------------------- -------
Pillow              10.0.1
pip                 23.2.1
psutil              5.9.5
Pygments            2.16.1
Pypubsub            4.0.3
pywin32             306
robotframework      6.1.1
robotframework-ride 2.0.7
six                 1.16.0
wxPython            4.2.1

**Comment by axiom41** [comment]
Hello.
Python 3.12 should be the cause (RIDE has been tested up to 3.11)

**Comment by bansal1988** [comment]
thank you for your suuport its solved now.
