### ISSUE TITLE
Preview fails - and possibly prevents RIDE from starting - when no file is open

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#280]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=245) by jrvilda on 18 Sep 2009*

C:\SVS RF-IDE&gt;python rundevel.py
Traceback (most recent call last):
  File "C:\SVS RF-IDE\src\robotide\application\preview.py", line 154, in
OnTypeChanged
    self.preview(self._datafile)
  File "C:\SVS RF-IDE\src\robotide\application\preview.py", line 134, in
preview
    datafile._serialize(writer)
AttributeError: 'NoneType' object has no attribute '_serialize'
Traceback (most recent call last):
  File "C:\SVS RF-IDE\src\robotide\application\preview.py", line 154, in
OnTypeChanged
    self.preview(self._datafile)
  File "C:\SVS RF-IDE\src\robotide\application\preview.py", line 134, in
preview
    datafile._serialize(writer)
AttributeError: 'NoneType' object has no attribute '_serialize'

18 (2009/09/18_1506 GMT
Windows XP sp3
ActivePython 2.5.4.4 (ActiveState Software Inc.) based on
Python 2.5.4 (<a href="https://code.google.com/p/robotframework-ride/source/detail?r=254">r254</a>:67916, Apr 27 2009, 15:41:14) [MSC v.1310 32 bit
(Intel)] on win32
wxpython '2.8.9.1 (msw-unicode)'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=245#c1) by @pekkaklarck on 18 Sep 2009*


Is this the latest trunk? I cannot reproduce the problem.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=245#c2) by jrvilda on 18 Sep 2009*


happens only if you have not opened any testcase.
Yes, is the latest trunk.
synchronized 2009/09/18_1506 GMT

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=245#c3) by @pekkaklarck on 18 Sep 2009*


I can reproduce this by opening empty RIDE and then selecting Preview from Tools. We
changed Preview plugin so that it's not loaded automatically, but in your case you
probably have old settings that still try to load it when RIDE is opened. That's
really annoying as it apparently prevents RIDE from opening -- in my case I just get
traceback to console as RIDE is already up and wx catches this kind of exceptions.

Anyway, I'll see if I can fix this immediately.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=245#c4) by @pekkaklarck on 18 Sep 2009*


Ought to be fixed in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=882">r882</a>. jrvilda, could you test this on your system?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=245#c5) by jrvilda on 18 Sep 2009*


perfect
