### ISSUE TITLE
[Tree View] Segmentation fault (core dumped) after pressing the ESC key while editing names of test suite/case/keyword

### ISSUE THREAD

**Issue by ZDabrowski** [robotframework/RIDE#2838]
After pressing the ESC key to cancel editng names of test suites/cases/keywords in a Tree View, RIDE closed with the segmentation fault.

**Environment**
Python 3.10.12
wxPython 4.2.1
robotframework 6.0.2
robotframework-ride 2.1.dev61
Ubuntu 22.04.4 LTS

**Steps**
1. Edit keyword name in a Tree View (F2)
![obraz](https://github.com/user-attachments/assets/6bbe2056-a043-49be-b71e-083f8cbbbdae)
2. Press ESC key to cancel editing:
[1]+  Segmentation fault      (core dumped) ride.py

**Comment by HelioGuilherme66** [comment]
@ZDabrowski This seems to be a problem with wxPython/wxWidgets library.

It did not crash on my system but the error is visible:
```
(__init__.py:8040): GLib-GObject-CRITICAL **: 19:11:24.153: ../gobject/gsignal.c:2585: instance '0x556068ee4ef0' has no handler with id '65536'
Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/wx/lib/agw/customtreectrl.py", line 1496, in OnChar
    self.StopEditing()
  File "/usr/lib64/python3.12/site-packages/wx/lib/agw/customtreectrl.py", line 1554, in StopEditing
    self.Finish()
  File "/usr/lib64/python3.12/site-packages/wx/lib/agw/customtreectrl.py", line 1471, in Finish
    self._owner.ResetEditControl()
  File "/usr/lib64/python3.12/site-packages/wx/lib/agw/customtreectrl.py", line 4975, in ResetEditControl
    self._editCtrl.Destroy()
wx._core.wxAssertionError: C++ assertion "m_inKeyPress" failed at ../src/gtk/textentry.cpp(77) in EndHandlingKeyPressAndCheckIfPending(): 
```
**Environment**
Python 3.12.4
wxPython 4.2.1
robotframework 7.0.1
robotframework-ride 2.1.dev61
Fedora 40

**Comment by ZDabrowski** [comment]
@HelioGuilherme66, noticed that this bug was already reported in the https://github.com/robotframework/RIDE/issues/2718

**Comment by HelioGuilherme66** [comment]
@ZDabrowski This problem is fixed in current development version, 2.2dev41.
