### ISSUE TITLE
Broken Desktop Shortcut creation in some Linux systems

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2912]
The command `logname` isw not returning the expected login name. The variable `$USER` contains the correct value.

When running script to create desktop shortcut, the following output is shown:
```
python -m robotide.postinstall -install
wxPython is installed.
4.2.1 gtk3 (phoenix) wxWidgets 3.2.2.1
logname: no login name
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/robotide/postinstall/__main__.py", line 26, in <module>
    main(*sys.argv[1:])
  File "/usr/local/lib/python3.10/dist-packages/robotide/postinstall/__init__.py", line 351, in main
    create_desktop_shortcut(platform)
  File "/usr/local/lib/python3.10/dist-packages/robotide/postinstall/__init__.py", line 310, in create_desktop_shortcut
    return _create_desktop_shortcut_linux(frame)
  File "/usr/local/lib/python3.10/dist-packages/robotide/postinstall/__init__.py", line 183, in _create_desktop_shortcut_linux
    user = str(subprocess.check_output(['logname']).strip(), encoding='utf-8')
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['logname']' returned non-zero exit status 1.
```

Linux Debian based: bullseye/sid
Python 3.10
wxPython 4.2.1
RIDE 2.1.1

**Comment by HelioGuilherme66** [comment]
Fixed in 2.1.1
