### ISSUE TITLE
after sometime usage, robot ide cannot startup

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#340]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=305) by feiyuw on 23 Nov 2009*

I removed the config file 3 days ago, and use robotide to open
file/directory, and edit cases.
But today it cannot startup. The error message is as below:

Traceback (most recent call last):
  File "C:\USERS\PyWork\RobotIDE\robotide\__init__.py", line 83, in &lt;module&gt;
    main(sys.argv[1:])
  File "C:\USERS\PyWork\RobotIDE\robotide\__init__.py", line 50, in main
    _run(*args)
  File "C:\USERS\PyWork\RobotIDE\robotide\__init__.py", line 60, in _run
    from robotide.application import RIDE
  File
"C:\Users\Program\Python\Lib\site-packages\robotide\application\__init__.py",
line 15, in &lt;module&gt;
    from application import RIDE, DataModel
  File
"C:\Users\Program\Python\Lib\site-packages\robotide\application\application.py",
line 19, in &lt;module&gt;
    from robotide import context
  File
"C:\Users\Program\Python\Lib\site-packages\robotide\context\__init__.py",
line 38, in &lt;module&gt;
    SETTINGS = RideSettings()
  File
"C:\Users\Program\Python\Lib\site-packages\robotide\context\__init__.py",
line 28, in __init__
    user_path = initialize_settings('ride', default_path)
  File
"C:\Users\Program\Python\Lib\site-packages\robotide\context\settings.py",
line 45, in initialize_settings
    _merge_settings(source_path, settings_path)
  File
"C:\Users\Program\Python\Lib\site-packages\robotide\context\settings.py",
line 52, in _merge_settings
    settings.merge(ConfigObj(user_path, unrepr=True))
  File
"C:\Users\Program\Python\Lib\site-packages\robotide\context\configobj.py",
line 1219, in __init__
    self._load(infile, configspec)
  File
"C:\Users\Program\Python\Lib\site-packages\robotide\context\configobj.py",
line 1286, in _load
    infile = [line.rstrip('\r\n') for line in infile]
MemoryError

Environment:
Robot Framework 2.1.2 (Python 2.5.2 on win32)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=305#c1) by feiyuw on 23 Nov 2009*


after removing the settings.cfg, it can startup. But sometimes later, the error occur
again.
