### ISSUE TITLE
RIDE crashes if user keyword data contains UserErrorHandlers

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#344]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=317) by jinbo_yu on 23 Nov 2009*

a. When I load directory : TestCase/TT/ATM Transport/, and RIDE can not 
work. 

C:\Python25\Lib\site-packages\robotide&gt;python __init__.py 
Traceback (most recent call last): 
  File "C:\Python25\Lib\site-packages\robotide\editors\eventhandler.py", 
line 25 
, in wrapped 
    method(self, event) 
  File "C:\Python25\Lib\site-packages\robotide\ui\suitetree.py", line 322, 
in On 
SelChanged 
    self.show_editor(handler.item) 
  File "C:\Python25\Lib\site-packages\robotide\ui\suitetree.py", line 330, 
in sh 
ow_editor 
    self._editor = Editor(item, self._editor_panel, self) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
30, in 
Editor 
    return editor_class(editor_panel, item, tree) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
50, in 
__init__ 
    self._populate() 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
110, in 
 _populate 
    ResourceFileEditor._populate(self) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
79, in 
_populate 
    self.sizer.Add(self._create_header(self.item.name), 0, wx.ALL, 5) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
62, in 
_create_header 
    header = wx.StaticText(self, -1, text) 
  File "C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", 
line 
1136, in __init__ 
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, 
**kwarg 
s)) 
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at 
..\..\src\m 
sw\control.cpp(159) in wxControl::MSWCreateControl(): 
CreateWindowEx("STATIC", f 
lags=52000100, ex=00000000) failed 
Traceback (most recent call last): 
  File "C:\Python25\Lib\site-packages\robotide\editors\eventhandler.py", 
line 25 
, in wrapped 
    method(self, event) 
  File "C:\Python25\Lib\site-packages\robotide\ui\suitetree.py", line 322, 
in On 
SelChanged 
    self.show_editor(handler.item) 
  File "C:\Python25\Lib\site-packages\robotide\ui\suitetree.py", line 330, 
in sh 
ow_editor 
    self._editor = Editor(item, self._editor_panel, self) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
30, in 
Editor 
    return editor_class(editor_panel, item, tree) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
50, in 
__init__ 
    self._populate() 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
110, in 
 _populate 
    ResourceFileEditor._populate(self) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
79, in 
_populate 
    self.sizer.Add(self._create_header(self.item.name), 0, wx.ALL, 5) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
62, in 
_create_header 
    header = wx.StaticText(self, -1, text) 
  File "C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", 
line 
1136, in __init__ 
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, 
**kwarg 
s)) 
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at 
..\..\src\m 
sw\control.cpp(159) in wxControl::MSWCreateControl(): 
CreateWindowEx("STATIC", f 
lags=52000100, ex=00000000) failed 

And there are many dialogs like following pop up, it also affect load 
efficiency, could it pop up this error dialog just one time for all suite 
with format error?

 

b. When I load testcase\tt\ip transport, robot ide can work, but there are 
no suite loaded 

C:\Python25\Lib\site-packages\robotide&gt;python __init__.py 
Traceback (most recent call last): 
  File "C:\Python25\Lib\site-packages\robotide\editors\eventhandler.py", 
line 25 
, in wrapped 
    method(self, event) 
  File "C:\Python25\Lib\site-packages\robotide\ui\mainframe.py", line 195, 
in On 
OpenDirectory 
    self.open_suite(path) 
  File "C:\Python25\Lib\site-packages\robotide\ui\mainframe.py", line 185, 
in op 
en_suite 
    self._application.open_suite(path) 
  File "C:\Python25\Lib\site-packages\robotide\application\application.py", 
line 
 69, in open_suite 
    self.model = DataModel(path) 
  File "C:\Python25\Lib\site-packages\robotide\application\datamodel.py", 
line 2 
8, in __init__ 
    self._open(path) 
  File "C:\Python25\Lib\site-packages\robotide\application\datamodel.py", 
line 3 
4, in _open 
    self._open_suite(path) 
  File "C:\Python25\Lib\site-packages\robotide\application\datamodel.py", 
line 4 
3, in _open_suite 
    self.suite = TestSuiteFactory(path) 
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 40, in 
Test 
SuiteFactory 
    return _TestSuiteFactory(TestSuiteData(path)) 
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 50, in 
_Tes 
tSuiteFactory 
    return InitFile(data, parent) 
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 347, 
in __i 
nit__ 
    _TestSuite.__init__(self, data, parent) 
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 282, 
in __i 
nit__ 
    for suite in data.suites ] 
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 50, in 
_Tes 
tSuiteFactory 
    return InitFile(data, parent) 
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 347, 
in __i 
nit__ 
    _TestSuite.__init__(self, data, parent) 
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 282, 
in __i 
nit__ 
    for suite in data.suites ] 
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 51, in 
_Tes 
tSuiteFactory 
    return TestCaseFile(data, parent) 
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 311, 
in __i 
nit__ 
    _TestSuite.__init__(self, data, parent) 
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 278, 
in __i 
nit__ 
    _AbstractDataFile.__init__(self, data) 
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 71, in 
__in 
it__ 
    self.keywords = UserKeywordTable(self, data.user_keywords) 
  File "C:\Python25\Lib\site-packages\robotide\utils\misc.py", line 63, in 
__ini 
t__ 
    self._parse_data(data) 
  File "C:\Python25\Lib\site-packages\robotide\model\tables.py", line 192, 
in _p 
arse_data 
    self.append(self._item_class(self.datafile, item)) 
  File "C:\Python25\Lib\site-packages\robotide\model\tcuk.py", line 83, in 
__ini 
t__ 
    _TcUkBase.__init__(self, datafile, data, name) 
  File "C:\Python25\Lib\site-packages\robotide\model\tcuk.py", line 31, in 
__ini 
t__ 
    keywords = data and data.keywords or [] 
AttributeError: UserErrorHandler instance has no attribute 'keywords'

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=317#c1) by @yanne on 16 Dec 2009*


This need to be split in separate issues.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=317#c2) by @yanne on 17 Dec 2009*


I split this issue in two, part a) of this issue is now handled in <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=356" title="Some data crashes RIDE when editors are created"> issue356 </a>.
Changed the title of this issue accordingly

jinbo_yu@&#8288;126.com, please see that new issue and report your operating system and
wxPython version

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=317#c3) by @yanne on 17 Dec 2009*


This issue (part b) of the original report is  actually caused because the test data
that is being opened contains invalid user keywords. The warning messages are now
displayed as one dialog when the data is opened, that can be used to see what invalid
user keywords there are.

However, I also fixed RIDE not crash in this case, the fix is committed in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=664be81622">r664be81622</a>

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=317#c4) by @yanne on 14 Jan 2010*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=356" title="Some data crashes RIDE when editors are created"> Issue 356 </a> covers the first part of this issue, but we could not reproduce this with 
current IPA tests. Do you still get that error message?
