### ISSUE TITLE
Copied test case's or keyword's settings cannot be edited 

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#375]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348) by Magnus.Smedberg on 9 Dec 2009*

After having had RIDE open for a while, and edited some test cases and
keywords, RIDE stops noticing changes made, i.e. the star that tells you
the file has been changed, never shows up.
Since it's not possible to save a file that isn't marked with a star, it's
very easy to loose your changes (workaround exists, explained further down).

Unfortunately, I haven't been able to figure out what triggers this
behavior, it just seems to appear after a while.

Stack trace from the logs:
------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\editor\kweditor.py", line
52, in OnText self._grid.set_dirty()
  File "C:\Python26\lib\site-packages\robotide\editor\kweditor.py", line
321, in set_dirty self._tree.mark_dirty(self._datafile)
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 274, in
mark_dirty self._mark_dirty(self._get_datafile_node(datafile))
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 240, in
_mark_dirty text = self.GetItemText(node)
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py",
line 5303, in GetItemText return _controls_.TreeCtrl_GetItemText(*args,
**kwargs)
ValueError: invalid null reference in method 'TreeCtrl_GetItemText',
expected argument 2 of type 'wxTreeItemId const &amp;'
------------------------------------------------------------------------

*Workaround to save files: Editing the name of a test case or kw still
marks the file as changed.  

RIDE 0.20
Robot Framework 2.1.1 (Python 2.6.2 on win32)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c1) by @jrantanen on 16 Dec 2009*


Need to see if we can reproduce this.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c2) by Magnus.Smedberg on 14 Jan 2010*


Let me know if I can help you with reproducing this issue.
I keep getting it frequently, although I still haven't figured out what is triggering it.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c3) by @yanne on 14 Jan 2010*


I was just wondering about this.

Can you run RIDE from latest head? I have restructured the tree code a bit, and even 
though I wasn't specifically trying to fix this, I also touched the code shown in 
your stack trace.

Instructions for cloning are here:
<a href="https://code.google.com/p/robotframework-" rel="nofollow">https://code.google.com/p/robotframework-</a>
ride/wiki/InstallationInstructions#Running_RIDE_from_mercurial_clone

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c4) by Magnus.Smedberg on 20 Jan 2010*


Ok, I'm now running from <a href="https://code.google.com/p/robotframework-ride/source/detail?r=679">revision 679</a>.
I'll see if I get the same behavior as before, or if it's fixed.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c5) by Magnus.Smedberg on 21 Jan 2010*


Happened again, but this time only when editing the Doc/Setup/Teardown etc. fields.
Got an error message on that the file had changed on disk (which it hadn't), and the
following stack trace:
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "src\robotide\utils\eventhandler.py", line 22, in wrapped if
self._can_be_edited(event):
  File "src\robotide\utils\eventhandler.py", line 39, in _can_be_edited return
self._show_modified_on_disk_warning(item, event)
  File "src\robotide\utils\eventhandler.py", line 52, in show_modified_on_disk_warning
    self.refresh_datafile(item, event)
  File "src\robotide\editor\editors.py", line 162, in refresh_datafile
self._tree.refresh_datafile(item, event)
  File "src\robotide\ui\tree.py", line 272, in refresh_datafile insertion_index =
self._get_datafile_index(orig_node)
  File "src\robotide\ui\tree.py", line 294, in _get_datafile_index insertion_index =
self.GetPrevSibling(node)
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line 5433,
in GetPrevSibling
    return _controls_.TreeCtrl_GetPrevSibling(*args, **kwargs)
ValueError: invalid null reference in method 'TreeCtrl_GetPrevSibling', expected
 argument 2 of type 'wxTreeItemId const &amp;'
-----------------------------------------------------------------------------

And then:
-----------------------------------------------------------------------------
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line
5303, in GetItemText
    return _controls_.TreeCtrl_GetItemText(*args, **kwargs)
ValueError: invalid null reference in method 'TreeCtrl_GetItemText', expected ar
gument 2 of type 'wxTreeItemId const &amp;'
Traceback (most recent call last):
  File "src\robotide\utils\eventhandler.py", line 23, in wrapped
    method(self, event)
  File "src\robotide\editor\editors.py", line 185, in OnClear
    self._update_and_notify()
  File "src\robotide\editor\editors.py", line 181, in _update_and_notify
    self._tree.mark_dirty(self._datafile)
  File "src\robotide\ui\tree.py", line 185, in mark_dirty
    self._mark_dirty(self._get_datafile_node(datafile))
  File "src\robotide\ui\tree.py", line 188, in _mark_dirty
    text = self.GetItemText(node)
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line
5303, in GetItemText
    return _controls_.TreeCtrl_GetItemText(*args, **kwargs)
ValueError: invalid null reference in method 'TreeCtrl_GetItemText', expected ar
gument 2 of type 'wxTreeItemId const &amp;'
Traceback (most recent call last):
  File "src\robotide\utils\eventhandler.py", line 22, in wrapped
    if self._can_be_edited(event):
  File "src\robotide\utils\eventhandler.py", line 39, in _can_be_edited
    return self._show_modified_on_disk_warning(item, event)
  File "src\robotide\utils\eventhandler.py", line 52, in _show_modified_on_disk_
warning
    self.refresh_datafile(item, event)
  File "src\robotide\editor\editors.py", line 162, in refresh_datafile
    self._tree.refresh_datafile(item, event)
  File "src\robotide\ui\tree.py", line 272, in refresh_datafile
    insertion_index = self._get_datafile_index(orig_node)
  File "src\robotide\ui\tree.py", line 294, in _get_datafile_index
    insertion_index = self.GetPrevSibling(node)
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line
5433, in GetPrevSibling
    return _controls_.TreeCtrl_GetPrevSibling(*args, **kwargs)
ValueError: invalid null reference in method 'TreeCtrl_GetPrevSibling', expected
 argument 2 of type 'wxTreeItemId const &amp;'
Traceback (most recent call last):
  File "src\robotide\utils\eventhandler.py", line 23, in wrapped
    method(self, event)
  File "src\robotide\editor\editors.py", line 169, in OnEdit
    self._update_and_notify()
  File "src\robotide\editor\editors.py", line 181, in _update_and_notify
    self._tree.mark_dirty(self._datafile)
  File "src\robotide\ui\tree.py", line 185, in mark_dirty
    self._mark_dirty(self._get_datafile_node(datafile))
  File "src\robotide\ui\tree.py", line 188, in _mark_dirty
    text = self.GetItemText(node)
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line
5303, in GetItemText
    return _controls_.TreeCtrl_GetItemText(*args, **kwargs)
ValueError: invalid null reference in method 'TreeCtrl_GetItemText', expected ar
gument 2 of type 'wxTreeItemId const &amp;'
-----------------------------------------------------------------------------

I'll see if I can pinpoint the issue further.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c6) by @yanne on 24 Jan 2010*


It seems that this might be related to the code that reloads data in case of external
modifications. Are you sure there were no updates done to your test data by external
sources (version control or other)? If there weren't then also the mechanism for
checking external changes is somehow broken.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c7) by @yanne on 24 Jan 2010*


It would be really cool if you could figure out simple steps to reproduce this, since
I am still unable to reproduce this.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c8) by Magnus.Smedberg on 25 Jan 2010*


It's not impossible that subversion somehow did something to the file during the time
I was working on it, but in that case, it did so without changing the date-modified
of the file.
Or maybe it's Vista playing tricks on me...
I will keep seeing if I can find a sure-fire way to reproduce it. 
Let me know if I should update to a later revision of the dev version, or if you want
me to go back to the released version.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c9) by Magnus.Smedberg on 25 Jan 2010*


Ok, I've now found a way to reproduce at least part of the issue:
1. Open a resource file.
2. Copy one of the key words in the resource file and rename it.
3. Edit Arguments or Timeout field.

On my system (Win Vista, Python 2.6.2) this results in the following stack trace
being thrown in the console:

----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 1461
8, in &lt;lambda&gt;
    lambda event: event.callable(*event.args, **event.kw) )
  File "src\robotide\utils\eventhandler.py", line 23, in wrapped
    method(self, event)
  File "src\robotide\editor\editors.py", line 169, in OnEdit
    self._update_and_notify()
  File "src\robotide\editor\editors.py", line 181, in _update_and_notify
    self._tree.mark_dirty(self._datafile)
  File "src\robotide\ui\tree.py", line 185, in mark_dirty
    self._mark_dirty(self._get_datafile_node(datafile))
  File "src\robotide\ui\tree.py", line 188, in _mark_dirty
    text = self.GetItemText(node)
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line
5303, in GetItemText
    return _controls_.TreeCtrl_GetItemText(*args, **kwargs)
ValueError: invalid null reference in method 'TreeCtrl_GetItemText', expected ar
gument 2 of type 'wxTreeItemId const &amp;'
----------------------------------------------------------------------

Try it out, and see if you can get the same behavior.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c10) by @jrantanen on 26 Jan 2010*


I was able to reproduce the problem.

The problem is actually in test case and keyword copy operation. I actually fixed
this issue while fixing <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=276" title="Test case and user keyword copy operation takes very long time to process after 10-15 copies"> issue 276 </a>. The problem was that when test or keyword was
copied, the file in which those items are included was duplicated. Questions about
changes on the filesystem was due there were two objects changing and checking one file.

I could not test this yet with trunk as there are some other issues in there, but
based on my testing on older revision the fix for <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=276" title="Test case and user keyword copy operation takes very long time to process after 10-15 copies"> issue 276 </a> fixes also this issue.

Magnus, Thank you very much for your effort on finding the root cause!

I still want to add unit test, otherwise this issue is ready to be closed.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c11) by @jrantanen on 26 Jan 2010*


Added unit test <a href="https://code.google.com/p/robotframework-ride/source/detail?r=089931e900">r089931e900</a>.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=348#c12) by Magnus.Smedberg on 26 Jan 2010*


Great work!
Thank you for fixing this, it was starting to get on my nerves a bit. ;-)
