### ISSUE TITLE
Some data crashes RIDE when editors are created

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#383]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=356) by @yanne on 17 Dec 2009*

I split <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=317" title="RIDE crashes if user keyword data contains UserErrorHandlers"> issue 317 </a> to 2 separate issues. This issue handles error condition
that leads to stack trace below. I suspect that there is some problematic
character is some name that is not handled properly.

C:\Python25\Lib\site-packages\robotide&gt;python __init__.py 
Traceback (most recent call last): 
  File "C:\Python25\Lib\site-packages\robotide\editors\eventhandler.py", 
line 25 
, in wrapped 
    method(self, event) 
  File "C:\Python25\Lib\site-packages\robotide\ui\suitetree.py", line 322, 
in On 
SelChanged 
    self.show_editor(handler.item) 
  File "C:\Python25\Lib\site-packages\robotide\ui\suitetree.py", line 330, 
in sh 
ow_editor 
    self._editor = Editor(item, self._editor_panel, self) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
30, in 
Editor 
    return editor_class(editor_panel, item, tree) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
50, in 
__init__ 
    self._populate() 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
110, in 
 _populate 
    ResourceFileEditor._populate(self) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
79, in 
_populate 
    self.sizer.Add(self._create_header(self.item.name), 0, wx.ALL, 5) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
62, in 
_create_header 
    header = wx.StaticText(self, -1, text) 
  File "C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", 
line 
1136, in __init__ 
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, 
**kwarg 
s)) 
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at 
..\..\src\m 
sw\control.cpp(159) in wxControl::MSWCreateControl(): 
CreateWindowEx("STATIC", f 
lags=52000100, ex=00000000) failed 
Traceback (most recent call last): 
  File "C:\Python25\Lib\site-packages\robotide\editors\eventhandler.py", 
line 25 
, in wrapped 
    method(self, event) 
  File "C:\Python25\Lib\site-packages\robotide\ui\suitetree.py", line 322, 
in On 
SelChanged 
    self.show_editor(handler.item) 
  File "C:\Python25\Lib\site-packages\robotide\ui\suitetree.py", line 330, 
in sh 
ow_editor 
    self._editor = Editor(item, self._editor_panel, self) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
30, in 
Editor 
    return editor_class(editor_panel, item, tree) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
50, in 
__init__ 
    self._populate() 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
110, in 
 _populate 
    ResourceFileEditor._populate(self) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
79, in 
_populate 
    self.sizer.Add(self._create_header(self.item.name), 0, wx.ALL, 5) 
  File "C:\Python25\Lib\site-packages\robotide\editors\editors.py", line 
62, in 
_create_header 
    header = wx.StaticText(self, -1, text) 
  File "C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", 
line 
1136, in __init__ 
    _controls_.StaticText_swiginit(self,_controls_.new_StaticText(*args, 
**kwarg 
s)) 
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at 
..\..\src\m 
sw\control.cpp(159) in wxControl::MSWCreateControl(): 
CreateWindowEx("STATIC", f 
lags=52000100, ex=00000000) failed

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=356#c1) by @yanne on 14 Jan 2010*


Cannot reproduce, asked the original author whether this still happens. If we get no 
feedback, this will be dropped from 0.21

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=356#c2) by @jrantanen on 21 Jan 2010*


I tested this and the problem cannot be reproduced. I guess some of the memory/tree
fixes have also fixed this issue.
