### ISSUE TITLE
Starting RIDE in an empty folder doesn't work

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#388]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=359) by c.martin.taylor on 4 Jan 2010*

Create an empty folder and start ride there.  It fails with this:

&gt;ride .
Traceback (most recent call last):
  File "C:\Python25\Scripts\ride.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "C:\Python25\Lib\site-packages\robotide\__init__.py", line 46, in main
    _run(*args)
  File "C:\Python25\Lib\site-packages\robotide\__init__.py", line 57, in _run
    ride = RIDE(inpath)
  File "C:\Python25\Lib\site-packages\robotide\application\application.py",
line 35, in __init__
    wx.App.__init__(self, redirect=False)
  File "c:\python25\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line
7836, in __init__
    self._BootstrapApp()
  File "c:\python25\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line
7433, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "C:\Python25\Lib\site-packages\robotide\application\application.py",
line 43, in OnInit
    self.open_suite(self._path)
  File "C:\Python25\Lib\site-packages\robotide\application\application.py",
line 64, in open_suite
    self.model = DataModel(path)
  File "C:\Python25\Lib\site-packages\robotide\application\datamodel.py",
line 27, in __init__
    self._open(path)
  File "C:\Python25\Lib\site-packages\robotide\application\datamodel.py",
line 33, in _open
    self._open_suite(path)
  File "C:\Python25\Lib\site-packages\robotide\application\datamodel.py",
line 42, in _open_suite
    self.suite = TestSuiteFactory(path)
  File "C:\Python25\Lib\site-packages\robotide\model\files.py", line 41, in
TestSuiteFactory
    return _TestSuiteFactory(TestSuiteData(path))
  File "C:\Python25\Lib\site-packages\robot\parsing\__init__.py", line 27,
in TestSuite
    return TestSuiteData(datasources)
  File "C:\Python25\Lib\site-packages\robot\parsing\model.py", line 36, in
TestSuiteData
    return DirectorySuite(datasources[0], suitenames)
  File "C:\Python25\Lib\site-packages\robot\parsing\model.py", line 123, in
__init__
    self._create_subsuites(subitems, suitenames, error)
  File "C:\Python25\Lib\site-packages\robot\parsing\model.py", line 79, in
_create_subsuites
    self.parent.suites.pop()
AttributeError: 'NoneType' object has no attribute 'suites'

This bug makes it very difficult to start a new project with RIDE.  Is
there some recommended procedure for starting a new, empty Robot Framework
test suite with RIDE?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=359#c1) by @pekkaklarck on 4 Jan 2010*


This was fixed in 0.19 version (<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=202" title="Possibility to open an empty directory or file"> issue 202 </a>). Are you using an older version or have
some recent changes caused a regression?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=359#c2) by c.martin.taylor on 4 Jan 2010*


I was using an older version, but before I reported this today I upgraded to RIDE
0.20. It still has the problem.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=359#c3) by @pekkaklarck on 4 Jan 2010*


I couldn't reproduce this using the latest development version which isn't that
different from the 0.20 release. I tried both giving an empty directory as an
argument from the command line and selecting it from the menu.

Are you absolutely sure installing the new version has succeeded? Can you check the
version from the `Help &gt; About` menu?

Is the directory fully empty? Opening a directory that's not empty but contains no
test cases is still not supported and there's already <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=92" title="Cannot open non-empty directory/file unless it contains at least one test case"> issue 92 </a> about it.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=359#c4) by c.martin.taylor on 5 Jan 2010*


OK, it wasn't COMPLETELY empty.  I had a RobotIDE.bat file in it (attached). Removing
this file removes the problem.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=359#c5) by @pekkaklarck on 5 Jan 2010*


Good that the root cause was found. In this case I'd say this is a dupe of <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=92" title="Cannot open non-empty directory/file unless it contains at least one test case"> issue 92 </a>.
Totally empty files and directories are special cased in Ride itself (<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=202" title="Possibility to open an empty directory or file"> issue 202 </a>) but
handling other cases require changes to RF's parsing modules that are targeted for
the next release.
