### ISSUE TITLE
error al parar la ejecucion desde el nuevo plugin.

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#395]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=366) by jrvilda on 2 Feb 2010*

Error continuo al pulsar stop en el nuevo plugin run. 

ValueError: I/O operation on closed file
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\run\ui.py", line 41, in OnTimer
    self._window.update_output(self._process.get_output(), finished)
  File "C:\Python26\lib\site-packages\robotide\run\process.py", line 69, in get
output

Se ha lanzado una suite con el siguiente comando configurado:
 pybot.bat --include auto Z:\TestCase

Usando :
python26
ride 0.21

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=366#c1) by jrvilda on 2 Feb 2010*


Continuing failure to press stop the new plugin execution.

Traceback (most recent call last):
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ ui.py", line 41, in
OnTimer
    self._window.update_output (self._process.get_output (), finished)
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 71,
in get_
output
    self._close_outputs ()
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 77,
in _clo
se_outputs
    self._remove_tempfile ()
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 86,
in _rem
ove_tempfile
    self._remove_tempfile (attempts-1)
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 86,
in _rem
ove_tempfile
    self._remove_tempfile (attempts-1)
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 86,
in _rem
ove_tempfile
    self._remove_tempfile (attempts-1)
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 86,
in _rem
ove_tempfile
    self._remove_tempfile (attempts-1)
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 86,
in _rem
ove_tempfile
    self._remove_tempfile (attempts-1)
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 86,
in _rem
ove_tempfile
    self._remove_tempfile (attempts-1)
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 86,
in _rem
ove_tempfile
    self._remove_tempfile (attempts-1)
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 86,
in _rem
ove_tempfile
    self._remove_tempfile (attempts-1)
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 86,
in _rem
ove_tempfile
    self._remove_tempfile (attempts-1)
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 86,
in _rem
ove_tempfile
    self._remove_tempfile (attempts-1)
  File "C: \ Python26 \ lib \ site-packages \ robotide \ run \ process.py", line 81,
in _rem
ove_tempfile
    os.remove (self._out_path)
WindowsError: [Error 32] The process can not access the file because being estß
or used by another process: 'c: \ docume ~ 1 \ xxxx \ \ config ~ 3 \ \ temp \ \
rfproc_xpg
xo6.txt '


It has launched a suite configured with the command in the new plugin:
 Auto-include pybot.bat Z: \ TestCase

Using:
python26
ride 0.21

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=366#c2) by @pekkaklarck on 3 Feb 2010*


I don't understand the description fully but this looks like a similar issue that has
been reported also inside NSN. Unfortunately we haven't been able to reproduce this
issue. If you have any more information that could help us investigate this further
let us know.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=366#c3) by @pekkaklarck on 3 Feb 2010*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=373" title="Stopping processes executed using the Run plugin does not always work"> Issue 373 </a> reports the same problem. Because it contains more detailed description I
resolve this one as its duplicate.
