### ISSUE TITLE
Adding keyword or test in an empty resource or test case fails

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#400]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=371) by ray.agil... on 3 Feb 2010*

Steps to reproduce
Open RIDE 0.21.1

<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1" title='Newline should be added after "\n" in test data'> Issue 1 </a>- By Default a Resource is shown
Add a new resource.It will be shown in existing Resource.

Add a keyword,but observe that the keyword is not shown.

This is what shown as trace
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 451, in 
OnNewUserKeyword
    self._tree.add_keyword(self._node, kw)
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 160, in 
add_keyword
    self._add_dataitem(parent_node, kw, lambda item: item.is_test_suite)
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 166, in 
_add_dataitem
    self.SelectItem(node)
  File "c:\python26\lib\site-packages\wx-2.8-msw-
unicode\wx\lib\mixins\treemixin.py", line 165,
in SelectItem
    **kwargs)
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", 
line 5537, in SelectI
tem
    return _controls_.TreeCtrl_SelectItem(*args, **kwargs)
ValueError: invalid null reference in method 'TreeCtrl_SelectItem', 
expected argument 2 of type
'wxTreeItemId const &amp;'

But if RIDE is closed and opened again the added keywords are shown

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=371#c1) by @yanne on 5 Feb 2010*


Actually the bug is even somewhat subtler.

If you create a new resource and try to expand it before creating a user keyword, you 
get the stack trace. If you don't touch the + before creating the user keyword, 
everything works fine.

Of course this is still a bug and must be fixed

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=371#c3) by @pekkaklarck on 25 Feb 2010*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=391" title="Problem adding first keyword to a file in RIDE"> Issue 391 </a> has been merged into this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=371#c7) by @yanne on 23 Mar 2010*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=415" title="New Test Case in a New Suite gets an exception"> Issue 415 </a> has been merged into this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=371#c8) by @yanne on 23 Mar 2010*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=417" title="User-defined keyword, dragged into a newly created Resource file, does not appear in the left-hand panel."> Issue 417 </a> has been merged into this issue.
