### ISSUE TITLE
Stopping processes executed using the Run plugin does not always work

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#402]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=373) by ray.agil... on 3 Feb 2010*

Python 2.6.3
RIDE 0.21.1
Windows

Using run menu config run setting and run a test.
Per release note stop should work for python 2.6
If stop is clicked, test has halted as browsers got closed,but status 
still shows its running.

Also this traceback is going infinitely

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\run\ui.py", line 41, in 
OnTimer
    self._window.update_output(self._process.get_output(), finished)
  File "C:\Python26\lib\site-packages\robotide\run\process.py", line 69, 
in get_output
    output = self._out_file.read()
ValueError: I/O operation on closed file
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\run\ui.py", line 41, in 
OnTimer
    self._window.update_output(self._process.get_output(), finished)
  File "C:\Python26\lib\site-packages\robotide\run\process.py", line 69, 
in get_output
    output = self._out_file.read()
ValueError: I/O operation on closed file
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\run\ui.py", line 41, in 
OnTimer
    self._window.update_output(self._process.get_output(), finished)
  File "C:\Python26\lib\site-packages\robotide\run\process.py", line 69, 
in get_output
    output = self._out_file.read()
ValueError: I/O operation on closed file
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\run\ui.py", line 41, in 
OnTimer
    self._window.update_output(self._process.get_output(), finished)
  File "C:\Python26\lib\site-packages\robotide\run\process.py", line 69, 
in get_output
    output = self._out_file.read()
ValueError: I/O operation on closed file
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\run\ui.py", line 41, in 
OnTimer
    self._window.update_output(self._process.get_output(), finished)
  File "C:\Python26\lib\site-packages\robotide\run\process.py", line 69, 
in get_output
    output = self._out_file.read()
ValueError: I/O operation on closed file ... 

Only option seems to close RIDE

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=373#c1) by @pekkaklarck on 3 Feb 2010*


There really seems to be something wrong with the stop functionality because we've
got the same error report inside NSN and there's also <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=366" title="error al parar la ejecucion desde el nuevo plugin."> issue 366 </a> that seems to
describe the same problem. The common theme with all these reports is that the
problem occurs in Windows. Unfortunately we haven't been able to reproduce this
problem ourselves. Could someone who can reproduce the issue give some more
information about the setup? It would be great to get an example we could try in our
machines.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=373#c2) by @pekkaklarck on 3 Feb 2010*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=366" title="error al parar la ejecucion desde el nuevo plugin."> Issue 366 </a> has been merged into this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=373#c3) by @yanne on 7 Mar 2010*


Removed 0.22 target since I am unable to reproduce this.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=373#c4) by @pekkaklarck on 6 Sep 2010*


We cannot reproduce this and thus cannot investigate this. Closing now but can be reopened later if there's more information.
