### ISSUE TITLE
Python 2.4 incompatibility

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#406]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=377) by @pekkaklarck on 7 Feb 2010*

A user reported that trying to start RIDE 0.20 with Python 2.4 failed with
the traceback below. The problem seems we use try/except/finally syntax in
the code although that's valid only in Python 2.5 (in older version you
need to next try/except inside try/finally). This needs to be fixed and we
must also test the release with Python 2.5 fully. 

Traceback (most recent call last):
  File "/usr/bin/ride.py", line 22, in ?
    main(sys.argv[1:])
  File "/usr/lib/python2.4/site-packages/robotide/__init__.py", line 46, in
main
    _run(*args)
  File "/usr/lib/python2.4/site-packages/robotide/__init__.py", line 56, in
_run
    from robotide.application import RIDE
  File "/usr/lib/python2.4/site-packages/robotide/application/__init__.py",
line 15, in ?
    from application import RIDE, DataModel
  File
"/usr/lib/python2.4/site-packages/robotide/application/application.py",
line 29, in ?
    from pluginloader import PluginLoader
  File
"/usr/lib/python2.4/site-packages/robotide/application/pluginloader.py",
line 62
    finally:
          ^
SyntaxError: invalid syntax

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=377#c1) by @pekkaklarck on 7 Feb 2010*


Notice also that RIDE 0.21.x is planned to be the last version compatible with Python
2.4 as explained in the roadmap:
<a href="https://code.google.com/p/robotframework/wiki/Roadmap" rel="nofollow">https://code.google.com/p/robotframework/wiki/Roadmap</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=377#c2) by @yanne on 7 Mar 2010*


Fixed
