### ISSUE TITLE
Generic Error while executing ride.py

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#419]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=390) by palani.selvam on 24 Feb 2010*

Hi, 
OS is WinXP SP2 and installed following tools in c:\python25
python-2.6.4.msi
robotframework-2.1.win32.exe
robotframework-seleniumlibrary-2.3.win32.exe
wxPython2.8-win32-unicode-2.8.10.1-py25.exe
robotide-0.21.1.win32.exe

 I got the following error, while executing ride.py

--------
C:\Python25\Tools\Scripts&gt;ride.py
Traceback (most recent call last):
  File "C:\Python25\Scripts\ride.py", line 21, in &lt;module&gt;
    from robotide import main
  File "C:\Python25\Lib\site-packages\robotide\__init__.py", line 34, in
&lt;module
&gt;
    from robotide.errors import DataError, NoRideError
  File "C:\Python25\Lib\site-packages\robotide\errors.py", line 15, in &lt;module&gt;
    from robot.errors import DataError
  File "C:\Python25\Lib\site-packages\robot\__init__.py", line 24, in &lt;module&gt;
    from output import Output, CommandLineMonitor, LOGGER
  File "C:\Python25\Lib\site-packages\robot\output\__init__.py", line 16,
in &lt;mo
dule&gt;
    from output import Output
  File "C:\Python25\Lib\site-packages\robot\output\output.py", line 18, in
&lt;modu
le&gt;
    from robot.common.statistics import Statistics
  File "C:\Python25\Lib\site-packages\robot\common\__init__.py", line 16,
in &lt;mo
dule&gt;
    from model import BaseTestSuite, BaseTestCase
  File "C:\Python25\Lib\site-packages\robot\common\model.py", line 18, in
&lt;modul
e&gt;
    from statistics import Stat
  File "C:\Python25\Lib\site-packages\robot\common\statistics.py", line 18,
in &lt;
module&gt;
    from robot import utils
  File "C:\Python25\Lib\site-packages\robot\utils\__init__.py", line 19, in
&lt;mod
ule&gt;
    from argumentparser import ArgumentParser
  File "C:\Python25\Lib\site-packages\robot\utils\argumentparser.py", line
25, i
n &lt;module&gt;
    from misc import plural_or_not
  File "C:\Python25\Lib\site-packages\robot\utils\misc.py", line 20, in
&lt;module&gt;

    import urllib
  File "c:\python25\lib\urllib.py", line 26, in &lt;module&gt;
    import socket
  File "c:\python25\lib\socket.py", line 46, in &lt;module&gt;
    import _socket
ImportError: No module named _socket
------------------------
 Please tell me, how can I solve this issue?

Thanks,
Palani.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=390#c1) by @yanne on 1 Mar 2010*


It seems that your Python installation is somehow broken. Could you try to re-install
Python and try again. 

In any case, this is not a RIDE problem, so I am closing this issue.
