### ISSUE TITLE
Code completion doesn't work for newly created suite's tests

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#431]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=402) by @khusa on 15 Mar 2010*

1. Create a new test suite
2. Import resource file
3. Create a test and try to enter a keyword from the resource using code 
completion.

No suggestions are displayed and an exception is printed to the prompt:

AttributeError: 'NoneType' object has no attribute 'get_resource_file'
Traceback (most recent call last):
  File ".\src\robotide\ui\actiontriggers.py", line 341, in __call__
    action.act(event)
  File ".\src\robotide\action\action.py", line 71, in act
    self.action(event)
  File ".\src\robotide\editor\__init__.py", line 135, in 
OnContentAssistance
    self.editor.show_content_assist()
  File ".\src\robotide\editor\editors.py", line 291, in show_content_assist
    self.kweditor.show_content_assist()
  File ".\src\robotide\editor\kweditor.py", line 224, in 
show_content_assist
    self.GetCellEditor(*self.selection.cell).show_content_assist()
  File ".\src\robotide\editor\kweditor.py", line 340, in 
show_content_assist
    self._tc.show_content_assist()
  File ".\src\robotide\editor\contentassist.py", line 68, in 
show_content_assist

    if self._populate_content_assist():
  File ".\src\robotide\editor\contentassist.py", line 80, in 
_populate_content_a
ssist
    return self._popup.content_assist_for(value)
  File ".\src\robotide\editor\contentassist.py", line 123, in 
content_assist_for

    self._choices = self._plugin.content_assist_values(value)
  File ".\src\robotide\pluginapi\plugin.py", line 273, in 
content_assist_values
    value)
  File ".\src\robotide\namespace\__init__.py", line 45, in 
content_assist_values

    self._get_item_variables(item) + \
  File ".\src\robotide\namespace\__init__.py", line 53, in 
_get_item_keywords
    user_kws = self._get_cached_user_kws(item, source_for_own_kws)
  File ".\src\robotide\namespace\__init__.py", line 142, in 
_get_cached_user_kws

    self._get_user_keywords_from_imports(item)
  File ".\src\robotide\namespace\__init__.py", line 91, in 
_get_user_keywords_fr
om_imports
    for res in item.imports.get_resources():
  File ".\src\robotide\model\importsettings.py", line 85, in get_resources
    return self._keywords_from_res_imports(lambda res: [res])
  File ".\src\robotide\model\importsettings.py", line 65, in 
_keywords_from_res_
imports
    name = self._replace_variables(name)
  File ".\src\robotide\model\importsettings.py", line 59, in 
_replace_variables
    return self.datafile.replace_variables(value)
  File ".\src\robotide\model\files.py", line 142, in replace_variables
    for res in self.get_resources():
  File ".\src\robotide\model\files.py", line 97, in get_resources
    resource = self.namespace.get_resource_file(self.source, name)
AttributeError: 'NoneType' object has no attribute 'get_resource_file'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=402#c1) by @yanne on 19 Mar 2010*


Fixxxed
