### ISSUE TITLE
New Test Case in a New Suite gets an exception

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#444]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=415) by c.martin.taylor on 20 Mar 2010*

I'm running RIDE 0.21.1 along with Robot Framework 2.1.3 (Python 2.6.4 on
win32). 

Create a New Suite (HTML File) in RIDE, the right click on the new suite
name and select "New Test Case" (since you can't save a new suite file
without adding a new test case first... possibly another bug).

The command window where RIDE was started will show this:

&gt;ride.py .
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 468, in
OnNewTestCase
    self._tree.add_test(self._node, test)
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 157, in
add_test
    self._add_dataitem(parent_node, test, lambda item: item.is_user_keyword)
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 166, in
_add_dataitem
    self.SelectItem(node)
  File
"c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\lib\mixins\treemixin.py",
line 165, in SelectItem
    **kwargs)
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py",
line 5537, in SelectItem
    return _controls_.TreeCtrl_SelectItem(*args, **kwargs)
ValueError: invalid null reference in method 'TreeCtrl_SelectItem',
expected argument 2 of type 'wxTreeItemId const &amp;'

It is then impossible to expand the test suite by clicking on the +.  The
only workaround is to save the Test Suite at this point and re-open it. You
pretty much have to do this anyway due to <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=414" title="New Suite (File or Folder) opens completely new RIDE view"> Issue 414 </a>, but the whole process
of creating a new suite with new test cases in RIDE is very frustrating.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=415#c1) by @yanne on 23 Mar 2010*


This has already been fixed.
