### ISSUE TITLE
User-defined keyword, dragged into a newly created Resource file, does not appear in the left-hand panel.

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#446]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=417) by c.martin.taylor on 22 Mar 2010*

I'm running RIDE 0.21.1 along with Robot Framework 2.1.3 (Python 2.6.4 on
win32). 

Create a new Resource file (I did so in a ~Resources sub-folder of the
folder where RIDE was currently open and editing tests.  This happened to
be the folder containing the Test Suite attached to <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=416" title="Auto-completion does not find user-defined keywords in the current Test Suite"> Issue 416 </a>.)
Drag and drop a user-defined keyword from a Test Suite into the new
Resource file. 
Observe that the user-defined keyword disappears from the expanded Test
Suite tree
Observe that the newly created Resource file does not auto-expand to show
the new content just dropped there.
Click the + beside the newly created Resource file.
Observe that nothing happens.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=417#c1) by c.martin.taylor on 22 Mar 2010*


If this is fixed as quickly and easily as <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=416" title="Auto-completion does not find user-defined keywords in the current Test Suite"> Issue 416 </a> was fixed, how can I get these
two fixes into my current RIDE build that I'm using to run a Robot Framework Tutorial
on Wednesday, 24-Mar-10?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=417#c2) by c.martin.taylor on 22 Mar 2010*


When doing the drag and drop step in the description above, the CMD window that
started RIDE shows this error exception:

&gt;ride.py .
Traceback (most recent call last):
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\lib\mixins\treemixin.py",
line 517, in OnEndDrag
    self.OnDrop(dropTarget, self._dragItem)
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 383, in OnDrop
    target.do_drop(dragged.item)
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 435, in do_drop
    self._tree.do_drop(self, test_or_kw)
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 390, in do_drop
    self.add_keyword(node, test_or_uk)
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 160, in add_key
word
    self._add_dataitem(parent_node, kw, lambda item: item.is_test_suite)
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 166, in _add_dataitem
    self.SelectItem(node)
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\lib\mixins\treemixin.py",
line 165, in SelectItem
    **kwargs)
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line
5537, in SelectItem
    return _controls_.TreeCtrl_SelectItem(*args, **kwargs)
ValueError: invalid null reference in method 'TreeCtrl_SelectItem', expected arg
ument 2 of type 'wxTreeItemId const &amp;'

This would seem to me to make this issue more like <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=415" title="New Test Case in a New Suite gets an exception"> Issue 415 </a> than <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=416" title="Auto-completion does not find user-defined keywords in the current Test Suite"> Issue 416 </a>.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=417#c3) by @pekkaklarck on 22 Mar 2010*


Martin, could you try checking out the code and running the development version to
find out is this already fixed? The steps to do this are:

1) Install Mercurial if you don't already have it:
<a href="http://mercurial.selenic.com/" rel="nofollow">http://mercurial.selenic.com/</a>
2) Clone the repository as explained here:
<a href="https://code.google.com/p/robotframework-ride/source/checkout" rel="nofollow">https://code.google.com/p/robotframework-ride/source/checkout</a>
3) Install the development version using "python setup.py install" or just run the
code directly with "python rundevel.py".

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=417#c4) by c.martin.taylor on 23 Mar 2010*


I'd like to be able to do this check-out and test, but the Mercurial learning curve
seems very steep and the instructions are not well geared to total newbies on
Windows.  I can't find the mercurial.ini file, or where to create it.  The "putty"
instructions are vague and seem to assume some prior knowledge (I've never used it).
 It would be a lot simpler if I could just download and unzip a source code tarball
to test the latest RIDE.  Is it possible to get one?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=417#c5) by c.martin.taylor on 23 Mar 2010*


Some further reading shows "Source code is hosted in the Google Code Mercurial
repository [4], which also supports read-only anonymous checkouts." but I don't see
any instructions as to how to do such a "read-only anonymous checkout".  What's the
simplest way to do this on Windows?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=417#c6) by @yanne on 23 Mar 2010*


I assume you need the Mercurial.ini to set proxy.
Type this in your command prompt:

echo &#37;USERPROFILE&#37;

That is the directory where Mercurial.ini should be located, if it does not exist you 
can create it. The content needed to set proxy is this:

[http_proxy]
host=&lt;host&gt;:&lt;port&gt;

after that, you should be able to clone the repository like this:

hg clone <a href="http://robotframework-ride.googlecode.com/hg/" rel="nofollow">http://robotframework-ride.googlecode.com/hg/</a> robotframework-ride 

Currently, we have no facility to distribute nightly builds, but we might take a look 
at making them available at some point.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=417#c7) by @yanne on 23 Mar 2010*


FWIW, I tested this on my machine and it works. Based on the stack trace I am fairly 
confident that this is just another manifestation of the underlying bug in <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=371" title="Adding keyword or test in an empty resource or test case fails"> issue 371 </a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=417#c8) by c.martin.taylor on 23 Mar 2010*


The right location for Mercurial.ini and the right [http_proxy] entry in that file
allowed me to do the anonymous check-out.  I built the code and tested it with this
Issue's scenario and it now works with no traceback in the CMD window.

I need to get this to my students TODAY so they can install prior to tomorrow's
tutorial.  Should I merge the changes into my local AccuRev repository and make my
own build, or is there any chance of an official build today?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=417#c9) by @yanne on 23 Mar 2010*


I have one open issue before the release and chances for official release today are 
slim.

You do not need to merge to create an installer (unless you have some custom add-
ons).
Windows installer can be created straight from the clone:

python setup.py bdist_wininst

If you want the version to be something else than 'trunk', it may be configured in 
file src/robotide/version.py
