### ISSUE TITLE
Children cannot be added to newly created directory

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#497]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=466) by picoge... on 29 Jun 2010*

It seems that creating nested directories in ride does not work properly.

This is the procedure I use to reproduce the bug:
Create a new project and select Directory as the type and leave format as Html. In my case I called my project DirTest
Now from the left Tree editor I try to add a subdir (suite) by clicking right clicking on DirTest and selecting "Add suite". I now select Directory again and name the directory subdir1.
Once I click ok, I notice that the tree on the left has not been modified and I see this error on the console:

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/robotide/ui/tree.py", line 501, in OnAddSuite
    self._tree.add_datafile(self.controller, ctrl)
  File "/usr/lib/python2.6/site-packages/robotide/ui/tree.py", line 153, in add_datafile
    snode = self._render_datafile(self._get_datafile_node(parent.data), suite)
  File "/usr/lib/python2.6/site-packages/robotide/ui/tree.py", line 107, in _render_datafile
    node = self._create_node_with_handler(parent_node, controller, index)
  File "/usr/lib/python2.6/site-packages/robotide/ui/tree.py", line 115, in _create_node_with_handler
    name = controller.data.__class__.__name__
AttributeError: 'NoneType' object has no attribute 'data'

I've tested this with Ride 0.25 and with the latest ride in hg, and get the same results.
pybot --version:
Robot Framework 2.5 (Python 2.6.5 on linux2)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=466#c2) by @yanne on 29 Jun 2010*


This issue was updated by <a href="https://code.google.com/p/robotframework-ride/source/detail?r=bb4fc312c1">revision bb4fc312c1</a>.
