### ISSUE TITLE
Error message running ride.py on Ubuntu

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#505]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=474) by philipth... on 2 Jul 2010*

Robotide has been built using and with the following packages

 robotframework-2.1.3  robotframework-2.1.3.tar.gz  robotide-0.21.1  robotide-0.21.1.tar.gz  wxPython-src-2.8.11.0  wxPython-src-2.8.11.0.tar.bz2

Error Message:

corejava@&#8288;corejava-desktop:~$ ride.py
Traceback (most recent call last):
  File "/usr/local/bin/ride.py", line 20, in &lt;module&gt;
    from robotide import main
  File "/usr/local/lib/python2.6/dist-packages/robotide/__init__.py", line 31, in &lt;module&gt;
    import wxversion
ImportError: No module named wxversion

Python: Version
corejava@&#8288;corejava-desktop:~$ python --version
Python 2.6.5
corejava@&#8288;corejava-desktop:~$ jython --version
Jython 2.2.1 on java1.5.0

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=474#c1) by @pekkaklarck on 3 Jul 2010*


You don't seem to have wxPython installed. Or at least it is not found when RIDE starts.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=474#c2) by @yanne on 9 Aug 2010*


You'd probably have to refer to wxPython docs about wxversion and installation from source. If you install wxPython with aptitude, the wxversion comes along automatically (That's what I do on Ubuntu).

Anyway, this issue is not really about RIDE.
