### ISSUE TITLE
RIDE 0.26 crashes when reporting errors

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#514]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=483) by @jussimalinen on 27 Jul 2010*

Traceback (most recent call last):
  File "C:\Python25\Lib\site-packages\robotide\ui\actiontriggers.py", line 341, in __call__
    action.act(event)
  File "C:\Python25\Lib\site-packages\robotide\action\action.py", line 71, in act
    self.action(event)
  File "C:\Python25\Lib\site-packages\robotide\utils\eventhandler.py", line 23, in wrapped
    method(self, event)
  File "C:\Python25\Lib\site-packages\robotide\ui\mainframe.py", line 138, in OnOpen
    self.open_suite(path)
  File "C:\Python25\Lib\site-packages\robotide\ui\mainframe.py", line 170, in open_suite
    self._controller.load_datafile(path, LoadProgressObserver(self, path))
  File "C:\Python25\Lib\site-packages\robotide\controller\chiefcontroller.py", line 71, in load_datafile
    load_observer.finish()
  File "C:\Python25\Lib\site-packages\robotide\ui\progress.py", line 35, in finish
    context.LOG.report_parsing_errors()
  File "C:\Python25\Lib\site-packages\robotide\context\logger.py", line 32, in report_parsing_errors
    for line in errors))
  File "C:\Python25\Lib\site-packages\robotide\context\logger.py", line 32, in &lt;genexpr&gt;
    for line in errors))
  File "C:\Python25\Lib\site-packages\robotide\context\logger.py", line 38, in _format_parsing_error_line
    index = line.index(':') + 1
ValueError: substring not found

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=483#c1) by @jussimalinen on 27 Jul 2010*


Error messages without ':' character caused an exception. Now fixed.

RIDE still reports collisions with variable names twice for some reason. I will make a separate issue about that.
