### ISSUE TITLE
Move up or down causing error in console

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#522]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=491) by jerry57 on 11 Aug 2010*

RIDE 0.26.1
RobotFramework 2.5.1
Python 2.6.1
Mac OS X 10.6.4

When I right click and select move a test or keyword up or down I am getting the following error in the terminal window that launched RIDE.

Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/robotide/ui/tree.py", line 559, in OnMoveUp
    if self.controller.move_up():
  File "/Library/Python/2.6/site-packages/robotide/controller/filecontroller.py", line 514, in move_up
    return self._parent.move_up(self._kw)
  File "/Library/Python/2.6/site-packages/robotide/controller/filecontroller.py", line 333, in move_up
    idx = items.index(item)
ValueError: list.index(x): x not in list
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/robotide/ui/tree.py", line 559, in OnMoveUp
    if self.controller.move_up():
  File "/Library/Python/2.6/site-packages/robotide/controller/filecontroller.py", line 514, in move_up
    return self._parent.move_up(self._kw)
  File "/Library/Python/2.6/site-packages/robotide/controller/filecontroller.py", line 333, in move_up
    idx = items.index(item)
ValueError: list.index(x): x not in list

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=491#c1) by jerry57 on 11 Aug 2010*


Forgot to mention that the first move worked normally, but the second and all subsequent attempts failed with the above output.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=491#c2) by @jussimalinen on 13 Aug 2010*


I have failed to reproduce this... Does this error occur on all your test suite files? Even if you create a new test suite with minimal data? (Only two test cases.)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=491#c3) by jerry57 on 13 Aug 2010*


This is happening in all of our suites.  Most notably after editing a suite, before saving and then trying to move something up or down.  

We use a resources file to store most of our custom keywords that are shared between lots of test suites.  We first create the keyword in a test suite and verify it is working.  after that verification we then drag/drop it into the resources.html file and try to move it up in that file.  Saving first doesn't seem to change this.  If we drag/drop it in, then save, exit ride and restart ride, then move it up or down it doesn't seem to crash.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=491#c4) by @jussimalinen on 15 Aug 2010*


The problem was with drag and drop, which did not update references correctly.

Now fixed.
