### ISSUE TITLE
Document that on 64bit OSX, RIDE will not start unless 32bit Python is used

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#533]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=502) by @jussimalinen on 19 Aug 2010*

RIDE will not start unless environment variable VERSIONER_PYTHON_PREFER_32_BIT=yes is set on 64bit Macs.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=502#c3) by jollych... on 21 Oct 2010*


Traceback (most recent call last):
  File "/usr/local/bin/ride.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "/Library/Python/2.6/site-packages/robotide/__init__.py", line 48, in main
    _run(*args)
  File "/Library/Python/2.6/site-packages/robotide/__init__.py", line 56, in _run
    from robotide.application import RIDE
  File "/Library/Python/2.6/site-packages/robotide/application/__init__.py", line 15, in &lt;module&gt;
    from application import RIDE, ChiefController
  File "/Library/Python/2.6/site-packages/robotide/application/application.py", line 17, in &lt;module&gt;
    import wx
  File "/var/tmp/wxWidgets/wxWidgets-13~522/2.6/DSTROOT/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wx-2.8-mac-unicode/wx/__init__.py", line 45, in &lt;module&gt;
    
  File "/var/tmp/wxWidgets/wxWidgets-13~522/2.6/DSTROOT/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wx-2.8-mac-unicode/wx/_core.py", line 4, in &lt;module&gt;
ImportError: /System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wx-2.8-mac-unicode/wx/_core_.so: no appropriate 64-bit architecture (see "man python" for running in 32-bit mode)
----
Is it the same reaseon?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=502#c4) by @jussimalinen on 4 Nov 2010*


Jollychang: Yes, it seems to be. Have you tried setting the environmant variable VERSIONER_PYTHON_PREFER_32_BIT=yes before running?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=502#c6) by john.gl... on 20 Sep 2011*


I think you should close this bug.  It's not a RIDE bug.  The problem is with installation.  Basically, Mac OSX users have to use 32-bit python because Apple is not fully supporting 64-bit libraries that are needed (gcc, etc).  There are ways to get Mac's to work with RIDE, so the RIDE team should update their installation instructions

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=502#c7) by @mkorpela on 20 Sep 2011*


Thanks for the comment! We decided to document this instead of just closing it.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=502#c8) by @mkorpela on 21 Sep 2011*


Added note to installation instructions.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=502#c9) by frs... on 12 Oct 2014*


ride.py was stuck at initialization.
