### ISSUE TITLE
Traceback when clicking in the Suite options

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#537]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=506) by jerry57 on 25 Aug 2010*

RIDE 0.27
RobotFramework 2.5.1
Python 2.6.1
Mac OS X 10.6.4

When I click on the Suite Setup/Teardown, I am getting the following Traceback.  It doesn't seem to be crashing RIDE, but shouldn't be happening.  Sometimes this happens when after editing a Test Case and then you mouse over the Suite upper panel.

Traceback (most recent call last):
  File "/var/tmp/wxWidgets/wxWidgets-13~231/2.6/DSTROOT/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wx-2.8-mac-unicode/wx/_misc.py", line 1341, in Notify
  File "/var/tmp/wxWidgets/wxWidgets-13~231/2.6/DSTROOT/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wx-2.8-mac-unicode/wx/_core.py", line 14653, in Notify
  File "/Library/Python/2.6/site-packages/robotide/utils/eventhandler.py", line 23, in wrapped
    method(self, event)
  File "/Library/Python/2.6/site-packages/robotide/editor/editors.py", line 243, in OnPopupTimer
    details = self._get_details_for_tooltip()
  File "/Library/Python/2.6/site-packages/robotide/editor/editors.py", line 250, in _get_details_for_tooltip
    return self._plugin.get_keyword_details(kw)
  File "/Library/Python/2.6/site-packages/robotide/pluginapi/plugin.py", line 285, in get_keyword_details
    return self.__namespace.keyword_details(self.datafile, name)
  File "/Library/Python/2.6/site-packages/robotide/namespace/namespace.py", line 127, in keyword_details
    kw = self._find_keyword(datafile, name)
  File "/Library/Python/2.6/site-packages/robotide/namespace/namespace.py", line 121, in _find_keyword
    return kwds[kw_name] if kw_name in kwds else None
  File "/Library/Python/2.6/site-packages/robot/utils/normalizing.py", line 108, in has_key
    return self.data.has_key(self._normalize(key))
  File "/Library/Python/2.6/site-packages/robot/utils/normalizing.py", line 82, in &lt;lambda&gt;
    self._normalize = lambda s: normalize(s, ignore, caseless, spaceless)
  File "/Library/Python/2.6/site-packages/robot/utils/normalizing.py", line 32, in normalize
    string = _WHITESPACE_REGEXP.sub('', string)
TypeError: expected string or buffer

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=506#c3) by @pekkaklarck on 8 Sep 2010*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=521" title="TypeError: expected string or buffer"> Issue 521 </a> has been merged into this issue.
