### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#554]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=521) by bryan.oakley on 8 Sep 2010*

When I start RIDE and my mouse hovers over an empty setting (such as Suite Setup), I get the following error in my console:

Traceback (most recent call last):
  File "//usr/local/lib/wxPython-unicode-2.8.9.2/lib/python2.5/site-packages/wx-2.8-mac-unicode/wx/_misc.py", line 1342, in Notify
    self.notify()
  File "//usr/local/lib/wxPython-unicode-2.8.9.2/lib/python2.5/site-packages/wx-2.8-mac-unicode/wx/_core.py", line 14676, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/opt/orbitz-st-3.0-B1/lib/python-2.5/site-packages/robotide/utils/eventhandler.py", line 23, in wrapped
    method(self, event)
  File "/opt/orbitz-st-3.0-B1/lib/python-2.5/site-packages/robotide/editor/editors.py", line 243, in OnPopupTimer
    details = self._get_details_for_tooltip()
  File "/opt/orbitz-st-3.0-B1/lib/python-2.5/site-packages/robotide/editor/editors.py", line 250, in _get_details_for_tooltip
    return self._plugin.get_keyword_details(kw)
  File "/opt/orbitz-st-3.0-B1/lib/python-2.5/site-packages/robotide/pluginapi/plugin.py", line 285, in get_keyword_details
    return self.__namespace.keyword_details(self.datafile, name)
  File "/opt/orbitz-st-3.0-B1/lib/python-2.5/site-packages/robotide/namespace/namespace.py", line 127, in keyword_details
    kw = self._find_keyword(datafile, name)
  File "/opt/orbitz-st-3.0-B1/lib/python-2.5/site-packages/robotide/namespace/namespace.py", line 121, in _find_keyword
    return kwds[kw_name] if kw_name in kwds else None
  File "/opt/orbitz-st-3.0-B1/lib/python-2.5/site-packages/robot/utils/normalizing.py", line 108, in has_key
    return self.data.has_key(self._normalize(key))
  File "/opt/orbitz-st-3.0-B1/lib/python-2.5/site-packages/robot/utils/normalizing.py", line 82, in &lt;lambda&gt;
    self._normalize = lambda s: normalize(s, ignore, caseless, spaceless)
  File "/opt/orbitz-st-3.0-B1/lib/python-2.5/site-packages/robot/utils/normalizing.py", line 32, in normalize
    string = _WHITESPACE_REGEXP.sub('', string)
TypeError: expected string or buffer

What little debugging I did revealed that 'string' in the last line of the traceback is None and normalize isn't prepared for that.

python 2.5.2, wxPython 2.8.8.1, robot version 2.5.3, RIDE 0.27

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=521#c1) by @pekkaklarck on 8 Sep 2010*


This ought to be fixed in the head.
