### ISSUE TITLE
Invalid plugin can cause RIDE to crash hard

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#605]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=572) by bryan.oakley on 2 Nov 2010*

I have a plugin that, when present in my system, prevents RIDE from starting up.

The culprit seems to be the method _import_classes inside pluginloader.py. The offending code appears to be this:

        return [ cls for _, cls in
                 inspect.getmembers(module, predicate=inspect.isclass) ]

In spite of the predicate, it appears to be returning things that are not classes. When I put some debug code in I'm seeing this when I print out each item: (notice the last line is printing out a dict rather than a class -- a dict defined in a library imported by the plugin)

...
cls= &lt;class 'testrunner.TestRunner'&gt; 
cls= &lt;class 'TestSuiteTreeCtrl.TestSuiteTreeCtrl'&gt;
cls= {'target': 'src/servicetest', 'lib': 'src/servicetest/lib', 'python': 'src/servicetest/python', 'root': 'src/servicetest', 'conf': 'src/servicetest/conf', 'robot': 'src/servicetest/robot', 'robot_report': 'src/servicetest/report/robot'} 

Here's the specific error message I get:
Traceback (most recent call last):
  File "/opt/orbitz-st-3.1-B4/bin/ride.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "/opt/orbitz-st-3.1-B4/lib/python-2.5/site-packages/robotide/__init__.py", line 48, in main
    _run(*args)
  File "/opt/orbitz-st-3.1-B4/lib/python-2.5/site-packages/robotide/__init__.py", line 57, in _run
    ride = RIDE(inpath)
  File "/opt/orbitz-st-3.1-B4/lib/python-2.5/site-packages/robotide/application/application.py", line 34, in __init__
    wx.App.__init__(self, redirect=False)
  File "/usr/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7978, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7552, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/opt/orbitz-st-3.1-B4/lib/python-2.5/site-packages/robotide/application/application.py", line 43, in OnInit
    context.get_core_plugins())
  File "/opt/orbitz-st-3.1-B4/lib/python-2.5/site-packages/robotide/application/pluginloader.py", line 30, in __init__
    standard_classes + self._find_classes(load_dirs) ]
  File "/opt/orbitz-st-3.1-B4/lib/python-2.5/site-packages/robotide/application/pluginloader.py", line 42, in _find_classes
    if issubclass(cls, Plugin) and cls is not Plugin:
TypeError: issubclass() arg 1 must be a class

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=572#c1) by bryan.oakley on 2 Nov 2010*


To duplicate this, create a plugin with the following contents:

from robotide.pluginapi import Plugin

class DotDict(dict):
    def __getattr__(self, attr):
        return self.get(attr, None)
    __setattr__=dict.__setitem__
    __delattr__=dict.__delitem__

class EmptyPlugin(Plugin):
    pass

foo=DotDict({"one":1, "two":2})

Loading that same code manually yields surprising results:

$ PYTHONPATH=/opt/orbitz-st/lib/python/site-packages python2.5
Python 2.5.2 (<a href="https://code.google.com/p/robotframework-ride/source/detail?r=252">r252</a>:60911, Aug 28 2008, 13:13:37) 
[GCC 4.1.2 20071124 (Red Hat 4.1.2-42)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
&gt;&gt;&gt; import junk
&gt;&gt;&gt; import inspect
&gt;&gt;&gt; inspect.getmembers(junk, predicate=inspect.isclass)
[('DotDict', &lt;class 'junk.DotDict'&gt;), ('EmptyPlugin', &lt;class 'junk.EmptyPlugin'&gt;), ('Plugin', &lt;class 'robotide.pluginapi.plugin.Plugin'&gt;), ('foo', {'two': 2, 'one': 1})]

Notice how it includes the instance of the DotDict in the results. That is why the plugin loader is throwing an error.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=572#c2) by @pekkaklarck on 2 Nov 2010*


The reason is that your __getattr__ is buggy. It never raises AttributeError which means that it is considered to have all special attributes. A simple way to reproduce this behavior is this:

 &gt;&gt;&gt; import inspect
&gt;&gt;&gt; class X:
...   def __getattr__(self, attr):
...     return None
... 
&gt;&gt;&gt; inspect.isclass(X())
True
&gt;&gt;&gt; callable(X())
True
&gt;&gt;&gt; hasattr(X(), '__xxx___')
True

I don't think RIDE can do much here and think this issue needs to be closed.

What you can try is changing the implementation of __getattr__ to `return self[attr]` or adding there a predicate like `if attr.startswith('_'): raise AttributeError(attr)`.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=572#c3) by bryan.oakley on 2 Nov 2010*


I agree that I can work around this bug by redefining the class, but I think it's a problem that a poorly written plugin can prevent RIDE from starting up. Perhaps the try/except statements need to trap more types of errors perhaps.

Still, if you want to close this I won't lose any sleep over it.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=572#c4) by @pekkaklarck on 2 Nov 2010*


It's true that RIDE shouldn't crash in this case. Otherwise doing something in this particular case isn't possible, and even the resulting error message will be quite poor.

My advice above to implement __getattr__ as `return self[attr]` is bogus because that would raise KeyErrors instead of AttributeErrors when attribute is not found. This ought to work correctly:

    def __getattr__(self, name):
        if name not in self:
            raise AttributeError(name)
        return self[name]

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=572#c5) by bryan.oakley on 2 Nov 2010*


The fix to ride is really trivial. All you need to do is put a try around the code that uses this information around line 42. As got the error message, none is needed IMO. This error can be safely ignored -- it merely means there is a bug in ride, not a bug in the plugin. 

I've already got a fix for my plugin, but thanks for the suggestion.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=572#c6) by @yanne on 29 Nov 2010*


This was trivial to fix, no need to keep it in the tracker.

Fix is in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=59b28951b848">revision 59b28951b848</a>
