### ISSUE TITLE
RIDE fails to start

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#609]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=576) by jpshfranco on 3 Nov 2010*

Hi,

I'm using Windows XP Professional, with versions:
Robot Framework 2.5 (Jython 2.5.2b1 on java1.6.0_20)
Robot Framework 2.5 (Python 2.7 on win32)
RIDE version: 0.26

I started to getting this error when I execute ride.py:

Traceback (most recent call last):
  File "D:\Programas\Python27\Scripts\ride.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "D:\Programas\Python27\lib\site-packages\robotide\__init__.py", line 48, in main
    _run(*args)
  File "D:\Programas\Python27\lib\site-packages\robotide\__init__.py", line 56, in _run
    from robotide.application import RIDE
  File "D:\Programas\Python27\lib\site-packages\robotide\application\__init__.py", line 15, in &lt;module&gt;
    from application import RIDE, ChiefController
  File "D:\Programas\Python27\lib\site-packages\robotide\application\application.py", line 20, in &lt;module&gt;
    from robotide.namespace import Namespace
  File "D:\Programas\Python27\lib\site-packages\robotide\namespace\__init__.py", line 15, in &lt;module&gt;
    from namespace import Namespace
  File "D:\Programas\Python27\lib\site-packages\robotide\namespace\namespace.py", line 26, in &lt;module&gt;
    from robotide.namespace.cache import LibraryCache, ExpiringCache
  File "D:\Programas\Python27\lib\site-packages\robotide\namespace\cache.py", line 18, in &lt;module&gt;
    from robotide.context import SETTINGS
  File "D:\Programas\Python27\lib\site-packages\robotide\context\__init__.py", line 42, in &lt;module&gt;
    SETTINGS = RideSettings()
  File "D:\Programas\Python27\lib\site-packages\robotide\context\__init__.py", line 32, in __init__
    user_path = initialize_settings('ride', default_path)
  File "D:\Programas\Python27\lib\site-packages\robotide\context\settings.py", line 46, in initialize_settings
    _merge_settings(source_path, settings_path)
  File "D:\Programas\Python27\lib\site-packages\robotide\context\settings.py", line 53, in _merge_settings
    settings.merge(ConfigObj(user_path, unrepr=True))
  File "D:\Programas\Python27\lib\site-packages\robotide\context\configobj.py", line 1214, in __init__
    self._load(infile, configspec)
  File "D:\Programas\Python27\lib\site-packages\robotide\context\configobj.py", line 1297, in _load
    raise error
robotide.context.configobj.ConfigObjError: Parsing failed with several errors.
First error at line 35.

Apparently there were no changes made by me, at least that I've noticed,  that could cause this error.
I've already uninstall/install all software components related to the framework, but I always get the same error message when I try to run RIDE.
Do you have a clue of what can be wrong?
Any support is needed.
Thank you in advance.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=576#c1) by @pekkaklarck on 3 Nov 2010*


This looks like the same bug as in <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=272" title="Settings file can be corrupted making it impossible to start RIDE"> issue 272 </a>. Can you try does removing settings file resolve the problem? Or can you upgrade to RIDE 0.29 where this problem ought to be fixed? 0.29 unfortunately has some severe bugs, but we are going to create 0.29.1 soon.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=576#c2) by jpshfranco on 3 Nov 2010*


I have removed settings.cfg file from ...\site-packages\robotide\context\, I have also upgraded to 0.29 RIDE version, but unfortunately the error it's always the same. Can it be something related to windows registry? I'm running out of ideas. It seems that any action, no matter what, leads to the same error result.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=576#c3) by @pekkaklarck on 3 Nov 2010*


The settings.cfg in site-packages\robotide\context\ is part of RIDE source and SHOULD NOT be removed. The file you should remove is your own settings.cfg that islocated at &#37;APPDATA&#37;\RobotFramework\ride\ on Windows. For more information see <a href="https://code.google.com/p/robotframework-ride/wiki/Settings" rel="nofollow">https://code.google.com/p/robotframework-ride/wiki/Settings</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=576#c4) by jpshfranco on 4 Nov 2010*


Sorry... my mistake deleting the wrong file.
It's working now, that really did the trick!
Thank you very much for the quick support, and hope that this issue can be fixed in future releases.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=576#c5) by @pekkaklarck on 4 Nov 2010*


Good that removing the settings file fixed the problem. The corruption of settings has been fixed in 0.29, so that should not happen anymore.
