### ISSUE TITLE
Test suite file is not reloaded when changed outside the editor

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#623]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=590) by aki.p.hi... on 10 Nov 2010*

This sequence produces the problem:

- Open RIDE
- Modify a test suite file (.txt format) in an external text editor
- Click "Yes" when RIDE asks "Do you want to reload the file?"

Result:

- The test suite file is not updated in RIDE
- The following traceback is printed:

Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/robotide/utils/eventhandler.py", line 22, in wrapped
    if self._can_be_edited(event):
  File "/usr/local/lib/python2.5/site-packages/robotide/utils/eventhandler.py", line 42, in _can_be_edited
    return self._show_modified_on_disk_warning(ctrl, event)
  File "/usr/local/lib/python2.5/site-packages/robotide/utils/eventhandler.py", line 58, in _show_modified_on_disk_warning
    self._show_warning(msg, ctrl, reload_datafile)
  File "/usr/local/lib/python2.5/site-packages/robotide/utils/eventhandler.py", line 70, in _show_warning
    yes_handler()
  File "/usr/local/lib/python2.5/site-packages/robotide/utils/eventhandler.py", line 54, in reload_datafile
    self.refresh_datafile(ctrl, event)
AttributeError: 'KeywordEditor' object has no attribute 'refresh_datafile'

After this, the file cannot be modified and saved in RIDE without restarting the editor.

Sometimes the sequence must be executed more than once to produce the problem. 

---
Robot Framework 2.5.3 (Python 2.5.4 on linux2)
RIDE 0.29.1

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=590#c1) by @pekkaklarck on 12 Nov 2010*


Need to investigate this ASAP.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=590#c4) by @yanne on 17 Nov 2010*


Fixed this in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=8083d6b2416a">revision 8083d6b2416a</a>
