### ISSUE TITLE
Touching a test suite file crashes the editor

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#624]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=591) by aki.p.hi... on 10 Nov 2010*

Repeating the following sequence crashes the editor:

1) Open a directory to RIDE
2) Update the timestamp of a test suite file in the directory: 
   touch dir/suite.txt
3) Click "Yes" when RIDE asks "Do you want to reload the file?"

No traceback is reported.

The sequence simulates checkout/checkin procedure of ClearCase version control system. Checking out/in a file in ClearCase causes the same problem.

The issue has existed also in several RIDE versions before 0.29.1.

---
Robot Framework 2.5.3 (Python 2.5.4 on linux2)
RIDE 0.29.1

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=591#c1) by aki.p.hi... on 10 Nov 2010*


Clarification: repeating the steps 2 and 3 causes the crash.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=591#c2) by @pekkaklarck on 12 Nov 2010*


Need to investigate this ASAP.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=591#c4) by @jussimalinen on 15 Nov 2010*


I did not manage to get a crash, but this:

Traceback (most recent call last):
  File "src\robotide\editor\editors.py", line 85, in OnMotion
    editor.OnMotion(event)
  File "C:\Python26\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 14590, in __getattr__
    raise PyDeadObjectError(self.attrStr &#37; self._name)
wx._core.PyDeadObjectError: The C++ part of the SettingEditor object has been deleted, attribute access no longer allowed.

That could very well cause a crash in another environment.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=591#c6) by @yanne on 17 Nov 2010*


I am unable to reproduce this on my Linux. Aki, which wxPython version you are using?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=591#c7) by aki.p.hi... on 17 Nov 2010*


wxPython version is 2.8.10.1

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=591#c8) by @yanne on 17 Nov 2010*


I fixed the stacktrace that Jussi got in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=cda1af3d7d27">revision cda1af3d7d27</a>.

Aki, can you try whether you can reproduce this with the latest revision?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=591#c9) by aki.p.hi... on 17 Nov 2010*


I can still reproduce the problem with the fix. 

Actually it seems that the close() method of _RobotTableEditor class is not accessed when RIDE crashes. The crash happens between the steps 2 and 3, just before RIDE should ask "Do you want to reload the file?".

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=591#c10) by @yanne on 19 Nov 2010*


Managed to fix this in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=7e87702ece93">revision 7e87702ece93</a>.
