### ISSUE TITLE
Keyword or variable cannot be moved from test suite to resource file (Linux)

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#648]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=614) by aki.p.hi... on 2 Dec 2010*

Moving a keyword or variable from a test suite to a resource file does not work (drag'n'drop). No traceback is reported.

Moving from a resource file to a test suite file works fine.

---
Robot Framework 2.5.3 (Python 2.5.4 on linux2)
RIDE 0.30

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=614#c1) by @yanne on 2 Dec 2010*


I cannot reproduce this on my Linux box. Can you make a simple, reproducable scenario.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=614#c3) by aki.p.hi... on 3 Dec 2010*


I did not manage to make a simple example. 

It seems that a larger test set is required to reproduce the problem. For example adding more test suite files made the problem occur in existing suite/resource files.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=614#c4) by aki.p.hi... on 8 Dec 2010*


I managed to make an example with 20 test suites each having 10 user keywords. 

Moving a keyword from any test suite to resource.txt reproduces the problem. Sometimes the moving may still work, but very often the keyword is not moved. If the problem does not occur at the first time, just keep moving the keywords.

Occasionally I had the following traceback, but this was very unusual:

Traceback (most recent call last):
  File "/usr/local/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14614, in &lt;lambda&gt;
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/local/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/lib/mixins/treemixin.py", line 165, in SelectItem
    **kwargs)
  File "/usr/local/lib/python2.5/site-packages/wx-2.8-gtk2-unicode/wx/_controls.py", line 5529, in SelectItem
    return _controls_.TreeCtrl_SelectItem(*args, **kwargs)
ValueError: invalid null reference in method 'TreeCtrl_SelectItem', expected argument 2 of type 'wxTreeItemId const &amp;'

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=614#c5) by @yanne on 14 Dec 2010*


It seems that this is related to scrolling when drag and drop is used.

If drag item gets outside the tree view (for example when trying to scroll down), drag and drop stops working. This happens only in Linux. When scrolling is done using middle button, this seems to work.

Seems to be quite difficult to fix, have to investigate whether we could switch the underlying tree component.

Couldn't get the stack trace reproduced at all.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=614#c9) by @yanne on 11 Apr 2011*


I really couldn't figure out how to fix this. Since this only occurs in Linux, it is not catastrophic, but perhaps a workaround could be implemented (e.g. context menu in the tree 'Send To | ' with submenu for each resource file.
