### ISSUE TITLE
Importing library with mutable object as argument fails

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#687]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=653) by kiwitargetgranule on 21 Dec 2010*

Version 0.30 running on Python 2.5.2 using Robot Framework 2.5.5.

20101221 11:21:55.026 [WARN]: Resolving keywords for library /home/tde/vld/trunk/VSV_RFW/LIBRARY/SCPI/SCPI_robotlib.py with args [{'parity': 'N', 'baudrate': '9600', 'bytesize': '8', 'xonxoff': 'False', 'interCharTimeout': 'None', 'rtscts': 'False', 'timeout': '10', 'stopbits': '2', 'dsrdtr': 'False', 'writeTimeout': 'None', 'port': '/dev/ttyS0'}] failed:

Traceback (most recent call last):
dict objects are unhashable
  File "/usr/lib/python2.5/site-packages/robotide/namespace/cache.py", line 53, in _with_error_logging
    return action()
  File "/usr/lib/python2.5/site-packages/robotide/namespace/cache.py", line 45, in _get_library_keywords
    if not self.library_keywords.has_key(self._key(name, args)):

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=653#c3) by @mkorpela on 19 Jan 2011*


Fixed in (<a href="https://code.google.com/p/robotframework-ride/source/detail?r=cbdd5c1039">revision cbdd5c1039</a>)
