### ISSUE TITLE
moving rows up and down beyond screen scroll limit does not work

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#689]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=655) by @jussimalinen on 22 Dec 2010*

Bug can be reproduced by selecting a row and moving it up or down either from context menu (or by pressing alt+arrow) and moving the row beyond the visible screen. End result is that extra rows are selected and rows are not moved correctly.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=655#c5) by @mkorpela on 16 Mar 2011*


Related stack trace with current development version:

In this case the selection is partly moved beyond screen scroll limit and then the user tries to move it again.

IndexError: list index out of range
Traceback (most recent call last):
  File "./src/robotide/utils/eventhandler.py", line 23, in wrapped
    method(self, event)
  File "./src/robotide/editor/kweditor.py", line 300, in OnKeyDown
    self._move_rows(keycode)
  File "./src/robotide/editor/kweditor.py", line 342, in _move_rows
    self.OnMoveRowsDown()
  File "./src/robotide/utils/eventhandler.py", line 23, in wrapped
    method(self, event)
  File "./src/robotide/editor/kweditor.py", line 171, in OnMoveRowsDown
    self._row_move(MoveRowsDown, 1)
  File "./src/robotide/editor/kweditor.py", line 175, in _row_move
    if self._execute(command(rows)):
  File "./src/robotide/editor/kweditor.py", line 116, in _execute
    return self._controller.execute(command)
  File "./src/robotide/controller/basecontroller.py", line 22, in execute
    return command.execute(self)
  File "./src/robotide/controller/commands.py", line 127, in execute
    result = self._execute_without_redo_clear(context)
  File "./src/robotide/controller/commands.py", line 132, in _execute_without_redo_clear
    result = self._execute(context)
  File "./src/robotide/controller/commands.py", line 182, in _execute
    if self.change_steps(context):
  File "./src/robotide/controller/commands.py", line 626, in change_steps
    context.move_step_down(row)
  File "./src/robotide/controller/macrocontrollers.py", line 143, in move_step_down
    self.step(index).move_down()
  File "./src/robotide/controller/macrocontrollers.py", line 125, in step
    return self.steps[index]
IndexError: list index out of range

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=655#c7) by @jussimalinen on 29 Mar 2011*


Fixed in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=3b87b046cc25">r3b87b046cc25</a>
