### ISSUE TITLE
Clicking tree when release notes is shown causes traceback

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#694]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=660) by @jrantanen on 23 Dec 2010*

Following trace occurs, but id does not cause any other problems.

20101223 10:13:39.256 [ERROR]: Error in listener: 'NoneType' object has no attribute 'tree_item_selected'

Traceback (most recent call last):
'NoneType' object has no attribute 'tree_item_selected'
  File "C:\Python27\lib\site-packages\robotide\publish\publisher.py", line 84, in __call__
    self.listener(event.data)
  File "C:\Python27\lib\site-packages\robotide\editor\__init__.py", line 109, in
 OnTreeItemSelected
    self._editor.tree_item_selected(message.item)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=660#c1) by @jrantanen on 20 Jan 2011*


Can't reproduce.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=660#c2) by bryan.oakley on 20 Jan 2011*


even though you can't reproduce it, why not just add a little defensive programming to prevent the stack trace or add some logging in case it happens again? All you have to do is an an "if self._editor is not None" statement.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=660#c5) by @jrantanen on 14 Mar 2011*


This issue was closed by <a href="https://code.google.com/p/robotframework-ride/source/detail?r=c8abfa8c19">revision c8abfa8c19</a>.
