### ISSUE TITLE
Rename Variable

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#714]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=680) by @mkorpela on 19 Jan 2011*

Current renaming functionality doesn't work correctly with variables.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=680#c1) by grompy on 23 Feb 2011*


Trying to rename a variable on the Tree results in :

Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\robotide\utils\eventhandler.py", line 23,
in wrapped
    method(self, event)
  File "C:\Python26\Lib\site-packages\robotide\ui\tree.py", line 521, in OnLabel
Edited
    if not event.IsEditCancelled() and handler.rename(event.Label):
AttributeError: 'VariableHandler' object has no attribute 'rename'
