### ISSUE TITLE
Sometimes copying cells is not possible

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#723]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=689) by bobobruhn on 27 Jan 2011*

Windows7 Ultimate
Ride 0.31
RFW  2.5.5

When trying to copy a range of selected cells into a user keyword, i sometimes get the following traceback.

I select the cells to be copied by marking upper left and lower right corner.
Then using the paste from Cells popup menu

I'll try to precise the handling for easier bugfixing later.

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\utils\eventhandler.py", line 23,
in wrapped
    method(self, event)
  File "C:\Python26\lib\site-packages\robotide\editor\kweditor.py", line 234, in
 OnPaste
    self._execute(PasteArea(self.selection.topleft, data))
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 602
, in PasteArea
    for col in range(len(content[0]))])
IndexError: list index out of range

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=689#c1) by @mkorpela on 10 Feb 2011*


We try to investigate this. If you can provide more information about how you can reproduce this it would help.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=689#c3) by @jrantanen on 11 Mar 2011*


Could you provide more information so that we could reproduce this problem?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=689#c5) by @jrantanen on 29 Mar 2011*


Did this problem occur when you were editing for loops?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=689#c6) by bobobruhn on 29 Mar 2011*


Yes it did for sure.

I tried to reproduce this with with 0.33 and wasn't able see it again.

But how can you say that problem is away if it occurs "sometimes".
 
Maybe this problem was related to loop detection problem.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=689#c10) by @mkorpela on 23 Sep 2011*


Does this still occur with the latest releases? We have fixed problems related to pasting and also this problem may have been fixed.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=689#c11) by bobobruhn on 23 Sep 2011*


Working with 38.1 now and haven't seen the problem anymore. Seems to be fixed

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=689#c12) by @yanne on 23 Sep 2011*


In that casem closing the issue

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=689#c13) by @pekkaklarck on 26 Sep 2011*


I'd say this is fixed rather than WontFixed.
