### ISSUE TITLE
Embedded images are not loaded when too old wxpython version

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#725]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=691) by kiwitargetgranule on 31 Jan 2011*

1)I used an old wxversion and each time ride start up embeddedimage is not found, which is normal, but should be note in installation process
2)there's always a warning for mutable object, i don't know if it's important

Thanks for ride

=RIDE LOG=

20110131 10:46:58.728 [WARN]: Importing library /home/tde/vld/trunk/VSV_RFW/LIBRARY/rs232_cpyserial/cpyserial_robotlib.py failed:

Traceback (most recent call last):
'dict' object has no attribute 'upper'
  File "/usr/lib/python2.5/site-packages/robotide/namespace/cache.py", line 65, in _with_error_logging
    return action()
  File "/usr/lib/python2.5/site-packages/robotide/namespace/cache.py", line 47, in &lt;lambda&gt;
    action = lambda: LibrarySpec(name, args).keywords
  File "/usr/lib/python2.5/site-packages/robotide/spec/xmlreaders.py", line 52, in __init__
    if args and len(args) &gt;= 2 and args[-2].upper() == 'WITH NAME':

20110131 10:46:59.044 [INFO]: Started RIDE version 0.32.1, running on linux2, python version 2.5.2 (<a href="https://code.google.com/p/robotframework-ride/source/detail?r=252">r252</a>:60911, Jan 20 2010, 21:48:48) 
[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu3)] with wx version 2.8.7.1.

20110131 10:46:59.044 [INFO]: Started RIDE version 0.32.1, running on linux2, python version 2.5.2 (<a href="https://code.google.com/p/robotframework-ride/source/detail?r=252">r252</a>:60911, Jan 20 2010, 21:48:48) 
[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu3)] with wx version 2.8.7.1.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=691#c1) by @mkorpela on 10 Feb 2011*


The required/recommended wxPython version definitely needs to be documented better. Hopefully we can also fix the other problem you reported.

In the future, please submit separate issues about different bugs/features.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=691#c2) by @mkorpela on 10 Feb 2011*


Also <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=709" title="Document with wxPython 2.8.10.1 in Windows 7 Argument, Timeout and Return Value Dialog are opened twice"> issue 709 </a> is about documenting wxPython versions.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=691#c3) by @mkorpela on 4 Mar 2011*


Documented wx version
<a href="https://code.google.com/p/robotframework-ride/wiki/InstallationInstructions" rel="nofollow">https://code.google.com/p/robotframework-ride/wiki/InstallationInstructions</a>

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=691#c4) by @mkorpela on 7 Mar 2011*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=726" title="Importing library with second last argument other than string type fails"> issue 726 </a> has been split from this one,
