### ISSUE TITLE
A case where delete cells undo fails

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#739]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=704) by bobobruhn on 3 Feb 2011*

Ride 32.1, 
tested under Ubuntu 10.10 and Windows 7 Ultimate

When opening the attached file in the ride everything looks good, except the highlighting in line 4 which indicates a possible argument in the 7the column.
When trying to change Row4, Column3 to 'In Range', the whole structure of the testcase is destroyed. row5 and 6 are indented and third for loop is empty.

This destroys the testcase completely.

It is also not possible to undo this operation, even it is offered.

Most probable same rootcause:
-----------------------------
If you delete cells from R5C2 to R6C5, the cells are correctly deleted. But when trying to undo, you get the following error trace, (ending up with IndexError: list index out of range) :

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\ui\actiontriggers.py", line 349, in __call__
    action.act(event)
  File "C:\Python26\lib\site-packages\robotide\action\action.py", line 86, in act
    self.action(event)
  File "C:\Python26\lib\site-packages\robotide\editor\__init__.py", line 152, in  OnUndo
    self.editor.undo()
  File "C:\Python26\lib\site-packages\robotide\editor\editors.py", line 497, in undo
    self.kweditor.OnUndo()
  File "C:\Python26\lib\site-packages\robotide\utils\eventhandler.py", line 23,in wrapped
    method(self, event)
  File "C:\Python26\lib\site-packages\robotide\editor\kweditor.py", line 244, in OnUndo
    self._execute(Undo())
  File "C:\Python26\lib\site-packages\robotide\editor\kweditor.py", line 109, in _execute
    return self._controller.execute(command)
  File "C:\Python26\lib\site-packages\robotide\controller\basecontroller.py", line 22, in execute
    return command.execute(self)
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 129, in execute
    result = context.pop_from_undo()._execute_without_redo_clear(context)
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 116, in _execute_without_redo_clear
    result = self._execute(context)
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 165, in _execute
    if self.change_steps(context):
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 631, in change_steps
    return any(changed for changed in CompositeCommand._execute(self, context))
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 609, in _execute
    executions = self._executions(context)
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 640, in _executions
    return [(cmd.change_steps(context), cmd._get_undo_command()) for cmd in self._commands]
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 631, in change_steps
    return any(changed for changed in CompositeCommand._execute(self, context))
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 609, in _execute
    executions = self._executions(context)
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 640, in _executions
    return [(cmd.change_steps(context), cmd._get_undo_command()) for cmd in self._commands]
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 436, in change_steps
    step.remove_empty_columns_from_end()
  File "C:\Python26\lib\site-packages\robotide\controller\stepcontrollers.py", line 225, in remove_empty_columns_from_end
    self._recreate(cells)
  File "C:\Python26\lib\site-packages\robotide\controller\stepcontrollers.py", line 400, in _recreate
    if cells[0] == '':
IndexError: list index out of range

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=704#c1) by @mkorpela on 3 Feb 2011*


This has some elements that most likely have the same root cause as (<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=453" title="Using Comments Rows or Colorizing for a complete FOR loop does not work correctly"> issue 453 </a>) -- the for loop isn't seen as a for-loop after changing the for-loop header row.

The undo part with the stack trace is a new defect.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=704#c2) by @mkorpela on 4 Feb 2011*


The undo problem is fixed in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=872542d801">revision 872542d801</a>.

As I'm very confident that the other issue is same as <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=453" title="Using Comments Rows or Colorizing for a complete FOR loop does not work correctly"> issue 453 </a>, I'm closing this one.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=704#c3) by @mkorpela on 4 Feb 2011*


Actually there was an additional error that has now been fixed in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=c36f996cd3">revision c36f996cd3</a>.

After this WeiredForHandling.tsv works as expected (although <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=453" title="Using Comments Rows or Colorizing for a complete FOR loop does not work correctly"> issue 453 </a> still exists).
