### ISSUE TITLE
Importing library with second last argument other than string type fails

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#761]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=726) by @jrantanen on 7 Mar 2011*

There's always a warning for mutable object, i don't know if it's important

Thanks for ride

=RIDE LOG=

20110131 10:46:58.728 [WARN]: Importing library /home/tde/vld/trunk/VSV_RFW/LIBRARY/rs232_cpyserial/cpyserial_robotlib.py failed:

Traceback (most recent call last):
'dict' object has no attribute 'upper'
  File "/usr/lib/python2.5/site-packages/robotide/namespace/cache.py", line 65, in _with_error_logging
    return action()
  File "/usr/lib/python2.5/site-packages/robotide/namespace/cache.py", line 47, in &lt;lambda&gt;
    action = lambda: LibrarySpec(name, args).keywords
  File "/usr/lib/python2.5/site-packages/robotide/spec/xmlreaders.py", line 52, in __init__
    if args and len(args) &gt;= 2 and args[-2].upper() == 'WITH NAME':

20110131 10:46:59.044 [INFO]: Started RIDE version 0.32.1, running on linux2, python version 2.5.2 (<a href="https://code.google.com/p/robotframework-ride/source/detail?r=252">r252</a>:60911, Jan 20 2010, 21:48:48) 
[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu3)] with wx version 2.8.7.1.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=726#c1) by @jrantanen on 7 Mar 2011*


This issue was closed by <a href="https://code.google.com/p/robotframework-ride/source/detail?r=19f2f3ad14">revision 19f2f3ad14</a>.
