### ISSUE TITLE
Bundle Robot Framework with RIDE to ease handling dependencies

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#764]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=729) by filip.noetzel on 9 Mar 2011*

setup.py does not require robotframework via install_requires in setup.py, but it should.

Possibly related to #622

ACTUAL:

$ pip install robotframework-ride
Downloading/unpacking robotframework-ride
  Downloading robotframework-ride-0.33.tar.gz (165Kb): 165Kb downloaded
  Running setup.py egg_info for package robotframework-ride
    package init file 'src/robotide/contrib/testrunner/__init__.py' not found (or not a regular file)
Installing collected packages: robotframework-ride
  Running setup.py install for robotframework-ride
    package init file 'src/robotide/contrib/testrunner/__init__.py' not found (or not a regular file)
    changing mode of build/scripts-2.6/ride.py from 644 to 755
    changing mode of /usr/local/bin/ride.py to 755
Successfully installed robotframework-ride
Cleaning up...

$ ride.py
Traceback (most recent call last):
  File "/usr/local/bin/ride.py", line 20, in &lt;module&gt;
    from robotide import main
  File "/Library/Python/2.6/site-packages/robotide/__init__.py", line 32, in &lt;module&gt;
    import robotpatch
  File "/Library/Python/2.6/site-packages/robotide/robotpatch.py", line 21, in &lt;module&gt;
    from robot.parsing.settings import Timeout, _Setting, Fixture, Template, Metadata
ImportError: No module named robot.parsing.settings

EXPECTED:

$&gt; pip install robotframework-ride
# ...

$&gt; ride.py # launches RIDE

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=729#c2) by @pekkaklarck on 9 Mar 2011*


I think a better solution is bundling Robot with RIDE. That would also prevent problems with Robot versions.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=729#c3) by @jrantanen on 11 Mar 2011*


At list following things need to be taken into account when bundling the Robot to RIDE:

1) Libraries might contain keywords that user does not have in the installed Robot (in case it exists), installed Robot is preferred in keyword completion.
2) Test Runner plugin needs to be able to execute tests using bundled Robot.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=729#c5) by @pekkaklarck on 11 Mar 2011*


I don't really understand the concern 1) in comment 3 above and the concern 2) ought to be easy to handle.

I've been thinking about this a bit more and think it should be done latest after RF 2.6 but possibly earlier. Doing this after RF 2.6 prevents problems in situations where people cannot upgrade from 2.5 and would even allow 2.1 users to use the latest RIDE. Doing this now would allow fixing <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=735" title="Using # character to comment rows collapses the commented row on next startup"> issue 735 </a> and other similar issues that depend on changes on RF side.

In version control bundling RF with RIDE ought to be relatively easy with Mercurial subrepositories [1] that work somewhat like svn:external. Code changes should be limited to changing `from robot import x` to `from ride.robot import x`.

[1] <a href="http://mercurial.selenic.com/wiki/Subrepository" rel="nofollow">http://mercurial.selenic.com/wiki/Subrepository</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=729#c6) by @jrantanen on 14 Mar 2011*


Concern 1 re-explained:

When there are installed and bundled robot, keywords that are provided by those robot versions might be different. This might cause user to select keywords to the tests which cannot be found if tests are executed with different version of the robot.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=729#c11) by marisab... on 1 Jun 2011*


OK - sorry I am new and evaluating Robot framework. Please tell me how I fix this error?  I can't get RIDE to open. Thank you!

$ ride.py
Traceback (most recent call last):
  File "/usr/local/bin/ride.py", line 20, in &lt;module&gt;
    from robotide import main
  File "/Library/Python/2.6/site-packages/robotide/__init__.py", line 32, in &lt;module&gt;
    import robotpatch
  File "/Library/Python/2.6/site-packages/robotide/robotpatch.py", line 21, in &lt;module&gt;
    from robot.parsing.settings import Timeout, _Setting, Fixture, Template, Metadata
ImportError: No module named robot.parsing.settings

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=729#c12) by @pekkaklarck on 1 Jun 2011*


@&#8288;marisab..., it seems you don't have Robot Framework installed. Or that you have a wrong Robot version. See <a href="https://code.google.com/p/robotframework-ride/wiki/InstallationInstructions" title="How to install RIDE and its prerequisites">InstallationInstructions</a> wiki page for more details.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=729#c13) by @jussimalinen on 3 Aug 2011*


This seems to be done, but we still need to try if everything really works in windows and if the workflow seems natural.

Robot was added as a subrepository in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=e50243b3da74">re50243b3da74</a>
Packaging changed to bundle robot for installation in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=3a9efc7d1705">r3a9efc7d1705</a>

Note that now you will need mercurial 1.7 or newer to work with Ride.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=729#c14) by @jussimalinen on 8 Aug 2011*


seems to work.
