### ISSUE TITLE
Find Usages highlighting failure

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#768]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=733) by @mkorpela on 10 Mar 2011*

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/robotide/widgets/list.py", line 50, in OnListItemSelected
    listener(event.Index)
  File "/usr/local/lib/python2.6/dist-packages/robotide/usages/usagesdialog.py", line 55, in _usage_selected
    listener(self.usages.usage(idx).item.parent, self._name)
  File "/usr/local/lib/python2.6/dist-packages/robotide/ui/tree.py", line 579, in highlight
    self._editor.highlight(text)
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/__init__.py", line 79, in highlight
    self._editor.highlight(text)
  File "/usr/local/lib/python2.6/dist-packages/robotide/editor/editors.py", line 162, in highlight
    editor.highlight(text, expand=expand)
TypeError: highlight() got an unexpected keyword argument 'expand'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=733#c3) by @jrantanen on 11 Mar 2011*


This issue was closed by <a href="https://code.google.com/p/robotframework-ride/source/detail?r=e7aec3c85f">revision e7aec3c85f</a>.
