### ISSUE TITLE
Save all causes traceback

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#771]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=736) by @jrantanen on 11 Mar 2011*

Traceback (most recent call last):

  File "C:\APPS\Python\lib\site-packages\robotide\ui\actiontriggers.py", line 349, in __call__

    action.act(event)

  File "C:\APPS\Python\lib\site-packages\robotide\action\action.py", line 86, in act

    self.action(event)

  File "C:\APPS\Python\lib\site-packages\robotide\utils\eventhandler.py", line 23, in wrapped

    method(self, event)

  File "C:\APPS\Python\lib\site-packages\robotide\ui\mainframe.py", line 184, in OnSaveAll

    self.save_all()

  File "C:\APPS\Python\lib\site-packages\robotide\ui\mainframe.py", line 188, in save_all

    self._controller.execute(SaveAll())

  File "C:\APPS\Python\lib\site-packages\robotide\controller\chiefcontroller.py", line 46, in execute

    return command.execute(self)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\commands.py", line 489, in execute

    datafile_controller.execute(SaveFile())

  File "C:\APPS\Python\lib\site-packages\robotide\controller\filecontrollers.py", line 128, in execute

    return command.execute(self)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\commands.py", line 481, in execute

    macro_controller.execute(Purify())

  File "C:\APPS\Python\lib\site-packages\robotide\controller\basecontroller.py", line 22, in execute

    return command.execute(self)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\commands.py", line 497, in execute

    step.remove_empty_columns_from_beginning()

  File "C:\APPS\Python\lib\site-packages\robotide\controller\stepcontrollers.py", line 231, in remove_empty_columns_from_beginning

    self._recreate(cells)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\stepcontrollers.py", line 406, in _recreate

    index_of_parent = self.parent.parent.index_of_step(self.parent._step)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\macrocontrollers.py", line 128, in index_of_step

    return [s._step for s in self.steps].index(step)

ValueError: list.index(x): x not in list

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=736#c1) by @jrantanen on 11 Mar 2011*


The problem seems to be in FOR loops steps. This should be investigated with <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=453" title="Using Comments Rows or Colorizing for a complete FOR loop does not work correctly"> issue 453 </a>.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=736#c7) by @mkorpela on 15 Feb 2012*


I'm almost certain that this has been fixed while FOR loops where changed.

Closing as invalid.
