### ISSUE TITLE
Delete rows causes traceback

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#772]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=737) by @jrantanen on 11 Mar 2011*

Traceback (most recent call last):

  File "C:\APPS\Python\lib\site-packages\robotide\utils\eventhandler.py", line 23, in wrapped

    method(self, event)

  File "C:\APPS\Python\lib\site-packages\robotide\editor\kweditor.py", line 251, in OnDeleteRows

    self._execute(DeleteRows(self.GetSelectedRows()))

  File "C:\APPS\Python\lib\site-packages\robotide\editor\kweditor.py", line 116, in _execute

    return self._controller.execute(command)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\basecontroller.py", line 22, in execute

    return command.execute(self)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\commands.py", line 127, in execute

    result = self._execute_without_redo_clear(context)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\commands.py", line 132, in _execute_without_redo_clear

    result = self._execute(context)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\commands.py", line 182, in _execute

    if self.change_steps(context):

  File "C:\APPS\Python\lib\site-packages\robotide\controller\commands.py", line 665, in change_steps

    return any(changed for changed in CompositeCommand._execute(self, context))

  File "C:\APPS\Python\lib\site-packages\robotide\controller\commands.py", line 643, in _execute

    executions = self._executions(context)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\commands.py", line 674, in _executions

    return [(cmd.change_steps(context), cmd._get_undo_command()) for cmd in self._commands]

  File "C:\APPS\Python\lib\site-packages\robotide\controller\commands.py", line 546, in change_steps

    self._change_value(context)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\commands.py", line 555, in _change_value

    context.remove_step(self._row)

  File "C:\APPS\Python\lib\site-packages\robotide\controller\macrocontrollers.py", line 200, in remove_step

    self._remove_step(self.steps[index])

  File "C:\APPS\Python\lib\site-packages\robotide\controller\macrocontrollers.py", line 207, in _remove_step

    step.remove()

  File "C:\APPS\Python\lib\site-packages\robotide\controller\stepcontrollers.py", line 234, in remove

    self.parent.data.steps.remove(self._step)

ValueError: list.remove(x): x not in list

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=737#c2) by @mkorpela on 15 Mar 2011*


Can't reproduce. Although I've seen it happen more than once.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=737#c8) by @mkorpela on 20 Aug 2011*


Fixed. Thanks monkey!
