### ISSUE TITLE
Model is broken after 2 for-loop move operation

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#799]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=764) by @mkorpela on 29 Mar 2011*

Data for test:
*** Test Cases ***
Jop
    : FOR  ${i}  IN RANGE  1  10
    \  Log  joo
    : FOR  ${j}  IN  1  2
    \  Log  jee

__Steps to reproduce the problem__

Move first row ": FOR ${i}.." 2 rows down to get to a state:
*** Test Cases ***
Jop
    Log  joo
    : FOR  ${j}  IN  1  2
    : FOR  ${i}  IN RANGE  1  10
    \  Log  jee

----&gt;
Model is broken and for example tool tip will produce this kind of exceptions:
AttributeError: 'ForLoop' object has no attribute 'args'
Traceback (most recent call last):
  File "./src/robotide/editor/tooltips.py", line 42, in OnShowToolTip
    content = self._grid.get_tooltip_content()
  File "./src/robotide/editor/kweditor.py", line 97, in get_tooltip_content
    cell_info = self._controller.get_cell_info(cell.Row, cell.Col)
  File "./src/robotide/controller/macrocontrollers.py", line 157, in get_cell_info
    steps = self.steps
  File "./src/robotide/controller/macrocontrollers.py", line 94, in steps
    self._recreate_steps()
  File "./src/robotide/controller/macrocontrollers.py", line 107, in _recreate_steps
    flattened_steps.extend(for_loop.steps)
  File "./src/robotide/controller/stepcontrollers.py", line 315, in steps
    return [IntendedStepController(self, sub_step) for sub_step in self._get_raw_steps()]
  File "./src/robotide/controller/stepcontrollers.py", line 11, in __init__
    self._step.args = self._change_last_empty_to_empty_var(self._step.args, self._step.comment)
AttributeError: 'ForLoop' object has no attribute 'args'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=764#c5) by @mkorpela on 23 Aug 2011*


Fixed in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=4f10e7dddc25">r4f10e7dddc25</a>.
