### ISSUE TITLE
Preview produces stack trace when no data is open

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#801]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=766) by @mkorpela on 29 Mar 2011*

Traceback (most recent call last):
  File "./src/robotide/ui/actiontriggers.py", line 349, in __call__
    action.act(event)
  File "./src/robotide/action/action.py", line 86, in act
    self.action(event)
  File "./src/robotide/ui/preview.py", line 56, in OnShowPreview
    self._update_preview()
  File "./src/robotide/ui/preview.py", line 68, in _update_preview
    if self.tab_is_visible(self._panel) and self.datafile:
  File "./src/robotide/pluginapi/plugin.py", line 132, in __getattr__
    raise AttributeError("No attribute or settings with name '&#37;s' found" &#37; name)
AttributeError: No attribute or settings with name 'datafile' found

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=766#c2) by @jrantanen on 29 Mar 2011*


Fixed in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=a9546cf5338d">revision a9546cf5338d</a>.
