### ISSUE TITLE
Possibility to edit variable names from tree

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#812]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=777) by @pekkaklarck on 31 Mar 2011*

To reproduce, first select a variable in the tree and then either press F2 or click the variable so that rename editor opens, type in new value, and press enter. In both cases you get an error like this to the console:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotframework_ride-0.34-py2.7-win32.egg\robotide\utils\eventhandler.py", line 23, in wrapped
    method(self, event)
  File "C:\Python27\lib\site-packages\robotframework_ride-0.34-py2.7-win32.egg\robotide\ui\tree.py", line 538, in OnLabelEdit
    if handler and handler.is_renameable:
AttributeError: 'VariableHandler' object has no attribute 'is_renameable'

A simple fix is adding `is_renameable = False` to `VariableHandler` but a better fix is making renaming variables like this possible.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=777#c1) by @jrantanen on 6 Apr 2011*


Variables can now be edited from tree. Fixed in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=3b1c3f0f4b29">revision 3b1c3f0f4b29</a>.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=777#c4) by @yanne on 11 Apr 2011*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=680" title="Rename Variable"> Issue 680 </a> has been merged into this issue.
