### ISSUE TITLE
AttributeError: 'MacRidePopupWindow' object has no attribute 'screen_position'

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#818]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=783) by jerry57 on 5 Apr 2011*

Python 2.6.1 (Mac default)
wx 2.8.8.1 (mac-unicode)
OS Mac OS X 10.6.7
RIDE 0.34

When I edit some testcase tags I noticed that the terminal where I launched ride from began spewing Tracebacks.  The only way to stop them was to close Ride and restart it.  Otherwise the terminal was worthless to do anything as tracebacks just keep scrolling.

This happened when editing tags or deleting tags.

Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/robotide/editor/editors.py", line 111, in OnIdle
    if self._last_shown_tooltip and self._mouse_outside_tooltip():
  File "/Library/Python/2.6/site-packages/robotide/editor/editors.py", line 117, in _mouse_outside_tooltip
    tx, ty = self._last_shown_tooltip.screen_position
AttributeError: 'MacRidePopupWindow' object has no attribute 'screen_position'
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/robotide/editor/editors.py", line 111, in OnIdle
    if self._last_shown_tooltip and self._mouse_outside_tooltip():
  File "/Library/Python/2.6/site-packages/robotide/editor/editors.py", line 117, in _mouse_outside_tooltip
    tx, ty = self._last_shown_tooltip.screen_position
AttributeError: 'MacRidePopupWindow' object has no attribute 'screen_position'
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/robotide/editor/editors.py", line 111, in OnIdle
    if self._last_shown_tooltip and self._mouse_outside_tooltip():
  File "/Library/Python/2.6/site-packages/robotide/editor/editors.py", line 117, in _mouse_outside_tooltip
    tx, ty = self._last_shown_tooltip.screen_position
AttributeError: 'MacRidePopupWindow' object has no attribute 'screen_position'
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/robotide/editor/editors.py", line 111, in OnIdle
    if self._last_shown_tooltip and self._mouse_outside_tooltip():
  File "/Library/Python/2.6/site-packages/robotide/editor/editors.py", line 117, in _mouse_outside_tooltip
    tx, ty = self._last_shown_tooltip.screen_position
AttributeError: 'MacRidePopupWindow' object has no attribute 'screen_position'
T

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=783#c1) by @mkorpela on 6 Apr 2011*


Fixed in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=2722694fd27c">revision 2722694fd27c</a>
