### ISSUE TITLE
Add keyword from tree when suite is collapsed produces traceback

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#825]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=790) by @mkorpela on 14 Apr 2011*

Traceback (most recent call last):
  File "/usr/lib64/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14614, in &lt;lambda&gt;
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/lib64/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/lib/mixins/treemixin.py", line 165, in SelectItem
    **kwargs)
  File "/usr/lib64/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_controls.py", line 5529, in SelectItem
    return _controls_.TreeCtrl_SelectItem(*args, **kwargs)
ValueError: invalid null reference in method 'TreeCtrl_SelectItem', expected argument 2 of type 'wxTreeItemId const &amp;'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=790#c3) by @mkorpela on 3 Aug 2011*


Fixed in <a href="https://code.google.com/p/robotframework-ride/source/detail?r=71c9a2f11b39">r71c9a2f11b39</a>.
