### ISSUE TITLE
ProgressDialog_Pulse can't be initialized when running ride along with projects file opening

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#833]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=798) by alex.sha... on 18 Apr 2011*

I'm running ride using X11 ssh forwarding on GNU/Linux machines.

When I'm running ride.py wo arguments and then opening my project via Ctrl+O, then it works fine.
When I'm trying to run "ride.py $path_to_project_file", then ride crashes with the following stacktrace:

Traceback (most recent call last):
  File "/svc/tmv726/opt/python-2.7.1/bin/ride.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/robotide/__init__.py", line 44, in main
    _run(*args)
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/robotide/__init__.py", line 51, in _run
    ride = RIDE(inpath)
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/robotide/application/application.py", line 35, in __init__
    wx.App.__init__(self, redirect=False)
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/wx-2.9.1-gtk2/wx/_core.py", line 8470, in __init__
    self._BootstrapApp()
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/wx-2.9.1-gtk2/wx/_core.py", line 8035, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/robotide/application/application.py", line 47, in OnInit
    self._load_data()
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/robotide/application/application.py", line 83, in _load_data
    self._controller.load_data(self._initial_path, observer)
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/robotide/controller/chiefcontroller.py", line 58, in load_data
    if self._load_datafile(path, load_observer):
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/robotide/controller/chiefcontroller.py", line 77, in _load_datafile
    datafile = self._loader.load_datafile(path, load_observer)
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/robotide/controller/dataloader.py", line 28, in load_datafile
    load_observer.notify()
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/robotide/ui/progress.py", line 29, in notify
    self._progressbar.Pulse()
  File "/svc/tmv726/opt/python-2.7.1/lib/python2.7/site-packages/wx-2.9.1-gtk2/wx/_windows.py", line 3703, in Pulse
    return _windows_.ProgressDialog_Pulse(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "wxEventLoopBase::GetActive()" failed at ../src/generic/progdlgg.cpp(467) in DoBeforeUpdate(): wxProgressDialog::DoBeforeUpdate needs a running event loop

Version 0.34 running on Python 2.7.1 using Robot Framework 2.5.6

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=798#c2) by @yanne on 10 Jan 2012*


Could not reproduce this earlier, but just noticed that this only occurs with wxPython 2.9.*

Fixed now.
