### ISSUE TITLE
Ride launch issues 

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#834]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=799) by ashwini.... on 19 Apr 2011*

hi,
I have been trying to launch ride.py but i get the below error each time. Please help.

I have installed the following:
Python 2.6.6
RobotFramework 2.1.3
wxPython - 2.8
Robotide 0.23

With Regards,
Ashwini

C:\Documents and Settings\Administrator&gt;ride.py
Traceback (most recent call last):
  File "C:\Python26\Scripts\ride.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "C:\Python26\lib\site-packages\robotide\__init__.py", line 46, in main
    _run(*args)
  File "C:\Python26\lib\site-packages\robotide\__init__.py", line 54, in _run
    from robotide.application import RIDE
  File "C:\Python26\lib\site-packages\robotide\application\__init__.py", line 15
, in &lt;module&gt;
    from application import RIDE, DataModel
  File "C:\Python26\lib\site-packages\robotide\application\application.py", line
 22, in &lt;module&gt;
    from robotide.namespace import Namespace
  File "C:\Python26\lib\site-packages\robotide\namespace\__init__.py", line 15,
in &lt;module&gt;
    from robotide import utils
  File "C:\Python26\lib\site-packages\robotide\utils\__init__.py", line 23, in &lt;
module&gt;
    from components import RideHtmlWindow, PopupMenu, ButtonWithHandler
  File "C:\Python26\lib\site-packages\robotide\utils\components.py", line 19, in
 &lt;module&gt;
    from robotide import context
  File "C:\Python26\lib\site-packages\robotide\context\__init__.py", line 41, in
 &lt;module&gt;
    SETTINGS = RideSettings()
  File "C:\Python26\lib\site-packages\robotide\context\__init__.py", line 31, in
 __init__
    user_path = initialize_settings('ride', default_path)
  File "C:\Python26\lib\site-packages\robotide\context\settings.py", line 45, in
 initialize_settings
    _merge_settings(source_path, settings_path)
  File "C:\Python26\lib\site-packages\robotide\context\settings.py", line 52, in
 _merge_settings
    settings.merge(ConfigObj(user_path, unrepr=True))
  File "C:\Python26\lib\site-packages\robotide\context\configobj.py", line 1214,
 in __init__
    self._load(infile, configspec)
  File "C:\Python26\lib\site-packages\robotide\context\configobj.py", line 1297,
 in _load
    raise error
robotide.context.configobj.ConfigObjError: Parsing failed with several errors.
First error at line 8.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=799#c1) by ashwini.... on 19 Apr 2011*


hi,
I was able to resolve this issue on my own. Basically, the settings.cfg file under C:\Documents and Settings\Administrator\Application Data\RobotFramework\ride\settings.cfg needed to be deleted before trying a re-install.

Earlier I was deleting the settings.cfg under C:\Python26\Lib\site-packages\robotide\context\settings.cfg but this did not work. 

Hope this is useful to others facing the same issue :-)

With Regards,
Ashwini

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=799#c2) by chethanb... on 13 Jul 2011*


Hi Ashwini,

Even i got the same error. But i tried to follow the steps you mentioned above.
I dint find the directory by name "RobotFramework" under C:\Documents and Settings\Administrator\Application Data

C:\Python26\Scripts&gt;ride.py
Traceback (most recent call last):
  File "C:\Python26\Scripts\ride.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "C:\Python26\lib\site-packages\robotide\__init__.py", line 50, in main
    _run(*args)
  File "C:\Python26\lib\site-packages\robotide\__init__.py", line 60, in _run
    from robotide.application import RobotIde
  File "C:\Python26\lib\site-packages\robotide\application\__init__.py", line 15
, in &lt;module&gt;
    from application import RobotIde
  File "C:\Python26\lib\site-packages\robotide\application\application.py", line
 19, in &lt;module&gt;
    from robotide import context
  File "C:\Python26\lib\site-packages\robotide\context\__init__.py", line 38, in
 &lt;module&gt;
    SETTINGS = RideSettings()
  File "C:\Python26\lib\site-packages\robotide\context\__init__.py", line 29, in
 __init__
    user_path = initialize_settings('ride', default_path)
  File "C:\Python26\lib\site-packages\robotide\context\settings.py", line 33, in
 initialize_settings
    _merge_settings(source_path, settings_path)
  File "C:\Python26\lib\site-packages\robotide\context\settings.py", line 40, in
 _merge_settings
    settings.merge(ConfigObj(user_path, unrepr=True))
  File "C:\Python26\lib\site-packages\robotide\context\configobj.py", line 1219,
 in __init__
    self._load(infile, configspec)
  File "C:\Python26\lib\site-packages\robotide\context\configobj.py", line 1302,
 in _load
    raise error
robotide.context.configobj.DuplicateError: Duplicate keyword name at line 9.


Kindly help me on this. I installed following s/w

python-2.6.4.msi
wxPython2.8-win32-unicode-2.8.9.2-py26.exe
set env variables-(C:\Python26\;C:\Python26\Scripts)
copy the folder paramiko-1.7.6, where python is installed
from command prompt :  python setup.py install
robotframework-2.1.1.win32.exe
robotide-0.17.win32.exe
pycrypto-2.1.0.win32-py2.6.exe
SSHLibrary-0.9.win32.exe

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=799#c3) by chethanb... on 13 Jul 2011*


Hi Ashwini,

Even i got the same error. But i tried to follow the steps you mentioned above.
I dint find the directory by name "RobotFramework" under C:\Documents and Settings\Administrator\Application Data

C:\Python26\Scripts&gt;ride.py
Traceback (most recent call last):
  File "C:\Python26\Scripts\ride.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "C:\Python26\lib\site-packages\robotide\__init__.py", line 50, in main
    _run(*args)
  File "C:\Python26\lib\site-packages\robotide\__init__.py", line 60, in _run
    from robotide.application import RobotIde
  File "C:\Python26\lib\site-packages\robotide\application\__init__.py", line 15
, in &lt;module&gt;
    from application import RobotIde
  File "C:\Python26\lib\site-packages\robotide\application\application.py", line
 19, in &lt;module&gt;
    from robotide import context
  File "C:\Python26\lib\site-packages\robotide\context\__init__.py", line 38, in
 &lt;module&gt;
    SETTINGS = RideSettings()
  File "C:\Python26\lib\site-packages\robotide\context\__init__.py", line 29, in
 __init__
    user_path = initialize_settings('ride', default_path)
  File "C:\Python26\lib\site-packages\robotide\context\settings.py", line 33, in
 initialize_settings
    _merge_settings(source_path, settings_path)
  File "C:\Python26\lib\site-packages\robotide\context\settings.py", line 40, in
 _merge_settings
    settings.merge(ConfigObj(user_path, unrepr=True))
  File "C:\Python26\lib\site-packages\robotide\context\configobj.py", line 1219,
 in __init__
    self._load(infile, configspec)
  File "C:\Python26\lib\site-packages\robotide\context\configobj.py", line 1302,
 in _load
    raise error
robotide.context.configobj.DuplicateError: Duplicate keyword name at line 9.


Kindly help me on this. I installed following s/w

python-2.6.4.msi
wxPython2.8-win32-unicode-2.8.9.2-py26.exe
set env variables-(C:\Python26\;C:\Python26\Scripts)
copy the folder paramiko-1.7.6, where python is installed
from command prompt :  python setup.py install
robotframework-2.1.1.win32.exe
robotide-0.17.win32.exe
pycrypto-2.1.0.win32-py2.6.exe
SSHLibrary-0.9.win32.exe

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=799#c4) by chethanb... on 13 Jul 2011*


Hi Ashwini,

Even i got the same error. But i tried to follow the steps you mentioned above.
I dint find the directory by name "RobotFramework" under C:\Documents and Settings\Administrator\Application Data

C:\Python26\Scripts&gt;ride.py
Traceback (most recent call last):
  File "C:\Python26\Scripts\ride.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "C:\Python26\lib\site-packages\robotide\__init__.py", line 50, in main
    _run(*args)
  File "C:\Python26\lib\site-packages\robotide\__init__.py", line 60, in _run
    from robotide.application import RobotIde
  File "C:\Python26\lib\site-packages\robotide\application\__init__.py", line 15
, in &lt;module&gt;
    from application import RobotIde
  File "C:\Python26\lib\site-packages\robotide\application\application.py", line
 19, in &lt;module&gt;
    from robotide import context
  File "C:\Python26\lib\site-packages\robotide\context\__init__.py", line 38, in
 &lt;module&gt;
    SETTINGS = RideSettings()
  File "C:\Python26\lib\site-packages\robotide\context\__init__.py", line 29, in
 __init__
    user_path = initialize_settings('ride', default_path)
  File "C:\Python26\lib\site-packages\robotide\context\settings.py", line 33, in
 initialize_settings
    _merge_settings(source_path, settings_path)
  File "C:\Python26\lib\site-packages\robotide\context\settings.py", line 40, in
 _merge_settings
    settings.merge(ConfigObj(user_path, unrepr=True))
  File "C:\Python26\lib\site-packages\robotide\context\configobj.py", line 1219,
 in __init__
    self._load(infile, configspec)
  File "C:\Python26\lib\site-packages\robotide\context\configobj.py", line 1302,
 in _load
    raise error
robotide.context.configobj.DuplicateError: Duplicate keyword name at line 9.


Kindly help me on this. I installed following s/w

python-2.6.4.msi
wxPython2.8-win32-unicode-2.8.9.2-py26.exe
set env variables-(C:\Python26\;C:\Python26\Scripts)
copy the folder paramiko-1.7.6, where python is installed
from command prompt :  python setup.py install
robotframework-2.1.1.win32.exe
robotide-0.17.win32.exe
pycrypto-2.1.0.win32-py2.6.exe
SSHLibrary-0.9.win32.exe

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=799#c5) by chethanb... on 13 Jul 2011*


Thanks Ashwini.

File was hiding in D:\basavara\Application Data\RobotFramework\ride
:)

I solved this issue. Very useful

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=799#c6) by @jussimalinen on 5 Aug 2011*


For future reference, the Ride settings file location is explained here:
<a href="https://code.google.com/p/robotframework-ride/wiki/Settings" rel="nofollow">https://code.google.com/p/robotframework-ride/wiki/Settings</a>

But good that you have been able to fix your problems. If there are more reports of people having this issue with the latest versions of Ride we will take a look at this. However your versions of Ride are very old. I will close this issue now as wontfix.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=799#c7) by aprilyej... on 28 Feb 2012*


Thanks so much. You are definitely great.
Very helpful.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=799#c8) by ashwini.... on 28 Feb 2012*


Good to know that chetan. Therefore i am editing my post with a generic path.

I was able to resolve this issue on my own. Basically, the settings.cfg file under ....\.....\Application Data\RobotFramework\ride\settings.cfg needed to be deleted before trying a re-install.

Earlier I was deleting the settings.cfg under C:\Python26\Lib\site-packages\robotide\context\settings.cfg but this did not work. 

Hope this is useful to others facing the same issue :-)

With Regards,
Ashwini
