### ISSUE TITLE
Error Copy and paste with utf-8 data

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#839]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=804) by jrvilda on 25 Apr 2011*

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\ui\actiontriggers.py", line 342,
in __call__
    action.act(event)
  File "C:\Python26\lib\site-packages\robotide\action\action.py", line 71, in ac
t
    self.action(event)
  File "C:\Python26\lib\site-packages\robotide\editor\__init__.py", line 164, in
 OnPaste
    self.editor.paste()
  File "C:\Python26\lib\site-packages\robotide\editor\editors.py", line 508, in
paste
    self.kweditor.OnPaste()
  File "C:\Python26\lib\site-packages\robotide\utils\eventhandler.py", line 23,in wrapped  method(self, event)
  File "C:\Python26\lib\site-packages\robotide\editor\kweditor.py", line 234, in OnPaste self._execute(PasteArea(self.selection.topleft, data))
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 602, in PasteArea for col in range(len(content[0]))])
  File "C:\Python26\lib\site-packages\robotide\controller\commands.py", line 380
, in __init__
    self._value = value if isinstance(value, unicode) else unicode(value, 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 1-3: invalid data

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=804#c1) by @pekkaklarck on 30 Apr 2011*


Could you give some more details on how to reproduce this and what RIDE version you use? We fixed some non-ASCII copy-paste problems with the latest release.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=804#c2) by @mkorpela on 23 Sep 2011*


Closing do the lack of information.
