### ISSUE TITLE
Error while running ride.py in RIDE version 0.35.1 in windows xp

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#845]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=810) by arunanir... on 10 May 2011*

I'm getting following error while running ride.py in command prompt

C:\Documents and Settings\aruna.t\Application Data&gt;ride.py
Traceback (most recent call last):
  File "C:\Python\Scripts\ride.py", line 20, in &lt;module&gt;
    from robotide import main
  File "C:\Python\Lib\site-packages\robotide\__init__.py", line 28, in &lt;module&gt;
    import wxversion
ImportError: No module named wxversion

C:\Documents and Settings\aruna.t\Application Data&gt;

Robot frame work version:(installed using one click installer)
-------------------------
C:\Documents and Settings\aruna.t\Application Data&gt;pybot --version
Robot Framework 2.5.7 (Python 2.5c2 on win32)

RIDE version:
-----------
0.35.1

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=810#c1) by @mkorpela on 10 May 2011*


You should first install wxpython. <a href="https://code.google.com/p/robotframework-ride/wiki/InstallationInstructions" rel="nofollow">https://code.google.com/p/robotframework-ride/wiki/InstallationInstructions</a>
