### ISSUE TITLE
Starting RIDE fails with bad error message when settings.cfg is read-only

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#858]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=823) by gpot... on 24 Jun 2011*

First run of ride.bat on new Windows 7 install throws the following exception:
C:\Users\testuser\Downloads\BATS-dev-1.1.0.0-1029-81669-all\bats&gt;ride.bat
Traceback (most recent call last):
  File "C:\Users\testuser\Downloads\BATS-dev-1.1.0.0-1029-81669-all\bats\robotide\robotframework-ride-0.35.1\src\bin\ride.py", line 22, in &lt;module&gt;
    from robotide import main
  File "C:\Users\testuser\Downloads\BATS-dev-1.1.0.0-1029-81669-all\bats\robotide\robotframework-ride-0.35.1\src\robotide\__init__.py", line 32, in &lt;module&gt;
    import robotpatch
  File "C:\Users\testuser\Downloads\BATS-dev-1.1.0.0-1029-81669-all\bats\robotide\robotframework-ride-0.35.1\src\robotide\robotpatch.py", line 22, in &lt;module&gt;
    from robotide.context import SETTINGS
  File "C:\Users\testuser\Downloads\BATS-dev-1.1.0.0-1029-81669-all\bats\robotide\robotframework-ride-0.35.1\src\robotide\context\__init__.py", line 42, in &lt;mod
ule&gt;
    SETTINGS = RideSettings()
  File "C:\Users\testuser\Downloads\BATS-dev-1.1.0.0-1029-81669-all\bats\robotide\robotframework-ride-0.35.1\src\robotide\context\__init__.py", line 32, in __in
it__
    user_path = initialize_settings('ride', default_path)
  File "C:\Users\testuser\Downloads\BATS-dev-1.1.0.0-1029-81669-all\bats\robotide\robotframework-ride-0.35.1\src\robotide\context\settings.py", line 46, in init
ialize_settings
    _merge_settings(source_path, settings_path)
  File "C:\Users\testuser\Downloads\BATS-dev-1.1.0.0-1029-81669-all\bats\robotide\robotframework-ride-0.35.1\src\robotide\context\settings.py", line 60, in _merge_settings
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment
 
C:\Users\testuser\Downloads\BATS-dev-1.1.0.0-1029-81669-all\bats&gt;
 
I have tracked it down to the setting.cfg file under the users AppData\Roaming\RobotFramework\ride\settings.cfg being RO, but this problem is being masked by an error in a try/except/finally statement as illustrated in the attached screen shot.

Once I unhid the AppData directory and unset the RO flag I could get it to run with out problems.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=823#c1) by @pekkaklarck on 27 Jun 2011*


I'm not sure could RIDE actually start if settings.cfg is read-only but it should report the situation clearly. Now there's obviously a bug in handling this error situation and that causes the really bad error message.

Thanks for the report and detailed analysis!

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=823#c3) by @yanne on 15 Aug 2011*


This issue was updated by <a href="https://code.google.com/p/robotframework-ride/source/detail?r=c68dd50d0a94">revision c68dd50d0a94</a>.
