### ISSUE TITLE
Error in listener: html_escape() got an unexpected keyword argument 'formatting'

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#859]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=824) by jollych... on 6 Jul 2011*

Robot Framework 2.6 beta1 (Python 2.7.2 on win32)
the ride is start correctly, and I chose test cases folder,RIDE load they correctly,but when I click and keywords/testcase/resource ,the edit tab in right is blank,and RIDE log is as below
-----
20110707 10:50:33.526 [INFO]: Started RIDE version 0.35.1, running on win32, python version 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)] with wx version 2.8.12.0.
20110707 10:50:52.906 [ERROR]: Error in listener: html_escape() got an unexpected keyword argument 'formatting'

Traceback (most recent call last):
html_escape() got an unexpected keyword argument 'formatting'
 File "E:\Program Files\python27\lib\site-packages\robotide\publish\publisher.py", line 84, in __call__
   self.listener(event.data)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\__init__.py", line 108, in OnTreeItemSelected
   self._show_editor()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\__init__.py", line 99, in _show_editor
   self._editor = self._create_editor()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\__init__.py", line 103, in _create_editor
   return self._creator.editor_for(self, self._tab, self.tree)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 922, in editor_for
   self._editor = editor_class(plugin, editor_panel, controller, tree)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 271, in __init__
   _RobotTableEditor.__init__(self, *args)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 97, in __init__
   self._populate()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 325, in _populate
   ResourceFileEditor._populate(self)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 286, in _populate
   self._add_settings()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 149, in _add_settings
   self._settings = self._create_settings()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 158, in _create_settings
   editor = settings.create_editor_for(setting)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 229, in create_editor_for
   return editor_cls(self.GetPane(), controller, self._plugin, self._tree)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 354, in __init__
   self._create_controls()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 366, in _create_controls
   self.update_value()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 580, in update_value
   self._value_display.SetPage(self._controller.visible_value)
 File "E:\Program Files\python27\lib\site-packages\robotide\controller\settingcontrollers.py", line 127, in visible_value
   return utils.html_escape(utils.unescape(self.value), formatting=True)

20110707 10:50:52.926 [ERROR]: Error in listener: html_escape() got an unexpected keyword argument 'formatting'

Traceback (most recent call last):
html_escape() got an unexpected keyword argument 'formatting'
 File "E:\Program Files\python27\lib\site-packages\robotide\publish\publisher.py", line 84, in __call__
   self.listener(event.data)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\__init__.py", line 108, in OnTreeItemSelected
   self._show_editor()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\__init__.py", line 99, in _show_editor
   self._editor = self._create_editor()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\__init__.py", line 103, in _create_editor
   return self._creator.editor_for(self, self._tab, self.tree)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 922, in editor_for
   self._editor = editor_class(plugin, editor_panel, controller, tree)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 271, in __init__
   _RobotTableEditor.__init__(self, *args)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 97, in __init__
   self._populate()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 325, in _populate
   ResourceFileEditor._populate(self)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 286, in _populate
   self._add_settings()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 149, in _add_settings
   self._settings = self._create_settings()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 158, in _create_settings
   editor = settings.create_editor_for(setting)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 229, in create_editor_for
   return editor_cls(self.GetPane(), controller, self._plugin, self._tree)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 354, in __init__
   self._create_controls()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 366, in _create_controls
   self.update_value()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 580, in update_value
   self._value_display.SetPage(self._controller.visible_value)
 File "E:\Program Files\python27\lib\site-packages\robotide\controller\settingcontrollers.py", line 127, in visible_value
   return utils.html_escape(utils.unescape(self.value), formatting=True)

20110707 10:50:54.371 [ERROR]: Error in listener: html_escape() got an unexpected keyword argument 'formatting'

Traceback (most recent call last):
html_escape() got an unexpected keyword argument 'formatting'
 File "E:\Program Files\python27\lib\site-packages\robotide\publish\publisher.py", line 84, in __call__
   self.listener(event.data)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\__init__.py", line 108, in OnTreeItemSelected
   self._show_editor()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\__init__.py", line 99, in _show_editor
   self._editor = self._create_editor()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\__init__.py", line 103, in _create_editor
   return self._creator.editor_for(self, self._tab, self.tree)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 922, in editor_for
   self._editor = editor_class(plugin, editor_panel, controller, tree)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 97, in __init__
   self._populate()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 642, in _populate
   self._add_settings()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 149, in _add_settings
   self._settings = self._create_settings()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 158, in _create_settings
   editor = settings.create_editor_for(setting)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 229, in create_editor_for
   return editor_cls(self.GetPane(), controller, self._plugin, self._tree)
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 354, in __init__
   self._create_controls()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 366, in _create_controls
   self.update_value()
 File "E:\Program Files\python27\lib\site-packages\robotide\editor\editors.py", line 580, in update_value
   self._value_display.SetPage(self._controller.visible_value)
 File "E:\Program Files\python27\lib\site-packages\robotide\controller\settingcontrollers.py", line 127, in visible_value
   return utils.html_escape(utils.unescape(self.value), formatting=True)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=824#c1) by jollych... on 6 Jul 2011*


btw, all testcase and resoure file is txt formatting

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=824#c2) by @pekkaklarck on 7 Jul 2011*


This was a bug in RF 2.6 beta 1. Fixed in beta 2.
