### ISSUE TITLE
Test runner plugin doesn't handler non-ASCII characters in test case names

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#861]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=826) by ttre... on 7 Jul 2011*

It is not possible to use German umlauts like ü ä ö in the name of a test case.

If you do so, the test case is not executed, although logged to the python console:

Traceback (most recent call last):
  File "E:\Robot\RIDE\App\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 246, in OnRuncommand = self._get_command()
  File "E:\Robot\RIDE\App\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 517, in _get_commandf.write("\n".join(standard_args))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 162: ordinal not in range(128)

Using umlauts in key words works fine.

Version info:
* the output of 'pybot --version': Robot Framework 2.5.4 (Python 2.6.1 on win32)
* RIDE: 0.34

Best regards,
Tobias

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=826#c1) by ttre... on 7 Jul 2011*


Here is a minimal example that yield the error:

------------------------- snip ------------------------------
*** Test Cases ***
TC abc
    KW äöü  äöü

TC äöü
    KW äöü  äöü

*** Keywords ***
KW äöü
    [Arguments]  ${msg}
    Log  ${msg}
------------------------- snap ------------------------------

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=826#c2) by @pekkaklarck on 8 Jul 2011*


This is a problem in the test runner plugin. Ought to be easy to fix when RIDE development resumes after RF 2.6.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=826#c3) by ttre... on 8 Jul 2011*


I did some further investigation. The error also occurs with version (taken from RIDE start screen):

Version 0.34 running on Python 2.7.2 using Robot Framework 2.5.7.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=826#c4) by @jussimalinen on 4 Aug 2011*


Alright, this was rather straightforward to fix. <a href="https://code.google.com/p/robotframework-ride/source/detail?r=8003046ccc3d">r8003046ccc3d</a>
