### ISSUE TITLE
ride.py giving errors

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#904]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=869) by p.smi... on 29 Sep 2011*

Hi,
Following are the framework, Python, and OS details:
Framework -- 2.6.0
Python -- 27
OS -- Windows 7
Ride -- 0.39.1

I was using ride ver 0.32.1. It was hanging while opening the folder. So I have downloaded the latest version 0.39.1. But when I run ride.py through command prompt, I am getting following error.
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\smpatil&gt;ride.py
Traceback (most recent call last):
  File "C:\Python27\Scripts\ride.py", line 20, in &lt;module&gt;
    from robotide import main
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 32, in &lt;module
&gt;
    import robotpatch
  File "C:\Python27\lib\site-packages\robotide\robotpatch.py", line 22, in &lt;modu
le&gt;
    from robotide.context import SETTINGS
  File "C:\Python27\lib\site-packages\robotide\context\__init__.py", line 42, in
 &lt;module&gt;
    SETTINGS = RideSettings()
  File "C:\Python27\lib\site-packages\robotide\context\__init__.py", line 32, in
 __init__
    user_path = initialize_settings('ride', default_path)
  File "C:\Python27\lib\site-packages\robotide\context\settings.py", line 46, in
 initialize_settings
    _merge_settings(source_path, settings_path)
  File "C:\Python27\lib\site-packages\robotide\context\settings.py", line 53, in
 _merge_settings
    settings.merge(ConfigObj(user_path, unrepr=True))
  File "C:\Python27\lib\site-packages\robotide\context\configobj.py", line 1214,
 in __init__
    self._load(infile, configspec)
  File "C:\Python27\lib\site-packages\robotide\context\configobj.py", line 1297,
 in _load
    raise error
robotide.context.configobj.ParseError: Invalid line at line "1".

C:\Users\smpatil&gt;

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=869#c1) by @yanne on 29 Sep 2011*


It seems that your settings file has been somehow corrupted.

Can you try to find your Settings file and rename/remove it and see whether this error still persists?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=869#c2) by @yanne on 29 Sep 2011*


Settings file location is explained in the Wiki:
<a href="https://code.google.com/p/robotframework-ride/wiki/Settings" rel="nofollow">https://code.google.com/p/robotframework-ride/wiki/Settings</a>

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=869#c3) by p.smi... on 29 Sep 2011*


Hi,
I renamed the file settings.cfg to settings1.cfg and tried removing the file also from its location and again ran ride.py
I am still getting the same error
Could you please help on this ?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=869#c4) by @mkorpela on 29 Sep 2011*


Was the settings file in &#37;APPDATA&#37;\RobotFramework\ride ?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=869#c5) by p.smi... on 29 Sep 2011*


settings.cfg was under C:\Python27\Lib\site-packages\robotide\context

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=869#c6) by p.smi... on 29 Sep 2011*


Hi,
I renamed the settings.cfg file under &#37;APPDATA&#37;\RobotFramework\ride and now this is working.

But RIDE hangs when I try to load some files into it and when I try to edit some thing in it.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=869#c7) by @mkorpela on 19 Dec 2011*


Is the original problem still valid?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=869#c8) by p.smi... on 19 Dec 2011*


Hi,
the these problems are solved now. Thanks for the support

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=869#c9) by @mkorpela on 20 Dec 2011*


Good!

Closing this as Invalid.
