### ISSUE TITLE
Robot IDE fails on OS X

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#92]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=58) by IlkkaNis... on 24 Nov 2008*

Operating system: OS X 10.5.5
Robot ide version 0.11
Robot from trunk (<a href="http://robotframework.googlecode.com/svn" rel="nofollow">http://robotframework.googlecode.com/svn</a>, revision: 1086)

How to reproduce:
1) open robot ide with command: python -m robotide .
path . contains written cases with normal text editor in html format
2) open Test Cases and click one testcase name. Following error appears on terminal window:
bash-$ python -m robotide .
Traceback (most recent call last):
  File "/Library/Python/2.5/site-packages/robotide/ui/suitetree.py", line 230, in OnSelChanged
    self._show_correct_editor(item)
  File "/Library/Python/2.5/site-packages/robotide/ui/suitetree.py", line 239, in 
_show_correct_editor
    self._editor = item.editor(self._editor_panel, item, self)
  File "/Library/Python/2.5/site-packages/robotide/ui/editors/editors.py", line 40, in __init__
    self._populate()
  File "/Library/Python/2.5/site-packages/robotide/ui/editors/editors.py", line 250, in _populate
    self._create_kweditor()
  File "/Library/Python/2.5/site-packages/robotide/ui/editors/editors.py", line 262, in 
_create_kweditor
    self.item.parent.project.keyword_cache)
  File "/Library/Python/2.5/site-packages/robotide/ui/editors/kweditor.py", line 202, in __init__
    self._tooltip = ContentAssistPopup(self, (650, 400), use_html=True)
  File "/Library/Python/2.5/site-packages/robotide/ui/editors/contenassist.py", line 147, in 
__init__
    wx.PopupWindow.__init__(self, parent)
  File "/BinaryCache/wxWidgets/wxWidgets-
11~88/Root/System/Library/Frameworks/Python.framework/Versions/2.5/Extras/lib/python/wx
-2.8-mac-unicode/wx/_windows.py", line 1732, in __init__
NotImplementedError

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=58#c1) by @yanne on 24 Nov 2008*


This is duplicate of <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=33" title="Support for OSX"> issue 33 </a>.
For some reason, all of the WX-toolkit is not implemented on Mac.
We will investigate what can be done to circumvent this issue.

**Comment by jmagaru** [comment]
I tried workaround on this using flat-package of wxPython 2.8 unicode:
https://github.com/jmagaru/wxPython2.8-osx-unicode-flat-package-py2.7
It works now. Mac OS El Capitan
