### ISSUE TITLE
Renaming a dirty Test Suite, gets its file deleted

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#934]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=899) by ing.guil... on 22 Dec 2011*

I observed this with RIDE 0.39.1

Steps To Reproduce:
- Modify a Test Suite without saving (An * is shown next to its name)
- Rename the Test Suite by selecting it and clicking its name. (If you do F2 or context menu -&gt; Rename issue wont happen)

Expected behavior:
- Test suite is renamed, and saved with all changes to file in disk. The * next to the file disappears

Actual behavior:
- The file appears to be renamed, but the * next to the Test suite name doesn't disappear.  
- In the file system the Test Suite "disappears", and when a Test Case inside is clicked a "File Changed On Disk" dialog appears.
- If I select No in the dialog, file doesnt gets rewritten.

Root cause:
I haven't investigated the issue but I noticed that the "File change on disk" dialog shows as changed file "C:\some\path\*TestSuite.txt". With an star in the begining.

This traceback should help with the investigation:
Traceback (most recent call last):
  File "C:\robotframework-ride-0.39.1\public\robotide\ui\tree.py", line 999, in OnLabelEdited
    self._get_handler(event.Item).end_label_edit(event)
  File "C:\robotframework-ride-0.39.1\public\robotide\ui\tree.py", line 882, in end_label_edit
    self.controller.execute(RenameFile(event.Label))
  File "C:\robotframework-ride-0.39.1\public\robotide\controller\basecontroller.py", line 22, in execute
    return command.execute(self)
  File "C:\robotframework-ride-0.39.1\public\robotide\controller\commands.py", line 308, in execute
    context.set_basename(self._new_basename)
  File "C:\robotframework-ride-0.39.1\public\robotide\controller\filecontrollers.py", line 219, in set_basename
    self.save()
  File "C:\robotframework-ride-0.39.1\public\robotide\controller\filecontrollers.py", line 250, in save
    self._chief_controller.serialize_controller(self)
  File "C:\robotframework-ride-0.39.1\public\robotide\controller\chiefcontroller.py", line 251, in serialize_controller
    self._serialize_file(controller)
  File "C:\robotframework-ride-0.39.1\public\robotide\controller\chiefcontroller.py", line 268, in _serialize_file
    serializer.serialize(controller.datafile)
  File "C:\robotframework-ride-0.39.1\public\robotide\writer\serializer.py", line 57, in serialize
    output = self._get_output(datafile)
  File "C:\robotframework-ride-0.39.1\public\robotide\writer\serializer.py", line 72, in _get_output
    return self._ctx.output or open(self._get_source(datafile), 'wb')
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:\\Foo\\Barr\\*MyTestSuite.txt'

I would consider this defect with high priority since it could lead to data (and lots of efforts) lost.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=899#c2) by @mkorpela on 27 Dec 2011*


Fixed in <a href="https://github.com/robotframework/RIDE/commit/721424d7c7ae907c4f480c351acc97372f5ff498" rel="nofollow">https://github.com/robotframework/RIDE/commit/721424d7c7ae907c4f480c351acc97372f5ff498</a>
