### ISSUE TITLE
Errors thrown by RIDE 0.40.2 Test Runner

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#953]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=918) by c.martin.taylor on 18 Jan 2012*

Every time I run tests in RIDE 0.40.2 Test Runner tab I get errors like the following.  This is not new.  I think the same errors were in 0.39.1, too.

Traceback (most recent call last):
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 14660, in &lt;lambda&gt;
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 803, in _post_result
    self._tree.running_suite(longname)
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\TestSuiteTreeCtrl.py", line 249, in running_suite
    self.SetState(suiteId, self.RUNNING_IMAGE_KEY)
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\TestSuiteTreeCtrl.py", line 241, in SetState
    node = self._nodes[self._convert_test_longname_key(testId)]
KeyError: u'ti-nspire.application framework'
Traceback (most recent call last):
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 14660, in &lt;lambda&gt;
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 803, in _post_result
    self._tree.running_suite(longname)
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\TestSuiteTreeCtrl.py", line 249, in running_suite
    self.SetState(suiteId, self.RUNNING_IMAGE_KEY)
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\TestSuiteTreeCtrl.py", line 241, in SetState
    node = self._nodes[self._convert_test_longname_key(testId)]
KeyError: u'ti-nspire.application framework.application framework'
Traceback (most recent call last):
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 14660, in &lt;lambda&gt;
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 799, in _post_result
    self._tree.running_test(longname)
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\TestSuiteTreeCtrl.py", line 245, in running_test
    self.SetState(testId, self.RUNNING_IMAGE_KEY)
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\TestSuiteTreeCtrl.py", line 241, in SetState
    node = self._nodes[self._convert_test_longname_key(testId)]
KeyError: u'ti-nspire.application framework.application framework.Test Application Name Recognition'

Traceback (most recent call last):
  File "c:\python26\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 14660, in &lt;lambda&gt;
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 808, in _post_result
    self._tree.test_passed(longname)
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\TestSuiteTreeCtrl.py", line 256, in test_passed
    self.SetState(testId, self.PASSED_IMAGE_KEY)
  File "C:\Python26\lib\site-packages\robotide\contrib\testrunner\TestSuiteTreeCtrl.py", line 241, in SetState
    node = self._nodes[self._convert_test_longname_key(testId)]
KeyError: u'ti-nspire.application framework.application framework.Test Application Name Recognition'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=918#c1) by c.martin.taylor on 18 Jan 2012*


Correction: These errors did not appear in RIDE 0.39.1 and the errors are serious in that they break RIDE's ability to update the window with test case PASS/FAIL information.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=918#c4) by @mkorpela on 19 Jan 2012*


Fixed in <a href="https://github.com/robotframework/RIDE/commit/67f91c2454eaed263ee9208151fb7c51ded8868a" rel="nofollow">https://github.com/robotframework/RIDE/commit/67f91c2454eaed263ee9208151fb7c51ded8868a</a>

Subdirectory name was not constructed correctly. This lead to these problems.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=918#c5) by @mkorpela on 19 Jan 2012*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=912" title="pass / fail status is not updated in the test runner plugin of ride during test execution "> Issue 912 </a> has been merged into this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=918#c6) by @mkorpela on 25 Jan 2012*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=921" title="Passed and Failed tests are not marked by color"> Issue 921 </a> has been merged into this issue.
