### ISSUE TITLE
Selenium Keyword auto complete does not work when Library import has an Argument

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#954]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=919) by desertbl... on 18 Jan 2012*

Steps to Recreate:
1. Create a new test case
2. Import Selenium Library with an argument server_port=${port} (Screen Attached)
3. In the test case try to use the auto complete
RIDE will not see any Selenium keywords for autocomplete

We pass the server port through Jenkins so we can run multiple instances on the same machine

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=919#c1) by @spooning on 19 Jan 2012*


Are there any error messages in the log (Tools|View RIDE Log)?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=919#c2) by @mkorpela on 19 Jan 2012*


Is the variable ${port} defined?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=919#c3) by desertbl... on 19 Jan 2012*


The variable ${port} is defined but it was done at the top level, in the __init__.txt.

I added it to the individual suite and it started to work. Below is the log output if you still want to work it.

20120119 08:53:31.624 [INFO]: Started RIDE 0.40.2 using python version 2.7.2 with wx version 2.8.12.0.

20120119 08:54:36.482 [WARN]: Importing test library "SeleniumLibrary" failed

Traceback (most recent call last):
Creating an instance of the test library 'SeleniumLibrary' with no arguments failed: ValueError: invalid literal for int() with base 10: '${port}'
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\SeleniumLibrary\__init__.py", line 281, in __init__
    server_port or 4444)
  File "C:\Python27\Lib\site-packages\SeleniumLibrary\__init__.py", line 293, in _parse_host_and_port
    return host, int(port)
  File "C:\Python27\Lib\site-packages\robotide\spec\xmlreaders.py", line 59, in __init__
    self.keywords, self.doc = self._init_from_library(self.name, args)
  File "C:\Python27\Lib\site-packages\robotide\spec\xmlreaders.py", line 68, in _init_from_library
    lib = RobotTestLibrary(name, args)
  File "C:\Python27\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 41, in TestLibrary
    lib.create_handlers()
  File "C:\Python27\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 115, in create_handlers
    self._libinst = self.get_instance()
  File "C:\Python27\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 181, in get_instance
    self._libinst = self._get_instance()
  File "C:\Python27\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 189, in _get_instance
    self._raise_creating_instance_failed()
  File "C:\Python27\Lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 244, in _raise_creating_instance_failed
    "failed: &#37;s\n&#37;s" &#37; (self.name, args, msg, details))

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=919#c4) by @mkorpela on 15 Feb 2012*


Marking this as invalid as the problem was the undefined variable
