### ISSUE TITLE
Can't run test from RIDE due to assci issue

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#982]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945) by polusok on 29 Feb 2012*

I got following trace in console
Traceback (most recent call last):
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 247, in OnRun
    command = self._get_command()
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 490, in _get_command
    command.append(self._relpath(self.model.suite.source))
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 529, in _relpath
    i = len(posixpath.commonprefix([start_list, path_list]))
  File "C:\Program Files (x86)\python27\lib\genericpath.py", line 71, in commonprefix
    s1 = min(m)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf9 in position 9: ordinal not in range(128)

My configuration:
- win7 RU
- python 2.7
- run from pybot
- Robot Framework 2.7 b1 (Python 2.7.2 on win32)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c1) by polusok on 29 Feb 2012*


RIDE version 0.41

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c2) by SamerAdra on 16 Mar 2012*


I am also seeing this, with WinXP x86, RIDE with pybot, RobotFramework 2.7bt, and Python 2.7.2, when trying to run a keyword with a parameter includeing a non-ASCII character ( (R) symbol).

-Samer

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c3) by polusok on 16 Mar 2012*


it seems we are alone with this issue :(

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c5) by @mkorpela on 16 Mar 2012*


What version of RIDE are you using?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c6) by polusok on 17 Mar 2012*


RIDE 0.42

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c7) by @mkorpela on 19 Mar 2012*


I could not reproduce the problem.

I replaced custom relpath implementation with the standard one.

@&#8288;polusok: Does this version work for you?
<a href="http://dl.dropbox.com/u/40102182/0.43/robotframework-ride-0.43previewRelPath.win32.exe" rel="nofollow">http://dl.dropbox.com/u/40102182/0.43/robotframework-ride-0.43previewRelPath.win32.exe</a>

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c8) by @mkorpela on 19 Mar 2012*


Making release moving these to the next one

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c9) by polusok on 19 Mar 2012*


yes, 043 is working for me, thanks, 
waiting this to be included and tested

thanks again

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c10) by polusok on 19 Mar 2012*


however find this issue for test with external library

working directory: C:\Users\ùðøñ÷ó
command: pybot.bat -V c:\demo\bdd.py --argumentfile c:\users\dc4d~1\appdata\local\temp\RIDEx_tr0d.d\argfile.txt --listener "C:\Program Files (x86)\python27\lib\site-packages\robotide\contrib\testrunner\SocketListener.py:53203" ..\..\demo
===================================================================================
Demo                                                                               
===================================================================================
Demo.Test :: suite descriptnon [<a href="http://google.com" rel="nofollow">http://google.com</a>]                                 
===================================================================================
UsingExternalLibrary                                                       | FAIL |
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf9 in position 11: ordinal not in range(128)
-----------------------------------------------------------------------------------
Demo.Test :: suite descriptnon [<a href="http://google.com" rel="nofollow">http://google.com</a>]                         | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
===================================================================================
Demo                                                                       | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
===================================================================================
Output:  c:\users\dc4d~1\appdata\local\temp\RIDEx_tr0d.d\output.xml
Log:     c:\users\dc4d~1\appdata\local\temp\RIDEx_tr0d.d\log.html
Report:  c:\users\dc4d~1\appdata\local\temp\RIDEx_tr0d.d\report.html

test finished 03/19/12 17:37:47

=====================
demo project is attached

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c11) by @mkorpela on 19 Mar 2012*


This might be related to encoding errors in Robot Framework 2.7. What version of pybot do you use? pybot --version

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c12) by polusok on 19 Mar 2012*


Robot Framework 2.7 (Python 2.7.2 on win32)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c13) by @mkorpela on 20 Mar 2012*


The current problem is in Robot Framework 2.7.
Thanks for the demo.rar - we will use it while fixing the issue.

I will close this issue.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c14) by polusok on 20 Mar 2012*


could you please point me out to reference issue in RF project so I can subscribe on it.

thanks

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=945#c15) by @mkorpela on 20 Mar 2012*


I added a issue about this <a href="https://code.google.com/p/robotframework/issues/detail?id=1092" rel="nofollow">https://code.google.com/p/robotframework/issues/detail?id=1092</a>

It could be that this is somehow related to <a href="https://code.google.com/p/robotframework/issues/detail?id=1091" rel="nofollow">https://code.google.com/p/robotframework/issues/detail?id=1091</a> or not..
