### ISSUE TITLE
Delete key behaves badly in 'Manage Run Configurations' dialog

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#984]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=947) by pasi.tiainen on 1 Mar 2012*

RIDE 0.42.1 on Python 2.6.6, RF 2.6.2

When some text is selected in 'Manage Run Configurations' dialog, pressing delete key doesn't delete the selected text but some other cell completely.

Deleting the text with backspace works as it should.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=947#c2) by @mkorpela on 19 Mar 2012*


Making release moving these to the next one

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=947#c3) by @mkorpela on 23 Apr 2012*


Traceback (most recent call last):
  File "src/robotide/editor/listeditor.py", line 105, in OnDelete
    self._with_column_width_preservation(self._delete_selected)
  File "src/robotide/editor/listeditor.py", line 111, in _with_column_width_preservation
    func()
  File "src/robotide/editor/listeditor.py", line 116, in _delete_selected
    self._controller.execute(DeleteItem(self._selection))
AttributeError: 'RunConfigs' object has no attribute 'execute'

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=947#c5) by @mkorpela on 23 Apr 2012*


Disabled delete key when editing a field

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=947#c6) by @mkorpela on 23 Apr 2012*


Fixed after
<a href="https://github.com/robotframework/RIDE/commit/7243b44ef9074f92c58594134d2567e9836d91a3" rel="nofollow">https://github.com/robotframework/RIDE/commit/7243b44ef9074f92c58594134d2567e9836d91a3</a>
