### ISSUE TITLE
Selecting Run -> Manage Run Configurations causes traceback

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#991]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=953) by aalto.tatu on 20 Mar 2012*

1) Open Ride
2) Select from menu: Run -&gt; Manage Run Configurations 
3) Manage Run Configurations is not opened and following traceback is seen in the command line: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\ui\actiontriggers.py", line 354, in __call__
    action.act(event)
  File "C:\Python27\lib\site-packages\robotide\action\action.py", line 86, in act
    self.action(event)
  File "C:\Python27\lib\site-packages\robotide\run\runanything.py", line 37, in OnManageConfigurations
    dlg = ConfigManagerDialog(self._configs)
  File "C:\Python27\lib\site-packages\robotide\run\configmanagerui.py", line 42, in __init__
    self._create_ui(configs)
  File "C:\Python27\lib\site-packages\robotide\run\configmanagerui.py", line 46, in _create_ui
    self._editor = self._create_editor(configs)
  File "C:\Python27\lib\site-packages\robotide\run\configmanagerui.py", line 53, in _create_editor
    editor = _ConfigListEditor(self, configs)
  File "C:\Python27\lib\site-packages\robotide\run\configmanagerui.py", line 80, in __init__
    ListEditorBase.__init__(self, parent, self._columns, configs)
  File "C:\Python27\lib\site-packages\robotide\editor\listeditor.py", line 32, in __init__
    self._create_ui(columns, controller)
  File "C:\Python27\lib\site-packages\robotide\editor\listeditor.py", line 38, in _create_ui
    self._list = self._create_list(columns, data)
  File "C:\Python27\lib\site-packages\robotide\run\configmanagerui.py", line 83, in _create_list
    return _TextEditListCtrl(self, columns, data)
  File "C:\Python27\lib\site-packages\robotide\run\configmanagerui.py", line 111, in __init__
    AutoWidthColumnList.__init__(self, parent, columns, data)
  File "C:\Python27\lib\site-packages\robotide\editor\listeditor.py", line 150, in __init__
    self.populate(columns, data)
  File "C:\Python27\lib\site-packages\robotide\editor\listeditor.py", line 155, in populate
    self.insert_data(data)
  File "C:\Python27\lib\site-packages\robotide\editor\listeditor.py", line 159, in insert_data
    self._set_column_widths()
  File "C:\Python27\lib\site-packages\robotide\editor\listeditor.py", line 171, in _set_column_widths
    min_width = self._parent.Parent.plugin.global_settings['list col min width']
AttributeError: 'ConfigManagerDialog' object has no attribute 'plugin'

Tested in:
win 7 (64bit)
Robot Framework 2.7 (Python 2.7.2 on win32)
Ride 0.43

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=953#c1) by @mkorpela on 20 Mar 2012*


Fixed in <a href="https://code.google.com/p/robotframework/source/detail?r=cfa988dc986dee25419462bd90fe2009cbd2b395" rel="nofollow">https://code.google.com/p/robotframework/source/detail?r=cfa988dc986dee25419462bd90fe2009cbd2b395</a>

and

<a href="https://github.com/robotframework/RIDE/commit/bcea4019750ab85a92801e6315fec0ad9094ef3d" rel="nofollow">https://github.com/robotframework/RIDE/commit/bcea4019750ab85a92801e6315fec0ad9094ef3d</a>
