### ISSUE TITLE
Starting a testcase from the run tab doesn't work, when testcase drive != ride drive

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#995]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=957) by bobobruhn on 21 Mar 2012*

Windows7 32bit
RIDE 0.43.2 running on Python 2.7.1. using robotframework 2.7

Starting a testsuite which is located on drive C (where python is installed) works as expected. When putting the same suite to drive D and trying to start, the traceback listed below appears and nothing is executed.. 

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 274, in OnRun
    command = self._get_command()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 521, in _get_command
    command.append(relpath(self.model.suite.source))
  File "C:\Python27\lib\ntpath.py", line 512, in relpath
    &#37; (path_prefix, start_prefix))
ValueError: path is on drive D:, start on drive C:

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=957#c1) by @mkorpela on 21 Mar 2012*


Thanks for the report!

Work around: Start ride from command line when you are on the drive D:

I'll target this to the next release.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=957#c2) by @mkorpela on 26 Mar 2012*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=958" title="Not possible to run a Test Case that is located on a network drive"> Issue 958 </a> has been merged into this issue.
