### ISSUE TITLE
After setting preferences PYTHONPATH Ride broken in strange way

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#998]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=960) by polusok on 29 Mar 2012*

My configuration:
- win 64 ru
- python 2.7 win 32
- pybot 2.7.1
- ride 0.43.3

Steps:
1. open ride
2. open my project
3. set in preferences pythonpath
4. closed it preferences
5. open search keywords and it hangs
6. then I kill process of ride
7. once opened strange behaviour, please look at screenshots

Strange bihaviour:
- syntax highlight doesn't work
- autocompletion doesn't work
- some test cases are not showing at all
- however I can run it
- can't find keywords in search keywords (even builtin)
- etc

in python console have following errors:
Traceback (most recent call last):
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\ui\keywordsearch.py", line 203, in OnActivate
    if self._plugin.have_keywords_changed():
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\ui\keywordsearch.py", line 61, in have_keywords_changed
    self._update()
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\ui\keywordsearch.py", line 66, in _update
    self.all_keywords = self.model.get_all_keywords()
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\controller\chiefcontroller.py", line 176, in get_all_keywords
    return self.get_all_keywords_from(ctrl.datafile for ctrl in self.datafiles if ctrl.datafile)
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\controller\basecontroller.py", line 100, in get_all_keywords_from
    return self._namespace.get_all_keywords(*datafiles)
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\namespace.py", line 77, in get_all_keywords
    kws.update(self._get_default_keywords())
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\namespace.py", line 82, in _get_default_keywords
    return self._lib_cache.get_default_keywords()
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\cache.py", line 81, in get_default_keywords
    return self._default_kws[:]
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\cache.py", line 42, in _default_kws
    self.__default_kws = self._build_default_kws()
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\cache.py", line 85, in _build_default_kws
    for spec in self._default_libraries.values():
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\cache.py", line 36, in _default_libraries
    self.__default_libraries = self._get_default_libraries()
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\namespace\cache.py", line 93, in _get_default_libraries
    default_libs[name] = LibrarySpec(name, args)
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\spec\xmlreaders.py", line 68, in __init__
    RideLogException(message=msg, exception=err, level='WARN').publish()
  File "C:\Program Files (x86)\python27\lib\site-packages\robotide\publish\messages.py", line 121, in __init__
    message += '\n\nTraceback (most recent call last):\n&#37;s\n&#37;s' &#37; (str(exception) ,''.join(traceback.format_list(tb)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 990-995: ordinal not in range(128)

Reinstallation doesn't help unfortunately

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=960#c1) by polusok on 29 Mar 2012*


please let me know if I need to add something so you can find out what the issue is. it may be logs from some place

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=960#c2) by @mkorpela on 30 Mar 2012*


What do you have in the pythonpath?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=960#c3) by polusok on 30 Mar 2012*


it's seems it's related to my special symbols in path which I reported previously
<a href="https://code.google.com/p/robotframework-ride/issues/detail?id=945" rel="nofollow">https://code.google.com/p/robotframework-ride/issues/detail?id=945</a>

as I created new user on my box with english letter and try and it's working for it. 
so this is issue with special symbols

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=960#c4) by @mkorpela on 30 Mar 2012*


I can not yet reproduce the problem.

I tried to add a library from C:\ùðøñ÷ó and it did work ..

So I need some more info to be able to reproduce the problem.

In your stacktrace the basic exception seems to be hidden by the fact that the exception formatting fails due to ascii encoding error.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=960#c5) by @mkorpela on 30 Mar 2012*


@&#8288;polusok:

This version should give the real exception - so could you try it?
<a href="http://dl.dropbox.com/u/40102182/0.43/robotframework-ride-0.43.3pythonpath.win32.exe" rel="nofollow">http://dl.dropbox.com/u/40102182/0.43/robotframework-ride-0.43.3pythonpath.win32.exe</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=960#c6) by polusok on 30 Mar 2012*


thanks for quick response,
i switch to another account where I don't have special symbols in path.
so I think you can close this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=960#c7) by @mkorpela on 30 Mar 2012*


Ok.

I'll close this as WontFix as there clearly is something wrong but it has an easy work around and I can not reproduce the problem.
